### ISSUE TITLE
ошибка с билдом

### ISSUE THREAD

**Issue by tigra323** [vtosters/lite#100]
в папке lite-master пишу scripts\build.bat в консоли (простая или в андроид студио). Первая ошибка при Build dex...
а точнее > Configure project :app но build.bat это пропускает, потом в Move version.properties to source dir... он пишет не найден файл и тут скрипт видит что произошла ошибка и останавливается.
лог [*тык*](https://pastebin.com/ayFduSsB)

**Comment by aliveoutside** [comment]
делай ```cd scripts``` и потом запускай скрипт

**Comment by tigra323** [comment]
если сделать так, то будет:
```
"gradlew" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.
```
А если добавить в path или изменить команду `call gradlew` на `call ..\gradlew` то будет:
```
* What went wrong:
Project directory '\lite-master\scripts' is not part of the build defined by settings file '\lite-master\settings.gradle'. If this is
an unrelated build, it must have its own settings file.
```
