### ISSUE TITLE
"фильтр слов и выражений" не поддерживает репосты

### ISSUE THREAD

**Issue by evil-raider** [vtosters/lite#1001]
**Опишите сам баг**
фразы, введенные в фильтр, не влияют на показ постов с этими словами

**Опишите действия для воспроизведения ошибки**
ввел в фильтр постов (настройки-настройки мода-лента-фильтр слов и выражений) ключевые фразы для блокировки (приют, реквизиты для помощи). Обновляю ленту (или захожу в сообщество)-посты (репосты) с этими словами по-прежнему вижу в ленте. Пример поста https://vk.com/wall-30022666_381165

**Опишите ожидаемый результат**
Ожидаю вообще не видеть посты\репосты, в которых встречаются фразы из фильтра

**Скриншот ошибки**
![Screenshot_20221231-230246](https://user-images.githubusercontent.com/39806024/210154613-3946d5a9-725e-46ed-9c22-408e5035aba3.png)
![Screenshot_20221231-230234](https://user-images.githubusercontent.com/39806024/210154615-27f1c077-91ed-4b85-8c9c-9abbea27dd30.png)

**Информация об устройстве:**
 - Устройство: blackberry key2
 - OS: Android 8.1.0
 - Коммит: 4cb73d6

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**
в vk next та же фигня, разраб Valentin в телеграм-чате сказал о том, что фильтр вообще перестал работать

**Comment by k1zn** [comment]
Это репост, пока что фильтры не поддерживают репосты
