### ISSUE TITLE
Улучшение интерфейса приложения

### ISSUE THREAD

**Issue by Jacanda** [vtosters/lite#1003]
Необходима функция включения отображения абсолютного времени (вместо округленного времени включить возможность отображения статуса онлайна или даты публикации постов на посекундное время).
Пример: (5 минут назад => 01 января 2023 22:22:22).

**Comment by gdlbo** [comment]
![Screenshot_20230102-231411.png](https://user-images.githubusercontent.com/41114720/210274862-143e3725-f261-472c-ac23-a25ea6d56992.png)
