### ISSUE TITLE
Баг с меню на разных устройствах

### ISSUE THREAD

**Issue by saraysxroom** [vtosters/lite#1006]
**Опишите сам баг**
Меня это уже бесит,меню,с ленты новостей не показывается

**Опишите действия для воспроизведения ошибки**
1.включил меню в новостях(хз как)
2.пролистнул вправо
**Опишите ожидаемый результат**
Должно было появиться меню

**Скриншот ошибки**
![Screenshot_20230103_104025_VTLite](https://user-images.githubusercontent.com/118358799/210317136-fff4021b-3420-4797-8404-d43121cd889a.jpg)

**Информация об устройстве:**
 - Устройство: Samsung Galaxy S20FE
 - OS: Android 13 | OneUi 5.0
 - Коммит: 4cb73d6

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**
Исправьте быстрее,я втостерс маме поставил вместо совы,так эта менюшка мало того что не слева а справа,так ещё и не работает!!!!

**Comment by aliveoutside** [comment]
> включил меню в новостях(хз как)

такой функции нет
