### ISSUE TITLE
Иконка док-бара при выборе фрагмента при запуске

### ISSUE THREAD

**Issue by rx1310** [vtosters/lite#102]
Если выбрать, допустим, фрагмент музыки при запуске тостера в док-баре подсвечена кнопка ленты. 

![IMG_20220402_142639.jpg](https://user-images.githubusercontent.com/33829769/161381029-f0654f09-053a-432f-a020-614355d65ebf.jpg)

**Comment by gdlbo** [comment]
Такое возможно только при редакторе докбара который сейчас мы реализовываем
![image](https://user-images.githubusercontent.com/41114720/161425337-c7eb1492-a7a5-4ad1-aaa7-05814af8098d.png)
