### ISSUE TITLE
Добавьте возможность изменить цвет сообщений

### ISSUE THREAD

**Issue by Manechkauwu** [vtosters/lite#1024]
Здравствуйте, я очень долго жду функцию покраски отправляемых сообщений в диалогах... Как в оригинальном ВК. Красивый градиент отправляемых сообщений... Я была бы очень рада, если бы вы это перенесли в свое приложение!ಥ⁠‿⁠ಥ
А то без этой функции переписка выглядит очень уныло... 
У вас есть возможность добавить только фон на сообщения, это хорошо, но хотелось так же возможность сменить на градиент, как в офф ВК!
Спасибо за внимание. Очень надеюсь, что вы это добавите и я смогу окончательно перейти на ваше приложение!
![Screenshot_2023-01-10-14-34-44-124_com vkontakte android](https://user-images.githubusercontent.com/122362971/211542049-22271565-3d1b-447d-bc15-977ce4c803fb.jpg)

**Comment by aliveoutside** [comment]
градиента не будет, покраску интерфейса добавили в v0.5
