### ISSUE TITLE
Ошибка обновлении ленты новостей

### ISSUE THREAD

**Issue by Vexille2** [vtosters/lite#1031]
Не загружает miniapps шаги вконтакте.
Жду фикс
![Screenshot_2023-01-11-17-05-04-69_9e1a5d6211a0228d32d39446541891f1](https://user-images.githubusercontent.com/122451419/211801941-b3f753de-b462-4c78-bfe5-fa7bca230396.jpg) бесконечно висит такой экран при запуске
модель устройства realme c3,android 10,версия оболочки realme v 1.0
возможных решений не нашёл
коммит:eba6c43

**Comment by danyyok** [comment]
@Vexille2 Шаги не работают на модифицированных версиях ВКонтакте, таких как VK Tea,VTLite и т.д
