### ISSUE TITLE
Ошибка обновлении ленты новостей

### ISSUE THREAD

**Issue by RusskiyChelik** [vtosters/lite#1037]
Нет обновления ленты новостей, сколько не обновлять, какие настройки ленты не ставить, через какой IP сидеть, новости с 1 января всё также, хотя в группах много нового контента

**Информация об устройстве:**
 - Устройство: OnePlus 8
 - OS: Android 13 | OOS13
 - Коммит: eba6c43

**Comment by danyyok** [comment]
@RusskiyChelik Настройки-Лента

**Comment by RusskiyChelik** [comment]
> @RusskiyChelikНастройки-Лента

![Screenshot_2023-01-12-00-10-10-78_9e1a5d6211a0228d32d39446541891f1](https://user-images.githubusercontent.com/122488559/211918491-48f5dfee-8bba-4e35-9170-23dcc336c72c.jpg)
![Screenshot_2023-01-12-00-10-15-76_9e1a5d6211a0228d32d39446541891f1](https://user-images.githubusercontent.com/122488559/211918495-7f2fa2db-eb36-4b22-a6c1-2fdcb45e425d.jpg)
![Screenshot_2023-01-12-00-10-20-59_9e1a5d6211a0228d32d39446541891f1](https://user-images.githubusercontent.com/122488559/211918498-7b25112b-07e6-44f0-983f-1eae2009872e.jpg)
![Screenshot_2023-01-12-00-10-23-45_9e1a5d6211a0228d32d39446541891f1](https://user-images.githubusercontent.com/122488559/211918500-43a2199e-9510-4b0d-814b-56f446d4f930.jpg)

**Comment by danyyok** [comment]
>Прочее(В самом низу)-Встроенные настройки новостей-Порядок записей>По времени публикации

**Comment by RusskiyChelik** [comment]
Боже, помогло, спасибо тебе большое!)

**Comment by icynstant** [comment]
Проблема не решается этим, интересная лента работает иначе чем в последней версии вк, подробнее объяснил в #1510

**Comment by icynstant** [comment]
Прошу открыть ошибку

**Comment by ayonovdenizs** [comment]
@icynstant https://github.com/vtosters/lite/issues/1510#issuecomment-1831906593
