### ISSUE TITLE
Перестали отображаться стикеры

### ISSUE THREAD

**Issue by Lisa2206** [vtosters/lite#1038]
В приложении перестали отображаться 
стикеры вк, будто их вообще у меня нет, хотя их море, в подсказках сообщений тоже не появляются, исправьте баг, приходится пользоваться оф. вк, хотя я направила вам свою финансовую поддержку!

![upload_2023_01_13_13_55_53_845](https://user-images.githubusercontent.com/122607967/212304061-3681aa8f-e2e7-44c3-838b-1c35eb8d843a.jpg)
![Screenshot_20230113_135143_com vtosters lite](https://user-images.githubusercontent.com/122607967/212304068-85ff040e-e7f5-45ce-bfdb-ec765e8e1a53.jpg)

**Comment by gdlbo** [comment]
Перезайди в приложение

**Comment by Lisa2206** [comment]
Я уже это делала, это началось около недели назад, последнее это наверно удалить и скачать заново приложение, но у меня все настройки слетят и аккаунты
--
Отправлено из Mail.ru для Android пятница, 13 января 2023г., 14:04 +03:00 от gdlbo  ***@***.*** :

**Comment by gdlbo** [comment]
Настройки -> Другое -> Очистка кеша приложения -> Очистить кеш стикеров

**Comment by Lisa2206** [comment]
Тоже не помогло 
--
Отправлено из Mail.ru для Android пятница, 13 января 2023г., 14:09 +03:00 от gdlbo  ***@***.*** :

**Comment by Lisa2206** [comment]
Всё наладилось 
--
Отправлено из Mail.ru для Android пятница, 13 января 2023г., 14:09 +03:00 от gdlbo  ***@***.*** :
