### ISSUE TITLE
Не качает музыку. 

### ISSUE THREAD

**Issue by Urbajaaaa** [vtosters/lite#1040]
Не качает музыку при нажатии на иконку "скачать mp3" просто ничего. Не ошибки не лагов ничего не вылезает какбудто и не нажимал никуда. Раньше все было круто все качал-но это было на других телефонах (тостером я пользуюсь 4-5 го.а/лет за это время сменил 4 телефона сейчас вроде 5 ну хз не суть на старых все было замечательно только позапрошлом при скачке надо было ещё раз нажать через чо качать вроде мп3 и ещё чо-то сейчас же вообще игнор.
Телефон: Honor
Версия: 9 Lite
Процессор: Hisilicon Kirin 659.
Ещё чо добавить надо?.

**Comment by kussaqqqehateyou** [comment]
@Urbajaaaa ну к примеру ещё версию коммита в "о приложении"

**Comment by Urbajaaaa** [comment]
Моя версия VTOSTERS LITE ПОТОМУ ЧТО ОБЫЧНЫЙ НЕ ГРУЗИИ ЛЕНТУ И ВООБЩЕ
ИНТЕРЕТ КАКБУДТО ОТСУСТВУЕТ ХОТЯ Я ПОДКЛЮЧЁН

сб, 14 янв. 2023 г., 0:49 kussaqqqehateyou ***@***.***>:

**Comment by abslike** [comment]
сделай тоже самое

**Comment by abslike** [comment]
настройки Vtosters - в самом низу "О приложении" отправь скриншот что там

**Comment by kussaqqqehateyou** [comment]
@Urbajaaaa версии "vtosters lite" не существует, существует только версия коммита в "о приложении"
