### ISSUE TITLE
Ошибка статуса. 

### ISSUE THREAD

**Issue by Nikitafyt** [vtosters/lite#1043]
**Опишите сам баг**
При включении оффлайн режима, ничего не меняется

**Опишите действия для воспроизведения ошибки**
1.  Зашел в настройки
2. Включил " не отправлять статус онлайна "

**Опишите ожидаемый результат**
Должен отправлять в режим оффлайн

**Скриншот ошибки**
Есть

![Screenshot_20230114-153915](https://user-images.githubusercontent.com/122677860/212471966-7577671d-a76d-4d5e-a9d2-a59dd5b6008b.png)

![Screenshot_20230114-154022](https://user-images.githubusercontent.com/122677860/212471993-4c0df9d4-0498-4962-b86a-15f1f1d855b0.png)

**Информация об устройстве:**
 - Устройство: Tecno spark 7
 - OS: Android 11 |
 - Коммит: eba6c4

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**
Не знаю

**Comment by danyyok** [comment]
Включи принудительный офлайн,после отправки в онлайн тебя сразу же отправит в офлайн
