### ISSUE TITLE
При смене темы на устройстве фон сообщений не меняется

### ISSUE THREAD

**Issue by AureaFox** [vtosters/lite#1045]
**Опишите сам баг**
При смене темы на устройстве (тёмная > светлая, например) фон сообщений в диалогах не меняется. 

**Опишите действия для воспроизведения ошибки**
1. Написать сообщения другу в светлой теме.
2. Свернуть приложение.
3. Дождаться смены темы по расписанию или сменить вручную. 
4. Зайти в тот же диалог.

**Опишите ожидаемый результат**
Фон сообщений будет соответствовать теме устройства.

**Скриншот ошибки**
![Screenshot_2023-01-16-16-14-35-76_9e1a5d6211a0228d32d39446541891f1](https://user-images.githubusercontent.com/28442601/212655091-34837305-a56e-41c7-8a24-420dc98b36d3.jpg)

**Информация об устройстве:**
 - Устройство: realme GT Neo 3T
 - OS: Android 13 | realmeUI 4.0
 - Коммит: eba6c43

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

**Comment by psamur** [comment]
@AureaFox дефолтный баг почти для всех приложений, с ним ничего не сделать - только перезагружать втлайт

**Comment by coff1nzz** [comment]
Точно такая же проблема на ми 9т про, андроид 10.
