### ISSUE TITLE
баги в докбаре и баг после изменений в нем

### ISSUE THREAD

**Issue by Mikola-Kachaw** [vtosters/lite#1047]
![Screenshot_2023-01-16-17-58-02-958_com vtosters lite](https://user-images.githubusercontent.com/88284895/212708257-656aeb45-ff30-48cf-9bb1-4eb3169b0dab.jpg)
![IMG_20230116_180242](https://user-images.githubusercontent.com/88284895/212708831-b0ae6334-25ed-4298-8303-ae3fdeb4d42f.jpg)
на первом скрине 2 кнопки друзья, а на втором друзья это сообщения
версия приложения 0.5.3

**Comment by gdlbo** [comment]
@Mikola-Kachaw Стоит ли франмент по умолчанию?

**Comment by gdlbo** [comment]
Стоит ли франмент по умолчанию?
