### ISSUE TITLE
Не скачивает музыку 

### ISSUE THREAD

**Issue by Urbajaaaa** [vtosters/lite#1049]
1. Обновлял 
2. Перезагружал 
3. Перескачивал
4. 9 андроид 
5. Хонор 9 лайт
6. Тостер лайт
7. Коммит eba6c43
8. Кстати новая обнова (не могу сказать какая) тоже перестала работать если раньше можно было скачать( но вк не обновлялся) то теперь как музыка игнорит 
9. (ЕС чо нажимаю скачать игнорит музыка нету ошибки ничего в крайние срока быстро это решите) 
10. Всё?

**Comment by danyyok** [comment]
Инвалид issue

**Comment by ayonovdenizs** [comment]
@Urbajaaaa По шаблону составь issue.

**Comment by ayonovdenizs** [comment]
@Urbajaaaa По шаблону составь, пожалуйста, так не понятно

**Comment by Urbajaaaa** [comment]
Да не буду я ничо составлять я уже 2 пост делаю и все что-то я надо. Не
хотите решать не надо гспд

вт, 17 янв. 2023 г., 6:33 Denis ***@***.***>:

**Comment by ayonovdenizs** [comment]
Да ты посмотри другие иссуе, там понятнее, а ты просто, извините, насрал сюда. Разработчикам будет понятнее, когда ты составишь по форме и прикрепишь скриншоты

**Comment by Urbajaaaa** [comment]
Да насрал очень много. Но почему я должен мучиться со скачкой почему все
раньше было круто я пользуюсь тостером с 18 года все збс все нрав а тут
такая херня. Д и темболее ВК выкупил тостер 100%

вт, 17 янв. 2023 г., 6:38 Denis ***@***.***>:

**Comment by abslike** [comment]
Beta >
