### ISSUE TITLE
Цвет кнопок на панели навигации

### ISSUE THREAD

**Issue by newspeednova** [vtosters/lite#105]
![IMG_20220404_044711](https://user-images.githubusercontent.com/102933630/161460969-158f93dc-f570-423a-92ad-f05f35d00d66.jpg)
Почти не видно белые кнопки на практически белой панели навигации. На скриншоте она еще серая. В реальности гораздо светлее. Можно сказать только тени кнопок отрисовываются.

**Comment by gdlbo** [comment]
Фича вк

**Comment by newspeednova** [comment]
Но ведь в других модах, основанных на 5й версии, панель была светло серой, а кнопки темно серыми. В том числеии в оригинальном Тостере.
