### ISSUE TITLE
Запускается  не вся музыка 

### ISSUE THREAD

**Issue by Volt567** [vtosters/lite#1052]
**Опишите сам баг**
Запускается не вся музыка , пишит что ошибка воспроизведения, но с интернетом всë нормально . 

**видео ошибки**

**Информация об устройстве **
Имя устройства -Redmi Note 10 Pro

Версия андроид 12
Версия прошивки MIUI 13
13.0.5.0
Версия коммита eba6c43

**Comment by danyyok** [comment]
@Volt567 Не проблема VTL

**Comment by aliveoutside** [comment]
#1051
