### ISSUE TITLE
Долгая загрузка переписки при открытии

### ISSUE THREAD

**Issue by valdomeh** [vtosters/lite#1061]
Открывая с кем то переписку очень долго прогружает переписку.
Очень часто уведомление о новом сообщении в трее висит
А в переписке сообщения нету
Приходится открывать закрывать переписку чтоб сообщение появилось.

![photo_2023-01-20_16-16-41](https://user-images.githubusercontent.com/123165356/213683012-2dede4ab-c95f-4ded-b057-d78da11468a8.jpg)

Samsung s8/android 9

При чистке кэша через SD MAID PRO время прогрузки уменьшается
Обьем памяти занят на 60%.

**Comment by danyyok** [comment]
Переводчик включен?

**Comment by MrNayz** [comment]
Часто происходит тоже самое

**Comment by gdlbo** [comment]
исправлено, скоро будет апдейт с патчем
