### ISSUE TITLE
Редактирование сообщений

### ISSUE THREAD

**Issue by Ra1T13** [vtosters/lite#1065]
Прошу сделать возможность редактировать сообщения, как в оригинальном клиенте

**Comment by psamur** [comment]
@Ra1T13 есть

**Comment by ayonovdenizs** [comment]
![Screenshot_20230125_194401_com vtosters lite](https://user-images.githubusercontent.com/77270222/214579344-36025e88-8db1-4f8f-b26a-ab29473050b5.jpg)
Тыкнуть на свое сообщение никак?
