### ISSUE TITLE
Отсутствие раздела "Недавно прослушанные" во вкладке музыки

### ISSUE THREAD

**Issue by Coredamn** [vtosters/lite#1067]
До недавних пор раздел присутствовал, но затем попросту исчез, все остальные разделы как были, так и остались:

![Screenshot_20230125_233234](https://user-images.githubusercontent.com/123594700/214683953-14948479-35a6-4049-bcf2-b0ec161f9570.jpg)
![Screenshot_20230125_233244](https://user-images.githubusercontent.com/123594700/214683962-3d356385-332f-4d9a-b86e-cb07940f6f63.jpg)

Сбрасывал настройки, переустанавливал клиент VTLite, ничего не помогает, при этом во вкладке "Раздел музыки по умолчанию" в настройках медиаконтента его все еще можно выбрать, вот только открываться будет раздел "Главная".

**Comment by danyyok** [comment]
Раздел был убран из за неработоспособности, похоже забыли убрать его из меню стартовых фрагментов...
