### ISSUE TITLE
Невидимка

### ISSUE THREAD

**Issue by d3zile** [vtosters/lite#1069]
Раньше пользовался приложение vtoster где у меня стояла функция "недавно был в сети " И после перехода на vtlite никак эту функцию не удаётся убрать. 
Подскажите пожалуйста что с этим можно сделать?

**Comment by danyyok** [comment]
@d3zile Скачай VK Мессенджер и оттуда убери офлайн - https://play.google.com/store/apps/details?id=com.vk.im
