### ISSUE TITLE
Вылетает при выборе вкладки Новости

### ISSUE THREAD

**Issue by dlcdjxzy** [vtosters/lite#1072]
**Опишите сам баг**
Вылетает при выборе вкладки "Новости"

**Опишите действия для воспроизведения ошибки**
1. Открыл вкладку "Подарки"
2. Немного пролистал
3. Вышел из приложения и снова зашел
4. Выбрал вкладку "Новости"
5. Вылет

**Опишите ожидаемый результат**
Должна открыться вкладка "Новости"

**Скриншот ошибки**
Приложил видео 

Устройство: OnePlus Nord CE 2 Lite (CPH2409)
OS: OxygenOS 12.1
Коммит: eba6c43

https://user-images.githubusercontent.com/87267125/215257131-c356478f-1d57-4f8d-b051-43d932c56a31.mp4

**Comment by aliveoutside** [comment]
логи в уведомления не появляются?

**Comment by matveytrik** [comment]
> логи в уведомления не появляются?

до этого не появлялись, но сейчас выскочили

[VTL_log_2023-01-29.16-51-48.txt](https://github.com/vtosters/lite/files/10529670/VTL_log_2023-01-29.16-51-48.txt)
