### ISSUE TITLE
проблема с обновлением новостей

### ISSUE THREAD

**Issue by nastyaooop** [vtosters/lite#1078]
не обновляется лента новостей

**Comment by danyyok** [comment]
Инвалид issue,нам ничего не ясно с того что ты сказала,дай нам коммит и полное описание проблемы

**Comment by ayonovdenizs** [comment]
зайди в настройки и следуй по скриншотам
![IMG_20230202_210759_210](https://user-images.githubusercontent.com/77270222/216361990-8e968a51-0a0b-4d85-bc10-dc6649d6e721.jpg)
![IMG_20230202_210801_083](https://user-images.githubusercontent.com/77270222/216362032-a233663f-e390-4e39-8cb3-abcb930ecf71.jpg)
