### ISSUE TITLE
Ошибка отображения фаерки

### ISSUE THREAD

**Issue by YujiFlow** [vtosters/lite#1093]
Случайно обнаружил то, что не отображается фаерка. Пишет что доступа в VT-функциям нет, но на скриншоте совсем иначе
![Screenshot_2023-02-10-16-49-42-875_com vtosters lite](https://user-images.githubusercontent.com/60260435/218108500-6fbb99a7-b852-4786-82ce-53081098be28.jpg)
![Screenshot_2023-02-10-16-50-52-872_com vtosters lite](https://user-images.githubusercontent.com/60260435/218108514-3c1b7684-2c3f-47ea-b043-67a32f7361e9.jpg)
![Screenshot_2023-02-10-16-49-47-886_com vtosters lite](https://user-images.githubusercontent.com/60260435/218108527-a62d3622-f4c3-428b-b29a-36c1a19e02e0.jpg)

**Comment by gdlbo** [comment]
Перезаход решает проблему

Это проблема получения данных с сервера из-за проблем с интернетом

**Comment by YujiFlow** [comment]
Благодарю за помощь
