### ISSUE TITLE
удаляются удалённые сообщения собеседника при обновлении страницы с диалогами. 

### ISSUE THREAD

**Issue by murnyatno** [vtosters/lite#1096]
удаляются удалённые сообщения собеседника при обновлении страницы с диалогами. сначала я вижу сообщение которое удалено, оно помечено как удаленное, но когда я обновляю страницу с диалогами, эти помеченные удаленные сообщения пропадают, исправьте это пожалуйста

**Comment by danyyok** [comment]
@murnyatno Так и должно быть

**Comment by murnyatno** [comment]
но в настройках есть функция оставлять удаленные сообщения, к чему тогда
она?

вс, 12 февр. 2023 г., 13:41 Danyy Okskiy ***@***.***>:

**Comment by danyyok** [comment]
@murnyatno Она оставляет удалённые сообщения

**Comment by murnyatno** [comment]
ну дк она не работает, они изчезают

вс, 12 февр. 2023 г., 13:52 Danyy Okskiy ***@***.***>:
