### ISSUE TITLE
Не работает кнопка "Обновить"

### ISSUE THREAD

**Issue by TheDyaDyaStrahooev** [vtosters/lite#1097]
При входе в приложение появляется окошко с обновлением и в самом низу этого окошка кнопка "Обновить".  При нажатии на неё приложение начинает жутко тормозить и по итогу не обновляется. При перезапуске приложения и устройства проблема не решается. Данная проблема происходит впервые.

**Comment by danyyok** [comment]
@TheDyaDyaStrahooev Информация об устройстве?
(Настройки-Другое->Скопировать инф. об устройстве)

**Comment by TheDyaDyaStrahooev** [comment]
> @TheDyaDyaStrahooevИнформация о богатстве? (Настройки-Другое->Скопировать инф. об наблюдениях)

А что конкретно необходимо написать об устройстве?

**Comment by TheDyaDyaStrahooev** [comment]
Извините, спустя час все заработало, аххаахахахахахах

**Comment by danyyok** [comment]
> Извините, спустя час все заработало, аххаахахахахахах

Отлично,но в следующий раз делая Issue делайте всё по шаблону а не стирайте всё и пишите о своей проблеме (обязательно копируйте инф. об устройстве, нажимая на эту кнопку в настройках VTLite всё автоматически скопируется в буфер обмена,просто вставьте скопированный текст)
