### ISSUE TITLE
Постоянные напоминалки о обновлениях

### ISSUE THREAD

**Issue by Kalkulatorrr** [vtosters/lite#1100]
При каждом открытии приложения появляется окно с информацией о новом обновлении.

Каждый раз, когда открываю приложение появляется это сообщение, даже после неоднократного обновления оно всё равно появляется:
![Screenshot_2023-02-12-19-34-05-48_9e1a5d6211a0228d32d39446541891f1](https://user-images.githubusercontent.com/125207343/218323954-872d4fcc-a6e1-4814-9be5-a89a7c833bb3.jpg)
Пользуюсь с realme c25s, пробовал переустанавливать приложение но все-равно после первого появления такого сообщения снова появляется этот баг.

**Comment by gdlbo** [comment]
Значит не обновилось, обновись вручную
