### ISSUE TITLE
кошмар тут

### ISSUE THREAD

**Issue by stagnacyst** [vtosters/lite#1102]
загрузка диалогов от 1 до 7 минут, выключается музыка после ~20 минут прослушивания(просто закрывается окно в приборной панели), все посты в новостях 3-5 дневной давности![x-XXjQzj95k.jpg](https://user-images.githubusercontent.com/125209059/218331763-ecb8eb59-c5f2-41df-97e5-dec703351b62.jpg)

**Comment by danyyok** [comment]
1.Выключи прокси/VPN/AdGuard
+Если в других клиентах/офвк тоже самое,значит проблема в интернете а не в самом VTLite
2Разреши приложении работать в фоне
3. https://t.me/vtostersfaq/16?single
4.Honor((

**Comment by stagnacyst** [comment]
honor(((((

**Comment by stagnacyst** [comment]
1: Теперь новостях только хуже, при загрузке текст "ошибка".
2: В других клиентах все славно работает.
3: Никакие VPN/Proxy не используются.
4: Скриншот интернета будет прикреплен к сообщению.![RsaHGIoYPv8.jpg](https://user-images.githubusercontent.com/125209059/218332721-d9533e80-443c-4456-832e-79ae42769225.jpg)

**Comment by danyyok** [comment]
> 1: Теперь новостям только хуже, при загрузке текст "ошибка".
> 2: В других клиентах все славно работает.  > 3:Приложению давно разрешено работать в фоне.

1.Переустанови
2.Блин ну тут хз
3.Honor:((((

**Comment by ayonovdenizs** [comment]
у меня _**Информация об устройстве:** 

- Commit: a15cd9b
- Android SDK: 29
- Product: HRY-LX1TRU
- Device: HWHRY-HF
- Board: HRY-L21T
- Manufacturer: HUAWEI
- Brand: HONOR
- Model: HRY-LX1T- Emui Version: EmotionUI_12.0.0_
все работает нормально
