### ISSUE TITLE
Пропали имена в диалоге 

### ISSUE THREAD

**Issue by VOIT18** [vtosters/lite#1107]
**Опишите сам баг**
При обновлении новостей вылезает ошибка

**Опишите действия для воспроизведения ошибки**
1. Обновил ленту интересных новостей
2. Пролистал до конца страницы

**Опишите ожидаемый результат**
Интересная лента должна прогружать результаты

**Скриншот ошибки**

**Скопируйте сюда информацию об устройстве нажав на кнопку "Скопировать информацию об устройстве" в Настройках -> Другое и удалите этот текст**

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

**Comment by danyyok** [comment]
Имена собеседников возле сообщений скоро будут
+Научись делать Issue нормально, а не изменяя только название а остальное пропускать
