### ISSUE TITLE
Вылетает при отображении анимированных стикеров

### ISSUE THREAD

**Issue by KatanaINC** [vtosters/lite#111]

**Comment by KatanaINC** [comment]
Моментальный вылет как только прогрузится анимация, как мне лог скинуть бы узнать,а то я далёк от этого

**Comment by KatanaINC** [comment]
[dumpstate-stats.txt](https://github.com/vtosters/lite/files/8425919/dumpstate-stats.txt)

**Comment by KatanaINC** [comment]
[VTL_log.txt](https://github.com/vtosters/lite/files/8425931/VTL_log.txt)
 Вроде оно

**Comment by gdlbo** [comment]
https://github.com/vtosters/lite/issues/5
