### ISSUE TITLE
Добавьте функцию закрепления диалогов как в обычном вк

### ISSUE THREAD

**Issue by L0kopok0** [vtosters/lite#1110]
Я хочу закрепить сверху чатов диалоги с людьми с которыми общаюсь чаще всего. 
Я не нахожу удобным добавление диалога на рабочий стол.
Занимает ненужное пространство да и выглядит не особо прикольно.
Благодарю за возможность оставить предложения по улучшению клиента

**Comment by ayonovdenizs** [comment]
@L0kopok0 повторяющийся issue. #12
