### ISSUE TITLE
Пикселятся картинки везде

### ISSUE THREAD

**Issue by dasurin** [vtosters/lite#1126]
**Опишите сам баг**
Пикселятся картинки везде, где только можно: на аватарках, в постах, даже в музыке. но стоит нажать на картинку - она покажется в полном кач-ве. невозможно из-за этого просмотреть картинку без нажатия на неё. очень неудобно

**Опишите действия для воспроизведения ошибки**
1. Зашёл в приложение
2. Открыл ленту новостей

**Опишите ожидаемый результат**
Картинки не выглядят как кучка пикселей

**Скриншот ошибки**
![Screenshot_2023-02-27-08-44-13-53_9e1a5d6211a0228d32d39446541891f1](https://user-images.githubusercontent.com/126443891/221485390-9cd36f66-85a2-4960-b92f-d10ae7e2bb77.jpg)
![Screenshot_2023-02-27-08-44-16-18_9e1a5d6211a0228d32d39446541891f1](https://user-images.githubusercontent.com/126443891/221485399-360e70d9-6fcc-448c-a578-648099ff9e9b.jpg)
![Screenshot_2023-02-27-08-48-03-58_9e1a5d6211a0228d32d39446541891f1](https://user-images.githubusercontent.com/126443891/221485402-bbd8a425-1b7a-4016-853f-9fd35cc6bcb1.jpg)
![Screenshot_2023-02-27-08-48-21-29_9e1a5d6211a0228d32d39446541891f1](https://user-images.githubusercontent.com/126443891/221485403-10757e35-a5ec-4164-b96b-885217fb89a5.jpg)

**Информация об устройстве:** 

- Commit: efb909c
- Android SDK: 31
- Product: RMX3393RU
- Device: RE879EL1
- Board: RM6877
- Manufacturer: realme
- Brand: realme
- Model: RMX3393

**Comment by danyyok** [comment]
Настройки-Медиаконтент->Сжимать фотографии
И как это вы не нашли инф. об устройстве? Она расположена в самом низу.
Если отключение "Сжимать фотографии" не поможет, сбросьте все настройки или переустановите приложение

**Comment by quick-wq** [comment]
Случайно экономия трафика в настройках не включена?
Настройки - Основные - Экономия трафика

**Comment by spanchbobr** [comment]
Подтверждаю. Такой же баг на Poco x3 nfc офиц.прошивка MIUI
Баг пропадает, если сидеть в приложении через вай фай.
Экономия трафика, сжатие картинок - всё отключено, приложение переустанавливалось.

**Comment by danyyok** [comment]
#1016
