### ISSUE TITLE
Ошибка при скачивании музыки

### ISSUE THREAD

**Issue by GoldrySeon** [vtosters/lite#1127]
**Опишите сам баг**
При скачивании музыки через "Скачать как mp3" приложение иногда крашится с ошибкой

**Опишите действия для воспроизведения ошибки**
Нажать "Скачать как mp3" (чаще всего случается, когда наблюдается замедление интернета)

[VTL_log_2023-02-27.20-31-50.txt](https://github.com/vtosters/lite/files/10842623/VTL_log_2023-02-27.20-31-50.txt)

**Comment by aliveoutside** [comment]
#1133
