### ISSUE TITLE
Ошибка с просмотром историй

### ISSUE THREAD

**Issue by Nikitos22222** [vtosters/lite#1129]
Ошибка с просмотром историй

При заходе в приложение VTlite и попытке посмотреть истории. Случается баг в некоторых группах когда посмотришь первую историю ,она будет дублироваться на протяжении всех других историй, хотя содержимое тех историй уже другое.

Ожидаемым результатом бы хотелось фикс этого бага не могу сказать точно он глобальный или только у меня.

Это история скриншот тут не поможет не будет ясна суть проблемы.

Это не текстовая ошибка после совершения этой ошибки никакой информации не выходит.
 
Не могу сказать из-за чего она происходит , но заметил что она появилась 2-3 месяца назад. Сначала она была в одном сообществе, теперь уже в двух.

**Comment by gga21u142** [comment]
Поддерживаю, все работало до последнего обновления, после него стало невозможно смотреть истории.

**Comment by xroll71** [comment]
Тоже самое

**Comment by gdlbo** [comment]
исправлено
