### ISSUE TITLE
Ошибка при добавлении трека в свой плейлист 

### ISSUE THREAD

**Issue by Volt567** [vtosters/lite#1130]
**Опишите сам баг**
При добавлении трека в плейлист выдает ошибку 

** видео об ошибке**
<!-- Error while uploading Screenrecorder-2023-03-02-00-35-15-966.mp4 -- 
**Информация об устройстве**
 Версия прошивки: miui 13.0.5
Версия андроид : 12 
Версия коммита : efb909c

**Comment by danyyok** [comment]
Гениально, вольт

**Comment by Volt567** [comment]
Не а как видео добавить,на гитхаб скриншот получается в видео нет

**Comment by danyyok** [comment]
> Не а как видео добавить,на гитхаб скриншот получается в видео нет 

Просто дай логи
