### ISSUE TITLE
Ошибка при скачивание е mp3

### ISSUE THREAD

**Issue by sergei91md** [vtosters/lite#1133]
**Опишите сам баг**
При нажатий на скачать как mp3 приложение закрывается с ошибкой.
[VTL_log_2023-03-05.09-15-25.txt](https://github.com/vtosters/lite/files/10891006/VTL_log_2023-03-05.09-15-25.txt)

**Comment by n1cholaspoole** [comment]
Не закрывается

**Comment by aliveoutside** [comment]
0f298b4fe3113cc7f579fce506f2fa1e949926d6 
будет исправлено в следующем обновлении
