### ISSUE TITLE
Не расшифровывает шифровку

### ISSUE THREAD

**Issue by Wperdex** [vtosters/lite#1135]
**Опишите сам баг**
Закодированное шифрованное сообщение не расшифровывает даже введение ключа. Текст сообщения видно лишь при его пересылке.

**Скриншот ошибки**
![Screenshot_2023-03-05-19-48-03-816-edit_com vtosters lite](https://user-images.githubusercontent.com/102802937/222975012-e201a2be-879f-4ef0-b9ce-e8f0e824f620.jpg)

**Comment by danyyok** [comment]
Для применения ключа нужно перезагрузить список чатов/приложение
А то, что при ответе оно видно, странно
