### ISSUE TITLE
Ошибка автоматической переключения тёмной темы 

### ISSUE THREAD

**Issue by MDMA454** [vtosters/lite#1136]
**Опишите сам баг**
При автоматической переключении темы по времени в настройках телефона с вверху остаёться часть темной темы

**Опишите действия для воспроизведения ошибки**
1. Выхожу из клиента с тёмной темы, после переключения остаються черная полоска возле новостей и интересные 

**Опишите ожидаемый результат**
Полное переключение темы в новостной ленте 

![Screenshot_2023-03-07-10-38-57-272_com android settings](https://user-images.githubusercontent.com/62618273/223369015-d38f768e-6eec-4862-88fd-59a811da87a1.jpg)
![Screenshot_2023-03-07-10-33-06-043_com vtosters lite](https://user-images.githubusercontent.com/62618273/223369024-9ee68034-82a9-42ec-8996-eef4d1b34c00.jpg)

Скопировать информацию об устройстве" в Настройках -> Redmi note 10s

**Comment by gdlbo** [comment]
Будет исправлено в следующем обновлении
