### ISSUE TITLE
Долгая или бесконечная загрузка чатов

### ISSUE THREAD

**Issue by MrNayz** [vtosters/lite#1140]
Достаточно часто происходит проблема, что при открытии любого чата идёт бесконечная или долгая загрузка 

-

Исправление данной проблемы

![IMG_20230311_091519.jpg](https://user-images.githubusercontent.com/123476723/224468482-9be7f31c-6fb2-4413-9e0e-51589f4171e4.jpg)

Poco x4 GT

**Comment by ayonovdenizs** [comment]
invalid issue
