### ISSUE TITLE
Некорректно переключается светлая/темная тема

### ISSUE THREAD

**Issue by crick-ru** [vtosters/lite#1144]
**Опишите сам баг**
Если в шторке переключить светлую/темную тему во время работы vtosters, то верхний, то нижний бар остается светлым при темной теме или теиным при светлой теме.

**Опишите действия для воспроизведения ошибки**
1. Запустил vtosters
2. В шторке переключил системную тему с темной на светлую или наоборот
3. Все приложение переключается вместе с системой, а верхний или нижний бар (рандомно) не переключается.

**Опишите ожидаемый результат**
Смена темы должна происходить корректно

**Скриншот ошибки**
![Screenshot_20230312-234806](https://user-images.githubusercontent.com/1965253/224573236-cad9f604-d2e5-46bc-b2a8-d8cab918c587.png)

![Screenshot_20230312-234715](https://user-images.githubusercontent.com/1965253/224573243-5843179f-1bbe-4d20-822d-33dcc724e976.png)

![Screenshot_20230312-233340](https://user-images.githubusercontent.com/1965253/224573251-59de2051-fecb-4826-8f32-12fedecf0986.png)

**Информация об устройстве**
- Commit: efb909c
- Android SDK: 29
- Product: parker_reteu
- Device: parker
- Board: parker
- Manufacturer: motorola
- Brand: motorola
- Model: motorola one zoom

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**
Есть [похожий баг](https://github.com/vtosters/lite/issues/1081), но там мне посоветовали создать новый issue

**Comment by crick-ru** [comment]
Если выгрузить приложение и зайти снова, бар отображается нормально.

**Comment by gdlbo** [comment]
Будет исправлено в следующей версии
