### ISSUE TITLE
Некорректная работа оффлайн режима

### ISSUE THREAD

**Issue by BlvckRacist** [vtosters/lite#1145]
Некорректная работа "не отправлять статус онлайн" 

1.  Включить "не отправлять статус онлайн"
2.  Отправить сообщение, на первый раз через 5 минут будешь оффлайн(был в сети 5 минут назад", последующие появления онлайн, отправляют в оффлайн через 2-3 минуты с статусом"был в сети только что"

Стабильно после онлайна работало "был в сети 5 минут назад"

**Скриншот ошибки**

**Информация об устройстве:** 

- Commit: efb909c
- Android SDK: 33
- Product: panther
- Device: panther
- Board: panther
- Manufacturer: Google
- Brand: google
- Model: Pixel 7

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

**Comment by gdlbo** [comment]
Возможно вк снова корректирует работу онлайна при загрузке/отправке сообщений

Это не исправить кроме как не открывать вкладку сообщений
