### ISSUE TITLE
Проблема со скачкой mp3 

### ISSUE THREAD

**Issue by FunCakee** [vtosters/lite#1146]
Пытаюсь скачать песню, вроде скачивается и загружается 
![Screenshot_20230313_234931](https://user-images.githubusercontent.com/98389344/224786867-1dc8b517-3231-4faa-b1a7-0d2994836965.jpg)
Но когда нажимаю чтобы открыть эту песню ничего не происходит, захожу в плеер но там тоже ничего нету
![Screenshot_20230313_234919](https://user-images.githubusercontent.com/98389344/224787091-ef6b9f42-20da-4fe5-8fee-a36620e32673.jpg)
В Кеше тоже не находится не знаю что делать уже около полугода пытался разобраться но так и не получилось
![Screenshot_20230313_234944](https://user-images.githubusercontent.com/98389344/224787217-f0943d63-5824-494f-a6ee-b100f9dc555f.jpg)

**Comment by GooDoG337** [comment]
@FunCakee В папке Music смотрел?
