### ISSUE TITLE
Непрочитанные сообщения приходят бесконечно

### ISSUE THREAD

**Issue by Aleksahaa** [vtosters/lite#1149]
Прихоят старые непрочитанные сообщения

1. Захожу в приложение
2. Зайдя в диалоги начинают бесконечно приходить старые не прочитанные сообщения
3. И при этом начинают не работать диалоги (новые сообщения не приходят), написано "Обновление..."
4. Пока не выйдешь из приложения старые непрочитанные сообщения так и будут приходить

**Опишите ожидаемый результат**
Хочется чтобы пофиксили данный баг, т.к. невозможно никому даже написать сообщение

Прилагаю скриншот с данными о телефоне
![Screenshot_2023-03-16-20-32-55-575_com android settings](https://user-images.githubusercontent.com/128076802/225704903-fc2a36c7-1185-42ec-9636-7cb4d76403ac.jpg)

**Comment by gdlbo** [comment]
исправлено, скоро будет апдейт с патчем
