### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by MikeGR97** [vtosters/lite#115]
Логи
[VTL_log.txt](https://github.com/vtosters/lite/files/8439665/VTL_log.txt)

**Comment by gdlbo** [comment]
При каких действиях происходит краш? Можешь записать видео?

**Comment by MikeGR97** [comment]
> 

Увидел в оповещениях при свёрнутом приложении

**Comment by Qqweshka** [comment]
[VTL_log.txt](https://github.com/vtosters/lite/files/8473074/VTL_log.txt)
Так же довольно часто встречается краш вк, как при открытом диалоге во время печати, так и в свёрнутом виде, но чаще первый вариант
