### ISSUE TITLE
Ошибка загрузки видео истории

### ISSUE THREAD

**Issue by RoodyRayne** [vtosters/lite#1150]
**Опишите сам баг**
При загрузке видео истории происходит

**Опишите действия для воспроизведения ошибки**
1. Загрузил видео истории

**Опишите ожидаемый результат**
Публикация видео истории

**Скриншот ошибки**
![Screenshot_2023-03-17-11-15-48-274_com vtosters lite](https://user-images.githubusercontent.com/128110396/225795175-890eb18a-3be9-49f9-baee-0e9e15d923c3.jpg)

**Скопируйте сюда информацию об устройстве нажав на кнопку "Скопировать информацию об устройстве" в Настройках -> Другое и удалите этот текст**

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

**Comment by gdlbo** [comment]
исправлено ...??

**Comment by RoodyRayne** [comment]
Конечно, 100 лет назад ещё
