### ISSUE TITLE
Кнопка закрытия перекрывает кнопку профиля в приложении Знакомства 

### ISSUE THREAD

**Issue by gawcat** [vtosters/lite#1151]
**Опишите сам баг**
Не могу зайти в свой профиль

**Опишите действия для воспроизведения ошибки**
1. Не могу зайти в свой профиль в сервисе знакомства.

**Опишите ожидаемый результат**
Интересная лента должна прогружать результаты

**Скриншот ошибки**
![Screenshot_2023-03-17-18-23-42-283-edit_com vtosters lite](https://user-images.githubusercontent.com/95079039/225947956-333b115b-01e5-45b0-8d7d-4f4eae64201f.jpg)

**Информация об устройстве:** 

- Commit: efb909c
- Android SDK: 31
- Product: joyeuse_global
- Device: joyeuse
- Board: joyeuse
- Manufacturer: Xiaomi
- Brand: Redmi
- Model: Redmi Note 9 Pro- Miui Version Code: 13
- Miui Version Name: V130
- Miui Version Incremental Code: V13.0.4.0.SJZMIXM

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

**Comment by gdlbo** [comment]
Не фиксится, проблема вк
