### ISSUE TITLE
Ошибка загрузки сообщений

### ISSUE THREAD

**Issue by Swwwofaj** [vtosters/lite#1154]
При входе на сообщения идёт бесконечная загрузка и потом выдаёт ошибку.

1. Выключила wi-fi и включала мобильный интернет и наоборот. 
2. Очистила кеш сообещний.
3. Переустановила приложение. 

Скриншот данной ошибки
![upload_2023_03_18_14_21_58_395](https://user-images.githubusercontent.com/128225408/226102186-b6cfeadb-ee5d-4144-91d8-229df0b288da.jpg)

**Comment by teaspwn** [comment]
@Swwwofaj щас везде в приложениях вк не работает, только в вебе
