### ISSUE TITLE
Ошибка загрузки сообщений

### ISSUE THREAD

**Issue by sMaksSs1** [vtosters/lite#1155]
Не загружаются сообщения, пробовал переустанавливать, сброс настроек, менял сеть. Музыка и новости, и остальные функции работают в норме
![Screenshot_2023-03-18-15-36-16-815_com vtosters lite](https://user-images.githubusercontent.com/128230204/226106515-67f39564-40f5-472d-8d8a-bc7a9220bc8b.jpg)

**Comment by GooDoG337** [comment]
Проблема у серверов ВК, как я знаю
