### ISSUE TITLE
Черный экран когда посмотришь истории

### ISSUE THREAD

**Issue by valdomeh** [vtosters/lite#1159]
При просмотре историй,становится черный экран когда открываешь записи сообщества или жмёшь еще

1. до просмотра истории все работает исправно, только просмотришь одну историю, становится черный экран на новые окна ,по типу сообщения музыка ,разворачивание постов, просмотр профилей.

хотелось бы чтоб пропал данный баг, ведь после просмотра историй неприятно перезапускать vtlite чтоб с комфортом смотреть предложку новостей и сообществ.

видео бага прикрепляю через гугол диск https://drive.google.com/file/d/1-0QBh09qpt7fcqC0vmXs0KRFTQoJkk8o/view?usp=share_link

Samsung s8 g950f
данный баг и на голой ненастроенной версии vtlite.

**Comment by gdlbo** [comment]
исправлено
