### ISSUE TITLE
Ошибка обновлении ленты новостей

### ISSUE THREAD

**Issue by x1ott** [vtosters/lite#1160]
Не работает лента,не обновляется,не появляются новые посты,есть только те которые появились в моменте авторизации в приложении

**Comment by Serdobine** [comment]
интересная лента отключена?

**Comment by youdfool** [comment]
Что делать то в итоге?

**Comment by danyyok** [comment]
> Что делать то в итоге?

https://t.me/vtostersfaq/16?single

**Comment by gadzhi-m** [comment]
> > Что делать то в итоге?
> 
> https://t.me/vtostersfaq/16?single

![Screenshot_20230327-133410_4PDA](https://user-images.githubusercontent.com/95399940/227872192-f437890a-e1ad-4fac-82f6-04aad9f80006.png)
Интересные новости в втлайт и других модах или оригинале по разному работают.
Очень хотелось чтоб починили

**Comment by gdlbo** [comment]
Нечего чинить, интересная лента работает идентичным способом что и в официальном клиенте ВКонтакте. Не нравится интересная лента - используйте временную

**Comment by gadzhi-m** [comment]
Вы не правы. На 4пда об этом писали множество раз
![Screenshot_20230327-205853_4PDA](https://user-images.githubusercontent.com/95399940/227982347-29360c3e-01a8-4a34-827f-c02e89d17277.png)
![Screenshot_20230327-210435_4PDA](https://user-images.githubusercontent.com/95399940/227982367-db9a8249-47b2-44e7-8fad-1b3d17b069d4.png)
![Screenshot_20230327-210820_4PDA](https://user-images.githubusercontent.com/95399940/227982377-91bba2a5-4442-4b29-880f-87bcc88c94aa.png)

**Comment by gadzhi-m** [comment]
Хорошо, не буду спорить, но добавлю последнее. Если вы проверяете на оф, как там работает, то вы не заметите разницу, потому что такое поведение сохранится на какое то время и в офвк. Нужно на несколько дней остатся на оф.

**Comment by icynstant** [comment]
Интересная лента работает не также как в вк, либо также как в старой версии, в новой версии вк она работает отлично (#1510). Да и достаточно давно всё работает нормально в оф версии вк, давно пользуюсь и не было проблем. Прошу доработать.

**Comment by ayonovdenizs** [comment]
@icynstant https://github.com/vtosters/lite/issues/1510#issuecomment-1831906593
