### ISSUE TITLE
Ошибочная покраска интерфейса на Android 5.1

### ISSUE THREAD

**Issue by Serega2024** [vtosters/lite#1168]
Есть планшет Amazon Kindle. В России довольно экзотическая штука, в мире популярен. На нем левое меню ВТостерс (иконки) красного цвета. Это явно так не задумывалось 

Не в каких-то случаях, а постоянно.
Также красным подписаны названия исполнителей и песен в Моей Музыке

Спасибо за этот чудесный проект!

*********
**Device info:** 

- Commit: efb909c
- Android SDK: 22
- Product: full_giza
- Device: giza
- Board: giza
- Manufacturer: Amazon
- Brand: Amazon
- Model: KFGIWI
![Screenshot_2023-03-30-15-58-29](https://user-images.githubusercontent.com/129393070/228830583-cb2cb202-71a8-4cd1-ae76-647a96708c60.png)

![Screenshot_2023-03-30-16-09-54](https://user-images.githubusercontent.com/129393070/228832069-de876599-cf8c-4634-829d-5328f5823672.png)

**Comment by gdlbo** [comment]
привет, у тебя ещё остался этот девайс? нужно проверить билд с возможным фиксом

https://t.me/vtosterschat/3466985/3559143
