### ISSUE TITLE
Лента новостей не обновляется .

### ISSUE THREAD

**Issue by sikiroshin** [vtosters/lite#1172]
Новостная лента перестала обновляться .

**Comment by JinnJopino** [comment]
То же самое .Пытался в настройках менять частоту обновления ленты и её кэширование ,но ничего не помогает . .

Commit: https://github.com/vtosters/lite/commit/21fc1713635b9383c90e67f4f63cfcf6fefab8bd
Android SDK: 33
Product: a51nsser
Device: a51
Board: exynos9611
Manufacturer: samsung
Brand: samsung
Model: SM-A515F
OneUi Major Version: 5
OneUi Minor Version: 1.0

**Comment by abslike** [comment]
@JinnJopino повторюсь, скиньте скриншот настроек историй

**Comment by JinnJopino** [comment]
@abslike Где он находится ?

**Comment by abslike** [comment]
@JinnJopino раздел лента

**Comment by JinnJopino** [comment]
@abslike А ,эти истории .Вот пожалуйста 
![Screenshot_20230415_181745_VTLite](https://user-images.githubusercontent.com/127394944/232226270-6e745e54-54c4-4d39-bf95-6d30ad6e5480.jpg)
