### ISSUE TITLE
Не прогружаются, виснут диалоги, проверено на разном инете и на разных устройствах 

### ISSUE THREAD

**Issue by Rustyfurry** [vtosters/lite#1173]
**Опишите сам баг**
При обновлении новостей вылезает ошибка

**Опишите действия для воспроизведения ошибки**
1. Обновил ленту интересных новостей
2. Пролистал до конца страницы

**Опишите ожидаемый результат**
Интересная лента должна прогружать результаты

**Скриншот ошибки**

**Скопируйте сюда информацию об устройстве нажав на кнопку "Скопировать информацию об устройстве" в Настройках -> Другое и удалите этот текст**

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

**Comment by danyyok** [comment]
Пересоздайте Issue ПО ШАБЛОНУ
