### ISSUE TITLE
Ошибка обновлении ленты новостей

### ISSUE THREAD

**Issue by sikiroshin** [vtosters/lite#1175]
**Опишите сам баг**
При обновлении новостей вылезает ошибка

**Опишите действия для воспроизведения ошибки**
Лента новостей не обновляется

**Опишите ожидаемый результат**
Чтобы лента вновь обновлялась 

Realme 6s 4/64
Realme UI

**Comment by JinnJopino** [comment]
То же самое .Пытался в настройках менять частоту обновления ленты и её кэширование ,но ничего не помогает . .

Commit: https://github.com/vtosters/lite/commit/21fc1713635b9383c90e67f4f63cfcf6fefab8bd
Android SDK: 33
Product: a51nsser
Device: a51
Board: exynos9611
Manufacturer: samsung
Brand: samsung
Model: SM-A515F
OneUi Major Version: 5
OneUi Minor Version: 1.0
