### ISSUE TITLE
Вк "зажевывает" диалоги

### ISSUE THREAD

**Issue by Tlalocelotl** [vtosters/lite#1176]
**Опишите сам баг**
При обновлении страницы диалогов, некоторые просто исчезают и ищутся только через поиск. Как я понимаю, клиент вк считает их за старые диалоги, в которые ничего не писали, хотя в некоторых подобных чатах активно ведется разговор.

**Опишите действия для воспроизведения ошибки**
1. Закрыть втостерс
2. Подождать несколько часов 
3. Открыть вкладку с сообщениями

**Опишите ожидаемый результат**
диалоги не должны зажевываться программой непонятно куда.

**Скриншот ошибки**

**Скопируйте сюда информацию об устройстве нажав на кнопку "Скопировать информацию об устройстве" в Настройках -> Другое и удалите этот текст**

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

**Comment by ayonovdenizs** [comment]
Данные диалоги были закреплены?
