### ISSUE TITLE
Не включается  открытие ссылок по умолчанию 

### ISSUE THREAD

**Issue by no3rk** [vtosters/lite#1177]
Зайдя в настройки ВК появляется окошко "установить открытие ссылок по умолчания", перейдя в настройки телефона не все поддерживаемые ссылки можно включить, при повторном заходе в настройки ВК снова появляется окошко

**Опишите действия для воспроизведения ошибки**
1. Зайти в настройки ВК
2. Открыть настройки телефона
3. Открыть поддерживаемые  веб адреса
4. Переключить все тумблер
5. Вернуться в пункт 1

**Опишите ожидаемый результат**
Должны срабатывать тумблеры поддерживаемых ссылок, и пропадать окошко в настройках ВК

**Видео ошибки**
https://youtu.be/8MDD9SoqXTM

**Информация об устройстве:** 

- Commit: cd08354
- Android SDK: 33
- Product: g0sxxx
- Device: g0s
- Board: s5e9925
- Manufacturer: samsung
- Brand: samsung
- Model: SM-S906B
- OneUi Major Version: 5
- OneUi Minor Version: 1.0

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

**Comment by gdlbo** [comment]
Приложение определяет выдано ли разрешение на открытие vk.com, а у тебя система сбрасывает почему-то открытие vk.com

Возможно стоит офвк и надо у него забрать права на открытие ссылок, либо я не знаю ибо это выглядит крайне странно и явно не проблема VTLite

**Comment by no3rk** [comment]
Офвк не стоит, на прошлой версии втлайт такого не было

вс, 2 апр. 2023 г., 12:21 gdlbo ***@***.***>:
