### ISSUE TITLE
Неправильный цвет сообщения в диалогах с темной темой

### ISSUE THREAD

**Issue by Maitrog** [vtosters/lite#1178]
**Опишите сам баг**
Когда включаю темную в приложении, то сообщения отправленные мной остаются светлыми

**Опишите действия для воспроизведения ошибки**
1. Включить темную тему в приложении 
2. Открыть диалог
3. Отправить сообщение

**Опишите ожидаемый результат**
Цвет сообщения соответствует темной теме

**Скриншот ошибки**
![Screenshot_20230402-121736](https://user-images.githubusercontent.com/35650757/229344428-301eca17-98e4-469f-96ec-c5f023a2ceb9.png)

**Информация об устройстве:** 

- Commit: cd08354
- Android SDK: 33
- Product: cheetah
- Device: cheetah
- Board: cheetah
- Manufacturer: Google
- Brand: google
- Model: Pixel 7 Pro

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

**Comment by gdlbo** [comment]
Перезаход помогает?

**Comment by abslike** [comment]
@Maitrog не баг, перезапусти приложение

**Comment by Maitrog** [comment]
Перезаход помогает, спс. Но это баг)
