### ISSUE TITLE
Редактирование новостей

### ISSUE THREAD

**Issue by holeech** [vtosters/lite#1179]
Сделайте так чтобы можно было редактировать раздел новостей.
![Screenshot_2023-04-02-13-03-12-615_com vtosters lite](https://user-images.githubusercontent.com/57586115/229346514-c7ad1811-8ee6-479e-b6d6-d10f28612d10.jpg)
Я имею ввиду вот эти поля на скриншоте: Екатеринбург, Нижний Новгород, Казань, Футбол. Хочется либо совсем их убрать, либо заменить на свои.

**Comment by gdlbo** [comment]
Это можно делать в веб версии вконтакте

**Comment by danyyok** [comment]
Open vtl settings😭😭🤯
