### ISSUE TITLE
Ошибка загрузки диалогов

### ISSUE THREAD

**Issue by Arrtemm** [vtosters/lite#1187]
**Опишите сам баг**
Долго происходит процесс загрузки  диалогов,  отправка сообщений, всё остальное грузится быстро

**Опишите действия для воспроизведения ошибки**
1. Запустил vkTost

**Опишите ожидаемый результат**
Быстрая загрузка

**Скриншот ошибки**
![Screenshot_2023-04-03-17-27-42-246_com vtosters lite](https://user-images.githubusercontent.com/129760446/229524136-3c03d30d-2193-4c65-80d3-1ade6d153a77.jpg)

**Скопируйте сюда информацию об устройстве нажав на кнопку "Скопировать информацию об устройстве" в Настройках -> Другое и удалите этот текст**
**Информация об устройстве:** 

- Commit: cd08354
- Android SDK: 29
- Product: lavender_ru
- Device: lavender
- Board: sdm660
- Manufacturer: Xiaomi
- Brand: xiaomi
- Model: Redmi Note 7
- Miui Version Code: 11
- Miui Version Name: V125
- Miui Version Incremental Code: V12.5.1.0.QFGRUXM

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**
Нету

**Comment by danyyok** [comment]
Переустанови клиент/перезайди в аккаунт

**Comment by WeSTManCoder** [comment]
Попробовал, ничего не помогает
