### ISSUE TITLE
Не заходит во вкладку "VT функции"

### ISSUE THREAD

**Issue by Monax112** [vtosters/lite#1188]
**Опишите сам баг**
Бесконечная загрузка

**Опишите действия для воспроизведения ошибки**
1. Нажать на вкладку " VT функции "

**Опишите ожидаемый результат**
Дополнительные функции  VT

**Скриншот ошибки**
![Screenshot_2023-04-03-19-47-17-731_com vtosters lite](https://user-images.githubusercontent.com/129769055/229545408-7b3784b2-7f1d-483e-a304-049ea8afa88d.jpg)

**Скопируйте сюда информацию об устройстве нажав на кнопку " Redmi note 8 pro

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

**Comment by danyyok** [comment]
Можете пересоздать Issue по шаблону?
