### ISSUE TITLE
Долгая загрузка диалогов (от 2 секунд до минуты)

### ISSUE THREAD

**Issue by Komanukechaann** [vtosters/lite#1192]
**Опишите сам баг**
Когда открываю диалог — загрузка, очень долгая, а затем, когда пишу сообщение, то оно долго доходит, хотя интернет стабильно хороший (такое "плохое соединение" только в этом приложении).

**Опишите действия для воспроизведения ошибки**
1. Открыла окно мессенджера и стала ждать загрузки 
2. Открыла диалог
3. Началась долгая прогрузка диалога
4. Наконец загрузился диалог, написала сообщение и снова загрузка — сообщения 

**Опишите ожидаемый результат**
Быстрая загрузка, не более 5-7 секунд

Мое устройство Vsmart 4 Joy+ 

Не знаю почему это происходит, но долго прогружается не только сам диалог, но и окно мессенджера, окно мессенджера обновляется ещё дольше, чем диалоги, хотя вот уведомления по прежнему работают хорошо. Интернет вообще отличный, так что сомневаюсь, что дело в нём. В приложении вконтакте такого нет и обновление происходит в течении нескольких секунд буквально.
!!!!!!(Ошиблась в названии темы. От восьми секунд до минуты)

**Comment by danyyok** [comment]
https://t.me/vtosters_faq/108
