### ISSUE TITLE
Голосовые не проигрываются на скорости 1.5х и 2х

### ISSUE THREAD

**Issue by amebster69** [vtosters/lite#1197]
**Опишите сам баг**
При проигрывании голосовых на 1,5x и 2x выдает ошибку 

**Опишите действия для воспроизведения ошибки**
1. Нажал на смену скорости голосового сообщения
2. Выдало ошибку

**Опишите ожидаемый результат**
Голосовое сообщение должно проигрываться на скорости 1,5x и 2x

**Скриншот ошибки**

**Скопируйте сюда информацию об устройстве нажав на кнопку "Скопировать информацию об устройстве" в Настройках -> Другое и удалите этот текст**

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

**Comment by tangenx** [comment]
@amebster69 Скриншот/текст ошибки?

**Comment by amebster69** [comment]
Не удалось воспроизвести голосовое сообщение. Проверьте соединение и повторите попытку.
