### ISSUE TITLE
Размытие/пикселизация/загрузка в низком разрешении картинок

### ISSUE THREAD

**Issue by spanchbobr** [vtosters/lite#1201]
В ленте, в музыке - все картинки с низким разрешением.

![Screenshot_2023-04-12-16-56-27-267_com.vtosters.lite.jpg](https://user-images.githubusercontent.com/87472239/231480921-0b747cca-a0ec-46da-8d97-635d852eeb76.jpg)

![Screenshot_2023-04-12-16-56-40-638_com.vtosters.lite.jpg](https://user-images.githubusercontent.com/87472239/231480919-2811e9c0-6c95-4ae1-8d1d-baeb41f90d53.jpg)

Смартфон Poco X3 NFC с официальной прошивкой MIUI. Проблема наблюдалась как на 11 андроид, так и после обновления на 12 андроид.

При нажатии в ленте на картинку - картинка открывается в нормальном качестве.

Приложение переустанавливалось. Режим экономии трафика выключен, так и выключено сжатие фотографий в медиаконтете. 
Баг пропадает если использовать интернет от вай-фай, а не от сим-карты. Соответственно проблема где-то там.
Также скажу, что проблема наблюдается и на старых версиях приложения.

Информация об устройстве в скриншоте:
![Screenshot_2023-04-12-18-26-32-190_com.android.settings.jpg](https://user-images.githubusercontent.com/87472239/231506310-a5cf155c-c564-409c-9588-3c090c9e96bb.jpg)

**Comment by danyyok** [comment]
Информация об устройстве?
(Настройки-Другое)

**Comment by Godfather06022023** [comment]
Проверь включена у тебя эта функция или нет. Если включена, то выключи

![Screenshot_20230428-133756_VTLite](https://user-images.githubusercontent.com/131881634/235073476-f92f1e4b-10a0-4ff2-a879-86f0e3992488.jpg)
