### ISSUE TITLE
После выхода из "Воспоминания" приложение умирает

### ISSUE THREAD

**Issue by danyyok** [vtosters/lite#1203]
**Опишите сам баг**
После выхода из "Воспоминания" (ничего не делая) приложение умирает и начинает зависать, экран становится черным

**Опишите действия для воспроизведения ошибки**
1. Зашёл в "Воспоминания"
2. Вышел из "Воспоминания"

**Опишите ожидаемый результат**
Приложенте не должно умирать после выхода из воспоминаний

**Скриншоты**
![Screenshot_2023-04-13-21-56-44-738_com.vtosters.lite.jpg](https://user-images.githubusercontent.com/110027540/231832028-a74e56b5-c86c-4c1b-8414-b02e3b5e3395.jpg)
![Screenshot_2023-04-13-21-56-32-399_com.vtosters.lite.jpg](https://user-images.githubusercontent.com/110027540/231832065-af1eee39-ff12-4462-95b7-e7972425623b.jpg)
![Screenshot_2023-04-13-21-56-57-414_com.vtosters.lite.jpg](https://user-images.githubusercontent.com/110027540/231832107-e09c7a6f-38a4-4030-8fe7-95911e511190.jpg)

**Информация об устройстве:** 

- Commit: 21fc171
- Android SDK: 28
- Product: ysl
- Device: ysl
- Board: ysl
- Manufacturer: Xiaomi
- Brand: xiaomi
- Model: Redmi S2
- Miui Version Code: 10
- Miui Version Name: V12
- Miui Version Incremental Code: V12.0.2.0.PEFMIXM

**Comment by aliveoutside** [comment]
не воспроизводится

**Comment by danyyok** [comment]
> не воспроизводится

Интересно, каждый раз воспроизводится у меня
