### ISSUE TITLE
Ошибка обновлении ленты новостей

### ISSUE THREAD

**Issue by dvyctory** [vtosters/lite#1204]
Во всех историях вылазит одна и та же, одного человека. Ошибка не исчезает

1. Открыла истории
2. Пролистала все истории, вылазит одна и та же

Актуальные истории разных людей 

Google pixel 3

Хз

**Comment by abslike** [comment]
Настройки историй скриншот

**Comment by JinnJopino** [comment]
То же самое .Пытался в настройках менять частоту обновления ленты и её кэширование ,но ничего не помогает . .

**Comment by tangenx** [comment]
Дубликат, #1129
