### ISSUE TITLE
Ошибка обновлении ленты новостей

### ISSUE THREAD

**Issue by Fligkkj** [vtosters/lite#1205]
Смотрю истории людей и вылезает история другого человека на все другие истории , не помогло очистить историю приложения , кеш , и данные, даже скрыл истории человека , ничего не помогло, баг так и не прекращается и он так зае...

**Comment by danyyok** [comment]
Пересоздайте Issue по шаблону прикрепив информацию об устройстве.

**Comment by danyyok** [comment]
https://t.me/vtosters_faq/110
