### ISSUE TITLE
Баг при просмотре stories

### ISSUE THREAD

**Issue by Gevorg19rus** [vtosters/lite#1206]
При пролистование stories у друзей у меня вылезает один и тот же пост, вот скрины
![Screenshot_20230416_114920_com vtosters lite](https://user-images.githubusercontent.com/130885708/232268666-2ad8ab46-3f2e-4653-a4be-ade7e0af6b82.jpg)
![Screenshot_20230416_114916_com vtosters lite](https://user-images.githubusercontent.com/130885708/232268676-671ff2b5-512d-423b-9b33-96b30e800502.jpg)
![Screenshot_20230416_114910_com vtosters lite](https://user-images.githubusercontent.com/130885708/232268680-b77babce-5934-49b8-9703-02bdc0593aa9.jpg)
![Screenshot_20230416_115140_com android settings](https://user-images.githubusercontent.com/130885708/232269311-753edba3-b231-486a-8e83-141b0be8495e.jpg)
![Screenshot_20230416_115136_com android settings](https://user-images.githubusercontent.com/130885708/232269328-d2dc0f28-2246-4c41-bb7c-d251c82f36fa.jpg)

**Comment by Bez-Imen** [comment]
Также только другой заел

**Comment by Sheidheda666** [comment]
У меня уже была такая проблема, через какое-то время её исправили. После последнего обновления опять началось.

**Comment by sosok-pisok** [comment]
Так а делать то что блин

**Comment by abslike** [comment]
@sosok-pisok пока что ждать

**Comment by danyyok** [comment]
Invalid issue
