### ISSUE TITLE
Повторение одной  и той же истории

### ISSUE THREAD

**Issue by Volt567** [vtosters/lite#1207]
**Скриншот ошибки**
![Screenshot_2023-04-17-20-03-27-779_com.vtosters.lite.jpg](https://user-images.githubusercontent.com/114720843/232495496-a125d049-18cc-425c-8471-5f1d765c36ee.jpg)

![Screenshot_2023-04-17-20-03-03-524_com.vtosters.lite.jpg](https://user-images.githubusercontent.com/114720843/232495502-80ca25a4-0ccb-4ab3-90df-d9338c91b45b.jpg)

![Screenshot_2023-04-17-20-02-34-612_com.vtosters.lite.jpg](https://user-images.githubusercontent.com/114720843/232495495-b53ddf17-28a4-4509-95bc-7b16e9d26e4b.jpg)

**Скопируйте сюда информацию об устройстве **
**Информация об устройстве:** 

- Commit: 21fc171
- Android SDK: 31
- Product: sweet_ru
- Device: sweet
- Board: sweet
- Manufacturer: Xiaomi
- Brand: Redmi
- Model: M2101K6G
- Miui Version Code: 13
- Miui Version Name: V130
- Miui Version Incremental Code: V13.0.5.0.SKFRUXM

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

**Comment by danyyok** [comment]
Дубликат #1129
Перед созданием Issue, воспользуйтесь поиском и посмотрите, не повторяете ли вы Issue другого человека
