### ISSUE TITLE
Ошибка отображения истории пользователей

### ISSUE THREAD

**Issue by denison21** [vtosters/lite#1208]
У всех друзей одна и та же история. История первого пользователя у которого было видео. 

**Опишите действия для воспроизведения ошибки**
1. Открыл истории и как только проповедуется видео, то оно отображается у всех, хотя при переходе к новому другу на долю секунды видно его историю. 
2. Так всегда. Вк сносил уже. После перезагрузки не помогает. 

**Опишите ожидаемый результат**
Хочу истории смотреть

![Screenshot_20230418_085116_VTLite](https://user-images.githubusercontent.com/54115126/232683402-4806565c-5a6d-44e8-a54a-55fbac620605.jpg)
![Screenshot_20230418_085123_VTLite](https://user-images.githubusercontent.com/54115126/232683423-f32be7f3-64fb-46fc-8612-c4190534726f.jpg)
![Screenshot_20230418_085126_VTLite](https://user-images.githubusercontent.com/54115126/232683439-2a87f26c-4fb6-43b4-b233-434e16413b09.jpg)
![Screenshot_20230418_085130_VTLite](https://user-images.githubusercontent.com/54115126/232683450-dfa56599-1eb1-48ff-a2ef-f8d3429782f3.jpg)

**Информация об устройстве:** 

- Commit: 21fc171
- Android SDK: 33
- Product: q2qxser
- Device: q2q
- Board: lahaina
- Manufacturer: samsung
- Brand: samsung
- Model: SM-F926B
- OneUi Major Version: 5
- OneUi Minor Version: 1.0

Произошло резко. Не после обновления. Иногда, очень очень редко отображается нормально все.

**Comment by danyyok** [comment]
Дубликат #1129
Перед созданием Issue, воспользуйтесь поиском и посмотрите, не повторяете ли вы Issue другого человека

**Comment by denison21** [comment]
А толку то? Решения что там нету. Что у меня))Отправлено с iPhone18 апр. 2023 г., в 11:47, Danyy Okskiy ***@***.***> написал(а):﻿
Дубликат #1129
Перед созданием Issue, воспользуйтесь поиском и посмотрите, не повторяете ли вы Issue другого человека

**Comment by danyyok** [comment]
> А толку то? Решения что там нету. Что у меня))Отправлено с iPhone18 апр. 2023 г., в 11:47, Danyy Okskiy ***@***.***> написал(а):﻿
> Дубликат #1129
> Перед созданием Issue, воспользуйтесь поиском и посмотрите, не повторяете ли вы Issue другого человека
> 
> —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

Issue уже исправляют разработчики, не надо повторять

**Comment by tescker** [comment]
Плюсую уже невозможно терпеть этот баг

**Comment by denison21** [comment]
Прикольно. Теперь просто истории не грузятся/) а вы ещё тикет закрыли))

чт, 20 апр. 2023 г., 14:30 aliveoutside ***@***.***>:

**Comment by aliveoutside** [comment]
выше написали что дубликат
