### ISSUE TITLE
баг с покраской кнопочек навигации

### ISSUE THREAD

**Issue by churanku46** [vtosters/lite#121]
![Screenshot_20220410-021144_VTLite](https://user-images.githubusercontent.com/102247118/162591881-bdab6ce9-681a-4bd2-853f-b7c16d667f44.png)
баг с кнопочками на aosp

**Comment by gdlbo** [comment]
включи жесты

**Comment by churanku46** [comment]
> включи жесты

:)

**Comment by gdlbo** [comment]
https://github.com/vtosters/lite/commit/f500f34e78e78658cc21d35691ce2306498bc163
