### ISSUE TITLE
Видео кружок 

### ISSUE THREAD

**Issue by Volt567** [vtosters/lite#1210]
**Опишите вашу идею максимально подробно и понятно**
Можно добавить видео кружок как в официальном вк. 

**Опишите возможное решение/реализацию функции (если понимаете как это можно реализовать на Java/C++)**

**Остальные мысли о предложенной функции**

**Comment by teaspwn** [comment]
@Volt567 Нет.

**Comment by Volt567** [comment]
Можно сделать мод на одноклассники 🤣
