### ISSUE TITLE
Ошибка историй в ленте новостей

### ISSUE THREAD

**Issue by Gremler5442** [vtosters/lite#1213]
**Опишите сам баг**
Все истории перекрываются одной когда то просмотренной историей;

**Опишите действия для воспроизведения ошибки**
1. Заходим в ленту
2. Открываем историю с видео
3. Видим 1 кадр исходной истории
4. Видим полную забагавшуюся историю

**Опишите ожидаемый результат**
Лента должна показывать актуальные истории без перекрытия их другой историей 

**Скриншот ошибки**
![Screenshot_2023-04-20-21-26-22-67_9e1a5d6211a0228d32d39446541891f1.jpg](https://user-images.githubusercontent.com/61729620/233380849-ad90a70b-24f9-477a-bebd-0b7b3388ffd2.jpg)

![Screenshot_2023-04-20-21-26-01-65_9e1a5d6211a0228d32d39446541891f1.jpg](https://user-images.githubusercontent.com/61729620/233380848-611eb80e-61cd-4342-b066-a0e0d00495a4.jpg)

**Запись ошибки**
https://user-images.githubusercontent.com/61729620/233381019-cb545cc9-ea2c-4e4d-aeae-0dede5dfa2bf.mp4

**Информация об устройстве:** 

- Commit: 21fc171
- Android SDK: 31
- Product: OnePlus7
- Device: OnePlus7
- Board: msmnile
- Manufacturer: OnePlus
- Brand: OnePlus
- Model: GM1900

**Comment by tangenx** [comment]
#1206

**Comment by danyyok** [comment]
Дубликат #1129
