### ISSUE TITLE
Старый кадр видеоролика при просмотре нового видео

### ISSUE THREAD

**Issue by MichaelllRRR** [vtosters/lite#1214]
**Опишите сам баг**
Старый кадр из видеоролика при начале просмотра нового видео

**Опишите действия для воспроизведения ошибки**
Просматриваю видеоролик, листаю ленту дальше, дохожу до очередного видео, и вместо нового воспроизведения показывает кадр из старого видео

**Опишите ожидаемый результат**
При просмотре любого видео, информация должна быть именно того видео, который смотрю, а не кадры из старых видеороликов

**Скриншот ошибки**

**Скопируйте сюда информацию об устройстве нажав на кнопку "Скопировать информацию об устройстве" в Настройках -> Другое и удалите этот текст**
Redmi k30s
**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

**Comment by danyyok** [comment]
Not planned to be fixed

**Comment by danyyok** [comment]
> Это почему?

Это не критичный баг, not planner
