### ISSUE TITLE
Ошибка отображения историй

### ISSUE THREAD

**Issue by kaneki13383** [vtosters/lite#1216]
При поосмотре любой истории открывается один и тот же видеоролик 

1. Открыл любую историю 
<
Истории должны отображаться корректно

**Comment by GooDoG337** [comment]
@kaneki13383 Дубликат очередной

**Comment by danyyok** [comment]
@kaneki13383 https://t.me/vtosters_faq/110
Duplicate+invalid issue 
#1129
