### ISSUE TITLE
Ошибка при просмотре историй, все истории заменяются на одну и ту же

### ISSUE THREAD

**Issue by DillerKing31** [vtosters/lite#1217]
**Опишите сам баг**
При просмотре историй у меня истории заменяются на определенную

**Опишите действия для воспроизведения ошибки**
1. Открыл историю
3. Но история не та а (моей девушки)
4. Я попросил удалить эту историю из ее архива историй, и все заменилось на новую историю которую я посмотрел после данной процедуры.

**Опишите ожидаемый результат**
5. Смотреть истории без ошибок

**Скриншот ошибки**

**Модель устройства**
Pixel 4 XL

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

**Comment by danyyok** [comment]
@DillerKing31 https://t.me/vtosters_faq/110
Duplicate+invalid issue 
#1129
