### ISSUE TITLE
Баг просмотра видео в историях

### ISSUE THREAD

**Issue by SHVERG** [vtosters/lite#1218]
Во время просмотра историй, которые содержат видео, воспроизводится первое видео из первой истории. Во всех историях одно и то же видео.
Пробовал чистить кэш, помогает, но ненадолго.

1. Открыл историю с видео
2. Перешёл на другую историю с видео

![Screenshot_2023-04-22-15-23-23-402_com vtosters lite](https://user-images.githubusercontent.com/11377052/233781399-e495a649-8312-48ff-81f9-fec406dbfd28.jpg)
![Screenshot_2023-04-22-15-23-29-074_com vtosters lite](https://user-images.githubusercontent.com/11377052/233781401-0b02b460-3dd6-456d-a7d7-d57d982ce14f.jpg)
![Screenshot_2023-04-22-15-23-37-353_com vtosters lite](https://user-images.githubusercontent.com/11377052/233781404-6683d720-542c-4e33-b02c-aa1f33806058.jpg)

**Информация об устройстве:** 

- Commit: 21fc171
- Android SDK: 31
- Product: vayu_ru
- Device: vayu
- Board: vayu
- Manufacturer: Xiaomi
- Brand: POCO
- Model: M2102J20SG
- Miui Version Code: 13
- Miui Version Name: V130
- Miui Version Incremental Code: V13.0.2.0.SJURUXM

**Comment by danyyok** [comment]
@SHVERG https://t.me/vtosters_faq/110
Invalid issue.
#1129
