### ISSUE TITLE
Некорректная работа историй 

### ISSUE THREAD

**Issue by Kinnsayer** [vtosters/lite#1219]
При просмотре видео историй(не статичная картинка) показывается одно и то же видео

Происходит постоянно

Ожидаю корректной работы историй
![Screenshot_20230422-204410](https://user-images.githubusercontent.com/131549362/233799178-4186c94f-5535-487f-b0e9-12eaaccba158.png)
![Screenshot_20230422-204403](https://user-images.githubusercontent.com/131549362/233799180-0c2c582f-c129-42aa-ab6e-2917dc9cf486.png)

**Comment by danyyok** [comment]
@Kinnsayer https://t.me/vtosters_faq/110
Duplicate+invalid issue 
#1129
