### ISSUE TITLE
Новое уведомление не отмечается прочитанным

### ISSUE THREAD

**Issue by Wperdex** [vtosters/lite#122]
Баг с уведами. При обновлении вкладки прочитанное уведомление не отмечается просмотренным и остаётся висеть в докбаре (версия втл на скрине)

![IMG_20220410_122848](https://user-images.githubusercontent.com/102802937/162611815-37f029fa-5699-48ec-8320-f482ec302e4e.jpg)
![IMG_20220410_122914](https://user-images.githubusercontent.com/102802937/162611819-828776f2-e706-46fd-ae8a-4d19e5ce86a3.jpg)
![IMG_20220410_123207](https://user-images.githubusercontent.com/102802937/162611909-b376a8a1-1fb6-4675-9f99-f34f4ac1d85a.jpg)

**Comment by gdlbo** [comment]
https://github.com/vtosters/lite/commit/af25a82eca9bfa935504c994c32193933b34e506
