### ISSUE TITLE
Крайне забавный баг со сторизами

### ISSUE THREAD

**Issue by tverrdiy** [vtosters/lite#1220]
Половину сторизов с ленте заменил видос про страусов. Я его до этого ни разу не видел. Перезапуски не помогли даже.

**Опишите действия для воспроизведения ошибки**
1. Зашёл в сториз.

![Screenshot_2023-04-23-14-05-23-270_com vtosters lite](https://user-images.githubusercontent.com/125725514/233830385-9f6d9f16-acd6-4502-b5c4-0c9e53ddb1d6.jpg)

Хз попытался видео приложить но чет не получилось 

**Информация об устройстве:** 

- Commit: 21fc171
- Android SDK: 31
- Product: vayu_ru
- Device: vayu
- Board: vayu
- Manufacturer: Xiaomi
- Brand: POCO
- Model: M2102J20SG
- Miui Version Code: 13
- Miui Version Name: V130
- Miui Version Incremental Code: V13.0.2.0.SJURUXM

**Comment by danyyok** [comment]
@tverrdiy https://t.me/vtosters_faq/110
Duplicate issue 
#1129
