### ISSUE TITLE
В новостом разделе, в историях, идёт одно и то же видео, какое не включу...

### ISSUE THREAD

**Issue by Discrete10** [vtosters/lite#1221]
**Опишите сам баг**
При обновлении новостей вылезает ошибка

**Опишите действия для воспроизведения ошибки**
1. Обновил ленту интересных новостей
2. Пролистал до конца страницы

**Опишите ожидаемый результат**
Интересная лента должна прогружать результаты

**Скриншот ошибки**

**Скопируйте сюда информацию об устройстве нажав на кнопку "Скопировать информацию об устройстве" в Настройках -> Другое и удалите этот текст**

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

**Comment by danyyok** [comment]
@Discrete10 https://t.me/vtosters_faq/110
Duplicate+invalid issue 
#1129
