### ISSUE TITLE
Ошибка в историях

### ISSUE THREAD

**Issue by Marija2020** [vtosters/lite#1222]
**Опишите сам баг**
Одна и та же история у нескольких человек, а реальные истории не показывает.

**Опишите действия для воспроизведения ошибки**
1. Открыла истории 
2. Начала листать

**Опишите ожидаемый результат**
Смотреть истории, а не одну и ту же картину у всех людей во всех историях)

**Скриншот  
@
/

Xiaomi 12 Lite

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

**Comment by tangenx** [comment]
@Marija2020 Дубликат.
#1129
