### ISSUE TITLE
Не скачивает всю музыку в кэш

### ISSUE THREAD

**Issue by KoTdZero** [vtosters/lite#1223]
При скачивании всех треков в кэш по какой то причине скачивается не вся музыка, а только первые 30-40 треков . Остальные не скачиваются, но показывает что они якобы скачанны
![Screenshot_20230424_081141](https://user-images.githubusercontent.com/131634870/233891963-0d2bf330-eaa8-4f5a-8a31-4b59297747e8.png)

**Comment by danyyok** [comment]
Пересоздайте Issue по шаблону прикрепив информацию об устройстве.
Invalid
