### ISSUE TITLE
Ошибка проигрывания историй 

### ISSUE THREAD

**Issue by Inkeesie** [vtosters/lite#1224]
При открытии историй проигрывается лишь одна, что заменяет собой истории различных авторов и содержания. Кликая на какую-либо историю, на секунду показывается картинка видео, что там должно быть, а затем оно заменяется на фрагмент, что постоянно проигрывается.

1. Открыла новостную ленту.
2. Кликнула на историю.

Истории должны воспроизводить не одно и то же видео, а разные.

![Screenshot_2023-04-24-22-27-39-57_9e1a5d6211a0228d32d39446541891f1](https://user-images.githubusercontent.com/131710386/234097471-68106c63-d8d3-4fcc-8e97-a3fd8ebe0d0d.jpg)
![Screenshot_2023-04-24-22-27-46-98_9e1a5d6211a0228d32d39446541891f1](https://user-images.githubusercontent.com/131710386/234097510-ab433fd8-8e6f-4672-acb0-2dc326a27813.jpg)
![Screenshot_2023-04-24-22-27-56-23_9e1a5d6211a0228d32d39446541891f1](https://user-images.githubusercontent.com/131710386/234097533-93f1eccc-e3d9-4d92-8d1c-70edae6f5ec7.jpg)

**Информация об устройстве:** 

- Commit: 21fc171
- Android SDK: 33
- Product: RMX3560
- Device: RE5489
- Board: k6895v1_64
- Manufacturer: realme
- Brand: realme
- Model: RMX3560

Истории от некоторых сообществ и групп не заменяются на другое видео. От чего это зависит - не понятно. Все истории от частных страниц также заменяются.

**Comment by tangenx** [comment]
@Inkeesie Дубликат.
#1129

**Comment by danyyok** [comment]
@Inkeesie https://t.me/vtosters_faq/110
Duplicate issue 
#1129
