### ISSUE TITLE
Одна и та же история везде

### ISSUE THREAD

**Issue by N0namenull** [vtosters/lite#1225]
Воспроизвожу историю, она отображается, далее во всех остальных историях, будь то истории людей или пабликов отображается эта, первая история. Сохраняется баг и день и неделю.
Помогает только полная очистка кэша. И опять, посмотрел историю, перелистнул на другую, а там та же картинка/видео, что и в первой

Прошивка one ui 5.1 телефон Samsung

**Comment by danyyok** [comment]
@N0namenull https://t.me/vtosters_faq/110
Duplicate+invalid issue 
#1129
