### ISSUE TITLE
Ошибка при скачивании музыки 

### ISSUE THREAD

**Issue by SneppiRus** [vtosters/lite#1226]
Опишите сам баг
При попытке загрузить музыку в кеш или мп3, приложение вылетает и выдает ошибку 

Опишите действия для воспроизведения ошибки.
Зашёл в свою музыку, нажал на значок установки.
Опишите ожидаемый результат
Музыка должна была загрузиться в кеш.

Скриншот ошибки
https://ibb.co/HGj8TR2

Скопируйте сюда информацию об устройстве нажав на кнопку "Скопировать информацию об устройстве" в Настройках -> Redmi note 8 pro

Дополнительная информация о баге или мыслях почему оно может происходить (если есть)

**Comment by GooDoG337** [comment]
@SneppiRus Неправильно заполнен issue

**Comment by GooDoG337** [comment]
@SneppiRus По шаблону

**Comment by SneppiRus** [comment]
@GooDoG337 
я в плане, как это сделать

**Comment by GooDoG337** [comment]
@SneppiRus Опишите сам баг
При обновлении новостей вылезает ошибка

Опишите действия для воспроизведения ошибки
1. Обновил ленту интересных новостей
2. Пролистал до конца страницы

Опишите ожидаемый результат
Интересная лента должна прогружать результаты

Скриншот ошибки

Скопируйте сюда информацию об устройстве нажав на кнопку "Скопировать информацию об устройстве" в Настройках -> Другое и удалите этот текст

Дополнительная информация о баге или мыслях почему оно может происходить (если есть)

**Comment by SneppiRus** [comment]
@GooDoG337 я правильно сделал?
что дальше делать

**Comment by GooDoG337** [comment]
@SneppiRus Осознать, что таких issues уже миллион, и все они дубликаты

**Comment by danyyok** [comment]
@SneppiRus Invalid issue
