### ISSUE TITLE
Ошибка воспроизведения историй 

### ISSUE THREAD

**Issue by xL0STx** [vtosters/lite#1229]
**Опишите сам баг**
При просмотре историй появляется одна история поверх других. При перелистывании просто одна и та же история воспроизводится заново 

**Опишите действия для воспроизведения ошибки**
1. Обновил ленту новостей 
2. Нажал на историю и стал перелистывать их

**Опишите ожидаемый результат**
Просто нормальный просмотр историй

**Скриншот ошибки**
Тут он не поможет
**Скопируйте сюда информацию об устройстве нажав на кнопку "Скопировать информацию об устройстве" в Настройках -> Другое и удалите этот текст**
**Информация об устройстве:** 

- Commit: 21fc171
- Android SDK: 31
- Product: curtana_global
- Device: curtana
- Board: curtana
- Manufacturer: Xiaomi
- Brand: Redmi
- Model: Redmi Note 9S
- Miui Version Code: 14
- Miui Version Name: V140
- Miui Version Incremental Code: V14.0.3.0.SJWMIXM

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**
Баг исправляется, если очистить кэш, но только на одну историю. При перелистывании или конца истории баг сразу же возвращается [https://youtu.be/dlDJf7iW5Rc](https://youtu.be/dlDJf7iW5Rc)

**Comment by GooDoG337** [comment]
@xL0STx Дубликат, о проблеме написано в faq https://t.me/vtosters_faq/110

**Comment by tangenx** [comment]
@xL0STx Дубликат.
#1129

**Comment by danyyok** [comment]
@xL0STx https://t.me/vtosters_faq/110
Duplicate issue 
#1129
