### ISSUE TITLE
Ошибка в работе сторис

### ISSUE THREAD

**Issue by Godfather06022023** [vtosters/lite#1230]
Не работают сторис должным образом

Все истории заменяются на это видео (записать не смог, но скриншот приложу), то есть включая любую историю, я вижу это видео.
В вк из плеймаркета все работает четко.

![Screenshot_20230426-201226_VTLite](https://user-images.githubusercontent.com/131881634/234586950-276c51d7-4b85-4b13-86b7-9f263b3e4161.jpg)

![Screenshot_20230426-195538_VTLite](https://user-images.githubusercontent.com/131881634/234587039-0af90f67-7998-48f7-96c8-5233b1a49959.jpg)

![Screenshot_20230426-201409_Settings](https://user-images.githubusercontent.com/131881634/234587157-329738cb-c496-41c3-9aa0-c39030f90aa1.jpg)

**Comment by danyyok** [comment]
@Godfather06022023 https://t.me/vtosters_faq/110
Duplicate+invalid issue 
#1129

**Comment by Godfather06022023** [comment]
> Не работают сторис должным образом
> 
> Все истории заменяются на это видео (записать не смог, но скриншот приложу), то есть включая любую историю, я вижу это видео. В вк из плеймаркета все работает четко.
> 
> ![Screenshot_20230426-201226_VTLite](https://user-images.githubusercontent.com/131881634/234586950-276c51d7-4b85-4b13-86b7-9f263b3e4161.jpg)
> 
> ![Screenshot_20230426-195538_VTLite](https://user-images.githubusercontent.com/131881634/234587039-0af90f67-7998-48f7-96c8-5233b1a49959.jpg)
> 
> ![Screenshot_20230426-201409_Settings](https://user-images.githubusercontent.com/131881634/234587157-329738cb-c496-41c3-9aa0-c39030f90aa1.jpg)

Телефон: samsung galaxy a10
