### ISSUE TITLE
Пропадают некоторые чаты из общего списка

### ISSUE THREAD

**Issue by Godfather06022023** [vtosters/lite#1231]
Пропадают чаты, но их возможно найти через поиск сообщений, диалогов.

Заметил эту проблему почти с самого начала пользования тостером,

**Comment by Godfather06022023** [comment]
Скрин скрин не получится приложить, потому что это случается редко (но метко).

**Comment by WeSTManCoder** [comment]
Поддерживаю, часть диалогов пропала. Но когда нажимаешь кнопку обновить, то они появляются. Но стоит прокрутить вниз, как снова пропадают
