### ISSUE TITLE
История

### ISSUE THREAD

**Issue by Daniil2465** [vtosters/lite#1232]
![Screenshot_2023-04-27-13-38-11-405_com vtosters lite](https://user-images.githubusercontent.com/107489417/234838647-c729da2a-62b4-4f66-9d41-96c2741c5c33.jpg)
![Screenshot_2023-04-27-13-38-19-552_com vtosters lite](https://user-images.githubusercontent.com/107489417/234838654-50945c13-1975-4056-8243-d9525a18ed6c.jpg)
Не отображается историю которую выложил

**Comment by tangenx** [comment]
@Daniil2465 Пересоздайте issue по шаблону.
Invalid

**Comment by danyyok** [comment]
Пересоздайте Issue по шаблону
