### ISSUE TITLE
при просмотре историй вместо оригинального видео отображается надпись "street mode"

### ISSUE THREAD

**Issue by hrtPP** [vtosters/lite#1233]
**Опишите сам баг**
при просмотре историй вместо оригинального видео отображается надпись "street mode"

**Опишите действия для воспроизведения ошибки**
1. нажал на иконку историй
2. воспроизводится надпись

**Опишите ожидаемый результат**
вместо надписи "street mode" истории пользователей

**Скриншот ошибки**
![Screenshot_20230427_204237](https://user-images.githubusercontent.com/132004214/234949968-4508c01b-a351-469e-851e-f9bc9bd6a6b6.jpg)

****Информация об устройстве:** 

- Commit: 21fc171
- Android SDK: 31
- Product: NTH-NX9RU
- Device: HNNTH
- Board: NTH
- Manufacturer: HONOR
- Brand: HONOR
- Model: NTH-NX9
**

**думается, что-то в обновлении приложения**

**Comment by danyyok** [comment]
Что?

**Comment by danyyok** [comment]
@hrtPP https://t.me/vtosters_faq/110
Duplicate issue 
#1129
