### ISSUE TITLE
Вылетает приложение когда просто включаю или перемешиваю музыку.

### ISSUE THREAD

**Issue by Mayskiy01** [vtosters/lite#1234]
Как только я включаю музыку, приложение вылетает.
Если перемешиваю песни такая же история.

1. Захожу в песни
2. Включаю любую/перемешиваю любые
3. Приложение вылетает выдавая ошибку

Хочу нормально слушать музыку и свободно ее перемешивать.

Realme Narzo A50; android 11; processor Hello G85; RAM 4GB;

![Screenshot_2023-04-28-08-14-00-50_92b64b2a7aa6eb3771ed6e18d0029815](https://user-images.githubusercontent.com/132033090/235045885-796024dd-dac5-4f59-b64e-7c383cd4c673.jpg)

Не понимаю, почему так может происходить, потому что все было нормально и резко вот так вот.

**Comment by abslike** [comment]
@Mayskiy01 Загрузите логи и приложите к issues

**Comment by danyyok** [comment]
Сохраните лог в файл и пересоздайте Issue прикрепив лог файлом, а не скриншотом
