### ISSUE TITLE
Ошибка просмотра сообществ

### ISSUE THREAD

**Issue by Isurafiru** [vtosters/lite#1235]
При открытии вкладки сообществ, выдает только первые 5 сообществ из списка, далее идут рекомендации. Всего сообществ 564 и ранее они отображались корректно, длинным списком. Сейчас посмотреть сообщества, в которых я состою, не представляется возможным.

**Comment by tangenx** [comment]
Разработчикам известно о баге, ожидайте

**Comment by tangenx** [comment]
Если критически необходимо попасть в список всех сообществ:
Профиль -> пункт "Подробная информация" -> Подписки
