### ISSUE TITLE
Рекомендации сообществ в основной секции

### ISSUE THREAD

**Issue by narKOT1** [vtosters/lite#1236]
В секции сообществ теперь рекомендации других пабликов перекрывают весь список моих подписок, не давая просматривать его полностью

1. Зашла во вкладку сообществ 

Рекомендации в секции рекомендаций, а не в сообществах 
![Screenshot_20230428_092626](https://user-images.githubusercontent.com/132044308/235072327-390e9bf8-7bae-4153-9ead-89563080ed55.jpg) 

Информация об устройстве — 
![Screenshot_20230428_093656](https://user-images.githubusercontent.com/132044308/235072900-736deeff-8e27-4b19-8e55-42da7b61fe27.jpg)

**Comment by danyyok** [comment]
Duplicate+invalid issue
#1235
