### ISSUE TITLE
Ошибка при скачивании музыки на устройство

### ISSUE THREAD

**Issue by 21Jarvis21** [vtosters/lite#1237]
**Опишите сам баг**
При скачивании музыки на устройство выходит ошибка #
![Screenshot_20230428-111216_VTLite](https://user-images.githubusercontent.com/132047723/235081400-fb04a2a4-a70f-4ebf-b087-18908489e36f.jpg)

**Comment by 21Jarvis21** [comment]
**Информация об устройстве:** 

- Commit: 21fc171
- Android SDK: 31
- Product: m31nsser
- Device: m31
- Board: exynos9611
- Manufacturer: samsung
- Brand: samsung
- Model: SM-M315F

**Comment by danyyok** [comment]
Сохраните лог в файл и пересоздайте Issue по шаблону прикрепив инф. об устройстве и ФАЙЛ с логом
