### ISSUE TITLE
Ошибка в списке сообществ

### ISSUE THREAD

**Issue by flypici** [vtosters/lite#1238]
**Опишите сам баг**
у меня 84 сообщества, но стало показывать так. (нельзя открыть полный список) как вообще получилось, что сообщества и рекомендации оказались в одной вкладке "сообщества"?

**Опишите действия для воспроизведения ошибки
просто зайти во вкладку сообществ

**Опишите ожидаемый результат**
должно показывать полный список сообществ на которые подписан

**Скриншот ошибки**
![Screenshot_20230428_173157_VTLite](https://user-images.githubusercontent.com/90459243/235121169-eb4132fb-95f2-4747-85aa-b76278b20a63.jpg)

samsung galaxy s22 sm-s901b/ds

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

**Comment by tangenx** [comment]
@flypici Дубликат.
#1235
