### ISSUE TITLE
Ошибка во воспроизведении историй

### ISSUE THREAD

**Issue by Artagonium1** [vtosters/lite#1240]
1. Истории, в которых лишь видео, без ссылки на какой либо пост, воспроизводится одно и тоже видео, меняется это самое видео 1 раз в день, то есть когда история с этим видео, в каком либо паблике была более 24 часов
2.

Истории должны меняться 

Скрин 
![Screenshot_2023-04-29-00-18-29-703_com vtosters lite](https://user-images.githubusercontent.com/132105147/235256297-dd9293b3-6235-4793-be05-3800db659f66.jpg)
![Screenshot_2023-04-29-00-18-50-110_com vtosters lite](https://user-images.githubusercontent.com/132105147/235256304-41d81518-7a21-4c41-bb11-6f6a51d8e757.jpg)

**Информация об устройстве:** 

- Commit: 21fc171
- Android SDK: 31
- Product: surya_ru
- Device: surya
- Board: surya
- Manufacturer: Xiaomi
- Brand: POCO
- Model: M2007J20CG
- Miui Version Code: 13
- Miui Version Name: V130
- Miui Version Incremental Code: V13.0.1.0.SJGRUXM

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**
Примерно около месяца это продолжается, еще если я переключаю историю, то на долю секунды я вижу картинку из нужной истории, а затем начинает грузится одна и та же, мб что то с кэшем, но я его чистил, приложение не переустанавливал, только обновлял, если отписаться от паблика откуда все время воспроизводятся истории( всегда из одного и того же), то после того как пройдёт +-24 часа, оттуда больше историй не будет, уже из нового паблика

**Comment by tangenx** [comment]
@Artagonium1 Дубликат.
#1129

**Comment by danyyok** [comment]
@Artagonium1 https://t.me/vtosters_faq/110

Duplicate+invalid issue 
#1129
https://t.me/vtosters_faq/110

**Comment by danyyok** [comment]
@Artagonium1 https://t.me/vtosters_faq/110

Duplicate+invalid issue 
#1129
https://t.me/vtosters_faq/110

**Comment by danyyok** [comment]
@Artagonium1 https://t.me/vtosters_faq/110

Duplicate+invalid issue 
#1129
https://t.me/vtosters_faq/110
