### ISSUE TITLE
Ошибка в проигрывании историй 

### ISSUE THREAD

**Issue by OverLordest** [vtosters/lite#1241]
**Опишите сам баг**
При просмотре историй сообществ с приложения всегда проигрывается первая просмотренная история, помогает только очистка кэша, но после очистки опять первая просмотренная история будет везде повторятся, причем в историях не сообществ такой проблемы ект

**Опишите действия для воспроизведения ошибки**
При открытии историй

**Скриншот ошибки**

**Информация об устройстве:** 

- Commit: 21fc171
- Android SDK: 31
- Product: redwood_ru
- Device: redwood
- Board: redwood
- Manufacturer: Xiaomi
- Brand: POCO
- Model: 22101320G
- Miui Version Code: 14
- Miui Version Name: V140
- Miui Version Incremental Code: V14.0.8.0.SMSRUXM

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**
Кэшируется первое видео истории, а затем оно же и показывается, остальные может просто не загружаются в кэш

**Comment by danyyok** [comment]
@OverLordest https://t.me/vtosters_faq/110

Duplicate issue 
#1129
https://t.me/vtosters_faq/110
