### ISSUE TITLE
При смене темы на темную сообщения пользователя становятся белыми и нечитаемыми 

### ISSUE THREAD

**Issue by Origame007** [vtosters/lite#1242]
**Опишите сам баг**
При обновлении новостей вылезает ошибка

**Опишите действия для воспроизведения ошибки**
1. Обновил ленту интересных новостей
2. Пролистал до конца страницы

**Опишите ожидаемый результат**
Интересная лента должна прогружать результаты

**Скриншот ошибки**

**Скопируйте сюда информацию об устройстве нажав на кнопку "Скопировать информацию об устройстве" в Настройках -> Другое и удалите этот текст**

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

**Comment by tangenx** [comment]
@Origame007 перезапустите клиент

**Comment by danyyok** [comment]
@Origame007 Invalid Issue
