### ISSUE TITLE
Ошибка в историях

### ISSUE THREAD

**Issue by Aboba829** [vtosters/lite#1243]
**Опишите сам баг**
При просмотре историй, вместо нужной вылазит абсолютно другая и повторяется когда перелистываю

**Опишите действия для воспроизведения ошибки**
1. Скидывают историю в сообщениях
2. Воспроизводится ошибка

**Comment by danyyok** [comment]
@Aboba829 https://t.me/vtosters_faq/110

Duplicate+invalid issue 
#1129
https://t.me/vtosters_faq/110
