### ISSUE TITLE
Ошибка загрузки историй

### ISSUE THREAD

**Issue by FabiousBIT** [vtosters/lite#1247]
Открываешь истории друзей и пабликов - приложа хватает одну из первых историй, рандомную, и включает вместо каждой последующей, кароче, будто паблик выложил все истории одинаковые...

1. Открыл приложу, включил первую историю, либо свою, со всеми одинаково происходит, повторяемость 100%.

Истории должны работать как в стоке, все логично

OnePlus 9 PRO (LE2121) Qualcomm 888 8G RAM
 Видео бага:
https://disk.yandex.com/i/RLzrRVzwER-_IA

Спасибо разработчикам за хорошее приложение, делаете большое дело, надеюсь это как нибудь вылечится

**Comment by danyyok** [comment]
@FabiousBIT https://t.me/vtosters_faq/110

Duplicate+invalid issue 
#1129
https://t.me/vtosters_faq/110
