### ISSUE TITLE
Проблема с записями в ленте новостей

### ISSUE THREAD

**Issue by LunyaAV** [vtosters/lite#1248]
В ленте находятся записи различного времени давности, то есть как новые, так и старые записи (могут быть и недельной давности), при этом они не идут по порядку типа от новых к старым, все вперемешку.

К сожалению не могу сказать как возможно воспроизвести данную проблему, потому что у меня она появилась будто просто так.

Очень бы хотелось, чтобы лента обновлялась от новых новостей к старым и они шли по порядку.

![Screenshot_2023-04-29-23-51-37-044_com vtosters lite](https://user-images.githubusercontent.com/132168746/235323765-23f4e15f-6d5d-4c74-a10a-eeece3f460fe.jpg)
![Screenshot_2023-04-29-23-51-13-581_com vtosters lite](https://user-images.githubusercontent.com/132168746/235323770-c3678112-918c-46d7-84ab-ff638d1801a2.jpg)
Вот примеры, где чётко видна проблема. 

**Информация об устройстве:** 

- Commit: cc55d5d
- Android SDK: 31
- Product: camellian_p_global
- Device: camellian
- Board: camellian
- Manufacturer: Xiaomi
- Brand: POCO
- Model: M2103K19PG
- Miui Version Code: 13
- Miui Version Name: V130
- Miui Version Incremental Code: V13.0.6.0.SKSMIXM

**Comment by danyyok** [comment]
https://t.me/vtostersfaq/16?single
+Duplicate issue
