### ISSUE TITLE
Ошибка воспроизведения историй

### ISSUE THREAD

**Issue by 4ickenBurg** [vtosters/lite#1249]
Видео истории проигрывают не верный контент.

1. Просмотрел историю одного человека.
2. У второго и всех последующих воспроизводится видео первого. (Истории с фото и без анимаций работают нормально)

А должно воспроизводить контент своего пользователя.

Ошибку не выдает, но воспроизводит не правильно.

**Информация об устройстве:** 

- Commit: cc55d5d
- Android SDK: 30
- Product: begonia_ru
- Device: begonia
- Board: begonia
- Manufacturer: Xiaomi
- Brand: Redmi
- Model: Redmi Note 8 Pro
- Miui Version Code: 12
- Miui Version Name: V125
- Miui Version Incremental Code: V12.5.3.0.RGGRUXM

При очистке кеша через настройки на телефоне проблема не решается; при очистке кеша в настройках приложения первая видео история воспроизводится нормально, затем снова "залипает".

**Comment by danyyok** [comment]
https://t.me/vtosters_faq/110

Duplicate issue 
#1129
