### ISSUE TITLE
Создание метки "Отметить как непрочитанное"

### ISSUE THREAD

**Issue by FHI123DD** [vtosters/lite#1250]
В VK Sova есть удобная функция как метка чата. Можно поставить её в чат с прочитанными сообщениями, тем самым сделать метку о наличие какой-то важной информации там.
Было неплохо ecли эта функция была реализована в VT Lite. 

Вот реализация этой функции в Сове:
![Screenshot_2023-04-29-11-36-06-053-edit_re sova five](https://user-images.githubusercontent.com/132121331/235335642-1c0ac832-fba1-4702-b6af-17bd6961737e.jpg)
![Screenshot_2023-04-29-11-34-35-187-edit_re sova five](https://user-images.githubusercontent.com/132121331/235335647-b7a5de61-05a9-4651-b7ae-07b2747ed288.jpg)
![Screenshot_2023-04-29-11-35-34-295-edit_re sova five](https://user-images.githubusercontent.com/132121331/235335651-e21b45a9-b9a8-47eb-8d97-9e35c822fe8c.jpg)

**Comment by danyyok** [comment]
@FHI123DD Не позволяет база самого ВК
Not planned
