### ISSUE TITLE
Ошибка при просмотре историй людей/сообществ

### ISSUE THREAD

**Issue by Vop1k** [vtosters/lite#1252]
**Опишите сам баг**
При просмотре историй иногда появляется ошибка и может стать постоянной

**Опишите действия для воспроизведения ошибки**
1. Начал просмотр историй
2. Первая или последующая история с содержанием видео (а также аудио и фото) может повторяться практически во всех последующих историях (кроме фото историй) 
P.s. ОС EMUI

**Опишите ожидаемый результат**
Просмотр тех историй, которые были выложены

**Скриншот ошибки
![Screenshot_20230501_040307_com vtosters lite](https://user-images.githubusercontent.com/132228379/235373886-50acb333-e30b-499d-9f92-660ad01dbef1.jpg)
![Screenshot_20230501_040303_com vtosters lite](https://user-images.githubusercontent.com/132228379/235373922-8953e135-4370-4c35-9c33-a176807f3961.jpg) (там должны быть другие истории) 
**

**Comment by danyyok** [comment]
@Vop1k https://t.me/vtosters_faq/110

Duplicate issue 
#1129
