### ISSUE TITLE
При просмотре некоторых историй выдаёт ошибку.

### ISSUE THREAD

**Issue by Mexahuk990** [vtosters/lite#1253]
![Screenshot_20230501-005203](https://user-images.githubusercontent.com/132232588/235377839-9853cae8-002d-4fed-a60e-9469dc0f4f2c.png)
Не прогружаются истории, при попытке обновить ничего не происходит.

**Comment by danyyok** [comment]
@Mexahuk990 https://t.me/vtosters_faq/110

Duplicate issue 
#1129
