### ISSUE TITLE
Ошибка сторис в ВК

### ISSUE THREAD

**Issue by PhilManukyan** [vtosters/lite#1254]
Samsung S20FE, последняя версия VTLite.
Баг в том, что при входе в ленту новостей, и открытии историй в ВК, запускается чье-то первое видео, и далее любой другой пользователь или сообщество, у кого есть сторис, начинают отображать тоже самое видео у себя. Главное, если пользователь выкладывает фото, то все в порядке, у каждого пользователя оно свое, проблема только с роликами.
 Чтобы обнаружить баг, нужно:
1. Открыть ленту новостей
2. Открыть сторис
3. 
![Screenshot_20230501_121739_VTLite](https://user-images.githubusercontent.com/132159042/235433904-435f4129-fa08-44cb-beb9-46beace2f68a.jpg)
![Screenshot_20230501_121734_VTLite](https://user-images.githubusercontent.com/132159042/235433908-6f3d5557-f467-4992-aaed-2822e2e62f22.jpg)
![Screenshot_20230501_121723_VTLite](https://user-images.githubusercontent.com/132159042/235433909-03dcbbb7-1666-4559-84db-da8582105ba3.jpg)
![Screenshot_20230501_121701_VTLite](https://user-images.githubusercontent.com/132159042/235433910-b54c0f0b-225f-478c-83b1-6bc3cbffeed3.jpg)

**Comment by tangenx** [comment]
@PhilManukyan Дубликат.
#1129

**Comment by ArinaNight** [comment]
У меня так же
