### ISSUE TITLE
Ошибка обновлении ленты новостей и отправки коментариев 

### ISSUE THREAD

**Issue by 13322422ffdddd** [vtosters/lite#1257]
[Device Info.txt](https://github.com/vtosters/lite/files/11376524/Device.Info.txt)
Вот, информация по устройству, как просили, если я правильно понял что нужно

**Comment by tangenx** [comment]
@13322422ffdddd Пересоздайте issue правильно, используя шаблон.

**Comment by danyyok** [comment]
@13322422ffdddd Смеешься?

**Comment by 13322422ffdddd** [comment]
> @13322422ffddddСмеешься?

Нет, туплю, я первый раз на гитхабе, что не так?

**Comment by danyyok** [comment]
> Нет, туплю, я первый раз на гитхабе, что не так?

Вас просят составить Issue по шаблону, тоесть описать баг, скинуть скриншоты бага и информацию об устройстве скопированную из настроек VTLite
