### ISSUE TITLE
Ошибка обновлении ленты новостей

### ISSUE THREAD

**Issue by 13322422ffdddd** [vtosters/lite#1258]
**Информация об устройстве:** 

- Commit: cc55d5d
- Android SDK: 29
- Product: S59Pro_EEA
- Device: S59Pro
- Board: k62v1_64_bsp
- Manufacturer: DOOGEE
- Brand: DOOGEE
- Model: S59Pro
![Screenshot_20230502-215119](https://user-images.githubusercontent.com/132286180/235759506-1cea8863-f72a-44dd-9fb0-381d3456d688.png)
![Screenshot_20230502-215515](https://user-images.githubusercontent.com/132286180/235759548-c60097ba-6e02-4370-9de9-29f16bf0f6e5.png)
![Screenshot_20230502-215352](https://user-images.githubusercontent.com/132286180/235759617-765729b7-8d8e-4e4f-a5fa-592a8359efb2.png)
При обновлении ленты и даже просмотре уже давно обновленной ленты, возникают проблемы в виде долгих задержек загрузки фотографий Аватарки пабликов, так же фотографий самих постов. То же самое при просмотре альбома сохраненных фотографий, так же при отправке в диалоге фотографии загрузка картинки длится около 2 минут, при комментировании записей тоже возникают длительные задержки в отправке. Так правильно создал?

**Comment by danyyok** [comment]
Спасибо. Теперь попробуй переустановить приложение(удалить и скачать заново с гитхаба)/перезайти в аккаунт

**Comment by danyyok** [comment]
> Все сделал, не исчезло, ещё заметил, при просмотре истории пабликов одна история накладывается на другие, получается что каждая история одна и та же 

По поводу историй известно.
Больше ни с чем не могу помочь, никогда не сталкивашся с такой проблемой
