### ISSUE TITLE
Вылетает при переключении треков в плейлистах

### ISSUE THREAD

**Issue by rever37** [vtosters/lite#1259]
Крашится при переключении трека в плейлиста, при перезапуске трек играет до конца и на следующем снова падение.

Началось примерно на последней неделе апреля.

**Информация об устройстве:** 

- Commit: cc55d5d
- Android SDK: 33
- Product: spark_raphael
- Device: raphael
- Board: msmnile
- Manufacturer: Xiaomi
- Brand: Xiaomi
- Model: Mi 9T Pro

Прошивка не сток

![Screenshot_20230502-231111_Chrome](https://user-images.githubusercontent.com/132400034/235775291-2365e2e4-fae0-4599-a536-ea60fa504a85.png)

**Comment by danyyok** [comment]
Проблема актуальна?
