### ISSUE TITLE
Краш при кэшировании большенства песен 

### ISSUE THREAD

**Issue by Horus891** [vtosters/lite#1263]
Когда я подаюсь кэшировать большую часть своей музыки приложение крашется и ничего не кэшируется 

[Вот логи](https://cdn.discordapp.com/attachments/1070629767147180043/1103998864551313569/VTL_log_2023-05-05.13-33-51.txt)

**Comment by ayonovdenizs** [comment]
дубликат #1228 и невалидный issue
