### ISSUE TITLE
ошибка просмотоа историй. 

### ISSUE THREAD

**Issue by nokogury** [vtosters/lite#1268]
**Опишите сам баг**
При просмотре историй возникает баг. 

**Опишите действия для воспроизведения ошибки**
1. открываешь историю, а вместо неё другая. 

Uploading Screenrecorder-2023-05-05-20-00-07-389.mp4…

**Comment by danyyok** [comment]
@nokogury https://t.me/vtosters_faq/110

Duplicate+invalid issue 
#1129
