### ISSUE TITLE
Не работает нивидимка вообще

### ISSUE THREAD

**Issue by A1brus** [vtosters/lite#1270]
**Опишите сам баг**
истории не загружает, только первую, иногда при заходе на страницу сразу отправляет в онлайн

**Опишите действия для воспроизведения ошибки**
1. Открыл группу
2. Зашёл в истории, попробовал полистать (сам кружок) (включён режим нечиталки историй)

**Опишите ожидаемый результат**
Истории должны пролистываться

**Скриншот ошибки**
![Screenshot_20230507-140235](https://user-images.githubusercontent.com/60397054/236668298-e89b7e93-d16a-4fa1-b1f8-c87a4f8ef474.png)
![Screenshot_20230507-140255](https://user-images.githubusercontent.com/60397054/236668299-b4a6bd8f-7375-4a8e-a192-2819b1ab0fd5.png)
![Screenshot_20230507-140304](https://user-images.githubusercontent.com/60397054/236668300-ebfb3be9-d82f-40e0-b356-509e2d490caa.png)
![Screenshot_20230507-140318](https://user-images.githubusercontent.com/60397054/236668302-43d941ae-b1a9-451d-9f21-3367e46b1367.png)
![Screenshot_20230507-140410](https://user-images.githubusercontent.com/60397054/236668303-8f5e9bae-5d17-4aa9-8da8-851b84dc014d.png)

**Информация об устройстве:** 

- Commit: cc55d5d
- Android SDK: 33
- Product: rtwo_cn
- Device: rtwo
- Board: rtwo
- Manufacturer: motorola
- Brand: motorola
- Model: XT2301-5

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**
Программисту заплатили, программист встать, программист работать.

**Comment by danyyok** [comment]
https://t.me/vtosters_faq/110

Duplicate issue 
#1129
