### ISSUE TITLE
лаг сторис

### ISSUE THREAD

**Issue by vanixxxxx** [vtosters/lite#1271]
посмотрел одну историю и теперь на она распространена на всех сторис, которые могу посмотреть
![photo_2023-05-07_20-13-58](https://user-images.githubusercontent.com/110800041/236676811-1fdb3abd-2cd9-4064-8c4b-31820b6f8d2f.jpg)
![photo_2023-05-07_20-13-55](https://user-images.githubusercontent.com/110800041/236676814-151ce17a-5708-4e94-b8b9-f5b5d64ea753.jpg)

**Comment by danyyok** [comment]
@vanixxxxx https://t.me/vtosters_faq/110

Duplicate+invalid issue 
#1129
