### ISSUE TITLE
Ошибка при просмотре историй

### ISSUE THREAD

**Issue by seishiki** [vtosters/lite#1273]
**Опишите сам баг**
В историях постоянно воспроизводиться одна и та же история. Сам баг наблюдаю на протяжении примерно 3-х версий приложения.
На скринах видно что история всегда одна и та же.

**Опишите действия для воспроизведения ошибки**
1. Нажимаю на историю любого сообщества

**Скриншот ошибки**
![Screenshot_2023-05-07-20-55-23-176_com vtosters lite](https://user-images.githubusercontent.com/132843225/236694612-77ba4fe0-49c8-4060-b755-6deda4068d1a.jpg)
![Screenshot_2023-05-07-20-55-29-900_com vtosters lite](https://user-images.githubusercontent.com/132843225/236694613-ea0cda4d-50f5-46b5-890c-07a08723d48a.jpg)
![Screenshot_2023-05-07-20-55-35-022_com vtosters lite](https://user-images.githubusercontent.com/132843225/236694614-684a9bdf-c492-495f-aa3e-52448ec3e2f7.jpg)

**Устройство POCO X3 Pro

**Comment by danyyok** [comment]
@seishiki https://t.me/vtosters_faq/110

Duplicate+invalid issue 
#1129
