### ISSUE TITLE
Ошибка был в сети "недавно"

### ISSUE THREAD

**Issue by Nikitakv2002** [vtosters/lite#1274]
Здравствуйте. 
Ошибка в приложении VTLite, пользовался с основания чтобы быть офлайн. Теперь хочу быть онлайн, но при выключении данной функции все равно остаюсь офлайн, и не вижу кто из друзей онлайн. Думал зайду в обычное приложение ВК и всё будет нормально, но нет. Даже было удалял приложение VTL, думая что оно причастно, но ничего не помогло.
Как быть в данной ситуации, потому что это как-то пугает уже?!
![Screenshot_2023-05-08-01-27-04-087_com vkontakte android-edit](https://user-images.githubusercontent.com/132855011/236705482-ac2b1f34-514a-438c-8016-5151c62ad340.jpg)

**Comment by Wperdex** [comment]
@Nikitakv2002 

 В VTLite невозможно настроить "в сети недавно". Тот офлайн, который настраивал ты — не невидимка.

Для снятия невидимки воспользуйся официальным мессенджером от ВК:

Скачать VK Мессенджер: https://play.google.com/store/apps/details?id=com.vk.im

Как настроить «был недавно»: Профиль > Конфиденциальность > Кто видит, что я онлайн

**Comment by Nikitakv2002** [comment]
> @Nikitakv2002
> 
> В VTLite невозможно настроить "в сети недавно". Тот офлайн, который настраивал ты — не невидимка.
> 
> Для снятия невидимки воспользуйся официальным мессенджером от ВК:
> 
> Скачать VK Мессенджер: https://play.google.com/store/apps/details?id=com.vk.im
> 
> Как настроить «был недавно»: Профиль > Конфиденциальность > Кто видит, что я онлайн

Спасибо!

**Comment by Nikitakv2002** [comment]
https://github.com/vtosters/lite/issues/1274#issuecomment-1537555209
Спасибо!
