### ISSUE TITLE
Ошибка открытия диалогов и сообщений

### ISSUE THREAD

**Issue by Cergik-2001** [vtosters/lite#1276]
**Опишите сам баг**
Сообщения очень долго прогружаются. Уже невыносимо общаться через VTlite.

**Опишите действия для воспроизведения ошибки**
1. Открываю диалог
2. Жду 43929274826 лет, пока загрузятся сообщения 

**Опишите ожидаемый результат**
Сообщения должны приходить и обновляться быстрее 

**Скриншот ошибки**

![Screenshot_2023-05-08-08-47-42-993_com vtosters lite](https://user-images.githubusercontent.com/132871521/236736495-e3eade31-5485-45c4-b52e-03e9e1b7e7e5.jpg)
![Screenshot_2023-05-08-08-47-34-206_com vtosters lite](https://user-images.githubusercontent.com/132871521/236736498-df9a7a10-dc65-41a1-bf13-1e357ee7921f.jpg)

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

**Comment by olegmortisov** [comment]
Здравствуйте, проверьте стабильность интернета.

**Comment by WeSTManCoder** [comment]
Здравствуйте! Такая же штука происходит, очень стали долго грузиться диалоги, у моего товарища такая же штука

**Comment by DeeMon404** [comment]
Та же история. Постоянно подтупливает. От интернета не зависит. Может затупить как на мобильном интернете так и на домашнем wi-fi

**Comment by wolf968** [comment]
Все тоже самое, только всегда и на разнос интернете, особенно сильно глчат чаты с большим количеством людей и сообщений

**Comment by gdlbo** [comment]
исправлено, скоро будет апдейт с патчем
