### ISSUE TITLE
Сломались истории

### ISSUE THREAD

**Issue by Nechegonepridymal** [vtosters/lite#1280]
Сломались истории, при показе картинок истории всё нормально, но при показе видео в историях показывает ранее просмотренную историю другого человека.

**Информация об устройстве:** 

- Commit: 681dd17
- Android SDK: 31
- Product: viva_global
- Device: viva
- Board: viva
- Manufacturer: Xiaomi
- Brand: Redmi
- Model: 2201116TG
- Miui Version Code: 13
- Miui Version Name: V130
- Miui Version Incremental Code: V13.0.6.0.SGDMIXM

Кэш не могу очистить, музыка долго собирал, реально ли это как то пофиксить?

**Comment by tangenx** [comment]
@Nechegonepridymal Дубликат.
#1129

**Comment by danyyok** [comment]
https://t.me/vtosters_faq/110
 
#1129
