### ISSUE TITLE
Баги в историях 

### ISSUE THREAD

**Issue by MrGreenier** [vtosters/lite#1281]
**Опишите сам баг**
При просмотре историй либо возникает ошибка "произошла ошибка при загрузке истории", либо ровно одна история (картинка) прогружается, и при попытке листать дальше, не важно какой паблик или человек, чья история, будет эта картинка заместо того, что запостили.

**Опишите действия для воспроизведения ошибки**
1. Обновил ленту 
2. Открыл историю

**Опишите ожидаемый результат**
Должна загрузиться история 

**Скриншот ошибки**
![Screenshot_20230509-115433_VTLite](https://user-images.githubusercontent.com/112576849/237046207-2fb8ec5f-7faa-42ca-a42d-49c9c3ffea55.png)

**Информация об устройстве:** 

- Commit: 681dd17
- Android SDK: 33
- Product: vayu
- Device: vayu
- Board: msmnile
- Manufacturer: Xiaomi
- Brand: POCO
- Model: M2102J20SI
- 

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**
Баг можно временно пофиксить очисткой кэша и перезапуском приложения, но это может сработать только с второго - третьего раза

**Comment by danyyok** [comment]
@MrGreenier https://t.me/vtosters_faq/110

Duplicate issue 
#1129
