### ISSUE TITLE
Залипает сторис

### ISSUE THREAD

**Issue by delavega212** [vtosters/lite#1284]
**Опишите сам баг**
При просмотре сторисов, залипает один из них и заменяет собой другие, они на пол секунды видны,а потом сразу идёт этот залипший сторис
**Опишите действия для воспроизведения ошибки**
1 открыл любой сторис
**Опишите ожидаемый результат**
увидеть сторисы тех, на кого подписан,а не один какой то рандомный.
![Screenshot_2023-05-10-16-48-13-58_ea44fb1caa4f2d77669d857426853335](https://github.com/vtosters/lite/assets/133126905/8d49d20b-d2cd-4534-af94-54c563722ff1)

RMX2063RU
681dd17
30

**Comment by danyyok** [comment]
@delavega212 https://t.me/vtosters_faq/110

Duplicate+invalid issue 
#1129
