### ISSUE TITLE
Ошибка обновлении ленты новостей

### ISSUE THREAD

**Issue by ca2701563** [vtosters/lite#1288]
**Опишите сам баг**
При обновлении новостей буквально ничего не происходит, остаются те же самые новости которые и были, а обновляется по своему желанию при перезаходе через время.

**Опишите действия для воспроизведения ошибки**
1. Обновил ленту интересных новостей

**Опишите ожидаемый результат**
Новостная лента должна обновляться 

**Скриншот ошибки**
![Screenshot_2023-05-12-09-59-53-105_com vtosters lite](https://github.com/vtosters/lite/assets/133315598/015a91e4-d7f8-4aaa-a029-744ded89320c)
![Screenshot_2023-05-12-09-59-58-743_com vtosters lite](https://github.com/vtosters/lite/assets/133315598/fde5815d-17e6-4a07-bdb7-a1fe1cfccfbe)

**Информация об устройстве:** 

- Commit: 681dd17
- Android SDK: 29
- Product: lavender_ru
- Device: lavender
- Board: sdm660
- Manufacturer: Xiaomi
- Brand: xiaomi
- Model: Redmi Note 7
- Miui Version Code: 11
- Miui Version Name: V125
- Miui Version Incremental Code: V12.5.1.0.QFGRUXM

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)** 
-вообще не в курсе почему так

**Comment by tangenx** [comment]
@ca2701563 В настройках новостей сортировка какая?

**Comment by icynstant** [comment]
Сначала интересные стоит и такая же проблема, откройте ошибку, она не решена, объяснил в #1510

**Comment by ayonovdenizs** [comment]
@icynstant https://github.com/vtosters/lite/issues/1510#issuecomment-1831906593
