### ISSUE TITLE
Ошибка обновлении ленты новостей

### ISSUE THREAD

**Issue by narKOT1** [vtosters/lite#1292]
Невозможно прикрепить изображение к посту в группе/паблик

1. Открываю редактор поста, выбираю добавить изображение
2. Приложение зависает и вылетает

![Screenshot_20230428_093656](https://github.com/vtosters/lite/assets/132044308/1fb4df38-deb1-4649-8c20-5ab9e2c01f01)

**Comment by Wperdex** [comment]
@narKOT1 отредактируйте issue с и укажите информацию об устройстве в правильном формате.

**Настройки > Другое > Скопировать информацию об устройстве**
