### ISSUE TITLE
Одна и та же история повторяется на истории из других источников 

### ISSUE THREAD

**Issue by unitrixxx** [vtosters/lite#1298]
**Опишите сам баг**
После просмотра истории с одним видео, на следующих историях повторяется это же видео. Так происходит, пока не очистить кэш приложения

**Опишите действия для воспроизведения ошибки**
1. Зашёл на историю и просмотрел
2. На остальных историях с видео повторяется эта же история 

**Опишите ожидаемый результат**
Должны прогружаться другие видео в истории
**Скриншот ошибки**
https://drive.google.com/file/d/19JRJ9CtOataJrEV_ITDkP3LxD_XhuKZj/view?usp=drivesdk
**Информация об устройстве:** 

- Commit: 681dd17
- Android SDK: 33
- Product: redfin
- Device: redfin
- Board: redfin
- Manufacturer: Google
- Brand: google
- Model: Pixel 5

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**
Происходит совершенно рандомно, история почему-то откладывается в кэш и потом этот кэш судя по всему воспроизводится вместо того, чтобы прогружать новую

**Comment by ayonovdenizs** [comment]
@unitrixxx https://t.me/vtosters_faq/110

Duplicate issue 
#1129
