### ISSUE TITLE
В историях повторяется одна и та же видеозапись

### ISSUE THREAD

**Issue by tonyst2** [vtosters/lite#1299]
**Опишите сам баг**
При просмотре историй повторяется в видеозапись, которую я просматривал первой. То есть, если в историю загружена ДРУГАЯ видеозапись, то воспроизводится видеозапись из первой истории, которую я посмотрел, этот баг также происходит, когда я хочу посмотреть историю уже другого человека, повторяется одна и та же видеозапись

**Опишите действия для воспроизведения ошибки**
1. Просто открыл VTLite
2. Открыл историю, с содержанием в ней видеозаписи

**Скриншот ошибки**
![Screenshot_2023-05-14-09-12-16-55_9e1a5d6211a0228d32d39446541891f1](https://github.com/vtosters/lite/assets/101515333/3359ce7a-aa71-4805-84bc-2b298e694fcc)
![Screenshot_2023-05-14-09-12-47-65_9e1a5d6211a0228d32d39446541891f1](https://github.com/vtosters/lite/assets/101515333/d66d7c0e-aab3-4551-9e46-963d77b78489)

**Информация об устройстве:** 

- Commit: 681dd17
- Android SDK: 33
- Product: RMX3630RU
- Device: RE8DDCL1
- Board: k6789v1_64
- Manufacturer: realme
- Brand: realme
- Model: RMX3630

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

Кеши чистил, переустанавливал приложение, ошибка повторяется.
Видео там должно быть разным, на официальном клиенте ошибки нет.

**Comment by ayonovdenizs** [comment]
@tonyst2 https://t.me/vtosters_faq/110

Duplicate issue 
#1129
