### ISSUE TITLE
Неверные цены на стикеры в магазине.

### ISSUE THREAD

**Issue by Gurenomaru** [vtosters/lite#13]
В магазине цены на стикеры отображаются без учёта скидки, при попытке купить выкидывает обратно.

**Comment by gdlbo** [comment]
Без скидки это проблема апи, фиксить это сейчас не в приоритете 

А закрытие покупки стикеров это баг если ты используешь блокировку рекламы (из-за блокировки метрики на странице сама страница закрывается)
