### ISSUE TITLE
Не пропадают рекомендации постов 

### ISSUE THREAD

**Issue by ForT4eHorde** [vtosters/lite#130]
Хоть в настройках и включено они не пропали
![Screenshot_20220411-230158](https://user-images.githubusercontent.com/76121080/162821858-cd6cee14-a439-49a6-bdc8-348234debed8.jpg)
![Screenshot_20220411-230140](https://user-images.githubusercontent.com/76121080/162821878-a061475d-52aa-4232-99df-0283660cecc3.jpg)

**Comment by gdlbo** [comment]
если переключатель включен - значит они включены
