### ISSUE TITLE
Добавить в хедер раздела сервисы кнопку для перехода в профиль

### ISSUE THREAD

**Issue by dkostarnov** [vtosters/lite#1301]
В vk tea (как и в оригинальном вк) имеется кнопка перехода в профиль в заголовке страницы "сервисы". Ее стоит добавить, так как имея эту кнопку там - можно убрать ее из док бара. В быстром доступе она нужна не всем, но хоть какой-то доступ к настройкам должен быть. А в настройки можно попасть только через бургер меню в профиле.

**Comment by dkostarnov** [comment]
Как это реализовано в vk tea
![telegram-cloud-photo-size-2-5411185165897681011-y](https://github.com/vtosters/lite/assets/73770663/8b08c18b-b182-4153-b35d-15c409799dce)

**Comment by gdlbo** [comment]
Не будет
