### ISSUE TITLE
Ошибка историй в ленте

### ISSUE THREAD

**Issue by San1k-02** [vtosters/lite#1302]
**Опишите сам баг**
В ленте историй после одной просмотренной истории такая же история отображается у других пользователей в ленте вместо их историй. То есть одна и та же отображается вместо нормальных

**Опишите действия для воспроизведения ошибки**
1. Просмотрел историю одного человека
2. Открываю историю другого человека, в ней содержание истории первого. 

**Опишите ожидаемый результат**
История второго человека должна быть другой, а не историей предыдущего

**Скриншот ошибки**
Нет, но могу прислать видео, если нужно будет

**Скопируйте сюда информацию об устройстве
**Информация об устройстве:** 

- Commit: 681dd17
- Android SDK: 33
- Product: vayu_global
- Device: vayu
- Board: vayu
- Manufacturer: Xiaomi
- Brand: POCO
- Model: M2102J20SG
- Miui Version Code: 14
- Miui Version Name: V140
- Miui Version Incremental Code: V14.0.1.0.TJUMIXM

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**
Какие-то истории отображаются нормально, но не все. Также в некоторых возникает ошибка загрузки истории, предварительно показав часть истории первого человека.

**Comment by GooDoG337** [comment]
@San1k-02 https://t.me/vtosters_faq/110

Duplicate issue 
#1129
