### ISSUE TITLE
В историях показывается другое видео

### ISSUE THREAD

**Issue by Sheidheda666** [vtosters/lite#1305]
**Опишите сам баг**
При открытии своей или чужой истории показывается одно и то же видео.

**Опишите действия для воспроизведения ошибки**

1. Загрузить любое видео в историю.
2. После того, как история загрузилась, открыть её снова.

**Опишите ожидаемый результат**
В истории должно показываться именно то видео, какое я загружаю.

**Скриншот ошибки**
![Screenshot_2023-05-16-14-54-28-62_9e1a5d6211a0228d32d39446541891f1](https://github.com/vtosters/lite/assets/120330975/9dc17298-3dd6-4a76-9080-534d9d037138)

**Информация об устройстве:** 

- Commit: 681dd17
- Android SDK: 33
- Product: RMX3472RU
- Device: RE54CBL1
- Board: holi
- Manufacturer: realme
- Brand: realme
- Model: RMX3472

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

**Comment by ayonovdenizs** [comment]
@Sheidheda666 https://t.me/vtosters_faq/110

Duplicate issue 
#1129
