### ISSUE TITLE
Баг с видео-историями

### ISSUE THREAD

**Issue by Pr0gger1** [vtosters/lite#1306]
**Опишите сам баг**
Происходит проигрывание одного и того же видео (я так понимаю, первого просмотренного) в других историях групп/людей. То есть видео-история группы/человека замещается одним и тем же видео из другой истории

**Опишите действия для воспроизведения ошибки**
1. Просмотрел первую в списке историю, содержащую видео 
2. Листаю истории дальше
3. На следующей истории, содержащей видео, воспроизводится контент из пункта 1

![Screenshot_2023-05-16-23-47-06-010_com.android.settings.jpg](https://github.com/vtosters/lite/assets/61430541/8054489e-57bd-4acb-a206-4aeddad12714)

![Screenshot_2023-05-16-23-46-54-629_com.android.settings.jpg](https://github.com/vtosters/lite/assets/61430541/b5c0285a-7a68-461b-a5cb-4c61cbf13f98)

**Comment by ayonovdenizs** [comment]
https://t.me/vtosters_faq/110

Duplicate issue 
[#1129](https://github.com/vtosters/lite/issues/1129)
