### ISSUE TITLE
Исчезли плейлист дня

### ISSUE THREAD

**Issue by Forec18** [vtosters/lite#1308]
**Опишите сам баг**
Исчезли плейлист дня

**Опишите действия для воспроизведения ошибки**
1. Зайти в музыку и пролистать чуть ниже в главной вкладке

**Опишите ожидаемый результат**
Должны появиться плейлисты дня собранные алгоритмами

**Скриншот ошибки**
![Screenshot_20230517-144000](https://github.com/vtosters/lite/assets/133872777/c7110e4f-b878-4c01-8290-b07858dda964)

**Информация об устройстве:** 

- Commit: 681dd17
- Android SDK: 26
- Product: AUM-L41RU
- Device: HWAUM-Q
- Board: AUM-L41
- Manufacturer: HUAWEI
- Brand: HONOR
- Model: AUM-L41
- Emui Version: EmotionUI_8.0.0 

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

**Comment by ayonovdenizs** [comment]
@Forec18 https://t.me/vtosters_faq/112

**Comment by aliveoutside** [comment]
исправлено в 16260c5666594de50f2ae21debbddbd86f0060c8
