### ISSUE TITLE
Одно и то же видео в историях

### ISSUE THREAD

**Issue by k1zn** [vtosters/lite#1309]
**Опишите сам баг**
Если посмотреть какую-то историю, которая содержит видео, то при листании следующих историй вместо их видео будет показываться первая просмотренная видеоистория (т.е, если ты открыл историю, внутри которой видео, то оно будет повторяться во всех следующих историях людей и сообществ, если у них формат истории тоже видео)

**Опишите действия для воспроизведения ошибки**
1. Открыть любую историю с видео
2. Начать смотреть следующие истории

**Опишите ожидаемый результат**
Следующие истории должны отображать корректные видео

**Скриншот ошибки**
\-

**Скопируйте сюда информацию об устройстве нажав на кнопку "Скопировать информацию об устройстве" в Настройках -> Другое и удалите этот текст**
думаю, не требуется (если потребуется, изменю текст)

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**
\-

**Comment by gresksn** [comment]
Подтверждаю, есть такой баг

**Comment by eastsidekillas** [comment]
**Информация об устройстве:** 

- Commit: 681dd17
- Android SDK: 33
- Product: OnePlus9
- Device: OnePlus9
- Board: lahaina
- Manufacturer: OnePlus
- Brand: OnePlus
- Model: LE2115

**Comment by masyaaaaaaa** [comment]
тож самое

**Comment by zappere50** [comment]
Оно в том числе ломает вкладки в приложении. Они не грузят содержимое. По крайней мере у меня так

**Comment by danyyok** [comment]
> Оно в том числе ломает вкладки в приложении. Они не грузят содержимое. По крайней мере у меня так

Известно

**Comment by kot-v-mechke** [comment]
Да, тоже самое. Могу еще добавить то, что если очистить полностью кеш приложения, то видео, которое показывается во всех историях, сотрётся, но если потом открыть снова историю, то загрузится уже новое видео, которое также в будущем будет отображаться в других историях

**Comment by Kiarant** [comment]
Такая же проблема.

**Comment by Torantillo** [comment]
То же самое

**Comment by ayonovdenizs** [comment]
> То же самое

Цитирую из: https://t.me/vtosters_faq/110

_У многих наблюдаются проблемы с воспроизведением видео-историй (повторение предыдущего видео). 

Разработчики уже изучают проблему, следите за новостями на основном канале_

**Comment by WeSTManCoder** [comment]
Подтверждаю, ловлю такой же баг

**Comment by Losb0533** [comment]
1. Захожу в приложение
2. Нажимаю на иконку с историей от паблика/группы
3. Воспроизводится 1-2 секунды и выходит ошибка (см скрин)
![Screenshot_20230530_200133_VTLite](https://github.com/vtosters/lite/assets/135052324/ecaecdea-707d-41e0-acff-f2b49583c99b)

4. При перелистывании историй выдает ошибку или предыдущую историю и продолжает её повторять при попытках просмотреть следующую.
5. Попытка очистки кеша и перестановка приложения продлемутне решает.

В текстовых и/или статичных историй (фото) проблем не наблюдаются, отображается корректно.

Ожидаемый результат.
Должно отображается корректное видео в истории.
Следующие истории должны отображать корректные видео.

**Информация об устройстве:** 

- Commit: ff8e7b7
- Full Version Information: main-ff8e7b7-dirty
- Android SDK: 33
- Product: z3sxser
- Device: z3s
- Board: exynos990
- Manufacturer: samsung
- Brand: samsung
- Model: SM-G988B
- OneUi Major Version: 5
- OneUi Minor Version: 1.0

**Comment by ayonovdenizs** [comment]
@Losb0533 Дубликат:https://t.me/vtosters_faq/110

**Comment by BForumer** [comment]
Поддерживаю, тот же баг, начался приблизительно с версии 0.7.0. 0.7.3 - проблема не исправлена.
Pixel 3a, Android 12

**Comment by tangenx** [comment]
@BForumer https://t.me/vtosters_faq/110

Дубликат. Вы откуда 0.7.3, взяли если релиз 0.7.2 вышел только 11 часов назад?
#1129 / #1309

**Comment by BForumer** [comment]
@tangenx Вроде обновление 0.7.3 пришло, обновлялся через приложение. Возможно, ошибся.  В самом приложении не видно номерную версию. Написано Release ff8e7b7 ( настройки - раздел о модификации)

**Comment by Losb0533** [comment]
> @BForumer Вы откуда 0.7.3, взяли если релиз 0.7.2 вышел только 11 часов назад?

В будущем живем)

**Comment by kaban999999999** [comment]
Тоже такой баг...
Samsung S23Ultra

**Comment by Solovey61** [comment]
Аналогично
Google pixel 7 pro

**Comment by KrackensCorp** [comment]
Актуально, 
OnePlus 6
API 30

**Comment by perwak123** [comment]
Xiaomi 12t 256 баг присутствует. 
Очистка кэша результата не несёт

**Comment by Serdobine** [comment]
@perwak123 дубликат

**Comment by JaguarSnake** [comment]
Присоединяюсь, уже месяц мучаюсь. Honor 20 Pro. Я так понял от телефона не зависит

**Comment by ayonovdenizs** [comment]
Читайте faq, зря ссылку оставлял? https://t.me/vtosters_faq/110

**Comment by Sibir23** [comment]
Уже на протяжении примерно 5 обновлений приложения эта проблема никак не решается. Одно и то же видео в историях повторяется и у других людей/сообществах. Не обязательно даже видео, просто фото с прикрепленным аудио так же повторяется. Когда будет решена проблема, разработчики?

**Comment by abslike** [comment]
@Sibir23 поподробнее насчёт фото с прикрепленным аудио

**Comment by Notnex-cat** [comment]
Да, та же самая проблема
**Информация об устройстве:** 

- Commit: cf17ed6
- Full Version Information: main-cf17ed6-dirty
- Android SDK: 33
- Product: dm1qxxx
- Device: dm1q
- Board: kalama
- Manufacturer: samsung
- Brand: samsung
- Model: SM-S911B
- OneUi Major Version: 5
- OneUi Minor Version: 1.0

**Comment by baskmooon** [comment]
Тоже самое на realme 6 pro, к слову этот баг не фиксят уже пол года.

**Comment by ayonovdenizs** [comment]
> Тоже самое на realme 6 pro, к слову этот баг не фиксят уже пол года.

https://t.me/vtosters_faq/110

**Comment by veron1ka19** [comment]
То же самое. Как это исправить?

**Comment by gresksn** [comment]
> То же самое. Как это исправить?

Удалить приложение. Баг не исправляют уже долгое время, значит не знают как.

**Comment by lollimerz** [comment]
![Screenshot_20230826-202816842](https://github.com/vtosters/lite/assets/122024882/4c683b60-741c-46c4-b0a5-f0bc0ceb6857)
Такая же проблема, вот инфа об устройстве

**Comment by keizixo** [comment]
**Информация об устройстве:** 

- Commit: cf17ed6
- Full Version Information: main-cf17ed6-dirty
- Android SDK: 33
- Product: cmi
- Device: cmi
- Board: cmi
- Manufacturer: Xiaomi
- Brand: Xiaomi
- Model: Mi 10 Pro
- Miui Version Code: 14
- Miui Version Name: V140
- Miui Version Incremental Code: V14.0.3.0.TJACNXM

**Comment by ayonovdenizs** [comment]
> **Информация об устройстве:**
> 
> * Commit: [cf17ed6](https://github.com/vtosters/lite/commit/cf17ed64c759d366ae7121dc61c4328205963ed4)
> * Full Version Information: main-cf17ed6-dirty
> * Android SDK: 33
> * Product: cmi
> * Device: cmi
> * Board: cmi
> * Manufacturer: Xiaomi
> * Brand: Xiaomi
> * Model: Mi 10 Pro
> * Miui Version Code: 14
> * Miui Version Name: V140
> * Miui Version Incremental Code: V14.0.3.0.TJACNXM

https://t.me/vtosters_faq/110
