### ISSUE TITLE
Выбор качества видео

### ISSUE THREAD

**Issue by slavrom21** [vtosters/lite#131]
При выборе качества видео два пункта 720p ![Screenshot_2022-04-11-23-00-15-27_9e1a5d6211a0228d32d39446541891f1.jpg](https://user-images.githubusercontent.com/71776639/162820947-9aa7fb5f-19ac-42a2-8607-b13b1971b8c8.jpg)

**Comment by gdlbo** [comment]
https://github.com/vtosters/lite/issues/113
