### ISSUE TITLE
пропали плейлисты "собрано алгоритмами"(((

### ISSUE THREAD

**Issue by ap11z3dex** [vtosters/lite#1313]
**Опишите сам баг**
пропали плейлисты

**Опишите действия для воспроизведения ошибки**
1. зашёл в раздел музыки 

**Опишите ожидаемый результат**
должны быть плейлисты😐

**Скриншот ошибки**
![IMG_20230519_233822_831](https://github.com/vtosters/lite/assets/134102996/1d68b6a3-4a8a-4946-a47b-e003ef01c0a1)

**Информация об устройстве:** 

- Commit: 681dd17
- Android SDK: 33
- Product: ingres_global
- Device: ingres
- Board: taro
- Manufacturer: Xiaomi
- Brand: POCO
- Model: 21121210G
- Miui Version Code: 14
- Miui Version Name: V140
- Miui Version Incremental Code: V14.0.2.0.TLJMIXM

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**
нет

**Comment by gdlbo** [comment]
Будет исправлено в следующей версии
