### ISSUE TITLE
одно и то же видео в историях 

### ISSUE THREAD

**Issue by masyaaaaaaa** [vtosters/lite#1314]
Одно и тоже видео в историях

1. просмотрела историю одного человека
2. она высвечивается вместо видеоисторий других людей и сообществ, в том числе вместо моих

Истории должны соответствовать их авторам

![Screenshot_20230520-004248_VTLite](https://github.com/vtosters/lite/assets/134106827/af543f43-cab5-4bb5-9c0e-9a96df42651a)
![Screenshot_20230520-004241_VTLite](https://github.com/vtosters/lite/assets/134106827/1762d782-41e7-4d66-8dd3-14dfc4d0fecd)
![Screenshot_20230520-004232_VTLite](https://github.com/vtosters/lite/assets/134106827/a34c48cd-d758-4716-96aa-6f647979ae97)

**Comment by gdlbo** [comment]
Дубликат #1309
