### ISSUE TITLE
Неправильная тёмная тема

### ISSUE THREAD

**Issue by AnemWind** [vtosters/lite#1315]
**Опишите сам баг**
При включении тёмной темы окно мои сообщений остаётся светлым, в то время как сам цвет текста поменялся на белый, и в итоге ничего не видно

**Опишите действия для воспроизведения ошибки**
1. Включил тёмную тему
2. Зашёл в сообщения и написал любое сообщение

**Опишите ожидаемый результат**
Чтобы нормально тёмная тема работала 

**Скриншот ошибки**
![1684610965077](https://github.com/vtosters/lite/assets/134167683/cf5539e8-e398-48dd-848b-f4acaa356011)

**Comment by danyyok** [comment]
Перезапустите клиент/принудительно закройте приложение через системные настройки
