### ISSUE TITLE
Ошибка при попытке опубликовать изображение в группе

### ISSUE THREAD

**Issue by narKOT1** [vtosters/lite#1317]
При попытке загрузить в пост изображение приложение вылетает

1. Открыть редактор постов
2. Выбрать опцию добавления изображения из телефона

Возможность загружать изображения в пост

Модель — V2027
Версия Android — 12
Процессор — 1,8 ГГц Snapdragon SDM460 восьмиядерный
ОЗУ — 4,00 Гб
Память телефона — 64,00 Гб
IMEI1 — 860410058530072
IMEI2 — 860410058530064
# версии аппаратного обеспечения — MP_0.1 
Версия ПО — PD2034F_EX_A_6.8.4
Прошивка модуля связи — RTA_GEN_PACK-1.47978 0.1.501023.1
Версия ядра — 4.19.136-perf+ 
Время компиляции — 2022 05 27

**Comment by danyyok** [comment]
Пересоздайте Issue по шаблону прикрепив информацию об устройстве
