### ISSUE TITLE
Отсутствие плейлистов от алгоритмов

### ISSUE THREAD

**Issue by narKOT1** [vtosters/lite#1318]
В меню музыки отсутствуют плейлисты от алгоритмов

Плейлисты от алгоритмов на своем месте

![Screenshot_20230521_084234](https://github.com/vtosters/lite/assets/132044308/c650681d-3dec-4d20-b72b-f81d9abded2b)

Модель — V2027
Версия Android — 12
Процессор — 1,8 ГГц Snapdragon SDM460 восьмиядерный
ОЗУ — 4,00 Гб
Память телефона — 64,00 Гб
IMEI1 — 860410058530072
IMEI2 — 860410058530064
# версии аппаратного обеспечения — MP_0.1 
Версия ПО — PD2034F_EX_A_6.8.4
Прошивка модуля связи — RTA_GEN_PACK-1.47978 0.1.501023.1
Версия ядра — 4.19.136-perf+ 
Время компиляции — 2022 05 27

**Comment by danyyok** [comment]
@narKOT1 Исправлено

**Comment by ayonovdenizs** [comment]
известно, ждите обновления
