### ISSUE TITLE
Недокрас в светлой теме

### ISSUE THREAD

**Issue by MRaist** [vtosters/lite#132]
0.1.0 alpha
![Screenshot_20220411-235038](https://user-images.githubusercontent.com/103269174/162830331-476a5d7f-b6eb-4d7c-b4db-25583d39ee34.png)
![Screenshot_20220411-235052](https://user-images.githubusercontent.com/103269174/162830339-5ea4f0d0-5e51-4d1d-b6c0-b3c007c963cf.png)

**Comment by gdlbo** [comment]
https://github.com/vtosters/lite/commit/2374785ae7ed8dd31d05e9dbbc67e41322a0c12c
