### ISSUE TITLE
Ошибка просмотра историй 

### ISSUE THREAD

**Issue by 777Best** [vtosters/lite#1320]
При просмотре историй своих или чьих-то ещё, смотришь истории от другого человека, при чём даже если эта история больше не доступна для просмотра.

Данная ошибка лично у меня лечится только перезаходом на страницу, но опять появляется как только посмотришь что-нибудь историю.

Почините это пожалуйста.

![Screenshot_2023-05-21-23-12-24-46_9e1a5d6211a0228d32d39446541891f1](https://github.com/vtosters/lite/assets/134232811/6394fd50-0941-4b8c-a3a6-228c50326d82)
![Screenshot_2023-05-21-23-12-28-02_9e1a5d6211a0228d32d39446541891f1](https://github.com/vtosters/lite/assets/134232811/164b8dba-0029-4d70-a962-f7476dd6c23c)
![Screenshot_2023-05-21-23-12-52-31_9e1a5d6211a0228d32d39446541891f1](https://github.com/vtosters/lite/assets/134232811/9535a180-2776-4c0a-9497-e8fdc0c0d8f7)

**Информация об устройстве:** 

- Commit: 8244b31
- Full Version Information: main-8244b31-dirty
- Android SDK: 31
- Product: RMX3085RU
- Device: RMX3085L1
- Board: RM6785
- Manufacturer: realme
- Brand: realme
- Model: RMX3085

**Comment by danyyok** [comment]
@777Best https://t.me/vtosters_faq/110

Duplicate+invalid issue 
#1129 / #1309
