### ISSUE TITLE
Сообщения сообщества не работают

### ISSUE THREAD

**Issue by artshevchenko95** [vtosters/lite#1325]
При открытии сообщества у которого я администратор и при заходе в раздел сообщения сообщества неожиданное поведение: открывается список личных бесед (не сообщества)

**Comment by danyyok** [comment]
@artshevchenko95 Второй раз зайдите в раздел сообщений

**Comment by artshevchenko95** [comment]
> @artshevchenko95 Второй раз зайдите в раздел сообщений

Хм, действительно работает. Получается можно закрывать баг
