### ISSUE TITLE
Не отображается статус онлайна у людей, если впн отключен 

### ISSUE THREAD

**Issue by MrNayz** [vtosters/lite#1328]
![Screenshot_2023-05-23-06-11-00-757_com vtosters lite-edit](https://github.com/vtosters/lite/assets/123476723/b544793d-a37a-4f28-b5b9-413a5bb9108d)
![Screenshot_2023-05-23-06-09-40-773_com vtosters lite-edit](https://github.com/vtosters/lite/assets/123476723/c153259c-2a98-4036-ae2d-a017ae27a475)

**Comment by ayonovdenizs** [comment]
пересоздайте issue по шаблону
invalid issue
