### ISSUE TITLE
Баг с историями 

### ISSUE THREAD

**Issue by Digrad228** [vtosters/lite#1331]
**Опишите сам баг**
При просмотре видео в историях, повторяется одно и тоже видео

**Опишите действия для воспроизведения ошибки**
1. Открываешь историю 
2. Пролистал до конца страницы

**Опишите ожидаемый результат**
Истории должны соответствовать тому что выкладывают в группах или что выкладывают люди

**Скриншот ошибки**
![Screenshot_20230523_143638_com vtosters lite](https://github.com/vtosters/lite/assets/134391446/6caf55b6-9f83-4505-9816-8cdba6930ea3)
![Screenshot_20230523_143643_com vtosters lite](https://github.com/vtosters/lite/assets/134391446/69c6a472-9771-452f-a5b6-fd6b3149b449)
![Screenshot_20230523_143645_com vtosters lite](https://github.com/vtosters/lite/assets/134391446/50098efa-d648-4d13-93d5-c162c89d52b8)

**Скопируйте сюда информацию об устройстве нажав на кнопку "Скопировать информацию об устройстве" в Настройках -> Другое и удалите этот текст**
 vk1.a.L97uYe48aOKp3o-Z8SMqxdaaq1HEaWgDTUvwtxADK0nH_0Gg5ao0GPUdG4UCOA9u5dd2KU5pKEP3HAP_Rr8mE0l5EjG4TJuj03_3ABA1U1ll7JPfdSTNKIpjIxDRwJOXGNr6eIsFx61StnbiwVtXHhXTDBxX4fGt3Uc9YQpREC4kYVTs8s9d5C0Ma__EKX_s
**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**
Повтор присутствует только на видео, а на записях с фотографиями такого нет

**Comment by tangenx** [comment]
@Digrad228 https://t.me/vtosters_faq/110

Дубликат.
#1129 / #1309
