### ISSUE TITLE
Error occurs intermittently 

### ISSUE THREAD

**Issue by MasseyKassey** [vtosters/lite#1335]
[VTL_log_2023-05-24.12-16-39.txt](https://github.com/vtosters/lite/files/11552990/VTL_log_2023-05-24.12-16-39.txt)
Link to log
[Log](content://com.google.android.apps.nbu.files.provider/1/file%3A%2F%2F%2Fstorage%2Femulated%2F0%2FDownload%2FVTL_log_2023-05-24.12-16-39.txt) 

**Информация об устройстве:** 

- Commit: 6d3dded
- Full Version Information: main-6d3dded-dirty
- Android SDK: 31
- Product: Armor_12S
- Device: Armor_12S
- Board: Ulefone
- Manufacturer: Ulefone
- Brand: Ulefone
- Model: Armor 12S

**Comment by danyyok** [comment]
Пересоздайте по шаблону
