### ISSUE TITLE
Ошибка с истриями. 

### ISSUE THREAD

**Issue by Miaco1** [vtosters/lite#1336]
Хочу посмотреть истории, но вместо контента, все истории меняются на одну и ту же историю. В вк такого бага нет, но в тостере он тоже присутствует. (хз как прикрепить видео, я думаю суть понятна)

**Comment by danyyok** [comment]
@Miaco1 https://t.me/vtosters_faq/110

Duplicate+invalid issue 
#1129 / #1309
