### ISSUE TITLE
Цвет акцента не распространяется на меню репоста

### ISSUE THREAD

**Issue by GmeX1** [vtosters/lite#1338]
При репосте какой-либо записи внутри меню репоста кастомный цвет акцента не распространяется на имя и галочку получателя.

1. Нажал на кнопку репоста записи
2. Выбрал получателей 

Все акцентные цвета должны быть покрашены в кастомный цвет.

![Screenshot_20230525-115731_VTLite](https://github.com/vtosters/lite/assets/66805207/b9f78106-66d5-492b-a3d6-21c48f2218d5)

**Информация об устройстве:** 

- Commit: 6d3dded
- Full Version Information: main-6d3dded-dirty
- Android SDK: 30
- Product: a31ser
- Device: a31
- Board: k68v1_64_titan
- Manufacturer: samsung
- Brand: samsung
- Model: SM-A315F
- OneUi Major Version: 3
- OneUi Minor Version: 1.0

**Comment by danyyok** [comment]
Покрасили всё, что могли

**Comment by GmeX1** [comment]
> Покрасили всё, что могли

Я могу здесь указать ещё один баг? Чтобы не открывать новую заявку

**Comment by GmeX1** [comment]
> Покрасили всё, что могли

Хочу добавить, что полупрозрачный динамичный кружок при записи голосового сообщения красится через раз. Он синий, если просто записывать голосовое, но если тапнуть по каком-нибудь ответу в сообщении, то цвет начинает отображаться корректно. Мне открывать новый коммит для этого?

**Comment by danyyok** [comment]
> полупрозрачный динамичный кружок при записи голосового сообщения красится через раз. Он синий, если просто записывать голосовое, но если тапнуть по какому-нибудь ответу в сообщениях, то цвет начинает отображаться корректно. Мне создавать новый коммит для этого?

Можешь сюда скинуть скриншоты

**Comment by GmeX1** [comment]
> Можешь сюда скинуть скриншоты

1. Записал голосовое (неправильный цвет)
2. Тапнул на ответ
3. Записал голосовое (правильный цвет)

![Screenshot_20230525-141614_VTLite](https://github.com/vtosters/lite/assets/66805207/50168e8a-da7b-4987-ad06-df090354dce2)
![Screenshot_20230525-141618_VTLite](https://github.com/vtosters/lite/assets/66805207/ecac2fcf-d0b0-4e16-aeb7-22c3a4506895)
![Screenshot_20230525-141624_VTLite](https://github.com/vtosters/lite/assets/66805207/5482162b-4121-49cd-95d1-f2d2788fa01d)

**Comment by Vologhat** [comment]
Проблема исправлена в последней версии
