### ISSUE TITLE
Не скрывается реклама в ленте

### ISSUE THREAD

**Issue by egf0x** [vtosters/lite#134]
Включил тумблер, чтобы не отображалась реклама, но она всё равно отображается, даже если обновить ленту
![Screenshot_20220412-022253](https://user-images.githubusercontent.com/97127436/162849216-cda567f6-5744-4df8-aa7c-d06af08fce1a.png)
![Screenshot_20220412-022259](https://user-images.githubusercontent.com/97127436/162849224-b09e880c-f3ab-47d8-84e1-82b19295881e.png)

Смартфон Redmi 9T

**Comment by gdlbo** [comment]
обнови ленту
