### ISSUE TITLE
После обновления перестала работать кнопка "Найти фото"

### ISSUE THREAD

**Issue by Zaeros77** [vtosters/lite#1341]
После обновления перестала работать кнопка "Найти фото"
![Screenshot_2023-05-26-00-13-15-697_com.vtosters.lite.jpg](https://github.com/vtosters/lite/assets/89293703/afd79709-7dcc-4d31-bcc6-63ceb1eb6fb9)

**Comment by danyyok** [comment]
Как именно? Перестала нажиматься или выдаёт ошибки?

**Comment by Zaeros77** [comment]
> Как именно? Перестала нажиматься или выдаёт ошибки?

Перестала нажиматься. Ошибок не выдаёт.

**Comment by danyyok** [comment]
> Перестала нажиматься. Ошибок не выдаёт.

Попробуйте включить милкшейк в настройках внешнего вида

**Comment by Zaeros77** [comment]
> > Перестала нажиматься. Ошибок не выдаёт.
> 
> Попробуйте включить милкшейк в настройках внешнего вида

Заработало
