### ISSUE TITLE
Игнорирование системного шрифта в некоторых местах

### ISSUE THREAD

**Issue by blwckcore** [vtosters/lite#1345]
Вместо системного шрифта, в некоторых местах используется Roboto.

**Опишите действия для воспроизведения ошибки**
Сменить шрифт на любой другой, отличный от Roboto (чтобы банально заметить это). Также, отмечу, что у меня стоит Xiaomi.eu, и шрифт здесь заменен на MiSans по умолчанию. Этот шрифт используется здесь абсолютно всеми приложениями, поэтому, мне кажется что его добавили путём замены файлов шрифта Roboto на MiSans.
![Screenshot_2023-05-28-08-48-35-416_com google android googlequicksearchbox](https://github.com/vtosters/lite/assets/107321994/25bd1d17-31f1-492b-aaa3-0e0d28494956)
Как видим, он используется даже в приложении Гугла и на сайтах в хроме. Интересно, что если заменить этот шрифт на другой в приложении "темы", то на сайтах и в гугле останется MiSans.
**Опишите ожидаемый результат**
Системный шрифт должен быть везде.

**Скриншот ошибки**
![Screenshot_2023-05-28-08-40-50-797_com vtosters lite](https://github.com/vtosters/lite/assets/107321994/91113474-6519-419a-b1e6-42b7d2a3733e)
![Screenshot_2023-05-28-08-40-40-703-edit_com vtosters lite](https://github.com/vtosters/lite/assets/107321994/416d5f17-be12-4792-b43c-ddda13702dee)
![Screenshot_2023-05-28-08-40-15-203_com vtosters lite](https://github.com/vtosters/lite/assets/107321994/80394da5-28e4-41b8-9a6c-437b862344fb)
![Screenshot_2023-05-28-08-39-02-007-edit_com vtosters lite](https://github.com/vtosters/lite/assets/107321994/7dfeee9e-dc00-4484-a746-72a68cd4c07e)
![Screenshot_2023-05-28-08-37-41-371-edit_com vtosters lite](https://github.com/vtosters/lite/assets/107321994/a93f9557-f43e-4394-a57d-d76975334739)
![Screenshot_2023-05-28-08-36-07-492-edit_com vtosters lite](https://github.com/vtosters/lite/assets/107321994/41ba37f5-aa05-4bba-a8d7-83ce5a0d74ed)
![Screenshot_2023-05-28-08-35-16-394-edit_com vtosters lite](https://github.com/vtosters/lite/assets/107321994/ee8028a2-ce2e-41b6-aed2-0743270dfb4d)
![Screenshot_2023-05-28-08-34-28-978-edit_com vtosters lite](https://github.com/vtosters/lite/assets/107321994/3aa5e096-3f43-4887-a385-cc767d5b03cc)
![Screenshot_2023-05-28-08-34-00-457-edit_com vtosters lite](https://github.com/vtosters/lite/assets/107321994/cbec0e26-3376-449a-bac7-33c28f03e9f7)
![Screenshot_2023-05-28-08-33-33-794-edit_com vtosters lite](https://github.com/vtosters/lite/assets/107321994/d8476128-62d5-4b5f-9c19-f7e3f605aff7)

**Информация об устройстве:** 

- Commit: 6d3dded
- Full Version Information: main-6d3dded-dirty
- Android SDK: 31
- Product: vayu_global
- Device: vayu
- Board: vayu
- Manufacturer: Xiaomi
- Brand: POCO
- Model: M2102J20SG
- Miui Version Code: 13
- Miui Version Name: V130
- Miui Version Incremental Code: V13.0.9.0.SJUMIXM

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**
Возможно в этих местах разрабы вк заставили интерфейс вк юзать именно робото, вместо системного шрифта. В разделе музыки робото вообще почти везде.

**Comment by gdlbo** [comment]
Это нормально, иначе ломается дизайн интерфейса
