### ISSUE TITLE
Счётчик участников беседы

### ISSUE THREAD

**Issue by danyanimous** [vtosters/lite#1352]
**сам баг**
В VTLite и VTosters (то есть баг ещё с бородатых времён) в беседах отображается количество участников, отличное от официального клиента

**действия для воспроизведения ошибки**
ошибка проявляется сама по себе

**ожидаемый результат**
отображение правильного числа участников беседы

**Device info:** 
- Commit: ff8e7b7
- Full Version Information: main-ff8e7b7-dirty
- Android SDK: 33
- Product: a51nsser
- Device: a51
- Board: exynos9611
- Manufacturer: samsung
- Brand: samsung
- Model: SM-A515F
- OneUi Major Version: 5
- OneUi Minor Version: 1.0

**Дополнительная информация о мыслях почему оно может происходить**
кто-то плохо учил математику...)

**Comment by danyyok** [comment]
Скриншоты?

**Comment by danyanimous** [comment]
пошёл делать скриншоты и....ВНЕЗАПНО проблема ушла. интэрэсно

**Comment by danyyok** [comment]
> пошёл делать скриншоты и....ВНЕЗАПНО проблема ушла. интэрэсно

Отлично тогда) переоткройте Issue, если проблема вновь появится (предоставляя скриншоты)
