### ISSUE TITLE
Проблемы с историей

### ISSUE THREAD

**Issue by Lopata77715** [vtosters/lite#1353]
Почему мне всё время показывает предыдущую историю? Первую которую посмотришь, та всё время будет показываться! Прошу вас исправить!
**Информация об устройстве:** 

- Commit: ff8e7b7
- Full Version Information: main-ff8e7b7-dirty
- Android SDK: 28
- Product: begonia_ru
- Device: begonia
- Board: begonia
- Manufacturer: Xiaomi
- Brand: Redmi
- Model: Redmi Note 8 Pro
- Miui Version Code: 9
- Miui Version Name: V11
- Miui Version Incremental Code: V11.0.3.0.PGGRUXM

**Comment by person10301** [comment]
@Lopata77715 https://github.com/vtosters/lite/issues/1309#issuecomment-1565337139

**Comment by tangenx** [comment]
@Lopata77715 https://t.me/vtosters_faq/110

Дубликат.
#1129 / #1309
