### ISSUE TITLE
Предыдущая историяв ВК каждый раз повторяется

### ISSUE THREAD

**Issue by Lopata77715** [vtosters/lite#1354]
У меня проблемы с историей! Почему-то первая история каждый раз повторяется всё время! Прошу вас исправить проблему!
**Информация об устройстве:** 

- Commit: ff8e7b7
- Full Version Information: main-ff8e7b7-dirty
- Android SDK: 28
- Product: begonia_ru
- Device: begonia
- Board: begonia
- Manufacturer: Xiaomi
- Brand: Redmi
- Model: Redmi Note 8 Pro
- Miui Version Code: 9
- Miui Version Name: V11
- Miui Version Incremental Code: V11.0.3.0.PGGRUXM

**Comment by person10301** [comment]
@Lopata77715 https://github.com/vtosters/lite/issues/1309#issuecomment-1565337139

**Comment by danyyok** [comment]
Для чего 2 issue по теме историй?
