### ISSUE TITLE
Повторяющиеся истории

### ISSUE THREAD

**Issue by sl1ghtxd** [vtosters/lite#1355]
После просмотра историй все последующие заменяются просмотренной, помогает очистка кэша, но со следующими историями баг повторяется.

1. Открыл историю
2. Перешел на следующую

Нормальный просмотр историй
![Screenshot_20230601-124241](https://github.com/vtosters/lite/assets/135200558/232b5735-3329-40eb-b3f1-b05f32f168f5)
![Screenshot_20230601-124243](https://github.com/vtosters/lite/assets/135200558/c4580d90-2f9d-40f6-a7af-f2264eb6a2fe)
![Screenshot_20230601-124245](https://github.com/vtosters/lite/assets/135200558/b2910691-38a3-4a9e-8ecc-7c13951dce01)

**Device info:** 

- Commit: ff8e7b7
- Full Version Information: main-ff8e7b7-dirty
- Android SDK: 31
- Product: LG7n-RU
- Device: TECNO-LG7n
- Board: TECNO-LG7n
- Manufacturer: TECNO
- Brand: TECNO
- Model: TECNO LG7n

**Comment by tangenx** [comment]
@sl1ghtxd https://t.me/vtosters_faq/110

Дубликат.
#1129 / #1309

**Comment by LessLatchLooked** [comment]
нашёл как можно временно исправить, почистить кэш приложения, видимо он сохраняет в кэше под одним названием и не меняет их. соответственно не подгружается новые истории т.к. уже файл с таким названием есть
