### ISSUE TITLE
Ошибка историй.

### ISSUE THREAD

**Issue by Ulyana2029** [vtosters/lite#1357]
При просмотре историй выдает либо ошибку,либо одну и туже историю абсолютно незнакомого человека у всех,кто есть в друзьях,связанной с армией или что-то вроде того.

1 Достаточно просто зайти и начать смотреть истории,но в данном случае я выложила историю и решила пересмотреть ее, вроде,для людей это норма,но выдает скриншот пересланной истории какого-то парня, эта же история отображается у всех , кого я хочу посмотреть,либо же просто выдает ошибку

Такая проблема наблюдается давно, надеюсь, что ее исправят

![IMG_20230603_204209](https://github.com/vtosters/lite/assets/135442324/e44acd67-7f95-476e-9c3c-af2e06d21214)

**Comment by tangenx** [comment]
@Ulyana2029 https://t.me/vtosters_faq/110

Дубликат.
#1129 / #1309
