### ISSUE TITLE
Запись не найдена

### ISSUE THREAD

**Issue by nokia61** [vtosters/lite#1362]
Под моим постом кто-то подставил лайк. 
Через уведомления пытаюсь зайти в пост, выскакивает сообщение "запись не найдена".

**Comment by nokia61** [comment]
> 

Спасибо, но не понял, какую группу? Это мой пост, который я сделал на своей же странице, на своей стене. Кстати, такое уже не первый раз, что некоторые посты, которые я делаю с ПК не видны в приложении. Пишет "запись не найдена"

**Comment by ayonovdenizs** [comment]
Возможно, твой пост попал в фильтры новостей
