### ISSUE TITLE
Возможность отключить автоматическую проверку обновлений

### ISSUE THREAD

**Issue by crick-ru** [vtosters/lite#1364]
Ставлю vtosters пенсионерам. Огромные диалоги обновления их пугают.

Кроме того, не хочется давать vtosters возможность устанавливать apk. Это небезопасно для тех же пенсионеров. Они не в состоянии распознать палево от каких-нибудь мошенников. Проще запретить vtosters устанавливать apk, чем объяснять пенсионрам, что ни в коем случае нельзя ничего устанавливать из непроверенных источников.

**Comment by danyyok** [comment]
Обновляете приложение и окно обновления не будет.

**Comment by abslike** [comment]
@crick-ru в таком случае лучше ставить оф клиент...

**Comment by Wperdex** [comment]
Не думаю, что пенсионерам стоит устанавливать моды, в таком случае.

Тостер, ровно как и любой другой мод — такое же непроверенное приложение из неизвестного источника, которое Вы установили. Если Вы хотите, чтобы они пользовались только проверенными приложениями из официальных источников, то в таком случае лучше скачать официальные VK или VK Мессенджер. Если же им требуется что-нибудь попроще, то подумайте над **Kate Mobile**, который также имеется в Google Play.

Отказ от обновлений поведёт за собой накопление багов, которое рано или поздно угробит приложение.

**Comment by Kernell** [comment]
> Не думаю, что пенсионерам стоит устанавливать моды, в таком случае.
> 
> Тостер, ровно как и любой другой мод — такое же непроверенное приложение из неизвестного источника, которое Вы установили. Если Вы хотите, чтобы они пользовались только проверенными приложениями из официальных источников, то в таком случае лучше скачать официальные VK или VK Мессенджер. Если же им требуется что-нибудь попроще, то подумайте над **Kate Mobile**, который также имеется в Google Play.
> 
> Отказ от обновлений поведёт за собой накопление багов, которые рано или поздно угробят приложение.

Ладно если бы обновления выходили не так часто. Буквально 3 часа назад я обновился, и вот только что выпустили ещё одну версию.
Постоянное вылетающее диалоговое окно очень раздражает. И причём ради фигни которая мне не интересна.

Тостер не единственное приложение которое хочет обновляться, и ничего, живут как-то без постоянных обновлений (а иначе начинается хаос, а некоторые приложения вообще обновлять вредно - прилетает функционал который нельзя выключить)

**Comment by gdlbo** [comment]
> > Не думаю, что пенсионерам стоит устанавливать моды, в таком случае.
> > 
> > Тостер, ровно как и любой другой мод — такое же непроверенное приложение из неизвестного источника, которое Вы установили. Если Вы хотите, чтобы они пользовались только проверенными приложениями из официальных источников, то в таком случае лучше скачать официальные VK или VK Мессенджер. Если же им требуется что-нибудь попроще, то подумайте над **Kate Mobile**, который также имеется в Google Play.
> > 
> > Отказ от обновлений поведёт за собой накопление багов, которые рано или поздно угробят приложение.
> 
> Ладно если бы обновления выходили не так часто. Буквально 3 часа назад я обновился, и вот только что выпустили ещё одну версию.
> Постоянное вылетающее диалоговое окно очень раздражает. И причём ради фигни которая мне не интересна.
> 
> Тостер не единственное приложение которое хочет обновляться, и ничего, живут как-то без постоянных обновлений (а иначе начинается хаос, а некоторые приложения вообще обновлять вредно - прилетает функционал который нельзя выключить)

Обновление раскатано ночью (у половины России по крайней мере так), так и ещё крайне важное обновление

Можно посмотреть на предыдущие обновления и на их даты выхода. Апдейты приходят дай бог два раза в месяц, а чаще всего реже
