### ISSUE TITLE
Баг оформления при пепемещении лайков вправо

### ISSUE THREAD

**Issue by crick-ru** [vtosters/lite#1365]
Если включить опцию, которая перемещает лайки вправо, то у индикатора количества просмотров не остается поля слева. Это некрасиво. Портит дизайн и бросается в глаза.

По всем законам хорошего дизайна у любого объекта должны быть поля. К тому же бросается в глаза, что у самих лайков справа поле есть, а у просмотров слева поля нет.

![Screenshot_20230608-222818](https://github.com/vtosters/lite/assets/1965253/dbd1d05a-6b84-4fcc-9fe5-1bc4adb309fe)

**Comment by gdlbo** [comment]
не баг
