### ISSUE TITLE
Не обновляются сообщения. Часто выдает ошибку при попытках открыть диалог. Скрывает сообщения или может снова выдать те, что были прочитаны пару часов назад. Зависает при попытке открыть сообщества и часто выдает ошибку

### ISSUE THREAD

**Issue by Gleden-Dwarf** [vtosters/lite#1372]
**Опишите сам баг**
При обновлении новостей вылезает ошибка

**Опишите действия для воспроизведения ошибки**
1. Обновил ленту интересных новостей
2. Пролистал до конца страницы

**Опишите ожидаемый результат**
Интересная лента должна прогружать результаты

**Скриншот ошибки**

**Скопируйте сюда информацию об устройстве нажав на кнопку "Скопировать информацию об устройстве" в Настройках -> Другое и удалите этот текст**

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

**Comment by danyyok** [comment]
Invalid Issue
