### ISSUE TITLE
Ошибка при изменении скорости воспроизведения голосовых сообщений

### ISSUE THREAD

**Issue by sanvlkv** [vtosters/lite#1377]
При изменении скорости воспроизведения голосовых вылезает ошибка

**Опишите действия для воспроизведения ошибки**
1. Открыть любой чат с ГС
2. Воспроизвести , изменив скорость 
ОР:
Скорость воспроизведения должна повыситься 

Скрин
![Screenshot_20230619-092755](https://github.com/vtosters/lite/assets/121596517/7cc119ed-175b-4601-9b06-04a87e7437a1)

*Google pixel 5, Android 13

Возможно, это из за использования для мода старой версии клиента. Но это не точно.

**Comment by danyyok** [comment]
Попробуйте принудительно закрыть приложение, после этого обновите список диалогов

**Comment by sanvlkv** [comment]
Попробовал, проблема актуальна 
--
Отправлено из Mail.ru для Android понедельник, 19 июня 2023г., 14:58 +05:00 от Danyy Okskiy  ***@***.*** :

**Comment by sanvlkv** [comment]
Приветствую) с выходом 0.8.0 проблема актуальна( 
--
Отправлено из Mail.ru для Android понедельник, 19 июня 2023г., 14:58 +05:00 от Danyy Okskiy  ***@***.*** :
