### ISSUE TITLE
F-Droid репозиторий

### ISSUE THREAD

**Issue by averyanalex** [vtosters/lite#1381]
Думаю, многим будет удобнее устанавливать и обновлять приложение, если вы сделаете для него репозиторий для F-Droid (или сможете добавить его в "официальный")

**Comment by gdlbo** [comment]
Это в первую очередь реверс инженеринг проект, а не открытый полностью исходный код

Открыт только код модификации которая добавляется в декомпилированную версию вк

**Comment by gdlbo** [comment]
> Ну это понятно, что это модификация проприетарного клиента, но свой собственный репозиторий то всё равно можно сделать, мне кажется.

Нельзя. Ключевой фактор выкладывания на FDroid - полностью открытый исходный код всех компонентов

**Comment by aliveoutside** [comment]
> > Ну это понятно, что это модификация проприетарного клиента, но свой собственный репозиторий то всё равно можно сделать, мне кажется.
> 
> Нельзя. Ключевой фактор выкладывания на FDroid - полностью открытый исходный код всех компонентов

В своём репозитории можно делать что угодно, вопрос лишь в наличии сервера который выдержит нагрузку.. боюсь, что такого у нас нет
