### ISSUE TITLE
Луп при открытии ссылок vk.com

### ISSUE THREAD

**Issue by 1234Andrew1234** [vtosters/lite#1382]
При открытии из приложения ссылок vk.com/* открывается браузер, из него сразу открывается приложение, из него снова браузер и так бесконечно. Проблемы нет, если выключить в настройках в системе переход в приложение по ссылкам, но тогда его не будет.

Samsung SM-G780G, android 13, Samsung browser, VTlite 5.56.1

**Comment by Wperdex** [comment]
@1234Andrew1234 пожалуйста, отредактируйте issue в соответствии с его шаблоном, указав корректирую информацию об устройстве 
**(Настройки > Другое > Скопировать информацию об устройстве)**
