### ISSUE TITLE
Повторные уведомления 

### ISSUE THREAD

**Issue by mrjinatan** [vtosters/lite#1383]
После перезапуска приложения повторно приходят уведомления всех непрочитанных сообщений

Воспроизводится если выйти из приложения и зайти заново
 

- Commit: 3cc81df
- Full Version Information: main-3cc81df-dirty
- Android SDK: 31
- Product: joyeuse_eea
- Device: joyeuse
- Board: joyeuse
- Manufacturer: Xiaomi
- Brand: Redmi
- Model: Redmi Note 9 Pro
- Miui Version Code: 14
- Miui Version Name: V140
- Miui Version Incremental Code: V14.0.4.0.SJZEUXM

**Comment by ayonovdenizs** [comment]
Так и в офф вк.
