### ISSUE TITLE
Баг в истории

### ISSUE THREAD

**Issue by ZSolEst** [vtosters/lite#1384]
Проблема ещё с января-февраля (обновления не помогают).
Статичные истории (фото) функционируют нормально, как и должны, а вот видео как я один раз посмотрел историю, так эта истории уже полгода накладывается на остальные заменяя их как бы и я никак не могу посмотреть истории. Приходиться смотреть через официальное приложение.

https://github.com/vtosters/lite/assets/137614027/f4913048-1e98-452d-b9b7-11f6e3883a66

**Comment by tangenx** [comment]
@ZSolEst https://t.me/vtosters_faq/110

Дубликат.
#1129 / #1309
