### ISSUE TITLE
Пропадают наборы стикеров ВК

### ISSUE THREAD

**Issue by n119htmare** [vtosters/lite#1385]
Когда хочу выбрать периодически все наборы стикеров пропадают, кроме добавленного из Телеграмма и не выскакивают даже в подсказках.

Стикеры пропадают сами по себе и появляются потом снова тоже сами по себе

Хотелось бы, чтобы стикеры не пропадали.

![IMG_20230625_172131](https://github.com/vtosters/lite/assets/137705822/8368d6ec-da70-4d58-b92f-c520e72f2b84)

**Информация об устройстве:** 

- Commit: 3cc81df
- Full Version Information: main-3cc81df-dirty
- Android SDK: 31
- Product: RMX3085RU
- Device: RMX3085L1
- Board: RM6785
- Manufacturer: realme
- Brand: realme
- Model: RMX3085
-

**Comment by abslike** [comment]
@n119htmare VK bug
