### ISSUE TITLE
Ошибка в тексте музыки 

### ISSUE THREAD

**Issue by DeLorian298** [vtosters/lite#1389]
Дело такое не тот текст в песне 
![Screenshot_2023-06-30-15-58-03-90_9e1a5d6211a0228d32d39446541891f1](https://github.com/vtosters/lite/assets/138214472/f872641a-cd9f-4a4a-b2b5-14d6a7ea3162)

**Comment by danyyok** [comment]
Все идёт с ВК/гениуса и втл не отвечает за правильность текста
