### ISSUE TITLE
Баг постов с источниками 2

### ISSUE THREAD

**Issue by Volt567** [vtosters/lite#1390]
**Опишите сам баг**
На новой версии приложения, баг постов с источниками повторился 
 
**Скриншот ошибки**
![Screenshot_2023-07-02-09-15-03-629_com.vtosters.lite.jpg](https://github.com/vtosters/lite/assets/114720843/0fa4aabe-dd66-4f6a-9344-ad9fc0a20f2f)

**Информация об устройстве:** 

- Commit: 281a0e8
- Full Version Information: main-281a0e8-dirty
- Android SDK: 31
- Product: sweet_ru
- Device: sweet
- Board: sweet
- Manufacturer: Xiaomi
- Brand: Redmi
- Model: M2101K6G
- Miui Version Code: 13
- Miui Version Name: V130
- Miui Version Incremental Code: V13.0.10.0.SKFRUXM

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

**Comment by danyyok** [comment]
Дубликат #1388
