### ISSUE TITLE
Не отображаются эмодзи которые отправляют друзья 

### ISSUE THREAD

**Issue by Adrinne1** [vtosters/lite#1391]
Не показываются эмодзи в сообщениях от друзей. Вместо них показывается обычный текст, который эти эмодзи так скажем описывает. 

1. Абсолютно в каждом чате вместо эмодзи появляется текст, когда в него заходишь. 

Эмодзи должны отображаются, а вместо них какой-то текст

![1688275476734](https://github.com/vtosters/lite/assets/128578365/81294dbc-1735-4b3e-969c-496bb30311d5)

![Screenshot_20230702_082654_com android settings](https://github.com/vtosters/lite/assets/128578365/3d52ee52-68cd-4e7d-936c-872aea0cc756)

**Comment by danyyok** [comment]
Выключите перевод сообщений
