### ISSUE TITLE
Не красятся сообщения в цвет акцента

### ISSUE THREAD

**Issue by Ghdie** [vtosters/lite#1393]
В цвет акцента окрашивается все, кроме сообщений во всех чатах, баг появился после скачанного обновления 1 июля.

**Опишите ожидаемый результат**
Хочу, чтобы окраска сообщений стала как раньше

**Скриншот ошибки**
![IMG_20230702_215400](https://github.com/vtosters/lite/assets/138397685/17e88985-ca19-4c1c-90ba-de405370e975)

**Comment by Ghdie** [comment]
**Информация об устройстве:** 

- Commit: 281a0e8
- Full Version Information: main-281a0e8-dirty
- Android SDK: 33
- Product: rosemary_ru
- Device: rosemary
- Board: rosemary
- Manufacturer: Xiaomi
- Brand: Redmi
- Model: M2101K7BNY
- Miui Version Code: 14
- Miui Version Name: V140
- Miui Version Incremental Code: V14.0.1.0.TKLRUXM

**Comment by gdlbo** [comment]
Исправлено
