### ISSUE TITLE
Обновленный движок акцента сломал запуск

### ISSUE THREAD

**Issue by Dum4G** [vtosters/lite#1395]
**Опишите сам баг**
После ручного выбора кастомного цвета акцента приложение крашится сразу при запуске

**Опишите действия для воспроизведения ошибки**
1. Обновляемся с 0.7.4 до 0.8.0
2. Наблюдаем, что цвет сбился на дефолтный синий
3. Идем в настройки возвращать как было
4. Выбираем через color picker какой-нибудь нестандартный цвет
5. Наблюдаем частичное применение цвета в рантайме
6. Фиксируем краш и собираем логи

**Опишите ожидаемый результат**
Кастомный цвет не будет мешать приложению запускаться и будет подтягиваться из старых версий при обновлении

**Информация об устройстве:**
Commit: https://github.com/vtosters/lite/commit/281a0e849974b55d6270eaf6998524a7a0c03d8c
Full Version Information: да хрен его теперь разберет, v0.8.0-release
Android SDK: 26
Product: OnePlus 5T
Device: ONEPLUS A5010
Board: 🤔
Manufacturer: 😐
Brand: 😑
Model: 🙄

[**Логи**](https://gist.github.com/Dum4G/e97d920c8c525b8fbd06d4c304ec1091)

**Comment by gdlbo** [comment]
Привет, спасибо за репорт! Сможешь зайти в наш чат в Telegram (https://t.me/vtosterschat) для проверки исправлений?
