### ISSUE TITLE
Одно и тоже видео в историях

### ISSUE THREAD

**Issue by Axel233** [vtosters/lite#1397]
Вы выпускаете обновление с исправлением ошибок. Но не в одном обновлении нету исправления данного бага. Даже после переустановки приложения повторяется все та же ошибка. Займитесь делом наконец

**Comment by person10301** [comment]
@Axel233 Исходный открыт - исправляй сам раз такой умный, никто не обязан его исправлять быстро

**Comment by danyyok** [comment]
Дубликат #1309
