### ISSUE TITLE
Видео в ленте очень низкого разрешения 

### ISSUE THREAD

**Issue by kubE-JD** [vtosters/lite#1398]
**Опишите сам баг**
В ленте очень зашакаленные превью видео или видеоклипов

**Опишите действия для воспроизведения ошибки**
1. Обновил ленту интересных новостей

**Опишите ожидаемый результат**
Хотя бы в 360р потоки видео в ленте

**Скриншот ошибки**
![Screenshot_2023-07-06-17-30-14-330_com vtosters lite](https://github.com/vtosters/lite/assets/69966353/48e4776c-d9a0-42d8-8ad3-2e40b09e99e1)

**Скопируйте сюда информацию об устройстве нажав на кнопку "Скопировать информацию об устройстве" в Настройках -> 

com.vtosters.lite

cdaf7909d4d6d9714101c4dc51facc70c9e00018

main

main-cdaf790-dirty

Sdk 33

sweet_global

sweet

sweet

Xiaomi

Redmi

M2101K6G

V140

14

V14.0.3.0.TKFTWXM

isMiui
Value: true 

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

**Comment by danyyok** [comment]
Отключи экономию трафика в настройках

**Comment by kubE-JD** [comment]
> Отключи экономию трафика в настройках

Отключена она, так и при открытии видосы сначала в очень низком качестве, потом еле как приходят в норму, часто если принудительно выставить разрешение ролика, интернет нормальный

**Comment by gdlbo** [comment]
исправлено, скоро будет апдейт с патчем
