### ISSUE TITLE
Бесконечное уведомление об обнове при входе в приложение

### ISSUE THREAD

**Issue by GitHubovec559** [vtosters/lite#1399]
**Опишите сам баг**
При входе в приложение каждый раз выводит внизу окно что вышла обнова, а когда жмешь обновить то обновляется как обычно, но проблема не устраняется.

**Опишите действия для воспроизведения ошибки**
1. Зайти в приложение (в моем случае на Андроид).
2. Внизу выдаст уведомление о выходе обновы.

**Опишите ожидаемый результат**
Плз исправьте, очень мешает

**Скриншот ошибки**
![Screenshot_20230706-201231_VTLite](https://github.com/vtosters/lite/assets/138794787/fe0b1c0f-eea0-45f9-a03a-769ef5292550)

**Информация об устройстве:** 
- Commit: 281a0e8
- Full Version Information: main-281a0e8-dirty
- Android SDK: 31
- Product: a31xx
- Device: a31
- Board: a31
- Manufacturer: samsung
- Brand: samsung
- Model: SM-A315F
- OneUi Major Version: 4
- OneUi Minor Version: 1.0

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**
После последнего обновления началось

**Comment by danyyok** [comment]
Вы точно обновляете приложение?

**Comment by GitHubovec559** [comment]
> Вы точно обновляете приложение?
Да, даже телефон перезапускал. Обновляю вхожу и снова пишет сто обнова вышла

**Comment by danyyok** [comment]
> Да, даже телефон перезапускал. Обновляю вхожу и снова пишет что обнова вышла

Через что обновляете?

**Comment by GitHubovec559** [comment]
Вот только что попробовал снова обновить и опять это окно 
![Screenshot_20230706-204844_Package installer](https://github.com/vtosters/lite/assets/138794787/d165b3c7-e9db-44fb-ae47-e217aac755dd)
![Screenshot_20230706-205006_VTLite](https://github.com/vtosters/lite/assets/138794787/79bfa041-544f-4c9f-a847-6b35a131d206)

**Comment by GitHubovec559** [comment]
> > Да, даже телефон перезапускал. Обновляю вхожу и снова пишет что обнова вышла
> 
> Через что обновляете?

Ну обычный загрузчик системный, скачивается и само обновляется
