### ISSUE TITLE
Ошибка при кешировании музыки

### ISSUE THREAD

**Issue by GekaiXX** [vtosters/lite#1403]
При скачивание кеша музыки и воспроизведении её приложение вылетает и появляется уведомление об ошибке
Устройство Poco f3
![Screenshot_2023-07-09-03-41-56-528_com android chrome-edit](https://github.com/vtosters/lite/assets/139023733/418e3d03-9a66-40fe-baf2-f3d9599e4dd5)

**Comment by danyyok** [comment]
Трек был удален из ВК, либо ты не докачал его

**Comment by ayonovdenizs** [comment]
было бы хорошо, если бы ты скинул логи из загрузок
