### ISSUE TITLE
Не отключается экономия трафика в роуминге.

### ISSUE THREAD

**Issue by Defolt168** [vtosters/lite#1404]
Эконмия трафика в настройках отключена, но фото и видео всё равно в плохом качестве
![Screenshot_2023-07-09-14-33-19-333_com vtosters lite](https://github.com/vtosters/lite/assets/139044988/91f522d3-4a4a-4f71-8a36-2c0ea1b44a6b)
![Screenshot_2023-07-09-14-33-24-294_com vtosters lite](https://github.com/vtosters/lite/assets/139044988/3778d6f9-a9d1-4734-b44c-aa58a0ecbda4)
честве.

**Comment by gdlbo** [comment]
исправлено, скоро будет апдейт с патчем
