### ISSUE TITLE
Ошибка обновлении ленты новостей

### ISSUE THREAD

**Issue by Louners** [vtosters/lite#1410]
**Опишите сам баг**
При обновлении новостей новости остаются теже (режим новостей: сначала интересные)

**Опишите действия для воспроизведения ошибки**
1. Обновил ленту интересных новостей
2. Увидел одни и те же посты в том же порядке
3. Повторить действия 1,2

**Опишите ожидаемый результат**
Интересная лента должна прогружать результаты (новые посты сообществ, которые ещё не отображались)

**Скриншот ошибки**
-
**Информация об устройстве:** 

- Commit: cdaf790
- Full Version Information: main-cdaf790-dirty
- Android SDK: 30
- Product: vayu_global
- Device: vayu
- Board: vayu
- Manufacturer: Xiaomi
- Brand: POCO
- Model: M2102J20SG
- Miui Version Code: 11
- Miui Version Name: V125
- Miui Version Incremental Code: V12.5.4.0.RJUMIXM

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**
Если в настройках ленты сделать какое либо изменение (двинуть ползунок туда обратно), то в новостях будут другие посты, но при последующих ручных обновлениях новостей вернётся на былые посты и изменятся не будут

**Comment by ayonovdenizs** [comment]
@Louners Переключи порядок ленты: Настройки - Лента - Встроенные настройки новостей - Порядок записей

**Comment by Louners** [comment]
> @Louners Переключи порядок ленты: Настройки - Лента - Встроенные настройки новостей - Порядок записей

Логично, что если поставить в режим "по времени публикации", то будут по порядку отображаться все посты 
Но в оригинальном ВК в режиме "сначала интересные" при обновлении ленты посты меняются. Т.е. пролистав несколько постов и обновив ленту мне покажут другие, а не теже самые в том же порядке

**Comment by Louners** [comment]
Я криворукий и случайно закрыл тему

**Comment by Louners** [comment]
> Всё работает, смотри внимательнее как обновляются посты

Ну они реально не меняются. Одно и тоже. Я в телегу тебе написал

**Comment by icynstant** [comment]
Откройте проблему, она не решена, интересная лента работает неправильно, объяснил в #1510

**Comment by ayonovdenizs** [comment]
@icynstant https://github.com/vtosters/lite/issues/1510#issuecomment-1831906593
