### ISSUE TITLE
Не убирается уведомление

### ISSUE THREAD

**Issue by Klycs** [vtosters/lite#1411]
![Screenshot_2023-07-12-11-19-04-874_com vtosters lite](https://github.com/vtosters/lite/assets/84291166/ca7cb414-e44f-4f0f-a536-1689d8b0b740)

Вкл. автокеширование музык всех моих. А оно хочет качать, а что качает не известно, или я не понимаю как оно работает. Но хочу убрать загрузку эту. Выкл. Все равно грузит и грузит, но % не прибавляется.

**Comment by danyyok** [comment]
Принудительно закройте приложение
