### ISSUE TITLE
Поддержка android 13

### ISSUE THREAD

**Issue by ShinyParadise** [vtosters/lite#1412]
Стоит добавить поддержку этой версси андроида, т.к. довольно много устройств поставляются уже с ней (в том числе и мой девайс). Довольно грустно было скачать апк, и обнаружить что приложение несовместимо с моим телефоном.

Я думаю достаточно обновить targetSdk и compileSdk с 32 до 33 версии.

**Comment by person10301** [comment]
@ShinyParadise Так работает на андроид 13, у меня самого 2 устройства на 13

**Comment by ShinyParadise** [comment]
@person10301 интересно, а что за девайсы? И какая стоит версия приложения (из стабильных релизов или из экшнов)?

**Comment by ayonovdenizs** [comment]
@ShinyParadise Все версии с поддержкой а13

**Comment by person10301** [comment]
Realme 9 pro - RUI 4.0 C16
А за второй не помню, дома буду посмотрю что там установлено

**Comment by ShinyParadise** [comment]
Спасибо ребята, приложения не ставилось из-за поврежденного апк (неизвестная причина, но на моей стороне). Скачал последний релиз заново и он поставился
