### ISSUE TITLE
Некорректно работает видео в историях 

### ISSUE THREAD

**Issue by kr1va** [vtosters/lite#1415]
При просмотре хотя бы одного видео в историях, все остальные видео заменяются на него 

**Опишите действия для воспроизведения ошибки**
1. Просмотрел историю с видео 
2. Переключаю на следующую историю с видео - мелькает первый кадр и потом воспроизводится видео из первой истории
3. Все видео в историях это первое просмотренное видео 

**Опишите ожидаемый результат**
Нормальное отображение видео в историях

**Скриншот ошибки*![Screenshot_20230714-210849_VTLite.png](https://github.com/vtosters/lite/assets/45786524/36bbaa6d-fb0f-4b72-9649-2b09ecee3197)

![Screenshot_20230714-210841_VTLite.png](https://github.com/vtosters/lite/assets/45786524/f8329251-da4f-4e40-91a0-13bd36f92c35)

![Screenshot_20230714-210831_VTLite.png](https://github.com/vtosters/lite/assets/45786524/4f5d6ec1-3064-4386-acda-154789e00b14)

![Screenshot_20230714-210856_VTLite.png](https://github.com/vtosters/lite/assets/45786524/07397514-b07f-40fd-9837-b3c6099fc33e)

**Информация об устройстве:** 

- Commit: cdaf790
- Full Version Information: main-cdaf790-dirty
- Android SDK: 33
- Product: panther
- Device: panther
- Board: panther
- Manufacturer: Google
- Brand: google
- Model: Pixel 7

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

**Comment by ayonovdenizs** [comment]
Читайте faq: https://t.me/vtosters_faq/110
