### ISSUE TITLE
Ошибка обновлении ленты новостей

### ISSUE THREAD

**Issue by CrazyIbragim** [vtosters/lite#1420]
Решил перейти с оригинального Тостерса на новый VTlite и сразу столкнулся с проблемой.
Не обновляется лента, не исчезают старые прочитанные посты.
Видел "решение", заключающееся в смене порядка постов по новейшим, но это не решает проблему, т.к. в нормальной ленте сочетаются и старые, и новые посты.

**Comment by danyyok** [comment]
Втл основан на более старой версии ВК, соотвественно лента там работает по другому.
Единственное решение - изменить порядок новостей
