### ISSUE TITLE
Один и тот же видеоролик в историях

### ISSUE THREAD

**Issue by Mksmblknv7308** [vtosters/lite#1424]
**Опишите сам баг**
При обновлении новостей вылезает ошибка

**Опишите действия для воспроизведения ошибки**
1. Обновил ленту интересных новостей
2. Пролистал до конца страницы

**Опишите ожидаемый результат**
Интересная лента должна прогружать результаты

**Скриншот ошибки**

**Скопируйте сюда информацию об устройстве нажав на кнопку "Скопировать информацию об устройстве" в Настройках -> Другое и удалите этот текст**

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

**Comment by danyyok** [comment]
@Mksmblknv7308 https://t.me/vtosters_faq/110

Duplicate+invalid issue 
#1129 / #1309
