### ISSUE TITLE
Ошибка с историями

### ISSUE THREAD

**Issue by denfromchb** [vtosters/lite#1425]
**Опишите сам баг**
При открытии истории происходит ошибка

**Опишите действия для воспроизведения ошибки**
1. Открыть истории
2. Листать

**Опишите ожидаемый результат**
Обычные истории
**Скриншот ошибки**

https://github.com/vtosters/lite/assets/84735654/2f97840a-d8fd-4994-b88f-487df29d902f

**Скопируйте сюда информацию об устройстве
**Информация об устройстве:** 

- Commit: 1b3896f
- Full Version Information: main-1b3896f-dirty
- Android SDK: 33
- Product: a52qub
- Device: a52q
- Board: atoll
- Manufacturer: samsung
- Brand: samsung
- Model: SM-A525M
- OneUi Major Version: 5
- OneUi Minor Version: 1.0
 

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

**Comment by danyyok** [comment]
@denfromchb https://t.me/vtosters_faq/110

Duplicate issue 
#1129 / #1309
