### ISSUE TITLE
Баг с удалением человека из друзей

### ISSUE THREAD

**Issue by Kalashnikov21** [vtosters/lite#1426]
При попытке удаления человека из друзей появляется сообщение " был удален из ваших друзей" и при обновлении ничего не меняется (надеюсь видно на скрине)
![Screenshot_2023-08-03-15-48-48-772_com vtosters lite](https://github.com/vtosters/lite/assets/141334343/7b97432e-95b3-4f56-a6df-eda59afc0d62)

**Comment by ayonovdenizs** [comment]
Пересоздайте issue по шаблону "Bug Report"

**Comment by Kalashnikov21** [comment]
Now is work
