### ISSUE TITLE
Вылет приложения

### ISSUE THREAD

**Issue by guringurasu** [vtosters/lite#1429]
Периодически стал вылетать ВТлайт, я не особо следила, в какой конкретно момент это происходит, но последний раз был при переходе в раздел новостей и обновлении. Вылезло вот такое сообщение
![Screenshot_2023-08-07-12-35-03-693_com mi android globallauncher](https://github.com/vtosters/lite/assets/141627522/7916129c-e71a-441c-a2f0-a37e75b57319)

**Comment by abslike** [comment]
@guringurasu нажмите сохранить в файл и отправьте результат сюда
