### ISSUE TITLE
Ошибка загрузки сообщений сообщества

### ISSUE THREAD

**Issue by SabishiSenshi** [vtosters/lite#1433]
После авторизации при первом открытии сообщений управляемого сообщества загружаются личные диалоги пользователя 

1. Открыть приложение
2. Авторизоваться под учётной записью
3. Перейти в управляемое сообщество
4. Нажать "Сообщения сообщества"

При открытии сообщений сообщества загружаются диалоги сообщества с пользователями

![Screenshot_20230807-223546__01.jpg](https://github.com/vtosters/lite/assets/36118971/00ac0311-5bce-4308-9f27-503c592621eb)

**Информация об устройстве:** 

- Commit: cf17ed6
- Full Version Information: main-cf17ed6-dirty
- Android SDK: 30
- Product: OnePlus6
- Device: OnePlus6
- Board: sdm845
- Manufacturer: OnePlus
- Brand: OnePlus
- Model: ONEPLUS A6003

**Comment by ayonovdenizs** [comment]
Перезайдите в сообщения группы.
