### ISSUE TITLE
У умершего человека не отображается такой статус

### ISSUE THREAD

**Issue by rakleed** [vtosters/lite#1439]
**Опишите сам баг**
Если у страницы установлен статус, что человек умер, то в ВТостерс Lite эта информация не отображается, а также указывается время последнего входа на страницу, хотя эта информация [должна быть скрыта](https://vk.com/faq18466).

**Опишите действия для воспроизведения ошибки**
1. Открыть страницу человека, у которого установлен статус как умершего

**Опишите ожидаемый результат**
Отображается информация, что это страница умершего человека, и не отображается время последнего входа в аккаунт.

**Скриншот ошибки**
<details><summary>Скриншот</summary>

![Screenshot_20230815-000503_VTLite](https://github.com/vtosters/lite/assets/19418601/a56396d0-0d60-4c14-aefc-484943fb58c2)

</details>

**Информация об устройстве:** 

- Commit: cf17ed6
- Full Version Information: main-cf17ed6-dirty
- Android SDK: 32
- Product: lineage_vayu
- Device: vayu
- Board: msmnile
- Manufacturer: Xiaomi
- Brand: POCO
- Model: M2102J20SG

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

**Comment by abslike** [comment]
@rakleed появилось в более поздних версиях ВК, not planned
