### ISSUE TITLE
Ошибка воспроизведения историй

### ISSUE THREAD

**Issue by ebxz2** [vtosters/lite#1441]
При воспроизведении видеоисторий, первая видеоистория воспроизводится нормально, следующая видеоистория, которая должна быть другой, повторяется за уже просмотренной, и это может происходить на протяжении нескольких дней, потом какая-то видеоистория новая прогружается, и происходит та же история

**Comment by danyyok** [comment]
https://t.me/vtosters_faq/110

Duplicate+invalid issue 
#1129 / #1309
