### ISSUE TITLE
Ошибка открытия записи сообщества + запись не видна на стене сообщества

### ISSUE THREAD

**Issue by Nowhaile** [vtosters/lite#1443]
**Опишите сам баг**
Запись не получается открыть. Пишет "Запись не найдена". Так же ее нет на стене сообщества

**Опишите действия для воспроизведения ошибки**
1. Получаю репост записи в сообщения
2. Жму открыть запись
2.а. Захожу в сообщество чтобы найти ее

**Опишите ожидаемый результат**
Запись должна открываться/быть видна в сообществе

**Скриншот ошибки**
Сначала это:
![IMG_20230818_155644.jpg](https://github.com/vtosters/lite/assets/13280749/2c337fff-79c9-4a47-aded-91d867ec3673)
Потом сменяется этим:
![IMG_20230818_155708.jpg](https://github.com/vtosters/lite/assets/13280749/9aa16d15-0ad9-48c3-9b20-b4e80f50caa1)

***Информация об устройстве:** 
- Commit: cf17ed6
- Full Version Information: main-cf17ed6-dirty
- Android SDK: 33
- Product: fleur_ru
- Device: fleur
- Board: fleur
- Manufacturer: Xiaomi
- Brand: Redmi
- Model: 2201117SY (Redmi Note 11s NFC)
- Miui Version Code: 14
- Miui Version Name: V140
- Miui Version Incremental Code: V14.0.2.0.TKERUXM

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**
Такое уже было раннее, но думал что статьи удаляют. Однако тут мне явно сказали что она доступна. Как итог - зашёл через браузер и смог ее открыть.
Ссылка на статью:
https://m.vk.com/wall-20629724_1532963

**Comment by abslike** [comment]
@Nowhaile скорее всего она попала под рекламный фильтр, попробуй отключить их
