### ISSUE TITLE
Ошибка скачивания музыки.

### ISSUE THREAD

**Issue by BiSMORCK** [vtosters/lite#1447]
Музыка в mp3 не скачивается

1. Нажимаешь скачать
2. Приложение делает вид, что скачивает, всё как задумано
3. Файлов нет. Даже папки по пути VK/Music нет

**Информация об устройстве:** 

- Commit: cf17ed6
- Full Version Information: main-cf17ed6-dirty
- Android SDK: 33
- Product: a52sxqxx
- Device: a52sxq
- Board: lahaina
- Manufacturer: samsung
- Brand: samsung
- Model: SM-A528B
- OneUi Major Version: 5
- OneUi Minor Version: 1.0

**Comment by gdlbo** [comment]
нет логов -> бага нет
