### ISSUE TITLE
Ошибка отображения постов групп

### ISSUE THREAD

**Issue by SabishiSenshi** [vtosters/lite#1449]
Посты опубликованные с десктопной версии сайта ВКонтакте не отображаются в мобильном клиенте VTlite

1. Пройти авторизацию на сайте vk.com
2. Открыть управляемую группу
3. Опубликовать пост

 Опубликованный пост отображается на всех доступных платформах

**Скриншот ошибки**
VTlite
![Screenshot_20230829-223857.jpg](https://github.com/vtosters/lite/assets/36118971/f50b01c6-7ef3-498d-b6b0-60bfcfe1fde3)

VK 
![Screenshot_20230829-223917.jpg](https://github.com/vtosters/lite/assets/36118971/251f4f02-e637-4996-8e13-f430cbce9c1a)

**Информация об устройстве:** 

- Commit: cf17ed6
- Full Version Information: main-cf17ed6-dirty
- Android SDK: 30
- Product: OnePlus6
- Device: OnePlus6
- Board: sdm845
- Manufacturer: OnePlus
- Brand: OnePlus
- Model: ONEPLUS A6003

При просмотре групп в VTlite не увидел закреплённый пост и не смог найти его просто в ленте сообщества, оформляя пост самостоятельно уже через сайт обнаружил что пост не отображается снова в VTlite, пробовал в двух группах, закреплённый и обычный пост, написанные посты через сайт не отображаются

**Comment by SabishiSenshi** [comment]
Добавил скрины для наглядности, обновление страницы не помогает, пост в одной из групп был написан неделю назад и закреплён - также не отображается

**Comment by danyyok** [comment]
Добавь группу в вайтлист (3 точки) и обнови страницу

**Comment by danyyok** [comment]
> Помогло, но неужели придется добавлять все сообщества в вайтлист чтобы избежать подобного?

Так срабатывает фильтр рекламы, если хочешь видеть все посты отключи рекламу в настройках
