### ISSUE TITLE
Ошибка воспроизведения историй

### ISSUE THREAD

**Issue by seishiki** [vtosters/lite#1451]
Всегда воспроизводится одна и та же история.

1. Нажимаю на историю любого сообщества

Должны воспроизводится разные истории у разных сообществ и групп

**Скриншот ошибки**
![Screenshot_2023-09-02-01-28-13-765_com.vtosters.lite.jpg](https://github.com/vtosters/lite/assets/132843225/a1f1e0e0-ebc1-4e85-adfd-41461df469af)

![Screenshot_2023-09-02-01-28-23-573_com.vtosters.lite.jpg](https://github.com/vtosters/lite/assets/132843225/6f15fa53-aadb-41ba-8208-ea2610cb0729)

![Screenshot_2023-09-02-01-28-07-425_com.vtosters.lite.jpg](https://github.com/vtosters/lite/assets/132843225/e86028e6-f46a-4b40-8fdc-9d119f699603)

![Screenshot_2023-09-02-01-27-59-496_com.vtosters.lite.jpg](https://github.com/vtosters/lite/assets/132843225/3fc37f3d-ad45-47ba-95e4-5adfd7ab7573)

Poco X3 Pro 8/256

**Comment by danyyok** [comment]
https://t.me/vtosters_faq/110

Duplicate issue 
#1129 / #1309
