### ISSUE TITLE
Ошибка в историях

### ISSUE THREAD

**Issue by SiAmSiK** [vtosters/lite#1452]
**Опишите сам баг**
Во всех историях с видео одно и тоже видео

**Опишите действия для воспроизведения ошибки**
1. Включить историю
2. Пролистать на другую

**Опишите ожидаемый результат**
Видео в историях именно те, которые выкладывают пользователи

**Скриншот ошибки**

**Скопируйте сюда информацию об устройстве нажав на кнопку "Скопировать информацию об **
Устройсво- samsung galaxy s21 ultra

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

**Comment by ayonovdenizs** [comment]
https://t.me/vtosters_faq/110

Duplicate issue 
[#1129](https://github.com/vtosters/lite/issues/1129) / [#1309](https://github.com/vtosters/lite/issues/1309)
