### ISSUE TITLE
Не загружаются истории/ работают неправильно 

### ISSUE THREAD

**Issue by VILLAIN006** [vtosters/lite#1455]
**Опишите сам баг**
При просмотре истоий они либо не загружаются (Нет сети, попробуйте снова), либо подменяются на историю из других групп/людей

**Опишите действия для воспроизведения ошибки**
1. Посмотреть несколько историй
2. Закрыть приложение
3. Дождаться новых историй
4. Посмотреть их

**Опишите ожидаемый результат**
Истории работают нормально 

**Скриншот ошибки**

**Скопируйте сюда информацию об устройстве**
**Информация об устройстве:** 

- Commit: cf17ed6
- Full Version Information: main-cf17ed6-dirty
- Android SDK: 31
- Product: sunny_ru
- Device: sunny
- Board: sunny
- Manufacturer: Xiaomi
- Brand: Redmi
- Model: M2101K7AG
- Miui Version Code: 14
- Miui Version Name: V140
- Miui Version Incremental Code: V14.0.4.0.SKGRUXM

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**
Если почистить кеш через настройки самого тостера, а после в настройках телефона, то вме загружается и работает нормально.

**Comment by danyyok** [comment]
@VILLAIN006 https://t.me/vtosters_faq/110

Duplicate issue 
#1129 / #1309
