### ISSUE TITLE
Ошибка сервисов вк

### ISSUE THREAD

**Issue by XJle6sus** [vtosters/lite#1456]
**Опишите сам баг**
Просто пропала функция смотреть/зайти в свою или в чью либо музыку 

**Опишите действия для воспроизведения ошибки**
Это просто случилось,без понятия как

**Опишите ожидаемый результат**
В сервисах вкладка музыки должна быть 

**Скриншот ошибки**
![Screenshot_2023-09-13-19-40-30-58_9e1a5d6211a0228d32d39446541891f1](https://github.com/vtosters/lite/assets/144940156/3e9f9c4c-6155-4181-a7cb-fa93b2663ef3)

**Скопируйте сюда информацию об устройстве нажав на кнопку "Скопировать информацию об устройстве" в Настройках -> Другое и удалите этот текст**

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

**Comment by gdlbo** [comment]
Read https://t.me/vtosters
