### ISSUE TITLE
Нет мужики во вкладке сервисы 

### ISSUE THREAD

**Issue by Pavlo124** [vtosters/lite#1457]
**Опишите сам баг**
При нажатии на сервисы где должна быть музыка теперь игры а музыки нет 

**Опишите действия для воспроизведения ошибки**
1. Обновил ленту интересных новостей
2. Пролистал до конца страницы

**Опишите ожидаемый результат**
Интересная лента должна прогружать результаты
![SAVE_20230914_242253](https://github.com/vtosters/lite/assets/144943366/0db78239-546d-4e4f-ae56-145d53034e28)

**Скриншот ошибки**

**Скопируйте сюда информацию об устройстве нажав на кнопку "Скопировать информацию об устройстве" в Настройках -> Другое и удалите этот текст**

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

**Comment by gdlbo** [comment]
Read https://t.me/vtosters
