### ISSUE TITLE
пропала иконка музыки из сервисов, а через поиск мини приложение музыка не грузиться 

### ISSUE THREAD

**Issue by seemeenok** [vtosters/lite#1458]
**Опишите сам баг**
При обновлении новостей вылезает ошибка

**Опишите действия для воспроизведения ошибки**
1. Обновил ленту интересных новостей
2. Пролистал до конца страницы

**Опишите ожидаемый результат**
Интересная лента должна прогружать результаты

**Скриншот ошибки**

**Скопируйте сюда информацию об устройстве нажав на кнопку "Скопировать информацию об устройстве" в Настройках -> Другое и удалите этот текст**

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

**Comment by ansoch** [comment]
Такая же ошибка, но появилась после альтаба

**Comment by danyyok** [comment]
@seemeenok t.me/vtosters_faq/118
