### ISSUE TITLE
Ошибка в просмотре историй

### ISSUE THREAD

**Issue by Anastasia-Kolomeets** [vtosters/lite#1459]
Постоянно на всех историях отображается фотография одной истории. Очищала кэш, начала смотреть историю, теперь видео повторяется на абсолютно всех историях или пишет ошибку подключения сети. 

Хочу посмотреть все истории своих друзей, а не одно и то же видео на повторе. 

![Screenshot_20230914_013320](https://github.com/vtosters/lite/assets/144957557/3c70c98f-d7cb-400e-b401-a28d279bc79d)

**Информация об устройстве:** 

- Commit: cf17ed6
- Full Version Information: main-cf17ed6-dirty
- Android SDK: 33
- Product: NTH-NX9
- Device: HNNTH
- Board: NTH
- Manufacturer: HONOR
- Brand: HONOR
- Model: NTH-NX9

**Comment by danyyok** [comment]
@Anastasia-Kolomeets https://t.me/vtosters_faq/110

Duplicate issue 
#1129 / #1309
