### ISSUE TITLE
Ошибка в меню приложения

### ISSUE THREAD

**Issue by Vl4D9** [vtosters/lite#1460]
В меню приложения VK Lite пропал значок музыки
Переустановка приложение не помогло

В меню должен появиться как раньше значок музыки и доступ к ней

![Screenshot_20230914_034642_VTLite](https://github.com/vtosters/lite/assets/144969349/b5120762-e6f4-4a66-bd9b-8bef5cc7e191)

Нет предположения почему так произошло

**Comment by danyyok** [comment]
@Vl4D9 t.me/vtosters_faq/118
