### ISSUE TITLE
В сервисах нет иконки музыки

### ISSUE THREAD

**Issue by Kira09097** [vtosters/lite#1461]
![Screenshot_2023-09-14-10-11-40-01_9e1a5d6211a0228d32d39446541891f1](https://github.com/vtosters/lite/assets/144981011/fe3fbd6e-7c21-4156-b39f-a594b58e07ca)
Нет иконки "музыка" В сервисах

**Comment by ayonovdenizs** [comment]
@Kira09097 http://t.me/vtosters_faq/118

**Comment by Kira09097** [comment]
> @Kira09097 http://t.me/vtosters_faq/118

Спасибо🙏💕

**Comment by Kira09097** [comment]
Решено
