### ISSUE TITLE
Пропадает иконка раздела музыки в меню

### ISSUE THREAD

**Issue by Krowchiik** [vtosters/lite#1462]
**Опишите сам баг**
При входе в меню где можно зайди в разделы с сообществами, стикерами, играми и тд. пропадает иконка с разделом музыки. 

**Опишите действия для воспроизведения ошибки**
1. Зашёл в меню, чтобы открыть раздел с музыкой.
2. Иконка раздела с музыкой исчезла, при попытке открыть полный список иконок, иконка с музыкой не появляется.

**Опишите ожидаемый результат**
Присутствие иконки с разделом музыки в меню.

**Скриншот ошибки**
![Screenshot_20230914_120345_VTLite](https://github.com/vtosters/lite/assets/145005345/dfd379af-0d60-4880-8a04-5cf99fd80c09)
![Screenshot_20230914_121935_VTLite](https://github.com/vtosters/lite/assets/145005345/cc71427c-f129-41f2-9528-ecae2ab0568c)

**Device info:** 

- Commit: cf17ed6
- Full Version Information: main-cf17ed6-dirty
- Android SDK: 33
- Product: a23nsxx
- Device: a23
- Board: bengal
- Manufacturer: samsung
- Brand: samsung
- Model: SM-A235F
- OneUi Major Version: 5
- OneUi Minor Version: 1.0
- 

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

**Comment by danyyok** [comment]
Обновись
