### ISSUE TITLE
Баг с историей реклама в истории 

### ISSUE THREAD

**Issue by Roman828483** [vtosters/lite#1463]
Здравствуйте у меня произошел баг с историей я не могу посмотреть историю так как мне мешает реклама из вот я включил в настройках блокировку рекламы но мне это никак не помогает я записал видео где мне мешает реклама прошу исправить данную ошибку(

**Comment by abslike** [comment]
скриншот ошибки

**Comment by Roman828483** [comment]
![Screenshot_2023-09-14-15-23-53-335_com vtosters lite](https://github.com/vtosters/lite/assets/145019672/aacd3483-b513-45bd-9502-eb58414c1c14)
![Screenshot_2023-09-14-15-23-51-259_com vtosters lite](https://github.com/vtosters/lite/assets/145019672/2876c433-d7fd-4d7d-baeb-e2369d6bd3e4)
![Screenshot_2023-09-14-15-23-46-500_com vtosters lite](https://github.com/vtosters/lite/assets/145019672/f844cc3e-fd35-4d64-8a03-5d6b689356a7)
![Screenshot_2023-09-14-15-23-38-936_com vtosters lite](https://github.com/vtosters/lite/assets/145019672/c5643fcf-e801-4a41-bbac-a834ed5a9878)
![Screenshot_2023-09-14-15-23-32-183_com vtosters lite](https://github.com/vtosters/lite/assets/145019672/6f6bc732-d533-42ef-97bb-644b5e578f8b)
![Screenshot_2023-09-14-15-23-35-672_com vtosters lite](https://github.com/vtosters/lite/assets/145019672/8c58a54c-d235-40a3-a782-c1add4ec11b4)
![Screenshot_2023-09-14-15-23-30-214_com vtosters lite](https://github.com/vtosters/lite/assets/145019672/dc2ee98a-6b94-4556-ab45-06975923c0e4)
![Screenshot_2023-09-14-15-23-28-260_com vtosters lite](https://github.com/vtosters/lite/assets/145019672/11553719-bc94-45a6-ba5b-5ad950ca675e)
![Screenshot_2023-09-14-15-23-26-002_com vtosters lite](https://github.com/vtosters/lite/assets/145019672/b85b3741-abe5-4c1b-b97e-685d14935ebc)
![Screenshot_2023-09-14-15-23-16-571_com vtosters lite](https://github.com/vtosters/lite/assets/145019672/a15eacd4-ff2e-429f-a470-d57096014e31)
![Screenshot_2023-09-14-15-23-11-179_com vtosters lite](https://github.com/vtosters/lite/assets/145019672/f1544d6d-9360-429e-ae80-2ec20c063bfc)
![Screenshot_2023-09-14-15-23-06-067_com vtosters lite](https://github.com/vtosters/lite/assets/145019672/ccca1e91-6685-48ea-bbac-1cfec1a77da3)
![Screenshot_2023-09-14-15-23-00-667_com vtosters lite](https://github.com/vtosters/lite/assets/145019672/ab78f1e9-664f-4b07-b14b-115a124acb5f)

**Comment by Roman828483** [comment]
Просто одна и та же реклама в историях

**Comment by Roman828483** [comment]
https://disk.yandex.com.am/i/M-DPXkWkGe6j3g

**Comment by Roman828483** [comment]
https://wdfiles.ru/1rMsW

**Comment by Roman828483** [comment]
Вот видео

**Comment by danyyok** [comment]
https://t.me/vtosters_faq/110

Duplicate+invalid issue 
#1129 / #1309

**Comment by Roman828483** [comment]
А вы не подскажите как решить эту проблему?

**Comment by Serdobine** [comment]
@Roman828483 настройки ленты > выключаешь "показывать истории в ленте"

**Comment by Roman828483** [comment]
Спасибо, сейчас займусь.

**Comment by Roman828483** [comment]
Не помогло, баг остался.
