### ISSUE TITLE
Отсутствует вкладка с музыкой в разделе сервисов

### ISSUE THREAD

**Issue by GnomBober** [vtosters/lite#1464]
**Опишите сам баг**
При обновлении новостей вылезает ошибка
После ошибки загрузки аудио, приложение вылетело и при последующих входах вкладка не появляется. Очистка Кеша, перезаход в приложение и выход и вход в аккаунт не помогают. Переустановка не пробовал, 6гб загруженных аудио жалко(
**Опишите действия для воспроизведения ошибки**
1. Обновил ленту интересных новостей
2. Пролистал до конца страницы

**Опишите ожидаемый результат**
Интересная лента должна прогружать результаты

**Скриншот ошибки**

**Скопируйте сюда информацию об устройстве нажав на кнопку "Скопировать информацию об устройстве" в Настройках -> Другое и удалите этот текст**

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

**Comment by danyyok** [comment]
@GnomBober Обновись
