### ISSUE TITLE
Ошибка загрузки сообщений 

### ISSUE THREAD

**Issue by lipuchka78** [vtosters/lite#1469]
Бесконечная загрузка вкладки "сообщения"

1. При заходе в сообщения начинается бесконечная загрузка переписок
2. Со временем появляется уведомление "Не удалось выполнить запрос"
3. Хотя через поиск можно зайти в отдельные переписки, но вместе они никак не прогружаются

1. Проблема появилась сегодня
2. Не помогает ни перезагрузка устройства, ни переустановка приложения, ни очистка кеша
3. В оригинальном вк всё работает

**Comment by danyyok** [comment]
Пересоздайте Issue по шаблону прикрепив информацию об устройстве
