### ISSUE TITLE
Ошибка загрузки сообщений 

### ISSUE THREAD

**Issue by lipuchka78** [vtosters/lite#1470]
Вкладка сообщения не загружается

При заходе в сообщения начинается бесконечная загрузка переписок

Со временем появляется уведомление "Не удалось выполнить запрос"

Хотя через поиск можно зайти в отдельные переписки, но вместе они никак не прогружаются

![Screenshot_2023-09-16-13-55-57-268_com vtosters lite](https://github.com/vtosters/lite/assets/145192867/3ff34d5a-1562-4977-89c3-6cb64ed0a9da)

Проблема появилась сегодня

Не помогает ни перезагрузка устройства, ни переустановка приложения, ни очистка кеша

В оригинальном вк всё работает как и было
(я не нашел как скопировать данные поэтому прикрепляю скриншот)

![IMG_20230916_162606](https://github.com/vtosters/lite/assets/145192867/f13b9334-b762-4c8a-9aed-74b490040d44)

**Comment by danyyok** [comment]
Пересоздайте Issue по шаблону прикрепив информацию об устройстве
