### ISSUE TITLE
Приложение вылетает при попытке скачать музыку

### ISSUE THREAD

**Issue by Cherro59** [vtosters/lite#1472]
**Описание**
Если нажать на кнопку, скачать как mp3, то приложение вылетает и перезагружается во вкладку "Музыка".

**Воспроизведение бага**
1. Открыл музыку
2. Выбрал трек
3. Нажал скачать как mp3

**Ожидаемый результат**
Музыка будет скачана на устройство

[Логи](https://pastebin.com/Hzt7YtAX) прилагаю

**Comment by danyyok** [comment]
Обнови приложение
