### ISSUE TITLE
Ошибка в переводе того, что не должно быть переведено или изменено

### ISSUE THREAD

**Issue by Raitorinkus** [vtosters/lite#1476]
**Скриншот ошибки
![Screenshot_20230926_170057_com vtosters lite](https://github.com/vtosters/lite/assets/140437408/2ba30b0b-b743-4e4b-a320-7ff035152f2b)
**

**Информация об устройстве:** 

- Commit: 7e5b3fe
- Full Version Information: main-7e5b3fe-dirty
- Android SDK: 29
- Product: JNY-LX1
- Device: HWJNY
- Board: JNY
- Manufacturer: HUAWEI
- Brand: HUAWEI
- Model: JNY-LX1
- Emui Version: EmotionUI_12.0.0

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

**Comment by gdlbo** [comment]
а где ошибка

**Comment by danyyok** [comment]
Отключи переводчик, если ты про эмодзи
