### ISSUE TITLE
Не приходят уведомления из беседы когда приложение закрыто

### ISSUE THREAD

**Issue by GitHubovec559** [vtosters/lite#1477]
**Опишите сам баг**
Часто перестали приходить уведомления из беседы, если приложение закрыто. Как только входишь во втостерс, то уведомления появляются. Иногда приходили и при закрытом втостерсе, но это было редко и то если в этой беседе сильно спамили.

**Опишите действия для воспроизведения ошибки**
1. Закрыть приложение
2. Если что-то напишут в беседе, то это уведомление отобразится только если открыть само приложение. 

**Опишите ожидаемый результат**
Уведомления должны приходить всегда

**Скриншот ошибки**
-

**Информация об устройстве:** 

- Commit: 7e5b3fe
- Full Version Information: main-7e5b3fe-dirty
- Android SDK: 31
- Product: a31xx
- Device: a31
- Board: a31
- Manufacturer: samsung
- Brand: samsung
- Model: SM-A315F
- OneUi Major Version: 4
- OneUi Minor Version: 1.0

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**
-

**Comment by gdlbo** [comment]
разреши работу в фоне и отключи любые ограничения аппе
