### ISSUE TITLE
Ошибка раздела музыки

### ISSUE THREAD

**Issue by Funt1UP** [vtosters/lite#1480]
**Опишите сам баг**
При обновлении раздела музыки приложение выкидывает из аккаунта.

**Опишите действия для воспроизведения ошибки**
1. Сначала я не смог обновить некоторых исполнителей, потом не смог найти похожую музыку, а после вообще музыка выключилась и при попытке включить приложение багет и выкидывает на страницу регистрации.

Разные движения производил, возможно ВК что-то подменила снова, чтобы такие как мы мучались.

**Comment by gdlbo** [comment]
глобальные проблемы самого вк

**Comment by aliveoutside** [comment]
https://downdetector.br-analytics.ru/vkontakte

что-то сломалось на их стороне, сейчас всё должно быть в порядке
