### ISSUE TITLE
Не обновляется лента новостей

### ISSUE THREAD

**Issue by FortisMax** [vtosters/lite#1487]
Постоянно одно и то же в новостях, на вкладке интересное. Что на планшете от Huawei, что на данном аппарате. Пробовал чистить кэш, перезапускать приложение, удалял полностью вместе с данными и устанавливал с нуля, ничего не помогает. 

**Информация об устройстве:** 

- Commit: f5180f6
- Full Version Information: main-f5180f6-dirty
- Android SDK: 31
- Product: OnePlus7Pro_CH
- Device: OnePlus7Pro
- Board: msmnile
- Manufacturer: OnePlus
- Brand: OnePlus
- Model: GM1910

**Comment by danyyok** [comment]
https://t.me/vtostersfaq/13?single

**Comment by FortisMax** [comment]
Так я и сделал. Это не решение, а костыль....
