### ISSUE TITLE
Периодическое зависание плеера музыки

### ISSUE THREAD

**Issue by Ghdie** [vtosters/lite#1488]
**Опишите сам баг**
При включении музыки на телефоне плеер виснет примерно на 5-10 секунд, то есть не дает ни нажать на паузу, ни листнуть на список с треками, даже сама дорожка песни не движется, соответственно время тоже. То же самое иногда происходит, когда слушаешь музыку с заблокированным экраном, потом включаешь телефон - плеер опять завис

**Опишите действия для воспроизведения ошибки**
1. Включение музыки
2. Разблокировка телефона при прослушивании музыки

**Опишите ожидаемый результат**
Отсутствие подвисания плеера

**Информация об устройстве:** 

- Commit: f5180f6
- Full Version Information: main-f5180f6-dirty
- Android SDK: 33
- Product: rosemary_ru
- Device: rosemary
- Board: rosemary
- Manufacturer: Xiaomi
- Brand: Redmi
- Model: M2101K7BNY
- Miui Version Code: 14
- Miui Version Name: V140
- Miui Version Incremental Code: V14.0.1.0.TKLRUXM

**Comment by WeSTManCoder** [comment]
Подтверждаю. А так же дополню, когда заходишь в кеш музыки, то вк зависает и может потребовать рестарт приложения уже от самого андройда
