### ISSUE TITLE
Белый фон в пересылке сообщений

### ISSUE THREAD

**Issue by advokat11** [vtosters/lite#149]
Вот так выглядит панель пересылки постов с ленты. Красным закрасил я.
![Screenshot_20220413-144546__01.jpg](https://user-images.githubusercontent.com/59486045/163173493-53d8b8a6-5579-494e-b1a8-efd93d6ef3cf.jpg)

**Comment by advokat11** [comment]
Имена аккаунтов отображаются белым, сливаются с фоном.

**Comment by gdlbo** [comment]
https://github.com/vtosters/lite/issues/2
