### ISSUE TITLE
Неправильное открытие VK ID

### ISSUE THREAD

**Issue by SuperSuslik312** [vtosters/lite#1490]
**Опишите сам баг**

Вместо VK ID открывается его подраздел "личная информация"

**Опишите действия для воспроизведения ошибки**
1. Открыть настройки
2. Открыть VK ID

**Опишите ожидаемый результат**

Открывается основной раздел VK ID, а не "личная информация"

**Видеозахват ошибки**

https://github.com/vtosters/lite/assets/74268455/8472f8e4-436b-4811-8970-02417666a88a

**Информация об устройстве:** 

- Commit: f5180f6
- Full Version Information: main-f5180f6-dirty
- Android SDK: 33
- Product: lineage_alioth
- Device: alioth
- Board: kona
- Manufacturer: Xiaomi
- Brand: POCO
- Model: M2012K11AG

**Comment by gdlbo** [comment]
вк сами пофиксили
