### ISSUE TITLE
Ошибка обновлении ленты новостей

### ISSUE THREAD

**Issue by Domunik47** [vtosters/lite#1491]
**Опишите сам баг**
При обновлении новостей не загружаются фото и видео, всё в низком качестве. Прогружаются только если открыть пост или фото, видео. Но когда возвращаешься в ленту новостей, фотографии которые уже должны были загрузиться, остаются в низком качестве. Экономия трафика отключена.
![Screenshot_2023-10-03-09-19-43-549_com vtosters lite](https://github.com/vtosters/lite/assets/146809090/0898d231-fd41-4c9f-bf22-7e000f81611a)

**Comment by danyyok** [comment]
Отключи экономию трафика/переустанови приложение
