### ISSUE TITLE
Более яркие разделители в AMOLED-теме

### ISSUE THREAD

**Issue by Bebraboy** [vtosters/lite#1492]
Было бы круто, если бы оригинальные серые разделители в amoled-теме стали бы более яркими, потому что их почти не видно и всё становится будто бы сплошно залитым чёрным. Выглядит это так себе. 
Говоря про разделители, я имею ввиду серые полосы, разделяющие посты в ленте, кнопки, диалоги и т.д.
![image](https://github.com/vtosters/lite/assets/130256877/a71e3ecc-0d3a-4550-ba82-60405a9b8139)

**Comment by gdlbo** [comment]
все кто просил амолед тему наоборот просили скрыть разделения, так что нет

**Comment by abslike** [comment]
@gdlbo тоже самое на монет теме сделано
