### ISSUE TITLE
Не работает "Фильтр слов и выражений"

### ISSUE THREAD

**Issue by syf1e** [vtosters/lite#1493]
Возможно я не совсем правильно понимаю как работает эта функция, но у меня она не работает.
![Screenshot_20231006_104925_VTLite](https://github.com/vtosters/lite/assets/123977934/e08873f2-9e17-4dc1-9710-1a2114487e3f)
![Screenshot_20231006_104846_VTLite](https://github.com/vtosters/lite/assets/123977934/3667fe83-04e7-488d-848a-49dbb2cc34c5)

**Информация об устройстве:** 

- Commit: cf05e05
- Full Version Information: main-cf05e05-dirty
- Android SDK: 33
- Product: m52xqxx
- Device: m52xq
- Board: lahaina
- Manufacturer: samsung
- Brand: samsung
- Model: SM-M526BR
- OneUi Major Version: 5
- OneUi Minor Version: 1.0
Версия VTLite 1.0.2

**Comment by gdlbo** [comment]
перезаход в приложение делал?

**Comment by syf1e** [comment]
> перезаход в приложении делал?

да делал, сейчас я принудительно остановил приложение и тот пост со скрина исчез. добавил его в список я еще вчера и до сегодняшнего дня он так и оставался в ленте. но прямо сейчас я попробовал скрыть рандом пост из ленты и он пропал после простого перезахода в приложение без принудительной остановки. так и не понял от чего это зависит, может баг разовый. кстати, а если ввести часть ссылки(wow.link например), то пост будет скрыт?

**Comment by gdlbo** [comment]
Группа не добавлена в исключения? Не включена ли функция инвертации списка?

**Comment by syf1e** [comment]
нет, в исключение не добавлял, список не инвертировал

**Comment by gdlbo** [comment]
![Screenshot_20231006-130841~2.png](https://github.com/vtosters/lite/assets/41114720/255dc8c9-8ba1-4e6d-89fc-08033ffdf28f)

![Screenshot_20231006-130935.png](https://github.com/vtosters/lite/assets/41114720/89f622f5-c935-4eb9-9297-81b9f88a878e)

Перезапуска хватило для применения фильтра

**Comment by syf1e** [comment]
небольшой сбой видимо, главное заработалов итоге, спасибо
