### ISSUE TITLE
Некорректное скачивание музыки в mp3

### ISSUE THREAD

**Issue by mexanoz** [vtosters/lite#1496]
При скачивании музыки в mp3 к концу названия файла перед расширением добавляется "null", а сам файл не содержит ID3-тегов (название, исполнитель, альбом).

1. Раздел музыки, выбираем любой трек (в примере "Shallowsky - Rift (feat. Cody Jamison")
2. Три точки -> "Скачать как mp3"

**Опишите ожидаемый результат**
В названии файла нет "null", в ID3-тегах указаны название и исполнитель.

**Скриншот ошибки**
![IMG_20231010_033522.jpg](https://github.com/vtosters/lite/assets/96656876/dec6eebb-2217-4aa0-ab78-fdd240b97382)

![IMG_20231010_034045.jpg](https://github.com/vtosters/lite/assets/96656876/10e8b2de-7bd7-4694-b7f6-f892fe6742df)

**Информация об устройстве:** 

- Commit: cf05e05
- Full Version Information: main-cf05e05-dirty
- Android SDK: 30
- Product: ginkgo
- Device: ginkgo
- Board: ginkgo
- Manufacturer: Xiaomi
- Brand: xiaomi
- Model: Redmi Note 8
- Miui Version Code: 12
- Miui Version Name: V125
- Miui Version Incremental Code: V12.5.2.0.RCOMIXM

**Comment by gdlbo** [comment]
будет исправлено уже в следующем обновлении
