### ISSUE TITLE
Сломанная темная тема

### ISSUE THREAD

**Issue by SonClick** [vtosters/lite#15]
При включении темной темы, в настройках сломан цвет шрифта ![Screenshot_20220325-231745707.png](https://user-images.githubusercontent.com/102040046/160160125-4442b18e-9b0d-4daa-9b24-641829e0e393.png)

**Comment by gdlbo** [comment]
https://github.com/vtosters/lite/issues/2

**Comment by SonClick** [comment]
0.0.3 fixed
