### ISSUE TITLE
Смена аккаунта, некорректное отображение боковой панели 

### ISSUE THREAD

**Issue by artem1998ss23** [vtosters/lite#1500]
**Опишите сам баг**
При смене аккаунта боковая панель отображаеться пустая !

**Опишите действия для воспроизведения ошибки**
1. Зашел в настройки 
2. Нажал сменить аккаунт 
3. Выбрал аккаунт 
4. Нажал на боковое меню 

**Опишите ожидаемый результат**
Корректно отображаться боковое меню

**Скриншот ошибки**
![Screenshot_20231012-213716_VTLite](https://github.com/vtosters/lite/assets/119823268/922ef560-2b0d-404b-a0d4-204665daba67)

![Screenshot_20231012-214034_Settings](https://github.com/vtosters/lite/assets/119823268/24385653-90ce-4628-a9e0-a1da9038879f)

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

**Comment by danyyok** [comment]
Перезапусти приложение
