### ISSUE TITLE
Воспроизводится только чути аудиозаписей и их произвольное переключение.

### ISSUE THREAD

**Issue by Colambus1** [vtosters/lite#1501]
При вопроизведении аудиозаписей, начиная не с первого трека, а пролистав ниже, в текущий плейлист добавляются не все треки к воспроизведкнию, что ниже по списку, а несколоко треков (от 20 до 50), прослушав которые вопроизведение заканчивается. Кнопка перемешивания отключена. Также иногда треки сами по себе выключается или переключаются на слудуюший, причину выяснить не удалось.

**Comment by danyyok** [comment]
Пересоздайте Issue по шаблону прикрепив информацию об устройстве
