### ISSUE TITLE
Не остаются удаленные сообщения 

### ISSUE THREAD

**Issue by Anastasia65477** [vtosters/lite#1502]
Функция "оставлять удалённые сообщения" - включена. Но от некоторых пользователей удалённые сообщения остаются, а от некоторых пользователей нет. С чем это связано? Но я ссылаюсь на то, что это недоработка 

Модель телефона poco m4 pro, miui 14

**Comment by danyyok** [comment]
Сохранение удаленных сообщений может некорректно работать в фоне/когда приложение закрыто
