### ISSUE TITLE
Внешний вид

### ISSUE THREAD

**Issue by Ko99929** [vtosters/lite#1504]
Аыыыы

**Comment by person10301** [comment]
@Ko99929 Сам и займётся

**Comment by Serdobine** [comment]
@Ko99929 данная функция уже имеется, но видна только пользователям с Android 12 и выше

**Comment by Ko99929** [comment]
Это material you,а не md

сб, 21 окт. 2023 г., 17:10 Serdobine ***@***.***>:

**Comment by Ko99929** [comment]
Он более тёмный,чем стандартная тема,без серых цветов

сб, 21 окт. 2023 г., 17:24 Kadir Imamaliev ***@***.***>:

**Comment by Ko99929** [comment]
Просто как тема кастомная

**Comment by abslike** [comment]
@Ko99929 md3 = mdy
хочешь материал тему = юзай а12+

**Comment by Ko99929** [comment]
![Uploading Screenshot_2023-10-21-15-58-44-90_4bbea2983defcba323392b274842bf2c.jpg…]()

**Comment by Ko99929** [comment]
![Screenshot_2023-10-21-15-58-44-90_4bbea2983defcba323392b274842bf2c](https://github.com/vtosters/lite/assets/135260330/d3b06930-2012-49e6-9206-59120a3f9c20)

**Comment by Serdobine** [comment]
@Ko99929 извиняюсь, но ты конченный идиот! втостерс не поддерживается и не обновляется ВООБЩЕ, качай его замену - VTLite (на странице которого ты и высрал ишью), там как раз функция материал дизайна есть

**Comment by Ko99929** [comment]
> @Ko99929 извиняюсь, но ты конченный идиот! втостерс не поддерживается и не обновляется ВООБЩЕ, качай его замену - VTLite (на странице которого ты и высрал ишью), там как раз функция материал дизайна есть

Ты шо дурачёк блять,мне интересно стало,можно ли такую хуйню добавить,как кастомную тему хотя,не еблань,овощ.Причём тут версия,кончина ,я чё ебу чё можно в ней,а чё нет,акцент понятно,мне фон основной нужен

**Comment by Ko99929** [comment]
В виде отдельной темы,просто окрашенной

**Comment by Ko99929** [comment]
Я как раз на сайте сижу,петушок,скрин с совы

**Comment by Ko99929** [comment]
Лайте

**Comment by Ko99929** [comment]
Как окрашенную тему,именно в версии 5.50(какая там у лайта),с этим интерфейсом,либо хотяб милкшейк

**Comment by Ko99929** [comment]
На милкшейк интерфейсе*

**Comment by Ko99929** [comment]
> На милкшейк интерфейсе*

На включенном,дурачёк:),я знаю,что там есть эта функция

**Comment by Ko99929** [comment]
Не обязательно отдельную тему,хоть настраиваемую(фон)

**Comment by Ko99929** [comment]
А,блять,ебать дурни,мне над было спросить,будет ли редактор фона,хахаххахаха

**Comment by Ko99929** [comment]
Ладно,зря бычил,извиняюсь)

**Comment by Ko99929** [comment]
Андроид 12 хуеглотская версия,я с 11 ещё пару лет посиду

**Comment by Serdobine** [comment]
@Ko99929 движок тем позволяет, реализация пока не планируется.. монет оформление уже меняет цвет фона в цвет акцента. если ты говоришь именно о картинках, то вряд такое будет

**Comment by abslike** [comment]
@Ko99929 md3 лучшее, в чем траблы этой версии? (кроме блокировки даты которая обходится любым проводником), также звучит как windows 7 юзер

**Comment by Ko99929** [comment]
Это самый охуительный мод(я обожаю интерфейс 5 версии ВК),+ ещё функции дохуя. Реакции,закрепы,остальное тому подобное,о чём многие ноют,мне не нужно,просто цвет фона уже приелся,хотя и так всё хорошо,но было б неплохо иметь возможность менять его

**Comment by Serdobine** [comment]
@Ko99929 с монет оформлением цвет фона меняется, если что. все зависит от акцента твоего устройства

**Comment by Ko99929** [comment]
Мод рабочий и с охуительный интерфейсом,который стабильно поддерживается к тому же,я старым втостером на этом интерфейсе до самой его смерти стоял

**Comment by Ko99929** [comment]
Не хочу 12 андроид😭

**Comment by Ko99929** [comment]
Буду терпеть,чё уж

**Comment by Ko99929** [comment]
Это неудобно,к тому же по всей системе и без возможности выключить,отдельный редактор был бы намного удобнее

**Comment by Ko99929** [comment]
Акцент может подойти к тостеру,но в другом приложении он мне может быть неудобен

**Comment by Ko99929** [comment]
Тем более акцент берется с обоев только

**Comment by Ko99929** [comment]
Не ходить же с нигером на обоях,чтоб сделать мд тему)

**Comment by Ko99929** [comment]
> Акцент может подойти к тостеру,но в другом приложении он мне может не нравиться

Либо акцент системы как то убого сделает,но при этом в приложении хорошо
