### ISSUE TITLE
Ошибка при воспроизведении музыки VTLite

### ISSUE THREAD

**Issue by Arinsuu** [vtosters/lite#1508]
Некоторые песни обрезаны или из них пропали куски

Сначала думал, что дело в наушниках, но послушав без них понял, что дело в приложении (не в самой композиции, на других площадках она звучит так, как я её помню, в том же приложении ВК музыки всё в порядке). Проверил на нескольких песнях: где-то всё звучит как раньше и как должно звучать, а где-то также обрезаны моменты (время разное)

Очень жду возвращения хорошего качества музыки, пользуюсь приложением только из-за неё.

**Comment by danyyok** [comment]
Треки кешированы?
