### ISSUE TITLE
Просмотренные новости не скрываются из ленты

### ISSUE THREAD

**Issue by r35p3ct** [vtosters/lite#1510]
Листаешь ленту, обновляешь и все тоже самое. Только новые записи добавляются в начало.

**Comment by Serdobine** [comment]
@r35p3ct просмотренные посты и не должны скрываться, это не тикток

**Comment by r35p3ct** [comment]
> @r35p3ct просмотренные посты и не должны скрываться, это не тикток

В оригинале скрывались, там при обновлении ленты посты обновлялись.

**Comment by Serdobine** [comment]
@r35p3ct что значит "посты обновлялись"? появлялись новые по времени, или ты про интересную ленту?

**Comment by r35p3ct** [comment]
> @r35p3ct что значит "посты обновлялись"? появлялись новые по времени, или ты про интересную ленту?

Новости, в настройках порядок записей: сначала интересные.

**Comment by Serdobine** [comment]
@r35p3ct поставь "сначала новые", тогда у тебя посты будут только новые

**Comment by Serdobine** [comment]
@Serdobine интересная лента в вк работает криво

**Comment by ayonovdenizs** [comment]
@icynstant Во первых, интересную ленту отдает ВК.
Во вторых, https://t.me/vtostersfaq/13?single

**Comment by icynstant** [comment]
> @icynstant Во первых, интересную ленту отдает ВК.
> Во вторых, https://t.me/vtostersfaq/13?single

Есть ли возможность как-то это исправить или создать собственную ленту? Меня всё устраивает, не хватает только чтобы просмотренные посты уходили с ленты при обновлении.

**Comment by icynstant** [comment]
Опять же, я всегда пользовался оф. вк и лента всегда работала должным образом
