### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by r35p3ct** [vtosters/lite#1511]
**Опишите сам баг**
Сообщение вылезло Толи после сворачивании приложения, Толи после его открытия

Мне кажется ошибка связано с особенностью устройства, раскладушка.
В разложенном положении истории отображаются не по центру.
![Screenshot_2023-10-27-09-18-09-12_9e1a5d6211a0228d32d39446541891f1.jpg](https://github.com/vtosters/lite/assets/7328803/d706ed84-3f8b-4e56-9fa9-6267796c5778)

![Screenshot_2023-10-27-00-24-04-77_9e1a5d6211a0228d32d39446541891f1.jpg](https://github.com/vtosters/lite/assets/7328803/b8981573-71bc-46a6-be66-9835efbc9858)

![VTL_log_2023-10-26.14-51-09.txt](https://github.com/vtosters/lite/files/13185543/VTL_log_2023-10-26.14-51-09.txt)

![VTL_log_2023-10-26.14-51-10.txt](https://github.com/vtosters/lite/files/13185545/VTL_log_2023-10-26.14-51-10.txt)

![VTL_log_2023-10-26.14-48-14.txt](https://github.com/vtosters/lite/files/13185541/VTL_log_2023-10-26.14-48-14.txt)

![VTL_log_2023-10-26.14-48-16.txt](https://github.com/vtosters/lite/files/13185542/VTL_log_2023-10-26.14-48-16.txt)

![VTL_log_2023-10-26.14-51-11.txt](https://github.com/vtosters/lite/files/13185544/VTL_log_2023-10-26.14-51-11.txt)

**Comment by Serdobine** [comment]
@r35p3ct да, на раскладушеах интерфейс может ломаться

**Comment by Serdobine** [comment]
@r35p3ct пофиксить и протестить разработчики не могут, потому что ни у кого нте

**Comment by r35p3ct** [comment]
> @r35p3ct пофиксить и протестить разработчики не могут, потому что ни у кого нте

В 8.54 оригинале уже стало нормально отображаться, пофиксили.

**Comment by gdlbo** [comment]
исправлено
