### ISSUE TITLE
Ошибка обновления сообщений!

### ISSUE THREAD

**Issue by Lolodd** [vtosters/lite#1514]
Не обновляются в диалогах сообщения.

При обновлении сообщений появляется ошибка запроса. Ранее такого не было

- Commit: f2ac845
- Full Version Information: main-f2ac845-dirty
- Android SDK: 33
- Product: DN2103
- Device: OP515BL1
- Board: k6893v1_64_k419
- Manufacturer: OnePlus
- Brand: OnePlus
- Model: DN2103

![Screenshot_2023-11-02-21-29-56-98_9e1a5d6211a0228d32d39446541891f1](https://github.com/vtosters/lite/assets/111492359/cf357b8b-b706-4112-8383-c7ee86b95076)

**Comment by danyyok** [comment]
Переустанови приложение/перезагрузи телефон

**Comment by Lolodd** [comment]
Ничего не помогает, перезагружал/переустанавливал..

**Comment by danyyok** [comment]
> Ничего не помогает, перезагружал/переустанавливал..

Выключи прокси(если включено) и попробуй перезайти в аккаунт(нажми на свое имя в настройках
Посмотри загрузку на m.vk.com/офвк

**Comment by Lolodd** [comment]
Прокси никогда не включал, перепробовал всё, другие моды нормально работают, а здесь беда какая-то..

**Comment by gdlbo** [comment]
исправлено, скоро будет апдейт с патчем
