### ISSUE TITLE
Отображение имени в групповых чатах

### ISSUE THREAD

**Issue by FoxInSmoke** [vtosters/lite#1515]
Предлагаю добавить функцию отображения имён над сообщениями в групповых чатах.

Это уже есть в официальной версии ВК, да и функция не особо сложная.

**Comment by Serdobine** [comment]
@FoxInSmoke сложная, потому что на той версии вк (5.56.1) этого не было. если сильно интересно, то можешь добавить сам, исходный код приложения открыт, а функция "не особо сложная"

**Comment by FoxInSmoke** [comment]
@Serdobine
