### ISSUE TITLE
Пропал опрос с надписью "вложение удалено"

### ISSUE THREAD

**Issue by Lefroel** [vtosters/lite#1516]
Пропал опрос в группе, вместо него появилось сообщение с надписью "вложение удалено", хотя на компьютере в веб версии он остался.

1. Зашёл в группу
2. Открыл опрос, чтобы посмотреть все варианты ответов
3. Высветилось окно об ошибке, и опрос пропал

Опрос не должен пропадать

**Скриншот ошибки**
![Screenshot_2023-11-03-13-13-42-71_9e1a5d6211a0228d32d39446541891f1](https://github.com/vtosters/lite/assets/46615502/c04477e8-a1c0-451e-be2a-487c5a0527b8)

Realme 9 pro+

**Comment by danyyok** [comment]
Скриншот "о приложении"

**Comment by Lefroel** [comment]
> Скриншот "о приложении"

![Uploading Screenshot_2023-11-03-15-02-18-34_9e1a5d6211a0228d32d39446541891f1.jpg…]()

**Comment by Lefroel** [comment]
> Скриншот "о приложении"

![Screenshot_2023-11-03-15-02-18-34_9e1a5d6211a0228d32d39446541891f1](https://github.com/vtosters/lite/assets/46615502/f3bd13dd-096e-41dd-96f8-3a1b5fd3de22)
