### ISSUE TITLE
Не работает прокси 

### ISSUE THREAD

**Issue by KOMPuteRSH4IK** [vtosters/lite#1517]
В последней версии приложения не работает прокси

**Comment by Serdobine** [comment]
@KOMPuteRSH4IK попробуй другой прокси. какой именно прокси не работает?

**Comment by KOMPuteRSH4IK** [comment]
Пробовал заборона, vika mobile и рандомный, ничего не работает

**Comment by KOMPuteRSH4IK** [comment]
Zaborona

**Comment by danyyok** [comment]
Пересоздайте Issue по шаблону прикрепив информацию об устройстве
