### ISSUE TITLE
При добавлении фото приложение зависает.
Ошибок не показывает.

### ISSUE THREAD

**Issue by r35p3ct** [vtosters/lite#1518]
При открытии галереи все зависает и происходит перезапуск приложения.

![Screenshot_2023-11-06-11-45-23-04_9e1a5d6211a0228d32d39446541891f1.jpg](https://github.com/vtosters/lite/assets/7328803/53608442-6af5-44a4-ad81-d9b2c8208550)

**Comment by danyyok** [comment]
Пересоздайте Issue по шаблону прикрепив информацию об устройстве
