### ISSUE TITLE
Не работает прокси zaborona.help

### ISSUE THREAD

**Issue by KOMPuteRSH4IK** [vtosters/lite#1519]
**Інформація про пристрій:** 

- Commit: f2ac845
- Full Version Information: main-f2ac845-dirty
- Android SDK: 31
- Product: gauguin_global
- Device: gauguin
- Board: gauguin
- Manufacturer: Xiaomi
- Brand: Xiaomi
- Model: M2007J17G
- Miui Version Code: 13
- Miui Version Name: V130
- Miui Version Incremental Code: V13.0.8.0.SJSMIXM
-

**Comment by danyyok** [comment]
Пересоздайте Issue по шаблону прикрепив скриншоты, доп. инф.
