### ISSUE TITLE
Ошибка обновления плейлиста "Для вас"

### ISSUE THREAD

**Issue by APerDRUG** [vtosters/lite#1520]
Каждый день слушаю музыку, но в последнее время плейлист, собранный алгоритмами "Для вас" не обновляется, хоть и написано "обновлён сегодня".возможно он реально обновляется, но содержание музыки, которую я вижу в нём, практически не изменяется.
Без понятия каким образом донести через скриншот содержание бага, но прошу исправить как нибудь
Если есть возможность то пожалуйста добавьте либо функцию для ручного обновления подобных плейлистов, либо отдельный плейлист в который можно будет обновлять и слушать рекомендации 
Все-равно Спасибо за прекрасное приложение

**Comment by danyyok** [comment]
В втлайте проблемы с отправкой прослушиваемых треков на сервера вк, соответственно плейлист не обновляется
Используйте для этого вк х - vkx.app
