### ISSUE TITLE
Проблема с сообщениями и чатами

### ISSUE THREAD

**Issue by Keigo-Takami** [vtosters/lite#1526]
Баг:
Долгая прогрузка сначала диалогов в целом,затем самого лс,а иногда может прогрузить одно сообщение и дату и пытаться "вспомнить" все то,что было перед этим.Хорошо,прогрузил,вспоснил,потратил на все минут 5.Далее отправляю сообщение,а оно исчезает.Тут сразу два варианта:либо оно отправится через минуты две-три,либо его кто-то украл и больше никто никогда не видел.

Действия:
1. Зашла в чаты
2. Сплошные загрузки и невозможность действовать из-за них

Ожидаемый результат:
Бесперебойная работа диалогов,лс и отправки сообщений.

Скриншоты:
![IMG_20231127_230204](https://github.com/vtosters/lite/assets/74225260/97c9aa2a-1228-49d4-9922-ee7097a788b3)
![Screenshot_2023-11-27-23-01-11-889_com vtosters lite](https://github.com/vtosters/lite/assets/74225260/14832ac4-00da-43d2-bc9a-c4c04d34b845)

Дополнительная информация о баге или мыслях почему оно может происходить (если есть)-Ничего сказать не могу.

Так же характеристики устройства в скриншоте (Xiaomi 12 lite):
![Screenshot_2023-11-27-23-04-20-827_com android settings](https://github.com/vtosters/lite/assets/74225260/550a080d-a71f-4ade-abe1-e02ca332f7b7)

**Comment by Keigo-Takami** [comment]
![Screenshot_2023-11-28-05-54-57-000_com vtosters lite](https://github.com/vtosters/lite/assets/74225260/c2664902-d632-4f80-805e-5daaaa592d31)

(я не знаю что такое коммит,но надеюсь это то,что нужно)

**Comment by danyyok** [comment]
Переустанови приложение/перезагрузи телефон

**Comment by gdlbo** [comment]
исправлено, скоро будет апдейт с патчем
