### ISSUE TITLE
Вылет приложения при печати сообщения

### ISSUE THREAD

**Issue by Vladnekit92** [vtosters/lite#1527]
**Опишите сам баг**
Во время обычной переписки, если останавливаюсь что бы выбрать подходящий стикер для слова, вылетает приложение. При перезаходе уже приходится заново писать и, если так же во время письма притормозить для выбора стикера, снова вылетает приложение

**Опишите действия для воспроизведения ошибки**
1. Во время письма, выбор стикера подходящего по написанному слову

**Опишите ожидаемый результат**
После перезахода в приложение, ожидалось что бага больше не будет 

**Скриншот ошибки**
Скриншота нет, так как приложение вылетает мгновенно и во время самого письма ничего визуально не происходит 

**Информация о телефоне**
На сяоми ненашёл как скопировать информацию об устройстве, возможно невнимательный, недоглядел, по этому пишу руками.
Устройство: Redmi Note 9 Pro
Прошивка: Индонезия MIUI 14 (14.0.1.0 SJZIDXM)
Андроид: 12(12 SKQ1.211019.001)
Дополнительно: Разблокирован загрузчик, есть права супер пользователя, Magisk 26.4

[VTL_log_2023-12-06.00-23-35.txt](https://github.com/vtosters/lite/files/13573139/VTL_log_2023-12-06.00-23-35.txt)

**Comment by Vladnekit92** [comment]
Хочу добавить то что на глобальной прошивке MIUI(MIUI 14.0.3.0.SJZMIXM) такого бага не было. Так же его не было и на русской прошивке MIUI(MIUI 14.0.1.0.SJZRUXM)

**Comment by mrgick** [comment]
Тоже начал появляться такой баг на таком же устройстве, но прошивка crDroid 9.2 c Magisk и разблокированным загрузчиком.
Смог воспроизвести баг при вводе слова "вот". Крашится приложение при вводе последней буквы. 
Предполагаю, что появляется какой-то особенный стикер, который и крашит приложение.

**Comment by mrgick** [comment]
Для себя пока что нашёл временное решение - отказаться от стикеров, и отключить их в всплывающем наборе https://vk.com/support/faq11996

**Comment by Vladnekit92** [comment]
Погонял обновление, баг полностью исчез. Тема закрыта
