### ISSUE TITLE
Не видна главная страница,где аватарка, всё время весит перезагрузка 

### ISSUE THREAD

**Issue by Dashuka** [vtosters/lite#1529]
![Screenshot_2023-12-13-14-04-55-108_com vtosters lite](https://github.com/vtosters/lite/assets/153729363/939b128e-fe35-4752-af97-ca036f1cab60)
**Опишите сам баг**
При обновлении новостей вылезает ошибка

**Опишите действия для воспроизведения ошибки**
1. Обновил ленту интересных новостей
2. Пролистал до конца страницы

**Опишите ожидаемый результат**
Интересная лента должна прогружать результаты

**Скриншот ошибки**

**Скопируйте сюда информацию об устройстве нажав на кнопку "Скопировать информацию об устройстве" в Настройках -> Другое и удалите этот текст**

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

**Comment by danyyok** [comment]
Легли сервера вк, скоро все наладится
