### ISSUE TITLE
Ошибка при посещении профиля пользователя и некоторых сообществ 

### ISSUE THREAD

**Issue by weixian446** [vtosters/lite#1530]
**Опишите сам баг**
При посещении профиля пользователя и некоторых сообществ появляется надпись «Ошибка загрузки» с предложением повторить, не срабатывающим.

**Опишите действия для воспроизведения ошибки**
1. Посетил профиль любого пользователя
2. Зашёл на сообщество (Некоторые сообщества загружаются исправно)
**Опишите ожидаемый результат**
Должны загрузиться все профили и сообщества 

**Скриншот ошибки**
https://ibb.co/fVJSzyx
https://ibb.co/h8Nk1dx
**Скопируйте сюда информацию об устройстве нажав на кнопку "Скопировать информацию об устройстве" в Настройках -> Другое и удалите этот текст**

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

**Comment by gdlbo** [comment]
дайте пример страницы ссылкой

**Comment by weixian446** [comment]
> дайте пример страницы ссылкой

ссылкой на страницу ВК? https://vk.com/id1

**Comment by ilanit7** [comment]
Проблема та же... 
В оригинальной версии открывается
![Screenshot_20231213-140701_VTLite](https://github.com/vtosters/lite/assets/153738162/ad0f68f9-7dc1-4603-af5c-7b83126a7e43)

**Comment by pak3935** [comment]
Аналогичная проблема, появилась сегодня утром

**Comment by Nikrodis** [comment]
Подтверждаю, проблема есть

**Comment by rzhavayalozhka** [comment]
Когда исправят проблему?? Что делать? С самого утра то же самое! 😡
