### ISSUE TITLE
Вылет приложения при просмотре стикера

### ISSUE THREAD

**Issue by Krarotus** [vtosters/lite#1537]
При просмотре стикера Чимми(или его отправлении собеседником), конкретно стикера,где над "Чимми" вылезает слово "Годнота",приложение вылетает. Код ошибки прикреплю ниже
![Screenshot_2023-12-18-11-27-34-44_b783bf344239542886fee7b48fa4b892](https://github.com/vtosters/lite/assets/55512181/cabed20b-6750-4ac3-830c-40398c7f5a4c)

**Comment by Spliterash** [comment]
+1, вылетает приложение при написании слова "годно" и пробел, стакттрейс тот же

**Comment by abslike** [comment]
@Spliterash повторяется
