### ISSUE TITLE
Ошибка обновлении ленты новостей

### ISSUE THREAD

**Issue by Banzaika** [vtosters/lite#1539]
**Опишите сам баг**
При выключенных уведомлениях приходят уведомления, как только открыть приложение

1. Открыл приложение 
2. Получил пуши

Лента уведомлений должна остаться пустой

**Comment by ayonovdenizs** [comment]
Пересоздайте issue по шаблону, прикрепив информацию об устройстве.

**Comment by Banzaika** [comment]
Xiaomi redmi note 12

**Comment by ayonovdenizs** [comment]
> Пересоздайте issue по шаблону, прикрепив информацию об устройстве.

**Comment by Banzaika** [comment]
Мне лень

**Comment by Banzaika** [comment]
> > Пересоздайте issue по шаблону, прикрепив информацию об устройстве.
> 
> 

С наступающим, ёпта! Не грусти
