### ISSUE TITLE
Ошибка установки/обновления на некоторых устройствах с Android 14

### ISSUE THREAD

**Issue by Tahgolov** [vtosters/lite#1551]
**Описание проблемы:**
Некоторые файловые менеджеры, мессенджеры, соц. сети или иное ПО, способное выполнять установку приложений, например, MT Manager или NekoGram не могут установить APK-файл клиента на определённых устройствах с Android 14.

**Воспроизведение:**

1. Попытаться установить APK-файл из подобного приложения на устройстве с Android 14.

**Ожидаемый результат:**
Баг должен быть незамедлительно исправлен, в противном случае пользователи банально не смогут нормально обновляться.

**Демонстрация ошибки**

https://github.com/vtosters/lite/assets/152777508/cfef650f-dd8d-48d4-ae28-46ab260980e1

**Информация об устройстве:** 
- Commit: 3068ff7
- Full Version Information: main-3068ff7-dirty
- Android SDK: 34
- Product: bluejay
- Device: bluejay
- Board: bluejay
- Manufacturer: Google
- Brand: google
- Model: Pixel 6a

**Дополнительная информация:**
Проблема возникает из-за слишком большого разрешения графического файла внутри самого APK-файла. Выяснилось это путём удаления атрибута [`android:icon`](https://developer.android.com/guide/topics/manifest/application-element#icon) из AndroidManifest. Решение достаточно простое и очевидное - уменьшить разрешение проблемного файла. Подобный баг уже наблюдался и был исправлен здесь: https://github.com/uazo/cromite/issues/595

**Comment by gdlbo** [comment]
а если падает, то как показывать icon

**Comment by Tahgolov** [comment]
> а если падает, то как показывать icon

Надо просто уменьшить разрешение файла, вроде это ресурс `vt_adaptive_launcher_foreground`. Но, справедливости ради, добавленных графических файлов с большим разрешением, чем нужно, которые используются как иконки, там ещё хватает. Так что я бы рекомендовал также сделать их обработку.
