### ISSUE TITLE
Долгая или бесконечная загрузка чатов и сообщений

### ISSUE THREAD

**Issue by MrNayz** [vtosters/lite#1552]
При заходе в сообщения или чаты

1. Зашёл в приложение
2. Перешёл во вкладку сообщения
3. Нажал на диалог

Исправление

![Screenshot_2024-01-28-12-54-33-117_com vtosters lite](https://github.com/vtosters/lite/assets/123476723/093fcec6-0504-451e-a01e-4f5d1d7c0343)

Лог ошибки
[VTL_log_2024-01-28.11-13-56.txt](https://github.com/vtosters/lite/files/14075542/VTL_log_2024-01-28.11-13-56.txt)

**Comment by Wperdex** [comment]
@MrNayz 1) Установлены ли обои чатов?

2) Пробовал переустановку начисто _(удалить и скачать заново)_?

**Comment by MrNayz** [comment]
1. Обои не устанавливал
2. Пробовал, проблема либо сразу, либо через несколько дней начинает беспокоить опять воскресенье, 28 января 2024г., 12:59 +03:00 от Wperdex  ***@***.*** :

**Comment by gdlbo** [comment]
исправлено, скоро будет апдейт с патчем
