### ISSUE TITLE
Проблемы с читаемостью при включении AMOLED режима в настройках кастомной прошивки

### ISSUE THREAD

**Issue by blwckcore** [vtosters/lite#1556]
**Опишите сам баг**
При включении "чистого черного цвета" в настройках темной темы кастомной прошивки (например, VoidUI или CrDroid), серый текст в VTLite становится трудночитаемым. Я бы не стал репортить это, если бы остальные приложения тоже работали бы криво с этой настройкой, но нет. Что гугловские, что пользовательские приложения (например, exteraGram, VK Equals, Dolphin) работают с этой функцией нормально и не имеют проблем с читаемостью.

**Опишите действия для воспроизведения ошибки**
1. Включить "Совершенно черный" в настройках темной темы кастомной прошивки.
2. Включить Monet в VTLite.
**Скриншот ошибки**
![Screenshot_20240209-183532_VTLite](https://github.com/vtosters/lite/assets/107321994/34c70d5f-d4a3-4539-bc5a-adaa2fc12e69)
![Screenshot_20240209-183611_VTLite](https://github.com/vtosters/lite/assets/107321994/051e4152-1415-43b9-8896-81c977a152c9)
![Screenshot_20240209-183521_VTLite](https://github.com/vtosters/lite/assets/107321994/31ffe961-e1de-4ff6-a06a-9928df8eacbb)

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**
Скорее всего "совершенно черный" режим меняет цвет в палитре Monet, который VTLite использует для серого текста на слишком темный. Пофиксить, думаю, можно просто форсировав серый цвет, вместо использования палитры. Либо же, при включении ползунка AMOLED со включенным ползунком Monet начинать использовать другой цвет для серого цвета, либо опять же форсировать серый цвет, но только для этого режима. Не знаю, поможет ли это вам, но вот скрин палитры с включенным совершенно черным режимом.
![Screenshot_20240209-184711_Material You Colors](https://github.com/vtosters/lite/assets/107321994/8763e19e-dd39-4b42-9445-cf24fd915608)

**Comment by blwckcore** [comment]
Также, как очень простое решение: просто брать самый главный акцент из Monet темы устройства и просто создавать AMOLED тему на основе уже встроенного редактора тем. То есть, это будто бы я сам нашел акцентный цвет в системе, зашёл в настройки приложения, зашёл в раздел "внешний вид", нажал на "Цвет акцента" и туда поставил тот самый акцентный цвет системы. Можно включать эту "искусственную" тему опять же при включении обоих ползунков "Monet" и "AMOLED".

**Comment by gdlbo** [comment]
ты долбаеб

**Comment by blwckcore** [comment]
> ты долбаеб

схуяли

**Comment by abslike** [comment]
@blwckcore поддержка подобной хуйни ни одним разработчиком не продумана, за этот баг ручаешься ты сам
