### ISSUE TITLE
Нет меню реакций при зажатии лайка

### ISSUE THREAD

**Issue by Kimen-no-Yami** [vtosters/lite#1558]
При попытке вызвать выбор реакций при зажатии лайка ничего не происходит. Только лайк ставится и всё.

Информация об устройстве: 

- Commit: 2a85b3a
- Full Version Information: main-2a85b3a-dirty
- Android SDK: 29
- Product: MAR-LX1HRU
- Device: HWMAR
- Board: MAR
- Manufacturer: HUAWEI
- Brand: HONOR
- Model: MAR-LX1H
- Emui Version: EmotionUI_12.0.0

**Comment by Serdobine** [comment]
@Kimen-no-Yami втлайт основан на версии 5.56.1, реакций тогда не было и в помине
