### ISSUE TITLE
Ошибка скачивания музыки/создания логов

### ISSUE THREAD

**Issue by BiSMORCK** [vtosters/lite#1565]
Музыка в mp3 не скачивается. Специально для gbldo: инструкция по логам проверена и выполнена , ЛОГИ НЕ СОЗДАЮТСЯ.

Музыка: 
1.Нажимаешь скачать
2. Приложение делает вид, что скачивает, всё как задумано
3. Файлов нет. Даже папки по пути VK/Music нет

Логи: 
1. Выполнено по инструкции в тг (запись API включена, запись лога нажата)
2.  Вылетов при ошибке нет. 
3. Принудительное завершение по инструкции + всеми видами (системное меню устройства, меню "разное" приложения, меню "для разработчиков") эффекта не даёт - окно логов отсутствует, файл лога по пути VK/Download [во внутренней памяти т.к. карты памяти у меня вообще нет] отсутствует)

Информация об устройстве:

Commit: cf17ed6
Full Version Information: main-cf17ed6-dirty
Android SDK: 33
Product: a52sxqxx
Device: a52sxq
Board: lahaina
Manufacturer: samsung
Brand: samsung
Model: SM-A528B
OneUi Major Version: 5
OneUi Minor Version: 1.0

**Comment by gdlbo** [comment]
проверь это https://t.me/vtosterschat/3499552/3558897

**Comment by BiSMORCK** [comment]
Бета версия - без изменений, ни лога, ни музыки
Релизная (которая только что появилась) - тоже самое

**Comment by BiSMORCK** [comment]
Не знаю, что внезапно изменилось (единственное, что у телефона было с момента последнего коммента - провал в связи, инета 2 минуты не было), но музыка скачиваться начала. Бред какой-то, ну да ладно. Вопрос пока закрыт.
