### ISSUE TITLE
не обновляется приложение

### ISSUE THREAD

**Issue by minolin228** [vtosters/lite#1567]
при в ходе в приложение высвечивается табличка обновить, обновляю, загружается обновление, нажимаю на установленную загрузку перекидывает в файлы и просто загруженный апк файл с которым никак не удается взаимодействовать, захожу в приложение снова высвечивается табличка обновление.. и так несколько раз 
возможно дело в телефоне но сомневаюсь ведь обновление грузит, антивирус выключен, все вроде должно загружать(?) впервые с таким сталкиваюсь вообще, может дело действительно в каком-то баге? 
давно уже пользуюсь этим приложением все работало все нравилось

**Comment by gdlbo** [comment]
обнови через сторонний проводник, miui (Xiaomi) сломали установщик и думают что ты каждый раз один и тот же апк ставишь
