### ISSUE TITLE
Несуществующие уведомления

### ISSUE THREAD

**Issue by nucocEHoTa** [vtosters/lite#1568]
Непонятно, куда пропадают бизнес-уведомления, в пуш окне всплывает, а в приложении нет

**Опишите действия для воспроизведения ошибки**
1. Всплыло пуш бизнес-уведомление - нажал
2. Открылось приложение, но просто на ленте новостей
3. В уведомлениях придожения не отображается
**Опишите ожидаемый результат**
Должно открыться уведомление

Телефон: SM-F711U1
One UI 6
Android 14

Наверно не воспринимает бизнес-уведомление как уведомление, после просмотра, уведомления нет и в пк версии

**Comment by abslike** [comment]
@nucocEHoTa свайпни вверх в разделе сообщений
