### ISSUE TITLE
Открываются несколько приложений

### ISSUE THREAD

**Issue by taymatyrg** [vtosters/lite#1569]
При отправке файла с помощью поделитсья, приложение открывается ещё раз.

1. Отправляю файл с помощью поделиться
2. Выбираю VTLite
3. Нажимаю отправить сообщением
И после этого открывается ещё один VTLute и повторив откроется ещё один и т.д
![Screenshot_2024-02-23-03-54-00-033_com miui home](https://github.com/vtosters/lite/assets/52503665/b67a7cd1-1532-4dbe-8578-0e562e154be4)

устройство: Redmi Note 10 Pro, MIUM 14.0.2

Раньше на официально клиенте была такая же проблема, но сейчас там изменили меню выбора кому отправить на всплывающее и это частично решило проблему.

**Comment by gdlbo** [comment]
проблема прошивки
