### ISSUE TITLE
Не открывается плейлист кешированной музыки

### ISSUE THREAD

**Issue by Zapadlo1337** [vtosters/lite#1570]
При попытке открыть плейлист, приложение зависает на 10-15 секунд, после вылетает

**Comment by Zapadlo1337** [comment]
> нужна лог ошибок из уведомлений, будем разбираться

Уведомления нет, просто вылетает и всё

**Comment by gdlbo** [comment]
сколько у вас загружено песен в кеш

**Comment by Zapadlo1337** [comment]
> сколько у вас загружено песен в кеш

430

**Comment by gdlbo** [comment]
у вас загружены только свои песни?

**Comment by Zapadlo1337** [comment]
Свои это только те которые у меня в музыке?

**Comment by gdlbo** [comment]
которые закешированы

**Comment by Zapadlo1337** [comment]
Ну закешированы вроде бы только мои, чужих нет
