### ISSUE TITLE
Не работает галерея в чатах.

### ISSUE THREAD

**Issue by Vesu-VI-us** [vtosters/lite#1573]
При попытке отправить фотографию или видео из галереи в чат не загружаются данные из неё, однако, приложение альбомы видит.

**Опишите действия для воспроизведения ошибки**
1. Открыть диалог;
2. Нажать кнопку "прикрепить".

**Опишите ожидаемый результат**
Видны фотографии из галереи.

**Скриншот ошибки*
![Screenshot_20240226-185612_VTLite](https://github.com/vtosters/lite/assets/161345384/fde1f34b-0cac-4df4-b7a3-85bdc4042d1e)
![Screenshot_20240226-185620_VTLite](https://github.com/vtosters/lite/assets/161345384/0ec29ff8-c351-4a28-910e-ecbe94d0a789)

**Информация об устройстве:** 

- Commit: 8959558
- Full Version Information: main-8959558-dirty
- Android SDK: 30
- Product: a50xser
- Device: a50
- Board: exynos9610
- Manufacturer: samsung
- Brand: samsung
- Model: SM-A505FN
- OneUi Major Version: 3
- OneUi Minor Version: 1.0

**Comment by abslike** [comment]
30239 фото, подождать стоит, ну совсем чуть-чуть...
