### ISSUE TITLE
Шифрование на основе ключей или пароля

### ISSUE THREAD

**Issue by Spp595** [vtosters/lite#1576]
Хотелось бы иметь функции шифрования на основе пароля либо ключа. В настройках указываешь и у тех людей которые ввели такой же ключ, пароль сообщение шифруются и дешифруется.
Сейчас кто угодно у кого есть vtlite может сообщения шифрованные прочитать.

**Comment by abslike** [comment]
@Spp595

**Comment by abslike** [comment]
выбираешь тип шифрования Vtosters Aes и вписываешь свой ключ ещё одним открытием
![Uploading Screenshot_20240301-010223.png…]()

**Comment by Spp595** [comment]
Спасибо, не знал)
