### ISSUE TITLE
Фоновый процесс

### ISSUE THREAD

**Issue by Moschimooschi** [vtosters/lite#1582]
Я хотел бы чтобы приложение всегда было открыто в фоновом процессе и когда я из него выходил бы в другое приложение, потом обратно заходил через большое количество времени всё так же быстро открылось и работало. Кстати музыка ещё чтобы оставалась та же, а не отключалась. Жду вашего ответа)

**Comment by ayonovdenizs** [comment]
dontkillmyapp.com
