### ISSUE TITLE
Ошибка загрузки вкладки музыки

### ISSUE THREAD

**Issue by Niga454** [vtosters/lite#1595]
**Опишите сам баг**
Не грузит страница музыки(бесконечная загрузка)

**Опишите действия для воспроизведения ошибки**
1. Зашел в веладку "музыка"
2. Бесконечная загрузка
**Опишите ожидаемый результат**
Хочу послушать музыку (я меломан) 

![Screenshot_2024-03-29-02-14-41-563_com vtosters lite](https://github.com/vtosters/lite/assets/165338459/465e7421-a281-4930-823a-50fe13c215ca)
 
Poco m4 pro 5G

**Comment by sunmisc** [comment]
https://github.com/vtosters/lite/issues/1592
