### ISSUE TITLE
Ошибка при воспроизведении музыки

### ISSUE THREAD

**Issue by m4rsh1k** [vtosters/lite#1598]
При включении любой музыки вылезает ошибка 

1. Включить трек

**Опишите ожидаемый результат**
Музыка должна воспроизводиться

**Скриншот ошибки**
![IMG_20240330_091743](https://github.com/vtosters/lite/assets/165457826/2424a188-5733-4861-8e9c-1867afe49134)

 Xiaomi Mi Note 10

**Comment by gdlbo** [comment]
нет информации об устройстве как написано в отправке issue
