### ISSUE TITLE
Некорректное значение счётчика аудиозаписей.

### ISSUE THREAD

**Issue by Exordio** [vtosters/lite#1599]
Счётчик аудиозаписей при количестве аудио больше 10 тысяч, показывает некорректное число. (Жесткий лок на 10к)

Для воспроизведения, нужно добавить 10к аудио и посмотреть что показывает счётчик :) 

Хотелось бы увидеть корректное количество аудио.
![image](https://github.com/vtosters/lite/assets/45700369/b4d526d0-88ff-4eff-af51-1758170e1dcc)

Информация об устройстве: 

- Commit: b202308
- Full Version Information: main-b202308-dirty
- Android SDK: 33
- Product: sweet_ru
- Device: sweet
- Board: sweet
- Manufacturer: Xiaomi
- Brand: Redmi
- Model: M2101K6G
- Miui/HyperOS Version Code: 14
- Miui/HyperOS Version Name: V140
- Miui Version Incremental Code: V14.0.2.0.TKFRUXM

**Comment by Exordio** [comment]
Хотя думается мне что это проблема самого VK, потому как если посмотреть с другой страницы - сколько у человека записей. Показывает так же 10к. Я напишу в поддержку, может ответят.

![image](https://github.com/vtosters/lite/assets/45700369/4128dc40-7bae-4433-b181-979035662f75)

**Comment by Serdobine** [comment]
@Exordio у вк лимит на 10к. если волшебным образом сделал больше, то молодец, но апи не покажет больше 10к
