### ISSUE TITLE
Улучшение голосовых сообщений

### ISSUE THREAD

**Issue by Death228** [vtosters/lite#1605]
**Опишите вашу идею максимально подробно и понятно**
Необходима функция улучшения голосовых сообщений. Она значительно улучшит запись голосовых сообщений и собеседнику будет лучше слышно меня

**Опишите возможное решение/реализацию функции (если понимаете как это можно реализовать на Java/C++)**

**Остальные мысли о предложенной функции**

**Comment by Serdobine** [comment]
@Death228 присутствует по умолчанию. если сравнивать с оригинальнвм вк, то в втлайте битрейт голосовых во много раз выше
