### ISSUE TITLE
Есть ли возможность добавить в видеоплеер встроенный - функционал поделиться с устройством (Chromecast)

### ISSUE THREAD

**Issue by hardcorp74** [vtosters/lite#1606]
Есть ли возможность добавить в видеоплеер встроенный - функционал поделиться видео с устройством (Chromecast).
Например как это работает в текущей версии актуального устройства, иногда удобно начать просмотр на телефоне, а потом его отправить на экран ТВ/ТВ-приставки.

**Comment by gdlbo** [comment]
Chromecast полностью платная и проприетарная функция, смотри видео через внешний плеер как VLC (или другие плееры с хромкастом) и уже через него можно хромкаст использовать
