### ISSUE TITLE
Не грузит ленту новостей после запуска приложения 

### ISSUE THREAD

**Issue by M228a** [vtosters/lite#1612]
**Опишите сам баг**
При обновлении новостей вылезает ошибка

**Опишите действия для воспроизведения ошибки**
1. Обновил ленту интересных новостей
2. Пролистал до конца страницы

**Опишите ожидаемый результат**
Интересная лента должна прогружать результаты

**Скриншот ошибки**

**Скопируйте сюда информацию об устройстве нажав на кнопку "Скопировать информацию об устройстве" в Настройках -> Другое и удалите этот текст**

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

**Comment by danyyok** [comment]
Пересоздайте Issue по шаблону прикрепив информацию об устройстве.

**Comment by vlasovsani** [comment]
Шо, так и нет решения проблемы? 
У меня просто в один момент отвалились новости. Время них картинка с девушкой и кнопка с предложением найти интересные новости... Хотя раздел Интересное робит без проблем.
![IMG_20240523_190039](https://github.com/vtosters/lite/assets/170647846/d667af29-9ef0-4c64-abf8-7b58af9dd007)

**Comment by M228a** [comment]
Нет также все иногда может погрузить и все

чт, 23 мая 2024 г., 18:02 vlasovsani ***@***.***>:

**Comment by Serdobine** [comment]
@vlasovsani вконтакте что-то меняют по полной, а старушка 5.56.1 не в силах это вывезти. у многих отвал новостей и музыки.

**Comment by M228a** [comment]
Пипец конечно не с музыкой вроде нечего нормально все

чт, 23 мая 2024 г., 18:04 Serdobine ***@***.***>:
