### ISSUE TITLE
Ошибка обновлении диалогов

### ISSUE THREAD

**Issue by Loli-Kross** [vtosters/lite#1615]
**Опишите сам баг**
При попытке открытия сообщений бесконечная загрузка

**Опишите действия для воспроизведения ошибки**
1. Обновил диалоги
2. Открыл приложение 

**Опишите ожидаемый результат**
Диалоги должны прогиужаться с хорошей скоростью
![Screenshot_20240508-082605](https://github.com/vtosters/lite/assets/76477541/9644b805-0d5c-4481-8c9c-01b061253d49)

**Скриншот ошибки**

**Скопируйте сюда информацию об устройстве нажав на кнопку "Скопировать информацию об устройстве" в Настройках -> Другое и удалите этот текст**

**Comment by Inhuma** [comment]
Та же самая проблема, вдобавок,если прогружаются диалоги,не отображаются сообщения кроме нескольких последующих,не отображается статус онлайна собеседников

**Comment by Serhiomon** [comment]
Присоединяюсь к проблеме. Оповещения о новых сообщениях приходят, но сами сообщения в приложении не грузятся. Загрузка приходящих сообщений происходит только спустя несколько перезапуском.

**Comment by gdlbo** [comment]
честно говоря идей по решению нет, проект фактически EOL + нет возможности почекать 

если будет какой-то умелец что посмотрит - будет класс, а так печально что мессаджи отвалились

**Comment by Loli-Kross** [comment]
Не следила за веткой ответов, но у меня на след день все наладилось
Всем спасибо большое ✨

чт, 9 мая 2024 г., 01:00 Artur Skubei ***@***.***>:
