### ISSUE TITLE
Баг с перемешиванием музыки 

### ISSUE THREAD

**Issue by Milanasa** [vtosters/lite#1622]
**Опишите сам баг**
При перемешивании всей своей музыки для прослушивания в случайном порядке воспроизводится не вся музыка, а её часть. То есть, из моих 500 с чем то треков воспроизводится около 30-40 и они зацикливаются, а остальные игнорируются, пока заново не перемешаю.

**Опишите действия для воспроизведения ошибки**
1. Перемешал музыку
2. Слушаю каждый трек, пока не дойду до первого
3. Снова перемешиваю музыку
4. Слышу уже другие треки

**Опишите ожидаемый результат**
Должна воспроизводится вся музыка, а не только её часть.

**Скриншот ошибки**
Как это показать???

Samsung A14 ОЗУ 4Gb

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**
Думаю что при перемешивании треки в случайном порядке добавляются в список, который или ограничен по размеру, или список превышает лимиты памяти для одного пользователя на сервере? На самом деле вообще без понятия.

**Comment by Milanasa** [comment]
Я не знаю, как выстроена ваша инфраструктура, но думаю решением проблемы будет передавать пользователю случайный трек, как только он дослушает предыдущий. То есть, не хранить в памяти, какие треки выбраны случайно, а генерировать на ходу, какой трек следующий

**Comment by danyyok** [comment]
@Milanasa Попробуйте прогрузить весь плейлист, либо нажать кнопку "показать все" в библиотеке, запустить трек а далее включить перемешивание
