### ISSUE TITLE
Невозможно просмотреть информацию удалённых аккаунтов

### ISSUE THREAD

**Issue by weixian446** [vtosters/lite#1625]
**Опишите сам баг**
При нажатии на удалённый, заблокированный или замороженный аккаунт вылезает «Ошибка загрузки».

**Опишите действия для воспроизведения ошибки**
1. Нажал на аккаунт заблокированного пользователя

**Опишите ожидаемый результат**
При нажатии на удалённый, заблокированный или замороженный аккаунт должна появиться причина удаления, блокировки или заморозки.

**Скриншот ошибки**
![Screenshot_2024-06-22-12-29-29-501_com vtosters lite](https://github.com/vtosters/lite/assets/153734543/bd10c419-523a-4a03-883d-85df03c39630)

**Информация об устройстве:** 

- Commit: f39463f
- Full Version Information: main-f39463f-dirty
- Android SDK: 34
- Product: mondrian_ru
- Device: mondrian
- Board: taro
- Manufacturer: Xiaomi
- Brand: POCO
- Model: 23013PC75G
- Miui/HyperOS Version Code: 816
- Miui/HyperOS Version Name: V816
- Miui Version Incremental Code: V816.0.3.0.UMNRUXM

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**
Вероятно, из-за обновлений самого ВК

**Comment by gdlbo** [comment]
баг вк
