### ISSUE TITLE
VTL крашится при зажатии стикера, чтобы его увеличить.

### ISSUE THREAD

**Issue by Abragadabra** [vtosters/lite#163]
При зажатии стикера, чтобы увеличить VTL крашится, вот [лог](https://foxbin.f0x1d.com/nobdXZ5kht).
https://user-images.githubusercontent.com/77795206/163709324-09c63e6a-9164-42db-a0cd-5db5d47242e0.mp4

**Comment by gdlbo** [comment]
https://github.com/vtosters/lite/issues/5
