### ISSUE TITLE
Создание lsposed модуля

### ISSUE THREAD

**Issue by develux44** [vtosters/lite#1642]
Легче поддерживать lsposed модуль, чем каждую новую версию вк пересобирать приложение (мне так кажется хз)

https://github.com/LSPosed/LSPosed и https://api.xposed.info/reference/packages.html в помощь

**Comment by abslike** [comment]
@develux44 АХАХАХАХХАХАХАХПХПХАХАХАХАХАХХАХП

**Comment by k1zn** [comment]
VTLite никто и не пересобирает, он с самого начала на старой версии
