### ISSUE TITLE
Ссылки не выделяются цветом и сливаются с текстом

### ISSUE THREAD

**Issue by Slimer91** [vtosters/lite#165]
![IMG_20220418_095751](https://user-images.githubusercontent.com/56431193/163769190-1a77b64b-4ffd-4047-b7c2-9969144ff195.jpg)
![IMG_20220418_095815](https://user-images.githubusercontent.com/56431193/163769304-957a2954-e055-4ab9-a9b3-29a55b0ff2ec.jpg)

**Comment by Wperdex** [comment]
Дополняю.
Сливаются с текстом также хэштеги, гиперссылки на имена людей при комментировании и шестерня на светлой теме. Шрифты в втл явно требуют жёстких фиксов, с ними оч много багов
![IMG_20220419_010513](https://user-images.githubusercontent.com/102802937/163884999-246d953b-47a4-469f-b9ad-49db2d8ada9e.jpg)
