### ISSUE TITLE
Ошибка обновления поста с опросом

### ISSUE THREAD

**Issue by jkinaru** [vtosters/lite#1652]
**Баг:**
При обновлении поста с опросом проценты проголосовавших смещаются влево.

**Действия для воспроизведения ошибки:**
1. Открыла (созданный мной) опрос постом в сообществе
2. Обновила страницу

**Ожидаемый результат:**
Смещения элементов не должно происходить

**Запись ошибки (видео):**

https://github.com/user-attachments/assets/ebd3e0e0-9941-411d-bf96-eab149920527

**Скриншоты ошибки:**
![Screenshot_20240923_032451_VTLite](https://github.com/user-attachments/assets/dc007338-6f5a-4e85-9fbf-9ca8a0f8d333)

![Screenshot_20240923_032456_VTLite](https://github.com/user-attachments/assets/df0cdb3e-177b-460b-9975-c458985df6d0)

![Screenshot_20240923_032500_VTLite](https://github.com/user-attachments/assets/54374af5-aef5-4ea4-b315-d9d2f1f05c92)

**Samsung S10 Lite | Версия Android 13**

**"О приложении":**

![Screenshot_20240923_031421_VTLite](https://github.com/user-attachments/assets/9709f7f7-5e42-4e72-ad41-989f63508322)

**Comment by jkinaru** [comment]
**Информация об устройстве:** 

- Commit: 93edbf2
- Full Version Information: main-93edbf2-dirty
- Android SDK: 33
- Product: r5qnaser
- Device: r5q
- Board: msmnile
- Manufacturer: samsung
- Brand: samsung
- Model: SM-G770F
- OneUi Major Version: 5
- OneUi Minor Version: 1.0

**Comment by jkinaru** [comment]
Upd. 
Тот же баг со смещением происходит и без открытия поста - например, если опрос есть в ленте и попадает в область видимости.

**Comment by gdlbo** [comment]
к сожалению не исправить баг с показом статистики опросов без голоса в опросе, визуальный и некритичный
