### ISSUE TITLE
Загружаются не все диалоги

### ISSUE THREAD

**Issue by rustzz** [vtosters/lite#17]
Показываются 7 диалогов и в конце списка бесконечная загрузка

**Comment by gdlbo** [comment]
Нужно видео + логи

**Comment by MgmtLkv** [comment]
Столкнулся с похожей проблемой. После запуска приложения первое же, что бросилось в глаза - бесконечно грузятся диалоги, при этом уведомления приходят и в чаты можно зайти либо через странички друзей, либо открыть уведомление. После этого чао появляется в списке, но остальных нет.
![Screenshot_20220326-184720_VTLite](https://user-images.githubusercontent.com/102426866/160247626-77f4e084-c99b-4a94-beaa-0d2775fd6a98.png)

**Comment by shizotoaster** [comment]
Такая же проблема, логи здесь: https://pastebin.com/WghtZeRc

**Comment by rustzz** [comment]
> Такая же проблема, логи здесь: https://pastebin.com/WghtZeRc

спасибо, после ответа разраба занят был
