### ISSUE TITLE
В 0.13 сломали опцию Покрасить панель навигации

### ISSUE THREAD

**Issue by newspeednova** [vtosters/lite#170]
Покрасить панель навигации в 0.13 не реагирует на ползунок вкл/выкл и всегда "покрашена"(белые кнопки на белой панели). До этого в положении выкл, она становилась черной.

**Comment by gdlbo** [comment]
https://github.com/vtosters/lite/commit/78432057caecc982a53bedaf02eedc8c4fdb8db6
