### ISSUE TITLE
Ошибка призагрузке видео в ленте

### ISSUE THREAD

**Issue by Ilya19911** [vtosters/lite#172]
Почти все видео, котрые открываю в ленте новостей не проигрываются, пишет произошла ошибка.
![Screenshot_20220423-122411_VTLite](https://user-images.githubusercontent.com/104249926/164885226-f42fd8a2-3176-4230-9006-bd6dd5640aa6.jpg)

**Comment by gdlbo** [comment]
https://github.com/vtosters/lite/issues/19
