### ISSUE TITLE
фикс интерфейса

### ISSUE THREAD

**Issue by b3rgg** [vtosters/lite#176]
Съезжают пропертис блока с комментарием (иногда нормально, но чаще всего - так)

![dgsdfds1](https://user-images.githubusercontent.com/94761521/164975259-ae6dabf5-fe85-40fd-90ec-f9407b55fd4a.png)

При выключении настройки "Хвосты сообщений" не все хвосты убираются (иногда при отправке картинок, ответов на сообщения, пересылки сообщений)

![fgsdsdf2](https://user-images.githubusercontent.com/94761521/164975829-ba4e8945-7da9-404f-b76e-99732131eabc.jpg)

При выключении "округлении чисел" числа все равно округляются 

баг или фича?

![fgdfgdfgdf](https://user-images.githubusercontent.com/94761521/164976194-d62b987b-4790-4b79-b671-a0a3eb918354.png)

Будет ли добавлен выбор основного цвета как в vk next/vk tosters ?

Добавление настройки переключения шрифта VK Sans и системного шрифта (сейчас в vtl одновременно 2 используются, VK Sans используется в тексте постов, VKid, редактирование страницы, приватность, активировать промокод, кол-во друзей, подписчиков, а все остальное - системный)

**Comment by gdlbo** [comment]
1. Фиксить баги с поплывшим интерфесом крайне сложно со стороны реверсинга, я конечно посмотрю но сомневаюсь что что-то сделаю
2. Думаю в вк нет макетов под пикчи без хвоста
3. Прикрепил пикчи, работает
4. Тебе в issue по темной теме, она в закрепе и я читаю её
5. Не планирую, инжектинг таких вещей сильно грузит аппу и проц (ибо делается костылями дичайшими)

![photo_2022-04-24_19-48-37](https://user-images.githubusercontent.com/41114720/164987227-2702fb20-6237-4a01-aad0-60f1a43c8e78.jpg)
![photo_2022-04-24_19-48-43](https://user-images.githubusercontent.com/41114720/164987230-914b2f21-d550-4e16-b46d-2c27633a9fca.jpg)
