### ISSUE TITLE
Покраска темной и AMOLED тем на "планшетной" версии приложения 

### ISSUE THREAD

**Issue by michael555444** [vtosters/lite#178]
При использовании приложения на планшетах или на 600+ DPI покраска отсутствует перекраска интерфейса, либо неправильная
![Screenshot_2022-04-24-19-59-01-268_com.vtosters.lite.jpg](https://user-images.githubusercontent.com/33288939/164987840-9619f3ec-028c-4ecd-a9eb-6e8095a16d45.jpg)

**Comment by k1zn** [comment]
@gdlbo @aliveoutside удаляйте это из todo, исправлено с 0.4.0

**Comment by gdlbo** [comment]
> @gdlbo @aliveoutside удаляйте это из todo, исправлено с 0.4.0

Поч если так же фигово красится

**Comment by michael555444** [comment]
@gdlbo, ну почему, без границ, конечно, но все же AMOLED
![](https://user-images.githubusercontent.com/33288939/180966209-25706623-f146-4420-a9e5-877ddb6f6891.jpg)
