### ISSUE TITLE
Не работает жест быстрого ответа на сообщение

### ISSUE THREAD

**Issue by Lxiv-64** [vtosters/lite#180]
При жесте выбора сообщения для быстрого ответа (свайп по сообщению влево) нечего не происходит. При этом, если выделить сообщение и нажать на кнопку ответа в строке действий, всё корректно отрабатывает.

**Comment by Lxiv-64** [comment]
Сначала демонстрация нормальной работы в полной версии, затем в lite. 
https://photos.app.goo.gl/uPmzToegGz4TZNof6

**Comment by gdlbo** [comment]
https://github.com/vtosters/lite/issues/62
