### ISSUE TITLE
Отсуствие вкладки VK Donut

### ISSUE THREAD

**Issue by XanoodlesThaBat** [vtosters/lite#186]
Вот так было в vtosters
![image](https://user-images.githubusercontent.com/65135635/165187055-89263f4d-afd9-4326-be12-49d00cfea92b.png)
А это vtosters lite
![image](https://user-images.githubusercontent.com/65135635/165187085-f2eaf160-fe54-4c6a-ae8f-4c53ec5e66a7.png)
А где?

**Comment by gdlbo** [comment]
В 2019 году вк донута не было

**Comment by XanoodlesThaBat** [comment]
Т .е. в vtosters lite не добавите?

**Comment by gdlbo** [comment]
нет
