### ISSUE TITLE
Шрифт. Снова. Светлая тема 

### ISSUE THREAD

**Issue by Wperdex** [vtosters/lite#188]
![IMG_20220426_144252](https://user-images.githubusercontent.com/102802937/165292912-3b21fe3d-18ca-416c-8646-2bd27b810bfc.jpg)
![IMG_20220426_144324](https://user-images.githubusercontent.com/102802937/165292924-8a8bc1c1-e04e-4e03-8b97-94bd2aa4f170.jpg)

**Comment by gdlbo** [comment]
https://github.com/vtosters/lite/commit/afc2a5b25800ca3faee84b95f9243363415a80ef
