### ISSUE TITLE
Не хватает фич при добавлении в беседу

### ISSUE THREAD

**Issue by Wperdex** [vtosters/lite#189]
В ВТЛ не хватает следующих фич при приглашении юзера в конфач:
![IMG_20220426_151238](https://user-images.githubusercontent.com/102802937/165299029-277205bb-ad00-41f9-b505-a7531cc646c2.jpg)
![IMG_20220426_151212](https://user-images.githubusercontent.com/102802937/165299040-8e3dc242-1b21-4ebd-ac72-dd5a26f5f57d.jpg)

1) В ВПоп Лайте чела выкидывает сразу при прожатии крестика. В чуть более актуальных версиях ВК уточняет моё желание кика. Не столь важная хрень (не важнее следующей фичи точно), но всё же.
2) Показ последних 250 сообщений приглашаемому, да. Оч нужная фича, надеюсь ты вонтфикс не повесишь

**Comment by k1zn** [comment]
@aliveoutside @gdlbo эта фича есть в VTLite

![](https://user-images.githubusercontent.com/46452865/181789652-9dac5db2-e539-434e-9e7b-d17e4782e5f3.png)
