### ISSUE TITLE
Проблемы загрузки видео в ленте/сообщениях

### ISSUE THREAD

**Issue by fareeder** [vtosters/lite#19]
https://user-images.githubusercontent.com/96731321/160184224-2a5af0c2-54ce-4860-bcca-9f51e59bc506.mp4

**Comment by gdlbo** [comment]
Вк может отдавать видео в неподдерживаемом формате, поэтому это не фиксится по крайней мере сейчас

**Comment by gdlbo** [comment]
Похоже проблема связана с региональными CDN серверами ВКонтакте

Список всех серверов (их поддоменов включая региональные)
https://pastebin.com/pYGeKN5b

Нужно обрабатывать региональные цдн ссылки для отображения видео

**Comment by KMatsko** [comment]
У меня на телефоне стоят одновременно VT и VTLite (были все версии с первой до текущей, 19) - VTLite не грузит видео в ленте (100% не загрузит, если видео в посте одно и начинает автоматически воспроизводиться). Если видео несколько, то часть воспроизводится, часть нет). В VT указанной проблемы нет.
