### ISSUE TITLE
Появилась реклама и не полная смена шрифта. 

### ISSUE THREAD

**Issue by userskill** [vtosters/lite#193]
Обновил на последнюю. И появилась реклаиа ![IMG_20220427_155700.jpg](https://user-images.githubusercontent.com/73518754/165504279-e497f31e-1f54-4941-a4db-e04c6c15b442.jpg)
![Screenshot_2022-04-27-15-57-24-35_9e1a5d6211a0228d32d39446541891f1.jpg](https://user-images.githubusercontent.com/73518754/165504372-7ed01b7f-a69e-47a4-bf47-1cc5c979a193.jpg)
Шрифт 
![Screenshot_2022-04-27-16-00-54-40_9e1a5d6211a0228d32d39446541891f1.jpg](https://user-images.githubusercontent.com/73518754/165504536-1ae46ce9-4450-4a27-bbf4-89a754d4ee78.jpg)
![Screenshot_2022-04-27-16-01-13-51_9e1a5d6211a0228d32d39446541891f1.jpg](https://user-images.githubusercontent.com/73518754/165504556-4400a520-2a24-4dc4-a5ae-24ea919377f1.jpg)

**Comment by gdlbo** [comment]
1. Обнови ленту
2. Дебаг фича, не надо её тыкать

**Comment by userskill** [comment]
> 1. Обнови ленту
> 2. Дебаг фича, не надо её тыкать

Конечно обновлял . это автомат . реклама осталась
