### ISSUE TITLE
Проблема с темной темой

### ISSUE THREAD

**Issue by somersbyscam** [vtosters/lite#199]
1. Включена темная тема. Во вкладке заявок в друзья появляется белая полоса. Непонятно, должен ли вообще быть такой отступ даже на белой теме.

2. Когда тема переключается с темной на белую, в диалогах остаются остатки темной темы. Решается перезапуском приложения.

3. Ещё недокрасы в музыке, в документах, при создании фотоальбома, в фотографиях, в диалогах.

![Screenshot_20220429-183159_VTLite](https://user-images.githubusercontent.com/104640535/165976960-c9854063-5abb-46f9-9772-421efca3cc73.png)
![Screenshot_20220429-183213_VTLite](https://user-images.githubusercontent.com/104640535/165976966-6f7dc189-fb88-4b9d-adff-d265cd20775b.png)

![Screenshot_20220429-181248_VTLite](https://user-images.githubusercontent.com/104640535/165974030-09ddbeb5-9a62-4f51-a4e0-3e12a296f128.png)
![Screenshot_20220429-181253_VTLite](https://user-images.githubusercontent.com/104640535/165974041-09b6e707-0b2f-456d-9096-b907cf608e9e.png)
![Screenshot_20220429-181308_VTLite](https://user-images.githubusercontent.com/104640535/165974045-340c5f34-ce64-44e9-ac56-85616764d144.png)
![Screenshot_20220429-182921_VTLite](https://user-images.githubusercontent.com/104640535/165976910-feed3ea5-659e-4388-b086-3fdf6ee93243.png)
![Screenshot_20220429-183033_VTLite](https://user-images.githubusercontent.com/104640535/165976921-5ed40ec5-1e06-483c-8357-a69458b493ff.png)
![Screenshot_20220429-183050_VTLite](https://user-images.githubusercontent.com/104640535/165976930-e4bf6c73-4079-4038-8156-0690b20208f9.png)
![Screenshot_20220429-183111_VTLite](https://user-images.githubusercontent.com/104640535/165976954-0cdfeda5-937d-4eef-aaf5-ef34fe3513db.png)
![Screenshot_20220429-183133_VTLite](https://user-images.githubusercontent.com/104640535/165976958-360579e4-c413-46c0-8ed7-eb5a9ea8adc7.png)
![Screenshot_20220429-184301_VTLite](https://user-images.githubusercontent.com/104640535/165978513-69e2d02f-db26-4582-8bfb-624b00628514.png)

**Comment by gdlbo** [comment]
Все проблемы с темной темой необходимо репортить сюда https://github.com/vtosters/lite/issues/2
