### ISSUE TITLE
Недоработки по интерфейсу(Темная тема)

### ISSUE THREAD

**Issue by questonit** [vtosters/lite#2]
Привет, 
Некоторые менюшки не окрашиваются в темной теме. В меню Новости на главной странице не видно надписей.

Плюс ещё заметил, что если удалять историю сообщений в чате, то сообщение(на скрине) висит бесконечно, пока сам не закроешь

Скриншоты:

![Screenshot_2022-03-24-20-10-31-10_9e1a5d6211a0228d32d39446541891f1](https://user-images.githubusercontent.com/52600536/159973250-b2ecf63b-c351-4b40-b228-60b5f974c1bd.jpg)
![Screenshot_2022-03-24-20-10-51-46_9e1a5d6211a0228d32d39446541891f1](https://user-images.githubusercontent.com/52600536/159973291-3c9f21de-cb20-4995-9c68-8dd8a83af70b.jpg)
![Screenshot_2022-03-24-20-11-10-00_9e1a5d6211a0228d32d39446541891f1](https://user-images.githubusercontent.com/52600536/159973342-0ae46008-f57a-4258-a9ac-dd20988a2b0c.jpg)
![Screenshot_2022-03-24-20-11-43-57_9e1a5d6211a0228d32d39446541891f1](https://user-images.githubusercontent.com/52600536/159973386-71d060bc-d283-44cb-8383-5035674e7078.jpg)

**Comment by oplexz** [comment]
Большинство недокрасов известны, но еще не были реализованы, так как в приоритете была работоспособность

**Comment by DeKvezz** [comment]
Вот еще немножко
![Screenshot_20220326-183626840~2](https://user-images.githubusercontent.com/49114327/160242093-01b5f6f7-9db4-456b-b26e-a48f66e8b704.jpg)
![Screenshot_20220326-183236103~2](https://user-images.githubusercontent.com/49114327/160242096-35b0a7df-5f18-47d2-a680-7966721df35d.jpg)

**Comment by imprmks** [comment]
![Screenshot_2022-03-27-00-40-37-799_com vtosters lite](https://user-images.githubusercontent.com/102409232/160258084-4f1a2206-decc-4418-82ab-7fa1196809fc.png)
опросы туда же

**Comment by imprmks** [comment]
> ![Screenshot_2022-03-27-00-40-37-799_com vtosters lite](https://user-images.githubusercontent.com/102409232/160258084-4f1a2206-decc-4418-82ab-7fa1196809fc.png) опросы туда же

надо бы мне найти пк нормальный пк который потянет андроид студио чтоб попробовать это исправить пока можно

**Comment by Wperdex** [comment]
Сообщения > Непрочитанные 
![IMG_20220419_005811](https://user-images.githubusercontent.com/102802937/163884251-d43fbaf1-9d6d-411b-b0fa-e69da3186c3a.jpg)
![IMG_20220419_005826](https://user-images.githubusercontent.com/102802937/163884260-1d71d2a2-3733-41f3-a496-e42a99a277ce.jpg)

**Comment by somersbyscam** [comment]
Меню через «три точки» на трансляциях

![Screenshot_20220430-195146_VTLite](https://user-images.githubusercontent.com/104640535/166115108-adba0988-fbd0-4296-b725-0fb30474a361.png)

**Comment by somersbyscam** [comment]
Создание аудио плейлиста

![Screenshot_20220430-223813_VTLite](https://user-images.githubusercontent.com/104640535/166120792-6156811e-319d-4307-92eb-12910d05c94e.png)
![Screenshot_20220430-223800_VTLite](https://user-images.githubusercontent.com/104640535/166120787-899f69fb-9873-4b0c-beca-788eaab5185b.png)

**Comment by MeowScript** [comment]
Кнопка повторить на видео не окрашена, опции у фотографий, а также статус бар на планшете остаётся синим словно тёмная тема не включена. Про меню репоста уже сообщали ранее... 
![Screenshot_20220506-181120.jpg](https://user-images.githubusercontent.com/95169658/167141471-93669508-fcb7-4e35-b234-210dd1ec99e7.jpg)![Screenshot_20220506-181133.jpg](https://user-images.githubusercontent.com/95169658/167141495-0df76dbb-6cd4-4ffe-b1ab-aab10c4c2071.jpg)![IMG_20220506_183349_808.jpg](https://user-images.githubusercontent.com/95169658/167142382-9595c1f5-f7d1-42eb-a20d-f31663323f73.jpg)

**Comment by P1xart** [comment]
Баг с отображением слов прямо в меню и ползунки в выключенном положении плохо видны
![Screenshot_20220525-000747_VTLite](https://user-images.githubusercontent.com/96487606/170113528-e4f36a01-687f-4023-9743-9f41a8c15c7f.jpg)
![Screenshot_20220525-000114_VTLite](https://user-images.githubusercontent.com/96487606/170113540-fe922cf4-d84c-4ba6-abbd-bde1da3b04bb.jpg)

**Comment by P1xart** [comment]
1) Кружки отключенных ползунков сливаются с темой
2) В меню аватарки нет темы
3) При репосте нет темы
![Screenshot_20220525-015345_VTLite](https://user-images.githubusercontent.com/96487606/170130868-c4fca411-f575-430f-bf63-1911f283c649.jpg)
![Screenshot_20220525-000747_VTLite](https://user-images.githubusercontent.com/96487606/170130827-fd21b6da-b43e-499b-9ecb-4c156fba211c.jpg)
![Screenshot_20220525-014603_VTLite](https://user-images.githubusercontent.com/96487606/170130854-81963faf-caf6-43dc-b126-04b4942fdfba.jpg)

**Comment by P1xart** [comment]
1. При удалении сообщения нет темы
2. При удалении сообщения "для всех" не видно пункта для галочки
![XRecorder_25052022_214920](https://user-images.githubusercontent.com/96487606/170317791-ca9272b5-3459-4eab-939b-52fcac2033dd.jpg)

![Screenshot_20220525-190704_VTLite](https://user-images.githubusercontent.com/96487606/170317832-2be78f94-f707-4595-94df-7efe93a6f695.jpg)

**Comment by P1xart** [comment]
4 белые точки в краях каждого видео
![Screenshot_20220528-134306_VTLite](https://user-images.githubusercontent.com/96487606/170818122-acc980f8-efca-4cf1-8a8d-5d74cf0ffe61.jpg)

**Comment by Internetx777max** [comment]
![Screenshot_2022-06-11-01-12-33-906_com vtosters lite](https://user-images.githubusercontent.com/91149355/173157447-4ccda509-2d4c-4afb-90f9-0beeab121c56.jpg)
Криво отображается прикреплённый альбом. Название еле резличимо, а также название группы не очень хорошо смотрится.

**Comment by blwckcore** [comment]
![Screenshot_20220611-214834_VTLite](https://user-images.githubusercontent.com/107321994/173201278-1357b6bd-961d-4cda-b717-5c9325856f87.png)
небольшая полоска в меню заявок в списке друзей

**Comment by Palvenok** [comment]
Привет, по поводу акцента темы. Просто предложение, может лучше текст оставить белым. Потому что в некоторых случаях текст становится трудно читаемым.
![Screenshot_20220612-121238_VTLite](https://user-images.githubusercontent.com/79199642/173226150-53719389-7916-4b22-944c-5fc9f6327cbc.png)

**Comment by abslike** [comment]
![Screenshot_20220616-013027_VTLite](https://user-images.githubusercontent.com/78505436/173922669-ade671c1-fa23-46d7-9f1f-5f18c884b44c.png)
Проблема с покраской для двухфакторной авторизации

**Comment by g0risha000kra0b** [comment]
![Screenshot_2022-06-17-07-48-54-144_com vtosters lite](https://user-images.githubusercontent.com/107666920/174228280-41a9bb6f-259e-4f9e-a1e4-9ebcb21ae947.jpg)
![Screenshot_2022-06-17-07-48-45-674_com vtosters lite](https://user-images.githubusercontent.com/107666920/174228296-f5c2a609-9548-44e8-b746-4359ca6eed51.jpg)
Не работает функция прочитывания сообщений как в вктостере

**Comment by dnlov4** [comment]
![Screenshot_20220617-155243_VTLite](https://user-images.githubusercontent.com/101515319/174285522-05e501b2-de6b-4d1c-a64b-d7704c0a8363.jpg)
![Screenshot_20220617-155334_VTLite](https://user-images.githubusercontent.com/101515319/174285541-65c56233-b393-441e-bc0d-08ad152ded7c.jpg)
Спасибо за проект, VTL пользоваться приятно. У меня на Android 12 (One UI Core 4.1) включена Monet тема, и кое-где (увидел в непрочитанных сообщениях, вложениях) текст слишком нечитаемый из-за светлых тонов Monet темы. Фикс покрасов для Android 12 включен, выключение не помогает. Понимаю, что тяжело красить, но логичным в этих ситуациях кажется более тёмный шрифт. Сможете в будущем покрасить, или проще смириться и менять цвет всей системы?

**Comment by k1zn** [comment]
<details>
  <summary>Непокрас</summary>

![image](https://user-images.githubusercontent.com/46452865/174287734-6c3137c1-7e00-4a23-a3c6-9c76216b20c5.png)
</details>
1) В планшетном режиме цвет панели уведомлений должен быть темного цвета, как цвет темной темы
2) Панель слева должна быть темного цвета, вместо синего при обычной теме
