### ISSUE TITLE
Вылетает при загрузке анимированное стикера

### ISSUE THREAD

**Issue by NikSavchenko3** [vtosters/lite#20]
Хотел посмотреть анимированные стикеры но **VTlite** крашнулся

https://user-images.githubusercontent.com/58150480/160184657-5fba6f5f-3a95-491b-95d0-40e54ae06da7.mp4

Логи: https://foxbin.f0x1d.com/YFlqtkbgc4

**Comment by gdlbo** [comment]
https://github.com/vtosters/lite/issues/5
