### ISSUE TITLE
При попытке открыть приложение выскакивает ошибка.

### ISSUE THREAD

**Issue by onupirat** [vtosters/lite#203]
![Screenshot_2022-04-30-19-35-36](https://user-images.githubusercontent.com/57112817/166114314-7465a3f0-0b11-4c9d-b205-f1fe1a51fafc.png)
В первых версиях программы этого не было. Если нужно больше информации дайте знать.

**Comment by onupirat** [comment]
Начиная с версии 0.0.9

**Comment by gdlbo** [comment]
Попробуй прологгировать проблему с помощью Matlog

https://t.me/vtosters_faq/21 3 вариант

**Comment by onupirat** [comment]
> Попробуй прологгировать проблему с помощью Matlog

Ок, благодоря этойго приложения разобрался в чём проблема. Оказалось нужно было очистить данные VTlite.
