### ISSUE TITLE
Неправильное количество отображаемых сообщений

### ISSUE THREAD

**Issue by egf0x** [vtosters/lite#205]
Снизу, где располагается кнопка "Сообщения" отображаемается неправильное количество сообщений, я обновлял список сообщений, но количество снизу, когда новых сообщений нет, равна единице, прикрепляю скриншот
![Screenshot_20220501-113301](https://user-images.githubusercontent.com/97127436/166138443-58c6c2f8-1908-428d-bf3d-3fde0616cc3b.png)

**Comment by egf0x** [comment]
а, тут на скриншоте вообще их количество равно двум, хотя непрочитанных сообщений нет

**Comment by gdlbo** [comment]
нажми на кнопку сообщения и тыкни на непрочитанные

**Comment by egf0x** [comment]
> нажми на кнопку сообщения и тыкни на непрочитанные

я нажимал, у меня НЕТ непрочитанных сообщений

**Comment by Internetx777max** [comment]
> > нажми на кнопку сообщения и тыкни на непрочитанные
> 
> я нажимал, у меня НЕТ непрочитанных сообщений

Этот баг встречался мне и в оригинальном ВК. Попробуй открыть каждый чат. Должно помочь

**Comment by egf0x** [comment]
> Этот баг встречался мне и в оригинальном ВК. Попробуй открыть каждый чат. Должно помочь

спасибо
