### ISSUE TITLE
Не хватает улучшения голосовых сообщений

### ISSUE THREAD

**Issue by Vantsev** [vtosters/lite#208]
В VTosters есть такая фича, как улучшенный битрейт записи голосовых сообщений. Очень сильно не хватает такого в Лайте
![Screenshot_20220502-114312_VTosters](https://user-images.githubusercontent.com/48063843/166208159-502c4ffd-b0de-47c7-86cc-dcbbfab5d3c2.jpg)

**Comment by gdlbo** [comment]
https://github.com/vtosters/lite/issues/55
