### ISSUE TITLE
Не обновляется лента

### ISSUE THREAD

**Issue by FuzzyWizard** [vtosters/lite#210]
Моя лента уже не обновляется неделю. Ещё посты за 25 апреля висят в ней. Ручное обновление ленты не работает, как и автоматическое. Прошу исправить

**Comment by gdlbo** [comment]
Переключи с интересной ленты на временную

**Comment by FuzzyWizard** [comment]
> Переключи с интересной ленты на временную

Как?

**Comment by RUZG0** [comment]
Каааак???

**Comment by psamur** [comment]
@RUZG0 На главной жмешь на «Новости» -> Настроить новости -> Порядок записей -> По времени публикации

**Comment by RUZG0** [comment]
Я дурачек, только сам сделал всё, но все равно благодарствую за помощь и уделённое тобой время 🥰
