### ISSUE TITLE
Не работают подсказки стикеров и анимация

### ISSUE THREAD

**Issue by Alexander5891** [vtosters/lite#216]
Ни в сообщениях, ни в комментариях. В настройках включаю, отключается назад автоматически.

**Comment by GooDoG337** [comment]
Подсказки и анимации отключены по умолчанию, всвязи с техническими проблемами с некоторыми стикерпаками, из-за которых вылетает приложение.

**Comment by gdlbo** [comment]
https://github.com/vtosters/lite/issues/5
