### ISSUE TITLE
Видео не работает

### ISSUE THREAD

**Issue by 1Radin1** [vtosters/lite#220]
![Screenshots_2022-05-04-06-49-19](https://user-images.githubusercontent.com/104880967/166620759-1aaaac00-f65a-4147-a153-0ef9578e8107.png)
![Screenshots_2022-05-04-06-58-07](https://user-images.githubusercontent.com/104880967/166621304-2b67ebfd-a47e-45fb-beca-9884586601ba.png)
![Screenshots_2022-05-04-06-57-04](https://user-images.githubusercontent.com/104880967/166621309-ddaa32ad-85ae-4ee3-8ec1-d892f15e7318.png)

- Видео не запускается, а еще обновление ленты работает крайне странно.

 - Лента сверху держит страые записи, а ниже обнавляются, но не по времени, а фиг знает как. (Обновлять по выходу новых записей) 

- скрытие планки возможных друзей
- иконки в доке разные

**Comment by gdlbo** [comment]
https://github.com/vtosters/lite/issues/19
Вроде работает, но посмотрю мб нюансы есть
Скрывается в настройках новостей
Насчёт иконок пока без понятия, наверное позже буду добавлять новые иконки из новых вк
