### ISSUE TITLE
Видео в ленте не воспроизводится через внешний видеоплеер

### ISSUE THREAD

**Issue by djbiomc** [vtosters/lite#224]
Часть видео в ленте не воспроизводятся (заметил, что там, где одно видео с автостартом воспроизведения), выдают ошибку связи с сервером. И не открываются внешним плеером.
Если видео добавить в свою библиотеку оно успешно открывается в том числе внешним плеером.  
Похоже тут сразу 2 бага:
1. Все видео воспроизводятся
2. Из ленты не открывается видео внешним плеером.

**Comment by 1Radin1** [comment]
У меня видео не влспроизводятся в ленте любым плеером. Добавлять не пробовал. Ошибка связи с сервером, ну очень уж надоел этот баг

**Comment by RED4911** [comment]
Из за этого бага, я до чих пор на старой версии и не могу перейти на Лайт. Не воспроизводится, никаких плеером.

**Comment by AleksOstr** [comment]
Не знаю как насчёт внешних плееров, но и с внутренним имеет место быть данный баг. А ещё заметил, что при включении VPN видео в ленте начинают прогружаться с 2-3 попыток. Без VPN совсем глухо
