### ISSUE TITLE
Уведомления на Mi Band (3)

### ISSUE THREAD

**Issue by xanax01d** [vtosters/lite#225]
В уведомлениях есть символ,который не понимает фитнес-браслет,пробелы сразу под откос,с ними всё хорошо
(
![IMG_20220504_214734](https://user-images.githubusercontent.com/104934416/166806080-5d228cb7-eccf-4b34-927f-51193e004740.jpg)
)
другого примера, к сожалению ,не было

**Comment by gdlbo** [comment]
Ну проблема аппы фитнес браслета
Проси мододелов добавить втлайт в список мессенджеров для зепп лайфа

**Comment by xanax01d** [comment]
проблема решается использованием не официального приложения для трекера (к примеру : Mi Bandage,Master for Mi Band(или как то так))
