### ISSUE TITLE
Не отображается часть диалогов

### ISSUE THREAD

**Issue by watislan** [vtosters/lite#227]
Если отыскать отсутствующий диалог и открыть его, то после этого он появится в списке. Если обновить сообщения, то диалог снова пропадет. Видео прилагается

https://user-images.githubusercontent.com/67457433/166879823-13b357fe-7583-490d-b2ad-8d72b8a3b8f6.mp4

**Comment by gdlbo** [comment]
https://github.com/vtosters/lite/issues/12
