### ISSUE TITLE
Невозможно кинуть жалобу на пост

### ISSUE THREAD

**Issue by aliveoutside** [vtosters/lite#23]
При попытке пишет "Что-то пошло не так"

**Comment by KMatsko** [comment]
У меня пишет, что жалобу невозможно кинуть, т.к. используется устаревший клиент:
![2022-05-03_14-25-51](https://user-images.githubusercontent.com/104833629/166444795-6da6f649-adab-4ccc-8e4b-9e10136a35ba.png)
