### ISSUE TITLE
Не обновляется лента

### ISSUE THREAD

**Issue by AbobaLova** [vtosters/lite#233]
Посты 3х дневной давности появляются в начале ленты. И так каждый день 🙃

**Comment by Wperdex** [comment]
Для начала проверь, какой порядок записей включён у тебя в настройках ленты. И если там будет "Сначала интересные", то те надо переключить на "по времени публикации".

**Comment by AbobaLova** [comment]
а где эти настройки? я не могу найти в настройках ленты такие параметры
--
Отправлено из Mail.ru для Android суббота, 07 мая 2022г., 19:00 +02:00 от Wperdex  ***@***.*** :

**Comment by Wperdex** [comment]
![IMG_20220507_200516](https://user-images.githubusercontent.com/102802937/167264567-f92b3405-a9cd-428e-a567-d844b96f1d20.jpg)
![IMG_20220507_200558](https://user-images.githubusercontent.com/102802937/167264568-9895b277-0691-4092-910f-5306d5e4002d.jpg)
![IMG_20220507_200612](https://user-images.githubusercontent.com/102802937/167264574-1ea3199a-1824-4be8-b9fa-8ff0638c4873.jpg)

**Comment by AbobaLova** [comment]
а все, нашел) Спасибо)
--
Отправлено из Mail.ru для Android суббота, 07 мая 2022г., 19:02 +02:00 от Даниил Мишин  ***@***.*** :
