### ISSUE TITLE
Постоянная обработка видео

### ISSUE THREAD

**Issue by Vantsev** [vtosters/lite#237]
Постоянная обработка видео затрагивает не только присланные видео, но и отправленные лично. На VT и десктопной версии вк эти же видео сразу же включаются без "обработки"
![20220510_110223](https://user-images.githubusercontent.com/48063843/167580220-00999a39-0964-4739-99d0-d1aff1e67759.jpg)

**Comment by gdlbo** [comment]
https://github.com/vtosters/lite/issues/96
