### ISSUE TITLE
Видео не работает в ленте

### ISSUE THREAD

**Issue by 1Radin1** [vtosters/lite#239]
Видеоо в ленте не работает, не со встроеным плеер не со стандартным. Ошибка сервера самый бесячий баг

**Comment by xoryman** [comment]
Не работают видеозаписи в закрытых сообществах. Выдает ошибку сервера. Настройки приложения по умолчанию, ничего не менял. Версия приложения последняя. Устройство Xiaomi Mi A1, Android One 9.1.

**Comment by Rognne** [comment]
То же самое
![Screenshot_20220513_124252](https://user-images.githubusercontent.com/59597650/168258512-9fabd292-f73a-4bc0-8641-3df3523f08b3.jpg)

**Comment by gdlbo** [comment]
https://github.com/vtosters/lite/issues/19
