### ISSUE TITLE
Баг с отображением песни

### ISSUE THREAD

**Issue by Coffeebar13** [vtosters/lite#24]
![Screenshot_20220326-103038](https://user-images.githubusercontent.com/60733236/160229616-60043085-9073-47fe-9844-11e2de2b5bdf.jpg)
![Screenshot_20220326-103050](https://user-images.githubusercontent.com/60733236/160229619-f35d100b-5d22-4773-8bb4-896c1d41d836.jpg)
Скорее всего нет нормальной смены цвета в ночной теме

**Comment by gdlbo** [comment]
https://github.com/vtosters/lite/issues/2
