### ISSUE TITLE
Персонализация и цветовые акценты

### ISSUE THREAD

**Issue by Fatumboy** [vtosters/lite#240]
Здравствуйте, находятся ли в разработке темы и акценты которые были в предыдущем VTosters? 
Понимаю, что текущая Lite версия только недавно начала разрабатываться, но очень не хватает возможности к персонализации клиента и выбора цветов интерфейса которые были в предыдущем VTosters :(
Особенно золотого акцента! :)

**Comment by DjackVorobeu** [comment]
Здравствуйте
Ответьте пожалуйста ведётся ли работа по добавлению акцентов и кастомизации приложения?
Да или нет, один ответ, третьего не дано
Я в основном только ради этой функции и устанавливал ваше приложение, и очень грустно что происходит вот такое :(
