### ISSUE TITLE
Пояснения к функциям перепутаны

### ISSUE THREAD

**Issue by slavrom21** [vtosters/lite#243]
Пояснения к функциям неписалки и нечиталки поменялись местами
v0.2.3-beta
![IMG_20220513_152912](https://user-images.githubusercontent.com/71776639/168283531-61933433-58bf-4f0b-af07-2194d49e78a9.jpg)
![IMG_20220513_152935](https://user-images.githubusercontent.com/71776639/168283537-750ccf8b-1527-4505-b190-5fbcd0257153.jpg)

**Comment by gdlbo** [comment]
https://github.com/vtosters/lite/commit/e0450d3835db1ae88470600dc6b264e5c3abcf70
