### ISSUE TITLE
Нельзя перемотать песню в шторке уведомлений

### ISSUE THREAD

**Issue by imprmks** [vtosters/lite#25]
![Screenshot_2022-03-26-11-47-31-932_com vtosters lite](https://user-images.githubusercontent.com/102409232/160232059-ab7575db-d1b9-4fcc-8591-d0306addcbb7.jpg)
![Screenshot_2022-03-26-11-48-43-961_com vtosters android](https://user-images.githubusercontent.com/102409232/160232060-94f0a3ce-e670-41b9-a58e-bbcf367c31f2.jpg)

**Comment by SonClick** [comment]
0.0.3 Работает

**Comment by imprmks** [comment]
Кстати, трек снизу не видно когда находишься в любой вкладке, кроме самой вкладки треков и меню по кнопке снизу справа. Возможно это было и на старой версии ВК, я честно говоря не в курсе.
