### ISSUE TITLE
Пропал последний чат из списка

### ISSUE THREAD

**Issue by UserNhammen** [vtosters/lite#253]
Отправил сообщение в каком-то диалоге (в списке чатов он был наверху, то есть совершенно недавно)
Закрыл диалог (передо мной список чатов) 
Нажал "Обновить" (кнопка со стрелочкой) 
Последний чат, в котором я оставил сообщение после этого из списка пропал (найти его всё ещё можно через поиск)

**Comment by AyonovDenizs** [comment]
Точно так же было

**Comment by gdlbo** [comment]
https://github.com/vtosters/lite/issues/12
