### ISSUE TITLE
Не грузится видео

### ISSUE THREAD

**Issue by RED4911** [vtosters/lite#254]
Пишет: Произошла ошибка связанная с подключением к серверу. Уже сколько версий обновилось, баг так и не исправлен
![IMG_20220518_011517](https://user-images.githubusercontent.com/6369947/168920725-250cc622-f0b4-49de-b46b-ad2b9cba0792.jpg)

**Comment by gdlbo** [comment]
https://github.com/vtosters/lite/issues/19
