### ISSUE TITLE
Не работает обновление ленты

### ISSUE THREAD

**Issue by FuzzyWizard** [vtosters/lite#255]
У меня до сих пор остались посты ещё с 8 мая. Как так то? Прошу исправить. Именно из за этого я не могу перейти на эту версию

**Comment by gdlbo** [comment]
Ну попробуй поставить начисто в чем проблема

**Comment by FuzzyWizard** [comment]
> Ну попробуй поставить начисто в чем проблема

Оно и так начисто стоит

**Comment by Leon-spike** [comment]
У меня все отлично с интернетом, но когда захожу в свой профиль, тупо загрузка, как будто нету инета
![Screenshot_20220519_212512](https://user-images.githubusercontent.com/105882372/169373314-c533a416-2cfa-4752-9e46-f9599a6a7120.jpg)

**Comment by gdlbo** [comment]
> > Ну попробуй поставить начисто в чем проблема
> 
> 
> 
> Оно и так начисто стоит

Тогда должно обновляться, у меня предлагает новые новости при входе
