### ISSUE TITLE
Краш при добавлении поста в закладки

### ISSUE THREAD

**Issue by TheCaJlaT** [vtosters/lite#266]
Случилось всего один раз, но все же...
![Screenshot_20220525-233019](https://user-images.githubusercontent.com/66368050/170363218-7019aded-9bec-4eb9-8849-021118156d44.png)

**Comment by P1xart** [comment]
Им логи нужны)) Скрина мало

**Comment by TheCaJlaT** [comment]
> Им логи нужны)) Скрина мало

Я понимаю, но они не сохранялись в файл. Всплывало уведомление, что логи сохранены, но их нет

**Comment by TheCaJlaT** [comment]
https://foxbin.f0x1d.com/E1q495UvFY
