### ISSUE TITLE
Не работают гиперссылки в постах

### ISSUE THREAD

**Issue by TheCaJlaT** [vtosters/lite#278]
![Screenshot_20220602-180401](https://user-images.githubusercontent.com/66368050/171661019-2feba39c-8766-4858-bb29-8ae543c11687.png)
![Screenshot_20220602-180323](https://user-images.githubusercontent.com/66368050/171661027-6e39f4ec-c8e9-4ae4-b273-3ccb9424be00.png)
![Screenshot_20220602-180058](https://user-images.githubusercontent.com/66368050/171661033-c0469a9e-ca2b-4163-a44a-cff4fcbbdaec.png)

**Comment by gdlbo** [comment]
https://github.com/vtosters/lite/issues/29
