### ISSUE TITLE
Непокрас (опять)

### ISSUE THREAD

**Issue by MRaist** [vtosters/lite#280]
0.2.6 beta
![Screenshot_20220603-125219](https://user-images.githubusercontent.com/103269174/171832252-0f085797-8dc6-4569-b95d-33bbe4444bda.png)
![Screenshot_20220603-125503](https://user-images.githubusercontent.com/103269174/171832579-f1a4013d-aed4-47c6-88a8-f4c94fadb3b1.png)

**Comment by TheCaJlaT** [comment]
Вот ещё недокрасы:

> Прикрепление файла/фото/видео
> Репост
> Стрелка перемотки чата
![Screenshot_20220603-180821](https://user-images.githubusercontent.com/66368050/171881745-9500d71d-11e6-411b-9ed9-8ca03444601a.png)
![Screenshot_20220603-180703](https://user-images.githubusercontent.com/66368050/171881752-2d943668-4c88-48fd-8ddb-34658d8ae341.png)
![Screenshot_20220603-180522](https://user-images.githubusercontent.com/66368050/171881754-0b2d3be1-5eec-4424-a8ea-d759e89f25a7.png)
![Screenshot_20220603-180408](https://user-images.githubusercontent.com/66368050/171881756-c0343516-9819-49b1-bf7d-1296d00d2c11.png)
![Screenshot_20220603-180405](https://user-images.githubusercontent.com/66368050/171881757-848359fc-5dd0-4651-9c14-8e6330f21a40.png)

**Comment by blwckcore** [comment]
![Screenshot_20220612-104649_VTLite](https://user-images.githubusercontent.com/107321994/173222933-f67ad914-f657-42cd-acf0-fe8923a5612a.png)
в светлой монет теме фон подарков черный, из-за этого текст нечитаемый
