### ISSUE TITLE
Добавьте прокси от xtranfrancyz в раздел "прокси".

### ISSUE THREAD

**Issue by SeratKlemence** [vtosters/lite#281]
В моей стране не работает не один прокси приведённый в приложении. Просьба добавить прокси от xtranfrancyz, ведь только с помощью этого прокси можно убрать ограничения на прослушивания музыки в моей стране.

**Comment by AyonovDenizs** [comment]
Автор этого прокси закрыл его.
Никак не добавят.

Цитата:

> В связи с вторжением россии на территорию Украины 24.02.2022 я прекращаю поддержку публичного прокси. Я не считаю нужным предоставлять доступ жителям Украины к российской пропаганде и помогать вражеским компаниям.

> Исходники` vk-proxy доступны на GitHub, вы все еще можете запустить прокси на своих серверах, форкнуть репу и делать что вашей душе угодно
