### ISSUE TITLE
Улучшение дизайна

### ISSUE THREAD

**Issue by TheArtyomMDev** [vtosters/lite#293]
Приложение классное, лучший альтернативный клиент ВК, особенно учитывая покраску Monet! Также очень хотелось бы видеть возможность включения более нового дизайна (например, как в последней версии Sova V)

**Comment by iNotFlying** [comment]
В 5.29 ещё не было нового дизайна, поэтому включить его невозможно 🙃

**Comment by TheArtyomMDev** [comment]
Эхх...
Жаль
А почему, кстати, VTosters не переходит на новую версию?

**Comment by iNotFlying** [comment]
Потому что читай [FAQ](https://t.me/vtosters_faq/64)
