### ISSUE TITLE
Проблема со скачиванием изображений

### ISSUE THREAD

**Issue by RoL3aN** [vtosters/lite#296]
Комментарий: В VTLite 0.27 появилась проблема обычного VTosters 6.13.2_19.6.3

Описание: Изображение скачивается, но не отображается в галереи длительное время. Диспетчер загрузок в этот момент выдаёт в "шторке" интерфейса уведомление об успешной загрузке.

Как лечится: Нажатием на уведомление об успешной скачке(загрузке) в "шторке" интерфейса, тем самым открывая изображение. После подобной манипуляции и выхода из просмотра изображения - оно мгновенно отображается в галереи. Такую махинацию нужно проводить каждый раз с отдельным изображением, которое не скачалось.
Частота появления бага: Рандом.  До ~50%

Информация о системе: Honor 8X (JSN-L21), Android 10.0 (C10E4R2P1), EMU 10.0.0

Версия VTLite: 0.27b

**Comment by GooDoG337** [comment]
А на основе чего решено, что это проблема у лайта и тостера, а не у галереи?

**Comment by RoL3aN** [comment]
> А на основе чего решено, что это проблема у лайта и тостера, а не у галереи?

Потому что ни с одним приложением, кроме VTL, такой ситуации не происходило за все 2+ года использования данного смартфона

**Comment by aliveoutside** [comment]
не могу воспроизвести проблему на MIUI и Pixel, фото качаются в /VK/Downloads и сразу появляются в галерее
