### ISSUE TITLE
Антивирус сбербанка

### ISSUE THREAD

**Issue by bbdzzz** [vtosters/lite#297]
Антивирус сбербанка ругается на приложение
![Screenshot_2022-06-12-01-40-46-120_ru sberbankmobile](https://user-images.githubusercontent.com/77416640/173200982-2ac28884-589c-4147-92d6-47c6b0c180cc.jpg)
![Screenshot_2022-06-12-01-40-50-872_com google android packageinstaller](https://user-images.githubusercontent.com/77416640/173200986-8667d833-8c9d-4814-bd2f-6d61ec835f9b.jpg)

**Comment by iNotFlying** [comment]
[Тинькофф](tinkoff.ru)

**Comment by iNotFlying** [comment]
Какая версия VTL установлена?![1.png](https://user-images.githubusercontent.com/100377648/173201274-fada1e53-2b30-4a15-b0d4-4404c93afff6.png)

**Comment by bbdzzz** [comment]
> Какая версия VTL установлена?![1.png](https://user-images.githubusercontent.com/100377648/173201274-fada1e53-2b30-4a15-b0d4-4404c93afff6.png)

Последняя
Это ещё на 0.2.7 появилось
