### ISSUE TITLE
Добавить настраиваемую кнопку на главной странице

### ISSUE THREAD

**Issue by blwckcore** [vtosters/lite#303]
По моему мнению, вкладка поиска, когда включен новый дизайн новостей, бесполезна, так как функционал рекомендаций перемещен на главную страницу. Предлагаю добавить настраиваемую кнопку (выбор между поиском и уведомлениями) на главной странице сверху с правой стороны, либо сразу после кнопки открытия камеры.

**Comment by gdlbo** [comment]
Редактор докбара же есть, настраивай как душе угодно нижнюю панель
