### ISSUE TITLE
Отображение точного времени

### ISSUE THREAD

**Issue by blwckcore** [vtosters/lite#304]
Хотелось бы иметь отображение точного времени всегда, по типу "был в сети в 12:22". Также предлагаю сделать сокращение подписи онлайна до простого "был в 12:22" или без включенной функции точного времени "был 2 часа назад". Секунды и дату, как в сове, думаю добавлять не стоит, ибо это уже излишне.

**Comment by gdlbo** [comment]
В настройках интерфейса уже есть, обновляйся почаще
