### ISSUE TITLE
Предпросмотр стикеров не работает

### ISSUE THREAD

**Issue by ImBr3ad** [vtosters/lite#31]
Если долго зажать на стикер вылезет предпросмотр но без стикера и если закрыть и заново попробовать открыть предпросмотр то краш

**Comment by aliveoutside** [comment]
какая версия приложения? (настройки -> о приложении)

**Comment by ImBr3ad** [comment]
> какая версия приложения? (настройки -> о приложении)

![Screenshot_2022-03-27-15-03-37-913_com.vtosters.lite.jpg](https://user-images.githubusercontent.com/61482580/160276473-6f8c080f-9089-4e07-8dc1-30c74c26a911.jpg)

**Comment by gdlbo** [comment]
https://github.com/vtosters/lite/issues/5
