### ISSUE TITLE
#crash/bug вкладки "Друзья"

### ISSUE THREAD

**Issue by KaworuNoriaki** [vtosters/lite#310]
При попытке зайти в "Друзья" приложение начинает лагать, виснуть и выдавать ошибку "Произошла ошибка при загрузке" . Приложение не вылетает но ошибка как и лаги остаются до полного перезапуска, при этом неважно на какую вкладку ты переключаешься после Друзей. Заметил что иногда такое же происходит после попытки перейти в свой профиль, но в отличии от профиля с "Друзьями" ошибку ловишь гарантированно 
Прошивка MIUI, Android 10  Версия vtl 0.2.9-prebeta

> [VK.logup.zip](https://github.com/vtosters/lite/files/8886717/VK.logup.zip)

https://user-images.githubusercontent.com/107300086/173252373-5c7e08c9-5aff-4e5a-8161-0d05dcb8f793.mp4

**Comment by k1zn** [comment]
@KaworuNoriaki Попробуй включить в Настройки -> О приложении -> Для разработчиков -> Включить MemLeak detect 

и снять логи ещё раз, может утечка памяти какая ? ? ?

**Comment by k1zn** [comment]
хотя нет. @gdlbo лог маленький, но могу предположить, что у человека происходит Rate limit из-за слишком частых запросов к account.getPingUrl. а вот почему хз) (насчёт ошибки при загрузке, возможно это как-то влияет и на лаги)
![image](https://user-images.githubusercontent.com/46452865/174401699-1e870afe-1bf0-479f-aadc-677561cffea8.png)

**Comment by k1zn** [comment]
@KaworuNoriaki а у тебя в втостерсе включены какие-то функции, отвечающие за онлайн?

**Comment by k1zn** [comment]
![image](https://user-images.githubusercontent.com/46452865/174403376-20c78ab4-495b-4dd0-8a18-ec8bbb1a1616.png)
@gdlbo  а не из-за этого случайно рейт лимит выдался?

**Comment by KaworuNoriaki** [comment]
> @KaworuNoriaki а у тебя в втостерсе включены какие-то функции, отвечающие за онлайн?

Не пользуюсь никакими функциями связанными с онлайном, утечек памяти не может быть, во всех остальных клиентах такой ошибки нет и не было
[VK.logup.zip](https://github.com/vtosters/lite/files/8931763/VK.logup.zip)
