### ISSUE TITLE
Вирус в 0.2.8

### ISSUE THREAD

**Issue by AureaFox** [vtosters/lite#311]
Антивирус видит вирус в этой версии, до того было всё нормально

![Screenshot_2022-06-13-02-22-01-38](https://user-images.githubusercontent.com/28442601/173252288-4e270a64-2132-40f9-af0d-e386237b8318.jpg)

**Comment by LNDEVIL** [comment]
Удали его

**Comment by AyonovDenizs** [comment]
Здесь нет вируса, антивирус ложное показание даёт.

Антивирусы не определяют на 100% вирус
