### ISSUE TITLE
Ошибка в разделе музыки 

### ISSUE THREAD

**Issue by Rostotskiy** [vtosters/lite#319]
Открываю музыку, сразу же "ошибка, повторите позже" 
Не переустановка, ни сброс кеша не помог

**Comment by sqwer228** [comment]
Тоже самое

**Comment by 667vwv** [comment]
отключи это
vk id > безопасность и вход.

![IMG_20220616_214630](https://user-images.githubusercontent.com/102009600/174223830-01617dcf-6acd-409d-89b0-21be7b263e31.jpg)

**Comment by 667vwv** [comment]
> Открываю музыку, сразу же "ошибка, повторите позже" Не переустановка, ни сброс кеша не помог

отключи это 
vk id > безопасность и вход
![IMG_20220616_214630](https://user-images.githubusercontent.com/102009600/174223928-b87aa790-79cd-49ff-ae2d-ec85315d1869.jpg)

**Comment by gdlbo** [comment]
Это VTLite, используй его последнюю версию
