### ISSUE TITLE
Вылет пункта "Музыка" в настройках мода

### ISSUE THREAD

**Issue by slavrom21** [vtosters/lite#320]
Лог:
https://foxbin.f0x1d.com/3Lhcj3nBaZ

**Comment by ricoshett** [comment]
Такая же проблема. 

https://user-images.githubusercontent.com/93671911/174167548-553ef513-6b2f-4399-a03f-17bf0d9da18d.mp4

**Comment by gdlbo** [comment]
https://github.com/vtosters/lite/commit/037ea4544835b965fbbbb2707505ce31dbaf0503

**Comment by ricoshett** [comment]
> [037ea45](https://github.com/vtosters/lite/commit/037ea4544835b965fbbbb2707505ce31dbaf0503)

И что с этой ссылкой делать-то?

**Comment by slavrom21** [comment]
> > [037ea45](https://github.com/vtosters/lite/commit/037ea4544835b965fbbbb2707505ce31dbaf0503)
> 
> И что с этой ссылкой делать-то?

Ждать следующей обновы
