### ISSUE TITLE
Проблемы с прочтением сообщений

### ISSUE THREAD

**Issue by g0risha000kra0b** [vtosters/lite#323]
![Screenshot_2022-06-17-07-48-45-674_com vtosters lite](https://user-images.githubusercontent.com/107666920/174229277-1c01b222-a40b-46f2-9d4a-688cac183da2.jpg)
![Screenshot_2022-06-17-07-48-54-144_com vtosters lite](https://user-images.githubusercontent.com/107666920/174229325-48b19d6a-a4cd-42f2-a557-c5cf05930ee0.jpg)

В вктостере была функция прочтения сообщений, в лайте такого нет, из-за этого крайне неудобно общаться. Даже когда отключаю нечиталку, то сообщения всë равно не читаются.

**Comment by gdlbo** [comment]
https://github.com/vtosters/lite/issues/261
