### ISSUE TITLE
Выдается ошибка, после обновление клиента.

### ISSUE THREAD

**Issue by Tropi4555** [vtosters/lite#331]
После обновления вчерашнего клиент крашит, после входа, до этого никогда у меня проблемы не было с обновлением. Пробовал установить заново данную версию, все равно такая проблема. Могу логи оставить, надеюсь в следующем обновление получится исправить. 
![Screenshot_2022-06-17-11-04-40](https://user-images.githubusercontent.com/107678517/174269955-2bb230b8-051d-48ed-b3a5-40f2fd2904e5.jpg)
[VTL_log.txt](https://github.com/vtosters/lite/files/8926354/VTL_log.txt)

**Comment by gdlbo** [comment]
Будет пофикшено сегодня

**Comment by gdlbo** [comment]
https://github.com/vtosters/lite/commit/2fc79dbdb88199640b0c665e008153af7cf1b045

**Comment by Tropi4555** [comment]
Спасибо большое)
