### ISSUE TITLE
запрос данных в активности грузит бесконечно

### ISSUE THREAD

**Issue by Koteika66** [vtosters/lite#333]
![image](https://user-images.githubusercontent.com/107679035/174271276-59104993-bc3a-42a8-959f-b732fea7658b.png)

**Comment by Zineks** [comment]
С каких пор VTosters стал лайтом?

**Comment by Koteika66** [comment]
хз

**Comment by Koteika66** [comment]
> С каких пор VTosters стал лайтом?

хз
