### ISSUE TITLE
Вылет при попытке залить документ из галереи в диалоге

### ISSUE THREAD

**Issue by fareeder** [vtosters/lite#34]
https://user-images.githubusercontent.com/96731321/160255583-58e12d94-0939-4b6e-ace2-3d95acbbfbc0.mp4

**Comment by fareeder** [comment]
[VTL_log.txt](https://github.com/vtosters/lite/files/8356262/VTL_log.txt)

**Comment by gdlbo** [comment]
https://github.com/vtosters/lite/commit/9a90ca4c53f2d526934f83c2e934d2ffdd3d8513 fixed
