### ISSUE TITLE
[non-bug] Где искать локализацию строк?

### ISSUE THREAD

**Issue by k1zn** [vtosters/lite#340]
Пытаюсь найти в коде, например "Что у Вас нового?" и нигде не могу найти эту строчку.

**Comment by iNotFlying** [comment]
https://github.com/vtosters/lite/blob/997d861f833901f38e0c736c9dcae6ec12717690/smali/res/values-ru/strings.xml
https://github.com/vtosters/lite/blob/997d861f833901f38e0c736c9dcae6ec12717690/smali/res/values/strings.xml
