### ISSUE TITLE
Плагин не работает, ошибка и типо нет инета. 

### ISSUE THREAD

**Issue by trash753** [vtosters/lite#346]
![Screenshot_2022-06-17-22-59-00-88_a26493664d4394a40e78749b8c5477f6](https://user-images.githubusercontent.com/107639364/174394654-d83709f5-9290-4ca9-a9f0-55e6ec164d63.jpg)

Ток в плагине пишет про ошибку и инет, все остальное в нём работает, только с музыкой траблы. (защита от подозрительных приложений отключена)

**Comment by iNotFlying** [comment]
Когда VTosters стал VTosters Lite?

**Comment by Tropi4555** [comment]
Разработчики уже говорили, что нужно переходить на другую версию, а именно на lite, так как обычный клиент уже не будет обновляться

**Comment by k1zn** [comment]
https://t.me/vtosters_faq/64
