### ISSUE TITLE
Что такое файрочка и как её получить 

### ISSUE THREAD

**Issue by asadik2001** [vtosters/lite#348]
Столкнулся с такой проблемой, что у меня скачан и вк тостер и вк тостер лайт, но я не могу получить доступ из вк лайт доступ к функциям обычного вктостера. Что делать? Как файрочек получить и что это такое

**Comment by granitta** [comment]
У меня точно такая же проблема,загружен Тостер и Лайт,но файрочку подключить не удается

**Comment by GooDoG337** [comment]
Файрочка включает в себя "Огонь Прометея на вашей странице и серверные функции", а насчёт функций, лайт пока что является бетой, и многих функций пока что нет

**Comment by 667vwv** [comment]
настройки самого мода находятся тут. файрочка отвечает только за серверные функции, которые открываются при получении огня прометея (файрочка). обычные функции работают и без нее!

![Screenshot_2022-06-19-09-01-01-852_com vtosters lite](https://user-images.githubusercontent.com/102009600/174465342-8d872780-2608-4921-bfdb-d637e990214b.jpg)
