### ISSUE TITLE
Не загружается раздел с музыкой 

### ISSUE THREAD

**Issue by UNDYINGEHOT** [vtosters/lite#354]
![S20618-13440495](https://user-images.githubusercontent.com/100080061/174434266-32ed9a9a-0f34-4dc3-8331-2a6387df66c6.jpg)

Раздел с музыкой не грузит, в то время как сама музыка из записей людей в ленте нормально воспроизводится, но не сохраняется в свою музыку.

**Comment by k1zn** [comment]
версия 0.30?

**Comment by GooDoG337** [comment]
Никто не собирается чинить ВТостер, так как поддержки клиента больше нет, да и зачем про тостер писать в лайте


> версия 0.30?

Мне кажется, это VTosters, так как у лайта вроде нет сервисов и такой покраски

**Comment by k1zn** [comment]
а да.

**Comment by UNDYINGEHOT** [comment]
Все понял, спасибо. Извините за беспокойство
