### ISSUE TITLE
Не работают подсказки для стикеров.

### ISSUE THREAD

**Issue by KayberCrystal** [vtosters/lite#355]
Спустя некоторое время после включения функции можно, не выходя из меню настроек, обнаружить, что ползунок возвращается в исходное положение.

**Comment by KayberCrystal** [comment]
https://user-images.githubusercontent.com/23233215/174437427-142c964e-d50a-4f8e-a003-0fa04852b25c.mp4

**Comment by AyonovDenizs** [comment]
#5
