### ISSUE TITLE
Последний пост в сообществе не отображается

### ISSUE THREAD

**Issue by nightadmin** [vtosters/lite#357]
В режиме VK Me на Android 12 не отображается последний пост в ленте сообщества.

Шаги:
1. Включить режим VK Me.
2. Открыть беседу сообщества.
3. Через список участников открыть сообщество.
4. Наблюдать баг - последний (по новизне) пост не отображается.

ОР:
Отображаются все посты.
ФР:
Вероятно, из-за неправильного среза по респонсу API отображаются все посты, кроме последнего.

**Comment by nightadmin** [comment]
Видео: https://youtu.be/vwUegumY12o

**Comment by gdlbo** [comment]
Скорее всего фильтр заблокировал, нежели пост срезался из-за апи
