### ISSUE TITLE
Нечиталка

### ISSUE THREAD

**Issue by Eno4ika** [vtosters/lite#365]
Сама нечиталка работает, но если мне надо чтобы сообщение было прочитано, при этом не отвечая на него,то естественно надо отключить нечиталку. Но когда отключаешь нечиталку, она все равно работает. Кнопки "отметить прочитанным" нет. Приходится отвечать на все сообщения, даже если на них не надо отвечать. Прошу исправить и добавить кнопку "отметить прочитанным".

**Comment by Boffeer** [comment]
Да. Не хватает кнопки "отметить прочитанным" в контекстном меню открытого диалога и в списке диалогов, когда удерживаешь тап на нужном диалоге.

Правда ведь бывают ситуации когда тебе нужно просто отметить диалог прочитанным, если тебе ответили что-то типа "хехе", "ну да", в общем бессмыслицу какую-то

Тажке было бы удобно, если нечиталку и неписалку можно было бы переключать не выходя из диалога
