### ISSUE TITLE
не отображаются закрепленные чаты

### ISSUE THREAD

**Issue by Lavshyak** [vtosters/lite#366]
хочу, чтоб закрепленные чаты отображались

**Comment by Boffeer** [comment]
Ранее закрепленные чаты просто не видны в олщем списке. Появились только после того, как открепил на десктопе

**Comment by AyonovDenizs** [comment]
#12 

Цитата gdlbo:
`фича вк апи который на старых версиях не отдает чаты из закрепа в список обычный`

**Comment by Lavshyak** [comment]
тогда супергениальное преложение: перейдите на новую версию апи, чтоб чаты из закрепа передавались в список обычный

**Comment by nightadmin** [comment]
Согласен, выглядит странно. Почему нельзя просто перейти на новую версию API? Или, если старая критична, использовать новую версию только в этом методе.
