### ISSUE TITLE
Не отображаются превью тгшных стикеров (pc messenger)

### ISSUE THREAD

**Issue by henapbc9** [vtosters/lite#368]
![image](https://user-images.githubusercontent.com/107342106/174470914-63eff5c4-a549-4862-a399-af8ae077329e.png)
![image](https://user-images.githubusercontent.com/107342106/174470924-00177a01-848d-4882-9e10-73b03f05d388.png)
![image](https://user-images.githubusercontent.com/107342106/174470934-e9ad6096-f541-4b52-859c-3fca4311e301.png)

**Comment by GooDoG337** [comment]
А причём тут VTLite и VTMessenger?

**Comment by henapbc9** [comment]
?

**Comment by henapbc9** [comment]
В каком смысле "при чём"?

**Comment by henapbc9** [comment]
в тг превью этих же стикеров прекрасно работают

**Comment by henapbc9** [comment]
если ты про то

**Comment by GooDoG337** [comment]
> В каком смысле "при чём"?

Ну, это репозиторий VTLite, тут issues касаются VTLite, а VTMessenger к этому репозиторию никакого отношения не имеет

**Comment by henapbc9** [comment]
а
понял

**Comment by AyonovDenizs** [comment]
> В каком смысле "при чём"?

Ничего, что ты пишешь в репо, связанный с VTLite?
