### ISSUE TITLE
Ошибка в тексте

### ISSUE THREAD

**Issue by ArturkaPturkaExterminatorStrangerHearts** [vtosters/lite#384]
Должно быть "Кто может отправлять мне запросы", а тут написано "Кто может отправлять мне вопросы"
![IMG_20220623_111522](https://user-images.githubusercontent.com/55980679/175221153-6c3d9451-8f27-4ff5-a143-a387cd5f1bb4.jpg)

**Comment by prmncr** [comment]
Не баг, а фича вк под названием "Вопросы". А страница с настройками приватности - вебвью, страница которого тянется напрямую от вк, поэтому наличие там фич, которых нет в моде - обычное дело, vt там ничего не трогает.

![Собственно сама фича справа](https://user-images.githubusercontent.com/39909848/175286345-f66f65b8-d954-4c2b-afbe-781b694af2d2.jpg)
