### ISSUE TITLE
Не доступен поиск музыки даже после переустановки

### ISSUE THREAD

**Issue by lexxxur** [vtosters/lite#387]
Когда переходишь во вкладку музыка пишет: "Ошибка" и ниже надпись: "Повторить" но когда нажимаешь ничего не меняется

**Comment by 667vwv** [comment]
> Когда переходишь во вкладку музыка пишет: "Ошибка" и ниже надпись: "Повторить" но когда нажимаешь ничего не меняется

[319](https://github.com/vtosters/lite/issues/319#issue-1274028000) 
![IMG_20220624_204259](https://user-images.githubusercontent.com/102009600/175570621-5f4090b4-dfdc-45cc-a0ac-df6918a9d892.jpg)

**Comment by nightadmin** [comment]
Норма, тостер не поддерживает музыку.

**Comment by 667vwv** [comment]
> Норма, тостер не поддерживает музыку.

не знаю, в вт лайт музыка работает, лично у меня. данная проблема наблюдается только в старом тосторе, благодаря отключению этой защиты музыка работает в штатном режиме.
