### ISSUE TITLE
Постоянно ошибка при воспроизведении видео в ленте 

### ISSUE THREAD

**Issue by Laki3i** [vtosters/lite#40]
![Screenshot_2022-03-27-09-35-38-84_9e1a5d6211a0228d32d39446541891f1](https://user-images.githubusercontent.com/102454120/160269800-d0d0cadf-bb39-489e-97f7-ef63a8b82faa.jpg)

**Comment by gdlbo** [comment]
https://github.com/vtosters/lite/issues/19
