### ISSUE TITLE
Не обновляются новости и рекомендации при свапе вниз

### ISSUE THREAD

**Issue by Baobab32** [vtosters/lite#407]
Когда свапаешь вниз, появляется круг обновления ленты,  этот круг проходит, но в ленте остаются старые посты, которым по 5,6,7 и т.д. дней

**Comment by punksexual** [comment]
Та же проблема с первого дня на vt lite и вот до последней версии включительно. Большинство постов в ленте видел уже 5+ раз, местами появляются новые посты. Пробовал и с фильтрами ленты и без проблема остаётся. При выборе "сначала новые" всё работает как надо
