### ISSUE TITLE
Баг тёмной темы после просмотра стрима

### ISSUE THREAD

**Issue by vipaoL** [vtosters/lite#408]
Если заходить на чью-то трансляцию вк, некоторые элементы интерфейса утрачивают свой чёрный цвет (пока заметил только строку написания сообщения/комментария и заголовок вкладки сообщений). Перекрашивается обратно только принудительной остановкой.
![1656575854325](https://user-images.githubusercontent.com/59665125/176625315-f6c28558-b13c-44cb-81f0-4685de1b36aa.jpg)
![1656575867345](https://user-images.githubusercontent.com/59665125/176625321-5c731d94-6458-426c-ad7c-013efc7bf35c.jpg)
![1656575913307](https://user-images.githubusercontent.com/59665125/176625326-9782a2f8-194b-452f-ba92-3bb0fe0c28de.jpg)
Версия 7dd30d5

**Comment by gdlbo** [comment]
Будет исправлено в следующем обновлении
