### ISSUE TITLE
Закладки в докбаре

### ISSUE THREAD

**Issue by ASChupin** [vtosters/lite#414]
Прошу добавить раздел Закладки при кастомизации докбара.

**Comment by Internetx777max** [comment]
Закладки в докбаре есть

**Comment by Internetx777max** [comment]
![Screenshot_2022-07-14-14-21-10-658_com vtosters lite](https://user-images.githubusercontent.com/91149355/178971400-4eb5994d-cc95-4a24-8754-874052be9396.jpg)
![Screenshot_2022-07-14-14-21-16-861_com vtosters lite](https://user-images.githubusercontent.com/91149355/178971408-ae051d7e-296b-4d4b-956c-54d8d643ceae.jpg)
Только они почему-то называются "Видеозапись"
