### ISSUE TITLE
Проблемная вкладка "профиль"

### ISSUE THREAD

**Issue by Internetx777max** [vtosters/lite#415]
Вкладка "профиль" не та, что в обычном Втостерс. И если включить редизайн с отсутствующей кнопкой в докбаре "настройки", больше ты туда не попадёшь никогда в жизни.
Также к воспоминаниям, и закладкам не перейти через тот же профиль.
Скрины с фейк аккаунтом.
VTosters
![Screenshot_2022-07-14-14-07-17-619_com vtosters android](https://user-images.githubusercontent.com/91149355/178969845-96503ca1-70e8-432e-a4cc-bfe118d241f4.jpg)
VTLite
![Screenshot_2022-07-14-14-07-32-546_com vtosters lite](https://user-images.githubusercontent.com/91149355/178969890-69870b71-c738-4578-88d1-09528179d417.jpg)

Больше стало похоже на большого брата, но всё же пока недоделано. Не то...

**Comment by Internetx777max** [comment]
С настройками разобрались.

**Comment by Internetx777max** [comment]
> Про настройки - Да! Я включил MilkShake тему-редизайн, и теперь не могу попасть обратно в настройки. Прикольно получается 🥴👍
> 
> P.S. Пришлось переустанавливать и ставить в докбар настройки.

Почитайте FAQ. Либо я вам тут напишу: в меню "профиль нужно свайпнуть справа налево, и тогда выпадет список тех самых пунктов, как в VTosters. Свайпом, конечно, не оч удобно, но как есть

**Comment by wetakor** [comment]
> > Про настройки - Да! Я включил MilkShake тему-редизайн, и теперь не могу попасть обратно в настройки. Прикольно получается 🥴👍
> > 
> > P.S. Пришлось переустанавливать и ставить в докбар настройки.
> 
> Почитайте FAQ. Либо я вам тут напишу: в меню "профиль нужно свайпнуть справа налево, и тогда выпадет список тех самых пунктов, как в VTosters. Свайпом, конечно, не оч удобно, но как есть 

Понял, спасибо большое!
