### ISSUE TITLE
Ошибки после обновления

### ISSUE THREAD

**Issue by SergejKreutz** [vtosters/lite#418]
Перестала открываться лента новостей. Так же невозможно зайти на свою страницу. В обоих случаях надпись "Ошибка загрузки". До обновления всё было в порядке.
![Screenshot_20220714_155651_com vtosters lite](https://user-images.githubusercontent.com/108700425/178988264-b260b316-1dd1-4b4e-9302-2d0293cbd937.jpg)

**Comment by GooDoG337** [comment]
Попробуй переустоновку версии, и/или очищение кэша
