### ISSUE TITLE
Музыка в докбаре

### ISSUE THREAD

**Issue by Vadikakaa** [vtosters/lite#421]
Если просто зайти в музыку то новая версия нормально работает) 
Но если добавить музыку в докбар и запустить  открывается музыка старой версии  =(

**Comment by Vologhat** [comment]
Если вы хотите поменять стиль фрагмента музыки, то зайдите в настройки, найдите пункт "Медиа контент" и нажмите на него, после отыщите опцию "Новый раздел музыки (beta)" и измените её состояние на необходимое нажатием
