### ISSUE TITLE
Крошится приложение, не запускается lite activity thread

### ISSUE THREAD

**Issue by GrayRats** [vtosters/lite#423]
- Vk тест приложение  ломается , ошибка java

**Comment by GrayRats** [comment]
![Screenshot_2022-07-14-20-28-33-935_com vtosters lite](https://user-images.githubusercontent.com/45000170/179006899-0ce60c7e-6ea8-4131-8d01-6167114f2e6f.jpg)
![Screenshot_2022-07-14-20-28-30-250_com vtosters lite](https://user-images.githubusercontent.com/45000170/179006910-0a8e3081-bb63-46c3-b6f0-06fe8f691f20.jpg)
![Screenshot_2022-07-14-20-28-21-013_com miui home](https://user-images.githubusercontent.com/45000170/179006919-ef303c29-cd85-4abc-960a-d3c84045808e.jpg)

**Comment by aliveoutside** [comment]
#419

**Comment by kula77713** [comment]
Тоже самое
