### ISSUE TITLE
друзья

### ISSUE THREAD

**Issue by tiititi** [vtosters/lite#427]
раздел друзья не прогружается. вероятнее, из-за того, что много друзей ( 4000+ ), т.к. 100 друзей на другой странице прогружются моментально. при том на прошлой версии клиента грузило всё и всегда. оставив телефон на пару минут на таком экране ( см.скрин) телефон начинает греться, очень заметно это. друзья при этом все равно не прогружаются.
 телефон poco x3 pro. от этой проблемы не прогружаются общие друзья. ![Screenshot_2022-07-14-19-26-02-741_com.vtosters.lite.jpg](https://user-images.githubusercontent.com/75739675/179031283-70bd8495-2428-455e-a458-32274e35f894.jpg)

**Comment by gdlbo** [comment]
А с милкшейком грузится или так же дохло?

**Comment by tiititi** [comment]
с милком друзья грузятся мгновенно. общие все равно не находит. и плюс ко всему я не знаю где на милке найти раздел настройки 😂

**Comment by AyonovDenizs** [comment]
> с милком друзья грузятся мгновенно. общие все равно не находит. и плюс ко всему я не знаю где на милке найти раздел настройки 😂

Свайп справа налево в профиле

**Comment by tiititi** [comment]
> > с милком друзья грузятся мгновенно. общие все равно не находит. и плюс ко всему я не знаю где на милке найти раздел настройки 😂
> 
> Свайп справа налево в профиле

да я уже знаю. спасибо

**Comment by k1zn** [comment]
Нужны логи @tiititi

**Comment by tiititi** [comment]
скачал последнюю версию с action. но не понимаю как сделать логи🥲

**Comment by k1zn** [comment]
@tiititi настройки -> о приложении -> зажимаешь логотип ВКонтакте
должно появиться уведомление о том, что дебаг меню активировано
затем переходишь в  настройки -> для разработчиков -> включаешь "логирование api" и жмешь "запись логов в файл"
после того как под "запись логов в файл" появится текст "запись включена" заходишь в список друзей и ловишь эту ошибку, затем перезаходишь в приложение (выходишь и заходишь заново) и у тебя сохраняется лог по пути /Download/VK/logs/com.vtosters.lite/ в виде архива. кинешь его сюда

**Comment by tiititi** [comment]
уведомление о активации дебаг меню не приходит никакое. следовательно и дебаг меню нет. я задал логотип ВК на 30 секунд. попробовал на двух телефонах. результат тот же😳

**Comment by k1zn** [comment]
тогда перейди по ссылке (надеюсь у тебя не андроид12, иначе добавь поддерживаемые ссылки втостерсу из списка приложений на устройстве)

[debug](https://vk.com/vt/debug)

**Comment by tiititi** [comment]
сделал. вот архив.![VK.logup.zip](https://github.com/vtosters/lite/files/9233162/VK.logup.zip)
