### ISSUE TITLE
Странное поведение списка друзей. Во всех планах.

### ISSUE THREAD

**Issue by junkiemori** [vtosters/lite#43]
1) Во-первых, кружок загрузки показывается поверх надписи "This list is empty"
2) Во-вторых, приложение почти намертво зависает при попытке открыть менюшку сверху, где там выбор исходящих заявок, дней рождения и др.
3) В-третьих, эти меню (заявки, дни рождения и др.) так и не открываются.

Все нажатия на видео показаны.

https://user-images.githubusercontent.com/86261854/160273026-f53ce4cc-3609-4a5e-909e-65e25164afb9.mp4

**Comment by omoriparanoid** [comment]
Да, забыл упомянуть.
Телефон - Redmi Note 9s.
Android 11.
Как видите, не MIUI.

**Comment by gdlbo** [comment]
больше 1000 друзей?

**Comment by ImBr3ad** [comment]
У меня со списком норм все. 230 друзей
И да забыл сказать. Как видите MIUI ![IMG_20220327_155945.jpg](https://user-images.githubusercontent.com/61482580/160278362-c8a1148d-74b6-42a1-b392-bd33fc73f7ae.jpg)

**Comment by omoriparanoid** [comment]
> больше 1000 друзей?

Наоборот. Нисколько не добавлено

**Comment by omoriparanoid** [comment]
На MIUI 11, Android 10 такой же баг, он еще жестче даже. Пункт Онлайн не открывается, хотя вроде на PE+ A11 открывался, там просто было написано, что список пуст.
https://user-images.githubusercontent.com/86261854/160297134-c1acc6fe-a551-4118-9532-8f875af33183.mp4

**Comment by gdlbo** [comment]
https://github.com/vtosters/lite/commit/d6d50bdc415dc41bfe706bc7178d747c66dd1d04
