### ISSUE TITLE
Не работает лента новостей и не отображается меню

### ISSUE THREAD

**Issue by CrimsonPie** [vtosters/lite#431]
![IMG_20220714_201847](https://user-images.githubusercontent.com/58173227/179044268-5ff2704c-85fd-4cc5-9882-edda39e64fac.jpg)
![IMG_20220714_201853](https://user-images.githubusercontent.com/58173227/179044273-d0f4acf8-64d7-4e93-8f53-5f248de4a944.jpg)

**Comment by aliveoutside** [comment]
#419
