### ISSUE TITLE
Отсутствует стрелка

### ISSUE THREAD

**Issue by MRaist** [vtosters/lite#434]
Отсутствует стрелка в левом верхнем углу, чтобы вернуться назад.
![IMG_20220714_211830_782](https://user-images.githubusercontent.com/103269174/179054633-3934f04c-a306-4edf-bc80-964ab2e939d4.jpg)
![IMG_20220714_211754_292](https://user-images.githubusercontent.com/103269174/179054690-3fd18bda-5b10-47b2-bb8a-d4ad7a72fa02.jpg)
![Screenshot_20220714-180012](https://user-images.githubusercontent.com/103269174/179054736-74830aaa-77bd-4e59-9e23-ead734393f01.png)
![Screenshot_20220714-180052](https://user-images.githubusercontent.com/103269174/179054929-e5214058-edc6-4bf7-a43d-c5f88c19e397.png)

**Comment by Internetx777max** [comment]
> Отсутствует стрелка в левом верхнем углу, чтобы вернуться назад. ![IMG_20220714_211830_782](https://user-images.githubusercontent.com/103269174/179054633-3934f04c-a306-4edf-bc80-964ab2e939d4.jpg) ![IMG_20220714_211754_292](https://user-images.githubusercontent.com/103269174/179054690-3fd18bda-5b10-47b2-bb8a-d4ad7a72fa02.jpg) ![Screenshot_20220714-180012](https://user-images.githubusercontent.com/103269174/179054736-74830aaa-77bd-4e59-9e23-ead734393f01.png) ![Screenshot_20220714-180052](https://user-images.githubusercontent.com/103269174/179054929-e5214058-edc6-4bf7-a43d-c5f88c19e397.png)

У вас есть наэкранная кнопка "назад". Зачем вам стрелка? Сейчас она уже никому не нужна. Даже мне с жестами без стрелок нормально
