### ISSUE TITLE
Не скачивается изображение

### ISSUE THREAD

**Issue by MRaist** [vtosters/lite#435]
Изображение как бы скачалось, приходит уведомление об успешном скачивании, но в телефоне скачанного изображения нет

**Comment by gdlbo** [comment]
Android moment

**Comment by Internetx777max** [comment]
Poco X3 Pro
A12 MIUI 13
Всё скачивается. Скачанные фотографии лежат по пути: Память устройства/VK/Downloads
Проверьте, может они есть, но просто не отображаются в галерее
