### ISSUE TITLE
Нельзя попасть в настройки после переключения на milkshake

### ISSUE THREAD

**Issue by Boffeer** [vtosters/lite#436]
В докбаре было 3 элемента: сообщения, музыка и менюшка со всеми другими сервисами и возможностью зайти в настройки.

После переключения на милкшейк последний пункт правравтился в профиль. В настройки никак не попасть. Ни двойной тап по элементу в докбаре, ни в 3 точках

![IMG_20220715_075609.jpg](https://user-images.githubusercontent.com/41575886/179153622-1af7978f-0e82-4af7-8ad0-09f02e305f47.jpg)

**Comment by GooDoG337** [comment]
В профиле свайпай справа налево

**Comment by Boffeer** [comment]
> В профиле свайпай справа налево

Тупанул совсем😂
Спасибо
