### ISSUE TITLE
Не открываются новости.

### ISSUE THREAD

**Issue by VanQ9** [vtosters/lite#437]
VTLite, стабильно выдаёт ошибку, при попытке открыть ленту новостей, проблема появилась после обновления, очистка кэша и переустановка приложения ни как не помогает.
![Screenshot_20220715-114907](https://user-images.githubusercontent.com/74460295/179189869-d45548f1-9064-4f99-a24f-c386a13e7304.png)

**Comment by Internetx777max** [comment]
Надо было ставить начисто.
Попробуйте стереть все данные VTLite через настройки. Удалить и начисто поставить VTLite 0.4.0
