### ISSUE TITLE
Не отображается новостная лента, выдает ошибку

### ISSUE THREAD

**Issue by Noley803a** [vtosters/lite#439]
Обновил приложение и началась такая проблема
![Screenshot_2022-07-15-20-22-11-67_9e1a5d6211a0228d32d39446541891f1](https://user-images.githubusercontent.com/96216837/179231684-7dda6342-2db5-4b06-b984-b15f1d4b6e1c.jpg)

**Comment by Vologhat** [comment]
Попробуйте отчистить данные приложения или же переустановить его, проблема на стороне вашего устройства.
