### ISSUE TITLE
Недопереводы некоторых разделов приложения

### ISSUE THREAD

**Issue by junkiemori** [vtosters/lite#44]
Тут дополнительно ничего не сказать. При установленном в системе Английском (США) проглядывается русский в пункте Музыки. Скриншот прилагаю.
![Screenshot_20220327-112057_VTLite](https://user-images.githubusercontent.com/86261854/160273240-dddebe87-1875-40bd-8cfc-b1024b36dcbc.png)

**Comment by gdlbo** [comment]
Пока возможны недопереводы из-за того, что некоторые пункты не финального названия/смысла самой фичи и этим некогда и некому заняться :(

**Comment by omoriparanoid** [comment]
> Пока возможны недопереводы из-за того, что некоторые пункты не финального названия/смысла самой фичи и этим некогда и некому заняться :(

Если что - обращайтесь. Что-что, а (красивые) названия функциям и перевод я могу придумать
