### ISSUE TITLE
Gif-анимацая 

### ISSUE THREAD

**Issue by AllFizer** [vtosters/lite#440]
Не грузят gif-анимации на последнем обновление

**Comment by GooDoG337** [comment]
Видео-доказательства есть?

**Comment by AllFizer** [comment]
https://user-images.githubusercontent.com/109364300/179257745-c054407c-3ba5-4daa-b7fd-799ab60e7f26.mp4

**Comment by aliveoutside** [comment]
не воспроизводится на 6b9f80284c1bc0f4c7a12dc9f5d34af66714147b

https://user-images.githubusercontent.com/53598473/179264222-272259eb-bb48-4c5e-999e-c49740ddc8ef.mp4
