### ISSUE TITLE
офлайн

### ISSUE THREAD

**Issue by saponite** [vtosters/lite#442]
в прошлых версиях приложения если оставить ползунки в таком положении ( см.скрин), то через 5 минут ты уходишь в офлайн, при этом сидишь листаешь ленту или диалоги или ещё что-то, кроме написания сбщ, иначе улетаешь в онлайн. грубо говоря, ты появишься в онлайн, когда произойдет прямое взаимодействие с сервером, что выведет тебя в онлайн. 
сейчас, как я протестировал и понял, обе функции ( см.скрин) работают одинаково: 1 функция выводит в офлайн через минуту, 2 функция выводит в офлайн мгновенно.
сейчас, оставив ползунки в таком положении ( см.скрин ), то ты онлайн, пока активно приложение.
протестировал на старые версии и новую на  poco x3 pro ![Screenshot_2022-07-15-20-45-38-231_com.vtosters.lite.png](https://user-images.githubusercontent.com/75739675/179348115-1712e319-d302-45f1-9f8c-163beed00810.png)

**Comment by AyonovDenizs** [comment]
А скрин то где?

**Comment by tiititi** [comment]
> А скрин то где?

добавил
