### ISSUE TITLE
Все сообщения приходят снова при нажатии этой кнопки

### ISSUE THREAD

**Issue by venom159** [vtosters/lite#445]
![upload_2022_07_16_12_32_39_198](https://user-images.githubusercontent.com/109409863/179345169-91acec8f-0297-4a90-9800-2daa72616a4d.jpg)
![upload_2022_07_16_12_33_02_673](https://user-images.githubusercontent.com/109409863/179345178-6a115e6c-2b7f-41f4-8342-e809ae301dbd.jpg)

**Comment by Vologhat** [comment]
Это даже не баг
