### ISSUE TITLE
В последней версии (0.4.0) не работает проски

### ISSUE THREAD

**Issue by Doiredus** [vtosters/lite#446]
В версии 0.4.0 не работает проски zaborona. А также, если зайти в настройки(не включив впн) приложение намертво зависает

**Comment by Vologhat** [comment]
Насколько я понимаю вы находитесь в том месте, где доступ в ВК заблокирован. Как писал сам автор zaborona, его прокси могут быть нестабильны. Для входа в ВК продолжайте использовать впн, либо настраивайте собственные прокси.

**Comment by Doiredus** [comment]
> Насколько я понимаю, вы находитесь в том месте, где доступ в ВК заблокирован. Как писал сам автор zaborona, его прокси могут быть нестабильны. Для входа в ВК продолжайте использовать впн, либо настраивайте собственные прокси.

Да, но сами проски работат, да и в прошлой версии все работало более менее

**Comment by Vologhat** [comment]
Может это является причиной? https://xtrafrancyz.net/unblock-vk 
![image](https://user-images.githubusercontent.com/47892605/179391839-cda4ae98-c92f-4f02-ab76-21ce86681991.png)

**Comment by Doiredus** [comment]
> Может это является причиной? https://xtrafrancyz.net/unblock-vk ![image](https://user-images.githubusercontent.com/47892605/179391839-cda4ae98-c92f-4f02-ab76-21ce86681991.png)

Он к проски zaborona не имеет никакого отношения.

**Comment by Vologhat** [comment]
Попробуйте другие прокси, либо пользуйтесь прошлой версией
