### ISSUE TITLE
Не скачиваются фотографии на телефон

### ISSUE THREAD

**Issue by RikoSakari** [vtosters/lite#447]
При нажатии кнопки "скачать" ничего не происходит

**Comment by Vologhat** [comment]
Попробуйте переустановить клиент, предоставить все разрешения, проверить директорию загрузок и галерею

**Comment by RikoSakari** [comment]
Сделал всё, как сказали, но это ни к чему не привело. Скачал Vtosters обычный, и там всё скачивается
