### ISSUE TITLE
Цвет

### ISSUE THREAD

**Issue by driswerq** [vtosters/lite#451]
Как поменять цвет букв и цифр?

**Comment by Vologhat** [comment]
На данный момент только с помощью модификации исходного кода. Если вы располагаете соответствующими возможностями, то можете попробовать.

**Comment by driswerq** [comment]
> 

А будет ли когда-нибудь добавлена, эта возможность как в втостерсе полном

**Comment by Vologhat** [comment]
Вполне возможно
