### ISSUE TITLE
Неверный ключ API бота и баг с темой milkshake

### ISSUE THREAD

**Issue by AureaFox** [vtosters/lite#452]
Старую версию удалил, новую 0.4.0 поставил. 1) Хотел добавить стикеры из телеги, но при нажатии на плюсик пишет "неверный ключ API бота", при заходе в шестерёнку и нажатии на первое меню - всё успешно удаляется. Но далее всё по кругу, на плюсик - та же ошибка.
2) При активации темы milkshake невозможно попасть в настройки приложения. Ни в профиле, ни где-либо ещё нет возможности добраться до настроек… пришлось удалять и ставить заново.

**Comment by AyonovDenizs** [comment]
Ты точно правильно вставил API ключ?
У меня все работает

**Comment by AyonovDenizs** [comment]
Ответ на 2 вопрос. Настройки в милкшейк теме открываются свайпом влево в профиле

**Comment by AureaFox** [comment]
Я не могу вставить ключ, оно не даёт его вставить СОВСЕМ. Не появляется никаких полей для ввода.

**Comment by gdlbo** [comment]
https://github.com/vtosters/lite/commit/2f30d070ec2cfc086b6c22dd87e2ffed21879dd0
