### ISSUE TITLE
Ошибка загрузки новостной ленты

### ISSUE THREAD

**Issue by Heskkkk** [vtosters/lite#460]
![Screenshot_2022-07-18-22-07-27-310_com vtosters lite](https://user-images.githubusercontent.com/109550640/179597812-2ff89706-0bb0-4612-bacf-b4b6e1820d47.jpg)
 
После обновления на ласт версию не грузит ленту

**Comment by GooDoG337** [comment]
-Не загружаются новости. Вылезает ошибка

Переустановите клиент с нуля. Удалите старую версию и скачайте новую
