### ISSUE TITLE
Проблема со скачиванием.

### ISSUE THREAD

**Issue by themrfire** [vtosters/lite#465]
– Сначала пытается загрузить аудозапись, но потом пишет «Не удалось загрузить аудозапись».
Скриншот:
![Screenshot_20220719-042719_VTLite](https://user-images.githubusercontent.com/73500223/179634086-19a2c66f-696e-489b-bbc5-f631ccbe39f0.jpg)

**Comment by themrfire** [comment]
> – Сначала пытается загрузить аудозапись, но потом пишет «Не удалось загрузить аудозапись».
> Скриншот:
> ![Screenshot_20220719-042719_VTLite](https://user-images.githubusercontent.com/73500223/179634086-19a2c66f-696e-489b-bbc5-f631ccbe39f0.jpg)

Вот это когда поправите?

**Comment by aliveoutside** [comment]
дайте логи как написано тут https://t.me/vtosters_faq/21 (вариант 2)
меню для разработчиков открывается по ссылке vk.com/vt/debug

**Comment by themrfire** [comment]
> дайте логи как написано тут https://t.me/vtosters_faq/21 (вариант 2)
> меню для разработчиков открывается по ссылке https://vk.com/vt/debug

Вот.
VK.log.txt:
UID_USER:552248700
USER_AGENT:VKAndroidApp/7.26-12338 (Android 11; SDK 30; armeabi-v7a; samsung SM-A015F; ru; 1520x720)
VERSION_CODENAME:REL
SDK CODE:30
MANUFACTURER:samsung
MODEL:SM-A015F
BOARD:QC_Reference_Phone
BRAND:samsung
DEVICE:a01q
HARDWARE:qcom
DISPLAY:RP1A.200720.012.A015FXXS5BVC1
VERSIONS:12338


01.08.2022 3:49:35:	229	E	AudioPlayerIpcClient[main] a:71 MusicLog :  LocalSettingChangeCmd available only in DEBUG app! 
01.08.2022 3:49:35:	294	D	QueueLogger[queue-sync-manager-552248700] a:1 Prepare to start sync for 1 queues 
01.08.2022 3:49:35:	296	D	QueueLogger[queue-sync-manager-552248700] a:1 Queues are split into 1 chunks 
01.08.2022 3:49:35:	297	D	QueueLogger[queue-sync-manager-552248700] a:1 Chunks number is 1. Run sync loop on current thread 
01.08.2022 3:49:35:	298	D	QueueLogger[queue-sync-manager-552248700] a:1 [queue-sync-loop-1] loop started 
01.08.2022 3:49:38:	405	I	HeadsetActivityPausedListener[main] onActivityPaused:1 MusicLog :  HSNMan onHostActivityPaused 
01.08.2022 3:49:38:	408	I	HeadsetNotificationManager[main] d:1 MusicLog :  HSNMan hide headset notification 
01.08.2022 3:49:38:	420	I	MusicStoriesPlayer[main] e:1 MusicLog :  
01.08.2022 3:49:38:	425	I	ExoPlayerHelper[main] stop:1 MusicLog :  
01.08.2022 3:49:38:	428	I	ExoPlayerHelper[main] a:3 MusicLog :  
01.08.2022 3:49:38:	430	I	ExoPlayerHelper[main] a:11 MusicLog :  state= STOPPED 
01.08.2022 3:49:38:	448	D	MemLowCapacityCache[main] b:2 AppStateCache TRIM mem: [AppStateCacheEntry(uid=f0dbd3e1-f953-4284-903a-e67836cdd90c_1659307677066, parcelable=com.vk.core.fragments.FragmentNavigationController$FragmentNavigationControllerState@1f462ed, keepAtLeastMs=0, isSavedOnDisk=true), AppStateCacheEntry(uid=dcb44c91-d86e-49cd-b10c-4df5ac4e0b64_1659307678582, parcelable=com.vk.core.fragments.FragmentNavigationController$FragmentNavigationControllerState@1f462ed, keepAtLeastMs=0, isSavedOnDisk=true), AppStateCacheEntry(uid=d7f93062-8c9d-4c0d-9674-ff61773744fa_1659307679639, parcelable=com.vk.core.fragments.FragmentNavigationController$FragmentNavigationControllerState@1f462ed, keepAtLeastMs=0, isSavedOnDisk=true), AppStateCacheEntry(uid=7d2bb97c-fdf8-4310-abcf-0d1990b5edca_1659307680583, parcelable=com.vk.core.fragments.FragmentNavigationController$FragmentNavigationControllerState@1f462ed, keepAtLeastMs=0, isSavedOnDisk=true), AppStateCacheEntry(uid=2542101f-60f5-4123-9c45-a4bdc60051a0_1659307686502, parcelable=com.vk.core.fragments.FragmentNavigationController$FragmentNavigationControllerState@1f462ed, keepAtLeastMs=0, isSavedOnDisk=true), AppStateCacheEntry(uid=c01b78b5-1084-470f-a691-cc0b16b9fae4_1659307724890, parcelable=com.vk.core.fragments.FragmentNavigationController$FragmentNavigationControllerState@1f462ed, keepAtLeastMs=0, isSavedOnDisk=true), AppStateCacheEntry(uid=8a85f905-2a2c-47bb-bae4-663c5ed2126c_1659307735450, parcelable=com.vk.core.fragments.FragmentNavigationController$FragmentNavigationControllerState@b808522, keepAtLeastMs=0, isSavedOnDisk=true), AppStateCacheEntry(uid=3e312da4-2ca1-48f7-ab41-e2fc77375f7d_1659307738213, parcelable=com.vk.core.fragments.FragmentNavigationController$FragmentNavigationControllerState@b808522, keepAtLeastMs=0, isSavedOnDisk=true), AppStateCacheEntry(uid=02f5cf93-5b3f-4785-85ea-48a53c466fd7_1659307770392, parcelable=com.vk.core.fragments.FragmentNavigationController$FragmentNavigationControllerState@b808522, keepAtLeastMs=0, isSavedOnDisk=true)].size to 8 
01.08.2022 3:49:38:	450	D	MemLowCapacityCache[main] a:6 AppStateCache PUT mem: c9c2d13a-1e06-41ef-8868-76fb78413670_1659307778442 
01.08.2022 3:49:38:	453	D	DatabaseCache[main] a:20 AppStateCache PUT store: c9c2d13a-1e06-41ef-8868-76fb78413670_1659307778442 - 3064 bytes 
01.08.2022 3:49:39:	408	I	AppStateTracker$j[main] run:1 ==== ENTER BACKGROUND ==== 01.08.2022 3:49:39:	409	D	QueueLogger
[queue-sync-manager-552248700] a:1 [queue-sync-loop-1] loop stopped by reason: java.lang.InterruptedException: request interrupted 
01.08.2022 3:49:39:	411	D	AppUseTime[main] b:16 close_app 1659307778404 
01.08.2022 3:49:39:	469	V	JobsLogger[main] a:1 app status is BACKGROUND 
01.08.2022 3:49:39:	473	V	JobsLogger[main] a:1 app status is BACKGROUND 
01.08.2022 3:49:43:	760	W	ImApi<-- 200 https://api.vk.com/ruim552248700?act=a_check&key=<HIDE>&ts=1724425418&wait=25&mode=746&version=10 (25563ms, 47-byte body)
01.08.2022 3:49:43:	767	D	ImTaskExecutor[BG]executing 'UsersGetByIdCmd(ids=[], source=CACHE, awaitNetwork=false, changerTag=null)' on 'im-long-poll-sync-thread' queue
01.08.2022 3:49:43:	770	V	ImTaskExecutor[BG]succeed 'UsersGetByIdCmd(ids=[], source=CACHE, awaitNetwork=false, changerTag=null)' (3 ms)
01.08.2022 3:49:43:	776	D	ImLongPollSyncThreadignoring sync state change: state not changed CONNECTED
01.08.2022 3:49:43:	779	V	ImLongPollSyncThreadrequest long poll live with timeout 25000
01.08.2022 3:49:43:	785	W	ImApi--> GET https://api.vk.com/ruim552248700?act=a_check&key=<HIDE>&ts=1724425418&wait=25&mode=746&version=10
01.08.2022 3:49:45:	123	D	UITrackingActivity[main] onActivityResumed:2 UiTracker: onActivityStarted FragmentWrapperActivity 
01.08.2022 3:49:45:	144	D	ImAudioMsgPlayerProvider[main] e:2 Stop AudioMsgPlayer foreground service 
01.08.2022 3:49:45:	147	I	AppStateTracker[main] a:11 ==== LEAVE BACKGROUND ==== 
01.08.2022 3:49:45:	149	D	AppUseTime[main] a:30 open_app 1659307785147 
01.08.2022 3:49:45:	172	D	BenchmarkTracker[main] k:2 Ping service Service is waking up and checking ping conditions 
01.08.2022 3:49:45:01.08.2022 3:49:	17445:	I	174	D	HeadsetAppResumedListener01.08.2022 3:49:45:01.08.2022 3:49:	17445:	I	174	D	HeadsetAppResumedListener	BenchmarkTracker$d[main] a:2 MusicLog :  HSNMan onAppResumed [vk-network-thread-4] run:3 Ping service Service is not needed now. Suspending... 

01.08.2022 3:49:45:	175	I	HeadsetNotificationManager[main] a:25 MusicLog :  HSNMan isNotificationRequestedInBg: false isPlayingMusic: false 
01.08.2022 3:49:45:	207	V	JobsLogger[main] a:1 app status is FOREGROUND_UI 
01.08.2022 3:49:45:	208	V	JobsLogger[main] a:1 app status is FOREGROUND_UI 
01.08.2022 3:49:45:	217	D	ImEngine#startBgSync - subscriber added: com.vtosters.lite=SyncInfo(bgSyncMode=FULL, cause=APP_RESUME), all subscribers: {com.vtosters.lite=SyncInfo(bgSyncMode=FULL, cause=APP_RESUME)}
01.08.2022 3:49:45:	218	D	ImEngine#doStartBgSync. SyncMode: FULL. Restart cause: null. Start cause: subscriber added: com.vtosters.lite=SyncInfo(bgSyncMode=FULL, cause=APP_RESUME), all subscribers: {com.vtosters.lite=SyncInfo(bgSyncMode=FULL, cause=APP_RESUME)}
01.08.2022 3:49:45:	219	D	ImEngineIgnoring request to startLongPoll for ImEnvironment. Reason: already started before
01.08.2022 3:49:45:	312	I	MenuCounterUpdater$subscribeForCountersUpdates$1[queue-sync-manager-552248700] invoke:2 Subscribing to UpdateCountersQueueEvent 
01.08.2022 3:49:46:	136	I	HeadsetActivityPausedListener[main] onActivityPaused:1 MusicLog :  HSNMan onHostActivityPaused 
01.08.2022 3:49:46:	137	I	HeadsetNotificationManager[main] d:1 MusicLog :  HSNMan hide headset notification 
01.08.2022 3:49:46:	139	I	MusicStoriesPlayer[main] e:1 MusicLog :  
01.08.2022 3:49:46:	142	I	ExoPlayerHelper[main] stop:1 MusicLog :  
01.08.2022 3:49:46:	144	I	ExoPlayerHelper[main] a:3 MusicLog :  
01.08.2022 3:49:46:	146	I	ExoPlayerHelper[main] a:11 MusicLog :  state= STOPPED 
01.08.2022 3:49:46:	158	D	QueueLogger[queue-sync-manager-552248700] a:1 Prepare to start sync for 1 queues 
01.08.2022 3:49:46:	159	D	QueueLogger[queue-sync-manager-552248700] a:1 Queues are split into 1 chunks 
01.08.2022 3:49:46:	160	D	QueueLogger[queue-sync-manager-552248700] a:1 Chunks number is 1. Run sync loop on current thread 
01.08.2022 3:49:46:	161	D	QueueLogger[queue-sync-manager-552248700] a:1 [queue-sync-loop-1] loop started 
01.08.2022 3:49:46:	176	D	UITrackingActivity[main] onActivityResumed:2 UiTracker: onActivityStarted MainActivity 
01.08.2022 3:49:46:	178	I	AppStateTracker[main] a:11 ==== LEAVE BACKGROUND ==== 
01.08.2022 3:49:46:	180	I	HeadsetAppResumedListener[main] a:2 MusicLog :  HSNMan onAppResumed 
01.08.2022 3:49:46:	183	I	HeadsetNotificationManager[main] a:25 MusicLog :  HSNMan isNotificationRequestedInBg: false isPlayingMusic: false 
01.08.2022 3:49:46:	192	D	ImTaskExecutor[BG]executing 'DialogsCountTotalCmd(filters=[UNREAD, REQUESTS], excludeDisabled=true, source=CACHE, isAwaitNetwork=false, changerTag=MenuCounterUpdater)' on 'im-tasks-pool-thread-4' queue
01.08.2022 3:49:46:	194	D	ImTaskExecutor[BG]executing 'DialogsFilterEnabledCmd(filter=UNREAD, source=CACHE, isAwaitNetwork=false, changerTag=MenuCounterUpdater)' on 'im-tasks-pool-thread-4' queue
01.08.2022 3:49:46:	200	V	ImTaskExecutor[BG]succeed 'DialogsFilterEnabledCmd(filter=UNREAD, source=CACHE, isAwaitNetwork=false, changerTag=MenuCounterUpdater)' (6 ms)
01.08.2022 3:49:46:	202	D	ImTaskExecutor[BG]executing 'DialogsCountGetCmd(filter=UNREAD, source=CACHE, isAwaitNetwork=false)' on 'im-tasks-pool-thread-4' queue
01.08.2022 3:49:46:	205	V	ImTaskExecutor[BG]succeed 'DialogsCountGetCmd(filter=UNREAD, source=CACHE, isAwaitNetwork=false)' (3 ms)
01.08.2022 3:49:46:	207	D	ImTaskExecutor[BG]executing 'DialogsFilterEnabledCmd(filter=REQUESTS, source=CACHE, isAwaitNetwork=false, changerTag=MenuCounterUpdater)' on 'im-tasks-pool-thread-4' queue
01.08.2022 3:49:46:	208	V	ImTaskExecutor[BG]succeed 'DialogsFilterEnabledCmd(filter=REQUESTS, source=CACHE, isAwaitNetwork=false, changerTag=MenuCounterUpdater)' (1 ms)
01.08.2022 3:49:46:	209	D	ImTaskExecutor[BG]executing 'DialogsCountGetCmd(filter=REQUESTS, source=CACHE, isAwaitNetwork=false)' on 'im-tasks-pool-thread-4' queue
01.08.2022 3:49:46:	212	V	ImTaskExecutor[BG]succeed 'DialogsCountGetCmd(filter=REQUESTS, source=CACHE, isAwaitNetwork=false)' (3 ms)
01.08.2022 3:49:46:	214	V	ImTaskExecutor[BG]succeed 'DialogsCountTotalCmd(filters=[UNREAD, REQUESTS], excludeDisabled=true, source=CACHE, isAwaitNetwork=false, changerTag=MenuCounterUpdater)' (22 ms)
01.08.2022 3:49:46:	297	D	UITrackingActivity[main] onActivityDestroyed:2 UiTracker: onActivityDestroyed FragmentWrapperActivity 
01.08.2022 3:49:47:	15	D	AppUseTime[main] b:8 open menu 1659307787014 
01.08.2022 3:49:48:	484	D	AppUseTime[main] b:8 open audio 1659307788484 
01.08.2022 3:49:48:	500	D	AppUseTime[main] a:24 close menu 1659307788500 menu 
01.08.2022 3:49:48:	515	I	MusicModelImpl[main] a:16 MusicLog :  loadOwner:  true , loadPlaylists:  true , audioOffset:  0 , audioCount:  200 owner: 552248700 
01.08.2022 3:49:49:	918	I	MusicModelImpl$d[main] a:2 MusicLog :  AudioGetMusicPage  request success with result:  tracks:  197 
01.08.2022 3:49:50:	210	I	MusicSectionsModelImpl$c[main] a:3 MusicLog :  MusicSectionsRequester3  request success  
01.08.2022 3:49:50:	436	I	MusicSectionsModelImpl[main] l:1 MusicLog :  
01.08.2022 3:49:51:	955	I	MusicSectionsModelImpl$e[main] a:4 MusicLog :  MusicSectionsRequester3  request success  
01.08.2022 3:49:59:	553	D	AppUseTime[main] b:8 open menu 1659307799553 
01.08.2022 3:49:59:	568	D	AppUseTime[main] a:24 close audio 1659307799567  
01.08.2022 3:50:0:	729	D	AppUseTime[main] a:24 close menu 1659307800728 menu 
01.08.2022 3:50:2:	34	I	HeadsetActivityPausedListener[main] onActivityPaused:1 MusicLog :  HSNMan onHostActivityPaused 
01.08.2022 3:50:2:	37	I	HeadsetNotificationManager[main] d:1 MusicLog :  HSNMan hide headset notification 
01.08.2022 3:50:2:	41	I	MusicStoriesPlayer[main] e:1 MusicLog :  
01.08.2022 3:50:2:	45	I	ExoPlayerHelper[main] stop:1 MusicLog :  
01.08.2022 3:50:2:	46	I	ExoPlayerHelper[main] a:3 MusicLog :  
01.08.2022 3:50:2:	47	I	ExoPlayerHelper[main] a:11 MusicLog :  state= STOPPED 
01.08.2022 3:50:2:	68	D	UITrackingActivity[main] onActivityCreated:2 UiTracker: onActivityCreated FragmentWrapperActivity 
01.08.2022 3:50:2:	77	D	UiTracker[main] a:5 get tracking listener on activity=com.vtosters.lite.FragmentWrapperActivity@4dc5418 
01.08.2022 3:50:2:	83	I	ExoPlayerHelper[main] a:11 MusicLog :  state= STOPPED 
01.08.2022 3:50:2:	85	I	ExoPlayerHelper[main] g:2 MusicLog :  player= null 
01.08.2022 3:50:2:	178	D	UITrackingActivity[main] onActivityResumed:2 UiTracker: onActivityStarted FragmentWrapperActivity 
01.08.2022 3:50:2:	180	I	AppStateTracker[main] a:11 ==== LEAVE BACKGROUND ==== 
01.08.2022 3:50:2:	181	I	HeadsetAppResumedListener[main] a:2 MusicLog :  HSNMan onAppResumed 
01.08.2022 3:50:2:	183	I	HeadsetNotificationManager[main] a:25 MusicLog :  HSNMan isNotificationRequestedInBg: false isPlayingMusic: false 
01.08.2022 3:50:2:	433	D	MemLowCapacityCache[main] b:2 AppStateCache TRIM mem: [AppStateCacheEntry(uid=dcb44c91-d86e-49cd-b10c-4df5ac4e0b64_1659307678582, parcelable=com.vk.core.fragments.FragmentNavigationController$FragmentNavigationControllerState@1f462ed, keepAtLeastMs=0, isSavedOnDisk=true), AppStateCacheEntry(uid=d7f93062-8c9d-4c0d-9674-ff61773744fa_1659307679639, parcelable=com.vk.core.fragments.FragmentNavigationController$FragmentNavigationControllerState@1f462ed, keepAtLeastMs=0, isSavedOnDisk=true), AppStateCacheEntry(uid=7d2bb97c-fdf8-4310-abcf-0d1990b5edca_1659307680583, parcelable=com.vk.core.fragments.FragmentNavigationController$FragmentNavigationControllerState@1f462ed, keepAtLeastMs=0, isSavedOnDisk=true), AppStateCacheEntry(uid=2542101f-60f5-4123-9c45-a4bdc60051a0_1659307686502, parcelable=com.vk.core.fragments.FragmentNavigationController$FragmentNavigationControllerState@1f462ed, keepAtLeastMs=0, isSavedOnDisk=true), AppStateCacheEntry(uid=c01b78b5-1084-470f-a691-cc0b16b9fae4_1659307724890, parcelable=com.vk.core.fragments.FragmentNavigationController$FragmentNavigationControllerState@1f462ed, keepAtLeastMs=0, isSavedOnDisk=true), AppStateCacheEntry(uid=8a85f905-2a2c-47bb-bae4-663c5ed2126c_1659307735450, parcelable=com.vk.core.fragments.FragmentNavigationController$FragmentNavigationControllerState@b808522, keepAtLeastMs=0, isSavedOnDisk=true), AppStateCacheEntry(uid=3e312da4-2ca1-48f7-ab41-e2fc77375f7d_1659307738213, parcelable=com.vk.core.fragments.FragmentNavigationController$FragmentNavigationControllerState@b808522, keepAtLeastMs=0, isSavedOnDisk=true), AppStateCacheEntry(uid=02f5cf93-5b3f-4785-85ea-48a53c466fd7_1659307770392, parcelable=com.vk.core.fragments.FragmentNavigationController$FragmentNavigationControllerState@b808522, keepAtLeastMs=0, isSavedOnDisk=true), AppStateCacheEntry(uid=c9c2d13a-1e06-41ef-8868-76fb78413670_1659307778442, parcelable=com.vk.core.fragments.FragmentNavigationController$FragmentNavigationControllerState@b808522, keepAtLeastMs=0, isSavedOnDisk=true)].size to 8 
01.08.2022 3:50:2:	435	D	MemLowCapacityCache[main] a:6 AppStateCache PUT mem: 964e29a5-ddc6-40aa-b61e-53ed2a17acf4_1659307802433 
01.08.2022 3:50:2:	436	D	DatabaseCache[main] a:20 AppStateCache PUT store: 964e29a5-ddc6-40aa-b61e-53ed2a17acf4_1659307802433 - 4232 bytes

**Comment by aliveoutside** [comment]
> Вот.

это точно все логи? Тогда в том же дебаг меню включите "Режим разработчика" (там подписано "форсирование аккаунта разработчика бла-бла-бла"), перезапустите приложения и снова запишите логи, затем отправьте мне их в лс файлом https://vk.com/hitriy_ximi
сюда лучше не кидать ибо может быть конфиндециальная информация
