### ISSUE TITLE
VK Pay не убирается из SuperApp

### ISSUE THREAD

**Issue by wetakor** [vtosters/lite#471]
![Screenshot_2022-07-19-21-17-44-184_com.vtosters.lite.jpg](https://user-images.githubusercontent.com/97191872/179821160-76c116c2-b1ed-4418-b4c3-81bfc0fa8ae4.jpg)
![Screenshot_2022-07-19-21-17-52-778_com.vtosters.lite.jpg](https://user-images.githubusercontent.com/97191872/179821178-16433a41-850f-4150-8101-36caf1317ed5.jpg)

VK Pay - отмечено что убран из SuperApp. Но на скриншоте видно что, все таки он присутствует.

**Comment by gdlbo** [comment]
![Screenshot_20220719-214114_VTLite](https://user-images.githubusercontent.com/41114720/179825002-7e280a0c-8591-4bcd-9ede-bd71e3630b6b.png)
Отключи просто суперапп и всё..........
