### ISSUE TITLE
Не отображаются мои плейлисты в моей музыке, только треки. 

### ISSUE THREAD

**Issue by Srgeymot** [vtosters/lite#475]
Если выбрать вкладку музыка, далее моя музыка, то там только треки, а плейлистов добавленых в мою музыку нет.

**Comment by GooDoG337** [comment]
-Не нашел/нашла свои плейлисты в музыке

Отключите новый раздел музыки в настройках Медиа контента

Позже это будет исправлено

**Comment by aliveoutside** [comment]
#420
