### ISSUE TITLE
Самое неудобное оформление отключения в superapp

### ISSUE THREAD

**Issue by kofemolochka** [vtosters/lite#480]
Много раз пытаюсь свайпнуть по тексту в разные стороны и никак не получается убрать пункт т.к. появляется анимация назад, лучше сделать в таком же стиле но не со свайпами. Предлагаю сделать так: зажать и потянуть вниз либо в пункте возле текста кнопка "-" и "+", так будет проще.
![Screenshot_20220721-041144~2](https://user-images.githubusercontent.com/109287107/180098175-19e0655f-e887-4dc4-91a8-636f98b3c4c1.png)

**Comment by Vologhat** [comment]
Отключите эту анимацию, если у вас такая проблема. Свайп работает нормально, это проблема исключительно вашего устройства. Мы подумаем над добавлением кнопок у пунктов

**Comment by aliveoutside** [comment]
свайп работает только для элементов, которые нельзя перемещать (меню приложения, например), но посмотрим можно ли будет сделать для всех

**Comment by Vologhat** [comment]
21c0ccd9fcb904232e863196de175c00a95e235d
