### ISSUE TITLE
Невозможно скачать изображения

### ISSUE THREAD

**Issue by RikoSakari** [vtosters/lite#484]
При попытке скачивания изображений в VTosters lite ничего не происходит. Такая де проблема была в предыдущей версии . Пробовал переустановить клиент, пробовал разные настройки, но результата нет. При этом в обычном VToster скачивание происходит. Приходится пользоваться новой функцией "оригинал фото" и скачивать через браузер, но это крайне неудобно.

**Comment by wetakor** [comment]
Изображения скачиваются, но в /Внутренняя Память/VK
