### ISSUE TITLE
В меню "Обзор" ничего нет

### ISSUE THREAD

**Issue by 7R1K4S** [vtosters/lite#487]
При попытке открытия этого меню в последней версии, там ничего не появляется.
![Screenshot_2022-07-21-00-02-19-18_9e1a5d6211a0228d32d39446541891f1](https://user-images.githubusercontent.com/75484759/180153181-67e178fb-2e27-428c-8322-f6127ab88f0a.jpg)

**Comment by gdlbo** [comment]
Скачай 0.4.2 с Github ещё раз
