### ISSUE TITLE
С обновления 0.4.0 перестал работать прокси

### ISSUE THREAD

**Issue by deadssamurai** [vtosters/lite#490]
Прокси от zaborona раньше нормально работал. Начиная с версии 0.4.0 перестал совершенно. Можно ли добавить хотя бы какой рабочий?

**Comment by AyonovDenizs** [comment]
А VPN юзать пока не пофиксили, не?

**Comment by deadssamurai** [comment]
> А VPN юзать пока не пофиксили, не?

Очень логично, и как я сам не додумался? 
Только вот это всё равно баг, который мешает комфортному использованию приложения. 🤷🏻‍♂️

**Comment by gdlbo** [comment]
https://github.com/vtosters/lite/issues/505
