### ISSUE TITLE
Бесконечный "запрос данных" в активности и незагрузка северных ф-ций

### ISSUE THREAD

**Issue by theKunda** [vtosters/lite#491]
Здравствуйте, столкнулся с такой проблемой. Идёт вечный запрос данных (ниже скриншот) при нажатии на вкладку "активность", пробовал переустанавливать клиент, + менять VPN/сервера, ничего не помогло
![Screenshot_20220721_154204](https://user-images.githubusercontent.com/67816756/180217428-e851ad2a-65c6-4708-b4ec-094224064482.jpg)
+ подобная ситуация с вкладкой "северные функции"
![Screenshot_20220721_154215](https://user-images.githubusercontent.com/67816756/180217520-4279250e-5978-4784-9017-bd1babb61e50.jpg)

**Comment by GooDoG337** [comment]
1.Это Втостерс Лайт.
2.ВТостер сдох, так что хоть он полностью не работает, это уже никого не едет
3.Читай фаг
Что делать если у вас не работает вкладка "Активность" в VTosters?

К сожалению старый VTosters больше не поддерживается и работает "как есть" до тех пор, пока не перестанет полностью работать


Если вам необходимо отключить/включить невидимку/был недавно в сети - Скачайте приложение play.google.com/store/apps/details?id=com.vk.im

Если вам нужен оффлайн/нечиталки и прочие полезные функции из основного VTosters - скачайте VTLite который находится в активной разработке

Скачать VTLite - vtosters.app

**Comment by theKunda** [comment]
> 1.Это Вотстерс Лайт. 2.ВТостер сдох, так что хоть он полностью не работает, это уже никого не едет 3.Читай фаг Что делать если у вас не работает вкладка "Активность" в VTosters?
> 
> К сожалению старый VTosters больше не верит и работает "как есть" до тех пор, пока не перестанет полностью работать
> 
> Если вам необходимо открыть/включить видимку/была добавлена ​​в сеть - скачать приложение play.google.com/store/apps/details?id=com.vk.im
> 
> Если вам нужен оффлайн/нечиталки и другие полезные функции из основных VTosters - скачайте VTLite, который находится в активной разработке
> 
> Скачать VTLite - vtosters.app

**Comment by AyonovDenizs** [comment]
> Здравствуйте, столкнулся с такой проблемой. Идёт вечный запрос данных (ниже скриншот) при нажатии на вкладку "активность", пробовал переустанавливать клиент, + менять VPN/сервера, ничего не помогло ![Screenshot_20220721_154204](https://user-images.githubusercontent.com/67816756/180217428-e851ad2a-65c6-4708-b4ec-094224064482.jpg)
> 
> * подобная ситуация с вкладкой "северные функции"
>   ![Screenshot_20220721_154215](https://user-images.githubusercontent.com/67816756/180217520-4279250e-5978-4784-9017-bd1babb61e50.jpg)

ВТостерс обычный умер. Юзай ВТЛайт и прочитай [коммент](https://github.com/vtosters/lite/issues/491#issuecomment-1191450325) выше
