### ISSUE TITLE
Забагалась недавно

### ISSUE THREAD

**Issue by Motoland140** [vtosters/lite#494]
Пользовался раньше приложением Втостерс использовал функцию скрытия онлайна чтобы писалось в строке онлайна "Недавно", позже Втостерс сломался сколько пытался никак не могу убрать это, и через втостерслайт пытался эту функцию убрать ничего не помогает

**Comment by deadssamurai** [comment]
Это убирается только через приложение VK me, в настройках приватности нужно выбрать, кому видно онлайн. А не через любые другие приложения.

**Comment by Motoland140** [comment]
Спасибо большое
