### ISSUE TITLE
Не работает лента 

### ISSUE THREAD

**Issue by vinc09333** [vtosters/lite#496]
Начинания с версии 0.4.0 не работает лента от слова совсем, устройство Huawei p20 lite 
![Screenshot_20220722_064009_com vtosters lite](https://user-images.githubusercontent.com/45268327/180357682-d78fa831-c554-46bc-994d-60099a997235.jpg)

**Comment by gdlbo** [comment]
Переустанови приложение

**Comment by vinc09333** [comment]
Уже делал

**Comment by vinc09333** [comment]
Разобрался, при удалении приложения его данные остаются на телефоне, а если обновлелся через ОТА возникает этот баг. Выход: приложение не удалять просто очистить данные приложения и кеш
