### ISSUE TITLE
Визуальная проблема связаная со входом в беседу

### ISSUE THREAD

**Issue by VanPlay** [vtosters/lite#498]
Если входить в беседу через личные сообщения, то чат беседы отображается поверх прошлого чата (личных сообщений).
![Screenshot_20220722_153606_com vtosters lite](https://user-images.githubusercontent.com/102915929/180442399-abb51b33-eabd-4e46-910e-36b86d242f16.jpg)

**Comment by AyonovDenizs** [comment]
Баг вк? Да

**Comment by wetakor** [comment]
По-моему это баг самого ВК, а не клиента
