### ISSUE TITLE
Краш из-за анимированных стикеров

### ISSUE THREAD

**Issue by aliveoutside** [vtosters/lite#5]
При отправке стикеров или написании "хз", "да" и прочего - вылезают предложения стикеров, из-за которых аппа падает

**Comment by Constantinkos** [comment]
Читал комментарии и приложение вылетело...

**Comment by gdlbo** [comment]
https://t.me/vtosters_faq/80

**Comment by AlexMercier** [comment]
@gdlbo 
Последняя версия 0.1.4 всё ещё крашится.
Лог ошибки:
https://hastebin.com/otiwodiwac

Набор стикеров - сберкот, больше чем кот.
![IMG_20220423_014650_017](https://user-images.githubusercontent.com/6580198/164814353-667c35f7-aa62-45ff-8826-1604ee05e9ef.jpg)

**Comment by UserNhammen** [comment]
Missing values for keyframe

**Comment by UserNhammen** [comment]
Missing values for keyframe
https://foxbin.f0x1d.com/NUvNrZsUN2
Redmi Note 9 Pro, MIUI 12, Android 11, 2.0 Beta.
Зайти в чат с анимированных стикером
