### ISSUE TITLE
Не работает прокси Zaborona

### ISSUE THREAD

**Issue by gdlbo** [vtosters/lite#505]

**Comment by realkalash** [comment]
При чём в старой версии (до 0.4.0) он работает. Значит это баг где-то на уровне приложения.

**Comment by realkalash** [comment]
Так же проверил Custom Proxy забороны через SOCKS 5 (https://zaborona.help/extra.html). 

На новых версиях приложение не грузит данные, на старой 3.0 всё работает работает.
