### ISSUE TITLE
VTlite ошибка при попытке подарить стикеры

### ISSUE THREAD

**Issue by EllmaxYT** [vtosters/lite#507]
"произошла ошибка на сервере. Повторите попытку позже"

Покупка стикеров работает, не получается только подарить 

![Screenshot_2022-07-25-13-40-44-329_com vtosters lite](https://user-images.githubusercontent.com/109958355/180759629-e6861584-c902-46c6-9b28-82862caa50c0.jpg)

**Comment by k1zn** [comment]
@gdlbo 
Новый VK 7.* получает превью подарка набора стикеров с помощью метода `store.prepareStickersOrder`
Его аргументы:

**product_ids** (айди набора стикеров), 
**recipient_ids** (скорее всего кому набор дарится, если открыть меню просто так этот аргумент пуст), 
device_id, lang, https

Когда VTLite вместо него пытается использовать ((возможно уже устаревший)) метод `execute.getGiftByStickerId` (https, sticker_id, no_inapp, lang, force_payment, device_id) который при любом значении sticker_id возвращает:
![](https://user-images.githubusercontent.com/46452865/180878115-15b6dbd8-1005-494d-b03f-1ab6ba720f58.png)
