### ISSUE TITLE
Не отображается автарка профиля в разделе VT Функции

### ISSUE THREAD

**Issue by hiterra** [vtosters/lite#513]
![Screenshot_20220726-002127_VTLite](https://user-images.githubusercontent.com/103932997/180876937-9a534a2b-cf6c-4a19-94f8-cfcda15ce8b4.png)
Не критично, но тем не менее не красиво

**Comment by AyonovDenizs** [comment]
Косяку более месяца

**Comment by k1zn** [comment]
@gdlbo @aliveoutside исправлено

**Comment by aliveoutside** [comment]
fixed
