### ISSUE TITLE
закреп диалогов

### ISSUE THREAD

**Issue by Tem-178Rus** [vtosters/lite#529]
Добавьте пожалуйста закреп диалогов,
очень не хватает) 
только из за отсутствия этой фишечки сижу на СОВЕ
как добавите, перейду на VT_Lite ))
спасибо)

**Comment by k1zn** [comment]
#12 

в следующей обнове появится фикс того, что они не отображаются
но пока они все еще не будут закреплены

**Comment by aliveoutside** [comment]
#12
