### ISSUE TITLE
Возможность удалять историю просмотров.

### ISSUE THREAD

**Issue by themrfire** [vtosters/lite#551]
Добавьте возможность удалять историю просмотров в разделе «Видео», пожалуйста.
Скриншот из официального приложения:
![Screenshot_20220731-195453_VK Tea.jpg](https://user-images.githubusercontent.com/73500223/182032284-ee224a93-c350-4daa-8006-4f53e3902d47.jpg)

**Comment by k1zn** [comment]
#c7621c44d5ad3729a7aa225caf89f9b230298ac1
