### ISSUE TITLE
Не работает кнопка "Подарить" в стикерах

### ISSUE THREAD

**Issue by blazee5** [vtosters/lite#553]
При нажатии на кнопку "Подарить" появляется загрузка и сразу исчезает, после ожидания ничего не появляется.
![IMG_20220731_223317](https://user-images.githubusercontent.com/109062318/182036289-c847bc8b-647e-4409-9cc4-a4c084f9b396.jpg)

**Comment by k1zn** [comment]
в следующем обновлении фикс + дубликат 507
@gdlbo @aliveoutside
