### ISSUE TITLE
Скачивание музыки.

### ISSUE THREAD

**Issue by themrfire** [vtosters/lite#557]
Второй раз прошу Вас, исправьте скачивание музыки, пожалуйста.
Скриншот:
![Screenshot_20220801-032114_VTLite.jpg](https://user-images.githubusercontent.com/73500223/182047589-454c6f80-9dda-4cd6-a23c-a4537d5f2dc5.jpg)

**Comment by aliveoutside** [comment]
не нужно создавать дубликаты 
#465
