### ISSUE TITLE
Траблы с музыкой

### ISSUE THREAD

**Issue by mollyChan03** [vtosters/lite#558]
Заходя в вк тостер в раздел музыки высвечивается ошибка. Просто ошибка - без номера, без лишних слов. Произошло это после сброса настроек телефона. Подскажите пожалуйста, как решить данную проблему

**Comment by gdlbo** [comment]
Используй втлайт

**Comment by neaxesa** [comment]
![Screenshot_2022-08-02-14-39-48-703_com vtosters lite](https://user-images.githubusercontent.com/110451946/182331683-c68fb394-0bbc-4129-9e5c-ef768df12950.png)
![IMG_20220802_143957](https://user-images.githubusercontent.com/110451946/182331697-7e46e19e-59ee-4a2d-b3cc-bf031fafd5ca.jpg)
отключи "защита от подозрительных приложений"
самый лучший способ это скачать втлайт
