### ISSUE TITLE
ᅠ

### ISSUE THREAD

**Issue by themrfire** [vtosters/lite#561]

**Comment by neaxesa** [comment]
![IMG_20220802_205658](https://user-images.githubusercontent.com/110451946/182405960-64df3e8f-5ddd-49a8-9d4c-bd61d388fa21.jpg)
пост со стены можно архивировать

**Comment by themrfire** [comment]
> ![IMG_20220802_205658](https://user-images.githubusercontent.com/110451946/182405960-64df3e8f-5ddd-49a8-9d4c-bd61d388fa21.jpg)
> пост со стены можно архивировать 

В разделе «Сообщения» не хватает этой функции.
