### ISSUE TITLE
Пропадают сообщения 

### ISSUE THREAD

**Issue by keika125** [vtosters/lite#564]
Иногда при любом взаимодействии пропадают сообщения (удаляются последние несколько десятков)

пропадать могут когда заходишь в чат, отправляешь сообщение или его удаляешь

[https://youtube.com/shorts/uMsT-Ld04bo?feature=share]()

**Comment by aliveoutside** [comment]
вероятно исправлено в 91bfea9917a645fac59194c5cccdf90f0afb1064

проверь [сборку с GitHub Actions](https://github.com/vtosters/lite/actions/runs/2800401615)
