### ISSUE TITLE
Не открывается комментарий

### ISSUE THREAD

**Issue by Freggly** [vtosters/lite#568]
"Ваш комментарий понравился..." в уведомлениях, после нажатия ничего не открывается. Если приложение открыто, то комментарий открывается.

**Comment by Freggly** [comment]
а видео никак не прикрепить, что-ли?

**Comment by k1zn** [comment]
ну загрузи на ютуб если не можешь сюда

**Comment by Freggly** [comment]
https://youtube.com/shorts/OvET-bgvrc4
