### ISSUE TITLE
Обход скрытия онлайна

### ISSUE THREAD

**Issue by stasgars** [vtosters/lite#57]
Когда я скрываю онлайн, я так же не вижу онлайн других пользователей. Можно сделать обход, который реализован в вк некст. Как я понимаю, он через аккаунт посредник собирает данные об онлайне и пересылает их мне. Будет очень полезно на телефоне, т.к такого у других на такой же платформе нету!

**Comment by gdlbo** [comment]
Обход уже давно есть же

**Comment by stasgars** [comment]
Увидел только обход в беседах. Ну может это то и есть. Спасибо.
