### ISSUE TITLE
вирус

### ISSUE THREAD

**Issue by tiititi** [vtosters/lite#570]
Сбербанк онлайн обнаружил несколько минут назад вирус![Screenshot_2022-08-04-20-37-49-660_ru.sberbankmobile.png](https://user-images.githubusercontent.com/75739675/182915321-1bedb9b6-8612-49d6-b22c-21a957f30025.png)

**Comment by inotflying** [comment]
Фича

**Comment by aliveoutside** [comment]
жалуйтесь сберу
https://www.virustotal.com/gui/file/92ffbfc2c5567d161b502ad6ea769c00c4625c2c4701a3326ae385925116525d
