### ISSUE TITLE
Краш приложения от обоев в чате

### ISSUE THREAD

**Issue by Al-anal** [vtosters/lite#572]
устройство samsung galaxy s22 ultra, при выборе фильторв, которые помечены надписью - "могут нагружать устройство" приложение зависает и крашится (зависает клиент, появляется черный экран и приложение останавливается). Так же после перезахода невозможно убрать этот фильтр и зайти на диалог - оба этих действия ведут к крашу. Помогает только сброс всех данных с приложения

**Comment by k1zn** [comment]
Нужны логи

**Comment by gdlbo** [comment]
https://github.com/vtosters/lite/commit/9fa8df30eb152b18c579f72c0db268b18cea3d61
