### ISSUE TITLE
Material You

### ISSUE THREAD

**Issue by rustzz** [vtosters/lite#573]
Хотелось бы в скорем времени, когда все цветовые схемы будут работать хорошо, увидеть поддержку динамической цветовой схемы.

К примеру малую часть: изменение иконок докбара и кнопок под цвет обоев, цвет сообщений.

Пусть даже не поменяется бэкграунд, но элементы хотелось бы видеть в единой цветовой палитре системы.

**Comment by aliveoutside** [comment]
в планах
