### ISSUE TITLE
Недоступны статьи сообществ только для их участников

### ISSUE THREAD

**Issue by vadimpaj** [vtosters/lite#575]
Невозможно читать статьи, доступные только подписчикам сообщества.
Например вот тут https://vk.com/deadinsideteam1337
![Screenshot_20220806-225405_VTLite](https://user-images.githubusercontent.com/10154706/183264292-e69ad905-c1da-4e90-9a43-9a7171a61a73.png)

VTLite 0.4.4
Android 10

**Comment by vadimpaj** [comment]
v0.4.7 проблема решена

**Comment by k1zn** [comment]
@vadimpaj Нихуя
