### ISSUE TITLE
Музыка не работает

### ISSUE THREAD

**Issue by Lozzin** [vtosters/lite#58]
Не работает музыка
![Screenshot_2022-03-28-02-14-00](https://user-images.githubusercontent.com/102478635/160290852-dc10fb8d-b67d-4a4d-bba1-e7a2efba0dcb.png)

**Comment by gdlbo** [comment]
Очистка данных приложения в помощь

**Comment by Grempak** [comment]
У меня музыка работает, но да, при темной теме внизу не видно названия песни
