### ISSUE TITLE
Синтатическая ошибка, при установки приложение 

### ISSUE THREAD

**Issue by Tropi4555** [vtosters/lite#584]
На моем устройстве не возможно установить данное приложение, но до версии 40 раньше все работало. Как только вышло релиз 40 и дальше версии которые выходят, не могу установить себе, так как ошибку выдает при установки. У меня модель телефона аsus zenfone 2 550kl андроид 5.1 Не хочется устанавливать старую версию, хочется новую установить :с 
Надеюсь поможете с данной проблемой и решите как-то. Больше клиентов наподобие не могу найти, так как это самое лучшее приложение и давно очень пользуюсь

**Comment by k1zn** [comment]
После перехода на новую базу приложение теперь требует андроид 7.0

**Comment by abslike** [comment]
прошив с 7.0 дроидом в помощь🤪

**Comment by Tropi4555** [comment]
> После перехода на новую базу приложение теперь требует андроид 7.0

а говорили, что данная версия со старыми версии андроида. Мда конечно

**Comment by Tropi4555** [comment]
> прошив с 7.0 дроидом в помощь🤪

сложно :с

**Comment by k1zn** [comment]
@Tropi4555  со следующей версии заработает

**Comment by Tropi4555** [comment]
> @Tropi4555 со следующей версии заработает

да нечего не поменялась, видимо что-то не так на моем телефоне. Раньше все работало. Как только появилась 40 версия, нельзя устанавливать приложение
