### ISSUE TITLE
Предложение: анти-автолайк постов

### ISSUE THREAD

**Issue by rustzz** [vtosters/lite#587]
[Демо](https://user-images.githubusercontent.com/74064444/183571313-005f5c5e-7632-4203-8db7-52e257e4797b.mp4)

**Comment by k1zn** [comment]
очень понятно

**Comment by rustzz** [comment]
Когда происходит репост, автоматически лайкается этот пост. Не всегда нужно ставить оценку посту при репосте

**Comment by rustzz** [comment]
Когда происходит репост, автоматически лайкается этот пост. Не всегда нужно ставить оценку посту при репосте

[Демо](https://user-images.githubusercontent.com/74064444/183571313-005f5c5e-7632-4203-8db7-52e257e4797b.mp4)

**Comment by k1zn** [comment]
Ну в вк также

**Comment by rustzz** [comment]
> Ну в вк также 

Наоборот, чтобы лайк **не ставился вместе с репостом**

**Comment by gdlbo** [comment]
Вк апи сам ставит лайк вроде, так что бессмысленно

**Comment by rustzz** [comment]
Так предложение в том, чтобы отключить автоматический лайк

**Comment by rustzz** [comment]
@gdlbo прочитай
