### ISSUE TITLE
При открыти "Закладки" приложение падает 

### ISSUE THREAD

**Issue by Grempak** [vtosters/lite#59]
https://foxbin.f0x1d.com/T1JuurkkZ2
![Screenshot_20220327-230134_VTLite](https://user-images.githubusercontent.com/55107052/160298696-0ca9c70c-70d9-427c-ba3e-9bcccb299bff.png)
![Screenshot_20220327-230151_DerpLauncher](https://user-images.githubusercontent.com/55107052/160298697-4b921cff-f751-4b1b-b18e-b069dcd39b31.png)

**Comment by Grempak** [comment]
Что на 11 Андроиде, что на 12

**Comment by gdlbo** [comment]
https://github.com/vtosters/lite/issues/49
