### ISSUE TITLE
Краш при выборе вкладки меню.

### ISSUE THREAD

**Issue by Heafraer** [vtosters/lite#592]
Появился после переключения темы на Milkshake.
![Screenshot_20220808-164253_VTLite](https://user-images.githubusercontent.com/49307568/183432298-e5f68896-1cab-4f37-90d3-d6980e089154.png)
[VTL_log_2022-08-08.16-44-35.txt](https://github.com/vtosters/lite/files/9282162/VTL_log_2022-08-08.16-44-35.txt)

**Comment by aliveoutside** [comment]
вопроизводится ли проблема на 0.4.6?

**Comment by k1zn** [comment]
36dceeef66a4273bd6a9ed13c1670c7f69590334
