### ISSUE TITLE
Корявый перевод в разделов

### ISSUE THREAD

**Issue by NikSavchenko3** [vtosters/lite#60]
В системе стоит Английский то показывается Русский

https://user-images.githubusercontent.com/58150480/160299099-7d62acfe-77ff-4bb2-b787-7ffd71f68ce4.mp4

https://user-images.githubusercontent.com/58150480/160299146-25617a51-df52-4bda-bfd6-73b24d0ceabb.mp4

https://user-images.githubusercontent.com/58150480/160299255-9dc4956d-977c-4538-a45d-d20ee2d73afa.mp4

**Comment by gdlbo** [comment]
https://github.com/vtosters/lite/issues/44
