### ISSUE TITLE
Невозможно открыть правое меню в профиле, при скрытии его из дока

### ISSUE THREAD

**Issue by pom1dorka** [vtosters/lite#604]
Скрыл кнопку "профиль" из док-бара, теперь даже если открыть свою страницу из любого другого места в вк, правое меню не открывается ни свайпом, ни кнопкой с тремя строчками

1. Скрыть "профиль" через редактор док-бара
2. Зайти на свою страницу например из написанного комментария
3. Попытаться открыть правое меню 

Правое меню должно было открыться

**Информация об устройстве:**
 - Устройство: Huawei P20 Lite
 - OS: Android 9 | EMUI 9.1.0
 - Коммит: fa12e8f (что делать с этим пунктом?)

**Comment by gdlbo** [comment]
fixed 0.4.8
