### ISSUE TITLE
Ошибка обновления иконки

### ISSUE THREAD

**Issue by TheArtyomMDev** [vtosters/lite#608]
**Опишите сам баг**
При нажатии на иконку ВК в меню обновления иконки иконка не меняется

**Опишите действия для воспроизведения ошибки**
1. Зашёл в настройки -> внешний вид
2. Выбрал "Выбрать иконку приложения"
3. Нажал на синюю иконку ВК и выбрал название "ВКонтакте", нажал применить
4. На рабочем столе иконка не поменялась

**Опишите ожидаемый результат**
Иконка должна меняться

**Скриншот ошибки**

**Информация об устройстве:**
 - Устройство: Redmi Note 10 Pro
 - OS: Android 12 | AOSP
 - Коммит: b86128a

**Comment by inotflying** [comment]
Установи нормальную прошивку

**Comment by AyonovDenizs** [comment]
@inotflying Реально

**Comment by TheArtyomMDev** [comment]
Нормальную - это miui?)

**Comment by inotflying** [comment]
Да

**Comment by gdlbo** [comment]
https://github.com/vtosters/lite/commit/f15cdf2ff4abac51be315079eeace014aca1df58

**Comment by TheArtyomMDev** [comment]
Спасибо!
