### ISSUE TITLE
Не устанавливает аватар

### ISSUE THREAD

**Issue by eraserhome** [vtosters/lite#61]
Приложение падает при попытке установить аватар (выбираю картинку из галереи телефона)

**Comment by gdlbo** [comment]
Логи

**Comment by eraserhome** [comment]
![Screenshot_20220328-093633](https://user-images.githubusercontent.com/102503626/160340078-94b2a039-6996-4b9c-85c3-bbdd34dc34af.png)
Я не знаю, куда сохраняется лог-файл, вот хотя бы скрин

**Comment by gdlbo** [comment]
https://github.com/vtosters/lite/commit/834d7e1da14a1667898420ede9efd329e870249b
