### ISSUE TITLE
Бесконечная загрузка параметров настройки "активность'

### ISSUE THREAD

**Issue by smirnof777** [vtosters/lite#610]
**Опишите сам баг**
Бесконечная закрузка параметра настроет "активность"

**Опишите действия для воспроизведения ошибки**
При нажатии на параметр "активность", идёт бесконечная загрузка с надписью "запрос данных"

**Опишите ожидаемый результат**
Я хочу зайти в раздел активность и что бы все видели что я в сети и что бы я видел кто в сети

** **

**Информация об устройстве:**
 - Устройство: xiaomi 11 lite
 - OS: Android 9
 - Коммит: fa12e8f (В О Приложении написана версия коммита)

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

**Comment by abslike** [comment]
бро, а ты точно тостер лайт используешь?

**Comment by aliveoutside** [comment]
не относится в VTosters Lite
https://t.me/vtosters_faq/86
Закрыто.

**Comment by oplexz** [comment]
@abslike
