### ISSUE TITLE
Ошибка перехода по ссылке из другого приложения

### ISSUE THREAD

**Issue by nullnesse** [vtosters/lite#611]
**Опишите сам баг**
При переходе по ссылке из другого приложения (баг тестировался только на ссылках, ведущих на записи в группе по типу "vk.com/wall...") втостерс лайт не открывается.

**Опишите действия для воспроизведения ошибки**
1. Открываем ленту новостей и копируем ссылку на первый попавшийся(любой) пост.
2. Закрываем приложение(втостерс лайт).
3. Открываем приложение, из которого мы будем переходить по ссылке. (например, телеграм - я проверял на телеграме и инстаграме)
4. Кому-нибудь отправляем ссылку (делаем ссылку кликабельной) и переходим по ней.

**Опишите ожидаемый результат**
Должен открыться вт лайт с записью из ссылки, но вместо этого перенаправляет в другое приложение, т.к вт лайт не может ее открыть.

**Прикреплено видео**

**Информация об устройстве:**
 - Устройство: POCO X3 PRO
 - OS: Чистый Android 11 без гугл сервисов, но с установленными GMS(microg)
 - Коммит: b86128a 

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

Заметил, что если при переходе по ссылке вт лайт не запущен - появляется анимация загрузки вт лайт и переносит в другое приложение, но если его запустить - переносит в вт лайт. 

И еще, если при запуске вт лайта не происходит обновления новостей, диалогов или какой-нибудь другой информации - в зависимости от раздела при запуске, то редиректа в вт лайт тоже не происходит. 

https://user-images.githubusercontent.com/111252749/184558648-d1030340-c910-4a4a-9b28-a9d6daa19b0d.mp4

На видео я сначала попробовал открыть ссылку:
- когда вт лайт не запущен - в вт лайт не переходит

- потом когда запущен, но без обновления ленты (автообновление ленты отключено) - в вт лайт не переходит

- потом когда запущен и лента была обновлена- переходит

Та же история происходит, если раздел при запуске - Диалоги - без их обновления редиректа не происходит.

**Comment by aliveoutside** [comment]
не могу воспроизвести 
попробуй открыть настройки приложения в самом андроиде (настройки твоего телефона -> приложения и найди там тостер)
далее пункт "Открывать по-умолчанию"
где-то там должен быть выбор ссылок, открываемых в приложении - поставь галочки на всех
![image](https://user-images.githubusercontent.com/53598473/184560995-4973ba08-f4b4-40df-9b18-26a23be770b2.png)

**Comment by nullnesse** [comment]
> не могу воспроизвести попробуй открыть настройки приложения в самом андроиде (настройки твоего телефона -> приложения и найди там тостер) далее пункт "Открывать по-умолчанию" где-то там должен быть выбор ссылок, открываемых в приложении - поставь галочки на всех ![image](https://user-images.githubusercontent.com/53598473/184560995-4973ba08-f4b4-40df-9b18-26a23be770b2.png)

Это первым делом проверил, у меня в системе по умолчанию все поддерживаемые приложением ссылки открываются, и все, что у тебя на скриншоте, имеется в списке. Настройки других приложений, которые тоже поддерживают эти ссылки, также проверил. Возможно, все таки в системе дело или в отсутствии гугл сервисов. Хотя с обычным втостерсом таких аномалий не возникает, да и с другими модами тоже.
