### ISSUE TITLE
Ошибка с окном дополнительной информации в беседах

### ISSUE THREAD

**Issue by Ravenberry** [vtosters/lite#616]
Суть ошибки:
При попытке открыть пункт "информация о беседе" ничего не происходит, только всплывающее меню сворачивается.

Действия:
1. зашёл в беседу;
2. нажал на НАЗВАНИЕ беседы сверху;
3. нажал на "информацию о беседе";

Как должно быть:
Должно открыться меню с доп. информацией.

Скриншот ошибки:
Нечего снимать, т.к ничего не происходит

Информация об устройстве:
 - Устройство: Xiaomi Redmi 8
 - OS: Android 10 | MIUI Global 12.5.3
 - Коммит: d68fb09
[VK.logup.zip](https://github.com/vtosters/lite/files/9337613/VK.logup.zip)

**Comment by gdlbo** [comment]
https://github.com/vtosters/lite/commit/315c2386f7c59a2d2eb8954ce85bb6784448261a
