### ISSUE TITLE
Жест для reply не работает

### ISSUE THREAD

**Issue by uniqueUsernameIsNotAvailable** [vtosters/lite#62]
Android 11, custom rom(nitrogen os)
Свайп для ответа не работает совсем, необходимо использовать кнопку. Проблема наблюдалась ещё у нескольких людей, судя по сообщениям в канале Тостерса. 

https://user-images.githubusercontent.com/98878225/160334193-a65a55f8-56c1-482b-9a68-f4863ba878f3.mp4

**Comment by gdlbo** [comment]
можешь это залоггать?

**Comment by uniqueUsernameIsNotAvailable** [comment]
> можешь это залоггать? 
[VK.Log](https://file.io/9WnawJKgBYPL)
Надеюсь, помог

**Comment by uniqueUsernameIsNotAvailable** [comment]
UPDATE!
Выяснил, что swipe to reply не работает, если в системе отключены анимации! Вернул анимации, всё отлично запустилось... надеюсь, это поможет фиксу, ведь в старшем Тостерсе фича работала и с animations off
