### ISSUE TITLE
Не получается загрузить историю 

### ISSUE THREAD

**Issue by Opasniy89** [vtosters/lite#620]
Не получается загрузить историю.
Когла нажимаешь на + для создания истории, то ничего не происходит.

**Comment by inotflying** [comment]
Какой именно «+»?

**Comment by Opasniy89** [comment]
+ который рядом с аватаркой моей, где ещё истории других людей, в самом начале идёт +, потом аватарка при на нажатии на которую открывается история. 
В общем просто историю загрузить не получается. 
И ещё, не знаю почему это, но такое каждый день, и каждый раз когда захожу в VtLite. При переходе из одного раздела в другой, те разделы которые на докбаре, где лента, профиль и т. д, я был в профиле, нажимаю на ленту и тут пусто, просто серый экран. 
--
Отправлено из Mail.ru для Android понедельник, 15 августа 2022, 09:44PM +04:00 от Egor  ***@***.*** :
