### ISSUE TITLE
Краш при переходе в диалог с уведомления 

### ISSUE THREAD

**Issue by daeeros** [vtosters/lite#622]
Если перейти в диалог с уведомления, появляется краш.

**Скриншот ошибки**
![Screenshot_2022-08-15-22-04-29-502_com android chrome](https://user-images.githubusercontent.com/34482855/184700008-6e85a7c6-4710-473c-8458-90dbf79e1de3.jpg)

**Информация об устройстве:**
 - Устройство: Mi 9T
 - OS: Android 10 | Miui 12
 - Коммит: 2a58d72

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

Лог ошибки: https://foxbin.f0x1d.com/TL0coUe9nj

**Comment by k1zn** [comment]
@daeeros Будет исправлено в следующем обновлении
