### ISSUE TITLE
В галерее не отображаются сохранённые картинки

### ISSUE THREAD

**Issue by HaK666MD** [vtosters/lite#627]
**Информация об устройстве:**
 - Устройство: Samsung Galaxy S9
 - OS: Android 10 | OneUi 2.5
 - Коммит: 9b462b9

**Comment by fnvm** [comment]
Такая же проблема, galaxy s9+

**Comment by Mehanik76** [comment]
Такая же проблема Realme C3

**Comment by stolyarvan** [comment]
Такая же проблема, устройство - Honor 9X

**Comment by Dopaminos** [comment]
@stolyarvan пофикшено в лейтест коммите

**Comment by HaK666MD** [comment]
> @stolyarvan @Mehanik76 @fnvm @HaK666MD пофикшено в лейтест коммите https://t.me/vtbetachat/10664
> 
> вы на старой версии

На этой то же не отображается

**Comment by fnvm** [comment]
Проблема осталась
