### ISSUE TITLE
Некоректное скачивание музыки из VTlite

### ISSUE THREAD

**Issue by Auther0n** [vtosters/lite#630]
Музыка становится не в правильной фрагментациии,части музыки как будто перемешали

1. Скачал музыку в VTlite
2. Открыл скачанный музон

Музыка должна скачиваться в нормальном состоянии

 - Устройство: Samsung Galaxy a50
 - OS: Android 11 | OneUi 3.1
 - Коммит: b86128a

**Comment by Auther0n** [comment]
Uploading lv_0_20220816233329.mp4…

**Comment by RegenbogenOhneBlau** [comment]
> Музыка становится не в правильной фрагментациии,части музыки как будто перемешали
> 
> 
> 1. Скачал музыку в VTlite
> 2. Открыл скачанный музон
> 
> 
> Музыка должна скачиваться в нормальном состоянии
> 
> 
> 
>  - Устройство: Samsung Galaxy a50
>  - OS: Android 11 | OneUi 3.1
>  - Коммит: b86128a
> 

Временно (или на постоянно) скачай [VK X](vkx.app), VK X это плеер для ВКонтакте, и имеет интеграцию с ВТостерс Лайт. Лиьо жди когда решат данную проблему с VTL.

**Comment by Dopaminos** [comment]
> 

@Auther0n MIUI 12.5.7, Android 11
Коммит: **72ce3eb**
https://user-images.githubusercontent.com/42616718/185252493-e9686563-f49f-410d-93eb-37c95aea77d0.mp4

Бага замечено не было.
