### ISSUE TITLE
Черный диалог при добавлении стикера тг

### ISSUE THREAD

**Issue by danyyok** [vtosters/lite#631]
**Опишите сам баг**
Диалог с добавлением нового стикера телеграм 
становится черным при нижеуказанных действиях
**Опишите действия для воспроизведения ошибки**
1. Смахнул в недавние приложения
2. Смахнул не до конца..
![Screenshot_2022-08-17-00-45-34-525_com vtosters lite](https://user-images.githubusercontent.com/110027540/184971199-ce66ce2c-51b9-49c3-9059-6d12fb8af49a.jpg)

**Опишите ожидаемый результат**
Диалог не должен быть черным и все должно быть видно

**Скриншот ошибки**

**Информация об устройстве:**
 - Устройство: Redmi S2
 - OS: Android 9 | miui 12.0.2.0
 - Коммит: 9b462b9

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**
...

**Comment by danyyok** [comment]
Видео с этим (немного опоздал)
https://user-images.githubusercontent.com/110027540/184992048-4556fb98-17ec-4d0e-b6f1-43798fe3a68d.mp4

**Comment by k1zn** [comment]
@danyyok миюай момент походу

**Comment by danyyok** [comment]
> @danyyok миюай момент походу

В любом случае ждем исправления
