### ISSUE TITLE
Поик сообщений в чате

### ISSUE THREAD

**Issue by danyyok** [vtosters/lite#633]
**Опишите сам баг**
При попытке нажать на кнопку "поиск" в чате ничего не происходит

**Опишите действия для воспроизведения ошибки**
1. Открыть чат
2. Найти и нажать на кнопку "поиск"

**Опишите ожидаемый результат**
Все должно открытся и искать нужные вложения/сообщения

**Скриншот ошибки**
...

**Информация об устройстве:**
 - Устройство: Redmi S2
 - OS: Android 9 | Miui 12.0.2.0
 - Коммит: d68fb09  (В О Приложении написана версия коммита)

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**
...

**Comment by k1zn** [comment]
обновись

**Comment by danyyok** [comment]
> обновись

0.4.7 не последняя?

**Comment by k1zn** [comment]
@danyyok ты точно на 0.4.7? этот баг был на 0.4.5 или на 0.4.6
