### ISSUE TITLE
Бесконечная загрузка сообщений

### ISSUE THREAD

**Issue by holeech** [vtosters/lite#64]
Все разделы работают нормально. Список сообщений пустой, постоянно крутиться кружок.
![Screenshot_2022-03-26-23-35-14-943_com vtosters lite](https://user-images.githubusercontent.com/57586115/160344250-e50cc1c3-e773-48c1-a00e-3cc39a41d122.jpg)

**Comment by holeech** [comment]
При нажатии на кнопку поделиться также не отображаются люди. 
![Screenshot_2022-03-28-10-19-41-558_com vtosters lite](https://user-images.githubusercontent.com/57586115/160346592-1e19e6b6-0dd4-4bc6-b127-2f0aa07912c6.jpg)

**Comment by gdlbo** [comment]
https://github.com/vtosters/lite/issues/17
