### ISSUE TITLE
Улучшение кастомизации чата и докбара

### ISSUE THREAD

**Issue by stolyarvan** [vtosters/lite#640]
Необходима функция акцентов. Эта функция была в VTosters, но переходя с этой версии на VTЛайт, я ограничился лишь возможностью установки обоев в чате. 

Визуальный выбор цвета предоставить через Color Picker.

Неприятная ситуация когда больше не можешь не можешь в принципе менять цвет акцента, как я это делал часто раньше.

**Comment by aliveoutside** [comment]
#240
