### ISSUE TITLE
Не открываются функции в диалоге с собеседником

### ISSUE THREAD

**Issue by Medister13** [vtosters/lite#647]
**Описание бага**
Не открываются функции в диалоге с собеседником

**Действия для воспроизведения ошибки**
1. Открыл список функций (поиск сообщений, вложения и прочее).
2. Нажатие на один из пунктов списка не переводит, например, на просмотр вложений или поиск сообщений. 

**Ожидаемый результат**
Возможность использования данного функционала

**Скриншот ошибки**
![Screenshot_2022-08-18-16-26-51-040_com vtosters lite](https://user-images.githubusercontent.com/111513670/185407000-ae643c96-03c2-410b-9386-d002d9e223aa.png)
**Информация об устройстве:**
 - Устройство: Poco X3 Pro
 - OS: Android 12 | MIUI 13.0.5
 - Коммит: d68fb09

**Comment by gdlbo** [comment]
Обновись
