### ISSUE TITLE
краш приложения при выборе обоев для чата

### ISSUE THREAD

**Issue by Al-anal** [vtosters/lite#649]
Возможно в первый раз зайти в настройку обоев для чатв и выбрать изображение, после этого приложение крашет, при попытке зайти в любой диалог - краш, в настройки обоев тоже краш

**Информация об устройстве:**
 - Устройство: Samsung Galaxy s21 ultra
 - OS: Android 12 One UI 4.0
 - Коммит: 9b462b9
![Screenshot_20220818-200526_VTLite](https://user-images.githubusercontent.com/68759449/185453834-1e3bf53a-91be-4c08-828e-dde5734e1e8f.jpg)
Величина файла по сути крашит все приложение и не дает поменять на другое фото без переустановки приложения

upd: сжал фото с 25 мб до 5 мб, все абсолютно тоже самое

**Comment by k1zn** [comment]
не получается повторить, нужны логи

**Comment by Al-anal** [comment]
> не получается повторить, нужны логи

сейчас запишу

**Comment by Al-anal** [comment]
https://foxbin.f0x1d.com/hwdSbUhPDe - краш при выборе фото для обоев в чате

https://foxbin.f0x1d.com/R4g0qUEsza - краш при заходе на диалог после неудачной установки обоев

**Comment by Mehanik76** [comment]
багованное гоавно)))))

**Comment by k1zn** [comment]
@Mehanik76 ебальник закрой

@Al-anal картинка слишком большого качества, пока что ставь поменьше, в следующих обновлениях скорее всего добавят проверку на размер

**Comment by Al-anal** [comment]
> багованное гоавно)))))

чел..... приложение в бете, доска на гитхабе создана как раз для устранения багов, вместо благодарности за труды, они получают таких долбаебов как ты, задумайся

**Comment by Al-anal** [comment]
> @Mehanik76 ебальник закрой
> 
> @Al-anal картинка слишком большого качества, пока что ставь поменьше, в следующих обновлениях скорее всего добавят проверку на размер

сомневаюсь, что проблема только в размере. написал в основном сообщение в upd: "сжал изображение с 25мб до 5 и все то же самое". так

**Comment by k1zn** [comment]
> > @Mehanik76 ебальник закрой
> > @Al-anal картинка слишком большого качества, пока что ставь поменьше, в следующих обновлениях скорее всего добавят проверку на размер
> 
> сомневаюсь, что проблема только в размере. написал в основном сообщение в upd: "сжал изображение с 25мб до 5 и все то же самое". так

ну так и 5 мб немало для фотографии

**Comment by Al-anal** [comment]
> > > @Mehanik76 ебальник закрой
> > > @Al-anal картинка слишком большого качества, пока что ставь поменьше, в следующих обновлениях скорее всего добавят проверку на размер
> > 
> > 
> > сомневаюсь, что проблема только в размере. написал в основном сообщение в upd: "сжал изображение с 25мб до 5 и все то же самое". так
> 
> ну так и 5 мб немало для фотографии

не спорю, но у меня до этого стояла фотография размером в 7мб (и сейчас она ставится без проблем)

**Comment by Al-anal** [comment]
обе фотографии формата .jpg, обе сделаны на один и тот же телефон

**Comment by gdlbo** [comment]
> обе фотографии формата .jpg, обе сделаны на один и тот же телефон

привет, можешь пожалуйста поделиться обоями которые вызывают проблему?

**Comment by Al-anal** [comment]
> 
![Uploading 20220816_193222.jpg…]()

**Comment by Al-anal** [comment]
> > обе фотографии формата .jpg, обе сделаны на один и тот же телефон
> 
> привет, можешь пожалуйста поделиться обоями которые вызывают проблему?
![Screenshot_20220823-141335_Gallery](https://user-images.githubusercontent.com/68759449/186144206-e4ad04a5-6707-4611-8316-3db8e2579f44.jpg)

**Comment by gdlbo** [comment]
> > > обе фотографии формата .jpg, обе сделаны на один и тот же телефон
> > 
> > 
> > привет, можешь пожалуйста поделиться обоями которые вызывают проблему?
> > ![Screenshot_20220823-141335_Gallery](https://user-images.githubusercontent.com/68759449/186144206-e4ad04a5-6707-4611-8316-3db8e2579f44.jpg)

<img width="529" alt="image" src="https://user-images.githubusercontent.com/41114720/186144971-57a4607c-0ca1-41bb-81ca-8bdbba17cde9.png">

Может попробуете отправить мне картинку документом в Telegram (https://t.me/gdlbo)

**Comment by Dopaminos** [comment]
@gdlbo и мне тоже @dopaminoa

**Comment by Dopaminos** [comment]
@Dopaminos @dopaminos **

**Comment by gdlbo** [comment]
https://github.com/vtosters/lite/commit/9fa8df30eb152b18c579f72c0db268b18cea3d61

**Comment by rambstl** [comment]
Появилась точно такая же проблема, но меня выбрасывает из приложения при входе в чаты. А если захожу в настройки обои чата, то выбрасывает в список всех настроек. Телефон OnePlus Ace перепрошитый на глобалку android 12 и обновленный до 13 фотографиия весит 4,7 мб. Подскажите хотя бы как сбросить приложение или сделайте эту функцию
