### ISSUE TITLE
Предложение добавить в друзья в диалогах 

### ISSUE THREAD

**Issue by trubyou** [vtosters/lite#656]
Уведомление, предлагающее добавить в друзьях в диалогах не убирается (после нажатия на крестик моментально возвращается), функция, блокирующая это уведомление включена. Пробовал включить - выключить с перезаходом, не помогло.
![IMG_20220821_002044](https://user-images.githubusercontent.com/36296546/185763093-bc8b9954-fc84-4cc4-8861-2779efffe22a.jpg)

Xiaomi redmi 8 pro, коммит е668сfb

**Comment by trubyou** [comment]
Ещё с прошлого обновления тяжело обновляются новости, коммит не знаю, ждал обновы, кто-то вроде писал об этом, но сильно не изменилось. В разделе "интересное" приходится по 8 раз обновлять ленту, чтобы она действительно обновилась. А в разделе новостей посты как будто не все отображаются, хотя здесь я не уверен

**Comment by trubyou** [comment]
С лентой новостей косяк мой, была включена интересная лента, исправил.

**Comment by gdlbo** [comment]
https://github.com/vtosters/lite/commit/32c469d870eb6c31923cc9566f01a383b6e6e304
