### ISSUE TITLE
Не открываются Шаги ВКонтакте 

### ISSUE THREAD

**Issue by s1atta** [vtosters/lite#658]
Когда открываю шаги ВКонтакте идёт бесконечная загрузка 

![Screenshot_2022-08-21-02-21-46-41_9e1a5d6211a0228d32d39446541891f1](https://user-images.githubusercontent.com/111665888/185769238-c16eb6ed-c3fa-4a3e-87fc-d374565541a6.jpg)

Информация об устройстве:
 - Устройство: realme 6
 - OS: Android 11 
 - Коммит: e668cfb

**Comment by gdlbo** [comment]
https://github.com/vtosters/lite/issues/602
