### ISSUE TITLE
Обнаружен вирус в последнем обновлении

### ISSUE THREAD

**Issue by AleXXXv1** [vtosters/lite#659]
Обновился на версию 0.4.9. Теперь приложение Сбербанк онлайн ругается на файл apk и само приложение, что в них обнаружен бэкдор. С предыдущими версиями VTLite такого не было.

**Comment by AyonovDenizs** [comment]
@AleXXXv1 Отключи антивирус от Сбера. Фейк уведомление

**Comment by aliveoutside** [comment]
следите за #660
