### ISSUE TITLE
Сбер/Касперский определяет АПК файл VTLite как бэкдор

### ISSUE THREAD

**Issue by PANFIL122** [vtosters/lite#660]
Это сообщение стало появляться после обновления 4.8.
![Screenshot_2022-08-21-08-50-37-77_56e3a6ebeab54d89da2ff3c4fc56e986.jpg](https://user-images.githubusercontent.com/103692286/185776071-b8c0b955-2b81-4afb-b17d-b1eff487ebf8.jpg)

**Comment by aliveoutside** [comment]
ложное срабатывание

**Comment by aliveoutside** [comment]
написал в поддержку касперского, будем разбираться

**Comment by AleXXXv1** [comment]
Учтите, что не только Касперский, но и антивирус Сбера находит бэкдор в последней обнове. И не только в установочном apk файле, но и в уже установленном приложении. Хотелось бы, чтобы приложение дружило с антивирями и не приходилось отключать защиту.

**Comment by aliveoutside** [comment]
> но и антивирус Сбера

антивируса Сбера сделан на базе Касперского, оно и неудивительно

**Comment by Dopaminos** [comment]
Play Защита на миуи тоже ругалась /shrug

**Comment by AyonovDenizs** [comment]
@Dopaminos Тоже ложное срабатывание

**Comment by Tropi4555** [comment]
Вопрос такой, а зачем вообще антивирусы и кто пользуются? Смысл? Трата памяти на телефоне и т.д Удали антивирус, на телефоне не нужны)

**Comment by AleXXXv1** [comment]
> Вопрос такой, а зачем вообще антивирусы и кто пользуются? Смысл? Трата памяти на телефоне и т.д Удали антивирус, на телефоне не нужны)

Надеюсь это рофл такой. По такой же логике снесите все антивири с компа, трапа памяти только...

**Comment by jplie** [comment]
@AleXXXv1 Да..

**Comment by k1zn** [comment]
@Tropi4555 В Сбер встроен антивирус

**Comment by Tropi4555** [comment]
> > Вопрос такой, а зачем вообще антивирусы и кто пользуются? Смысл? Трата памяти на телефоне и т.д Удали антивирус, на телефоне не нужны)
> 
> Надеюсь это рофл такой. По такой же логике снесите антивирь с компа, трата памяти только...

Не рофл, а на самом деле. Если так подумать, зачем антивирусы на телефоне? На пк ладно, а на телефоне то зачем..

**Comment by AleXXXv1** [comment]
> > > Вопрос такой, а зачем вообще антивирусы и кто пользуются? Смысл? Трата памяти на телефоне и т.д Удали антивирус, на телефоне не нужны)
> > 
> > 
> > Надеюсь это рофл такой. По такой же логике снесите антивирь с компа, трата памяти только...
> 
> Не рофл, а на самом деле. Если так подумать, зачем антивирусы на телефоне? На пк ладно, а на телефоне то зачем..

Затем что смарты уже очень давно привлекательны для создателей вирусов, тут вам и куча конф. информации, и банковские данные, и все ваши акки, и прочее, даже майнить на них можно. А такая популярная ось как андроид, да и ещё в открытом доступе, ясен пень что для неё куча вирусов всяких разных пишется, и не зря постоянно прилетают обновы системы безопасности, чтобы дыры залатывать.

**Comment by aliveoutside** [comment]
Ещё актуально? Касперский выдаёт что файл чист https://opentip.kaspersky.com/D659DECA57A898065D319CE16F0309FCD6FEDA713EDD2A680516B7DE2703E9CA/

@PANFIL122 @AleXXXv1

**Comment by PANFIL122** [comment]
Спасибо. Предупреждение пропало.

**Comment by AleXXXv1** [comment]
Спасибо. Все чисто.
