### ISSUE TITLE
При удалении одного сообщения может удалиться ведь диалог за день

### ISSUE THREAD

**Issue by GeckoMagnificent** [vtosters/lite#662]
**Опишите сам баг**
Иногда пр удалении одного сообщения может удалиться как все сообщения за день, так и за несколько дней сразу

Происходит всегда неожиданно, каких либо конкретных действий (кроме удаления) что бы вызвать этот баг не обнаружил

Один раз помог перезапуск приложения через настройки, однако во второй раз этого было недостаточно, переустанавливал приложение. Сообщения удаляются только на мобильной версии, на ПК всё остаётся на месте

Пользуюсь актуальной версией Lite

**Информация об устройстве:**
 - Устройство: Samsung Galaxy J1 Mini
 - OS: Android 9 | OneUi 3.0
 - Коммит: fa12e8f (В О Приложении написана версия коммита)

**Comment by nullnesse** [comment]
+, бывает такое
