### ISSUE TITLE
Ошибка скрытия блока рекомендаций друзей

### ISSUE THREAD

**Issue by Miku-nya** [vtosters/lite#663]
В последней версии приложения наблюдается проблема со скрытием блока рекомендации добавления в друзья, в меню "Интерфейс", пункт "Скрыть рекомендации"  -> Включено, но при заходе в переписки данный блок всё же остаётся. Ранее в предыдущей версии приложения оно убиралось, появилась ошибка в этом обновлении.
![1](https://user-images.githubusercontent.com/53754434/185789617-e697fe4a-0f33-4455-9826-65294ac8752e.jpg)
![2](https://user-images.githubusercontent.com/53754434/185789622-06f12b61-1e33-4edd-9ef9-20126f95e353.jpg)
![3](https://user-images.githubusercontent.com/53754434/185789626-a508af0c-a71c-4e65-a0e9-59161047b32c.jpg)

**Информация об устройстве:**
 - Устройство: Oneplus 8 Pro
 - OS: Android 10 | OxygenOS 10.5.11
 - Коммит: e668cfb

**Comment by gdlbo** [comment]
https://github.com/vtosters/lite/issues/657
