### ISSUE TITLE
Антивирус сбербанка ругается на приложение

### ISSUE THREAD

**Issue by baskmooon** [vtosters/lite#666]
При заходе в приложение сбербанка вылетает предупреждение об найденном вирусе
![Screenshot_2022-08-22-13-36-05-24_7686309dddc2e04e1a25c8452ee891a0](https://user-images.githubusercontent.com/81561514/185901349-7a9fa825-c400-47de-95b9-df06063a3a0a.jpg)
При нажатии удалить сбербанк предлагает удалить VTosters lite
![Screenshot_2022-08-22-13-36-19-38_3d73e98b1ad3bd2575f7a56513d89a0c](https://user-images.githubusercontent.com/81561514/185901565-774b4800-7354-4e64-bf97-44065ca62601.jpg)

(Не знаю нужно было ли так расписывать такую фигню)
Если возможно, то я бы хотел, чтобы это исправили в следующих обновлениях.

**Comment by aliveoutside** [comment]
дубликат #660
