### ISSUE TITLE
Стикеры накладываются на альтернативный дизайн выбора эмодзи

### ISSUE THREAD

**Issue by danyyok** [vtosters/lite#675]
**Опишите сам баг**
Если через альтернативный дизайн выбора эмодзи ввести эмодзи (например:😆)  то выйдут стикеры и встанут поверх выбора эмодзи,а после этого использование эмодзи станет сложным и не удобным.

**Опишите действия для воспроизведения ошибки**
1. Выбрал любой стикер под который будет выявлен  стикер

**Опишите ожидаемый результат**
Эмодзи должны встать поверх стикеров

**Скриншот ошибки**
Скриншот как все не должно быть:
![Screenshot_2022-08-23-22-21-36-819_com.vtosters.lite.jpg](https://user-images.githubusercontent.com/110027540/186225276-ccca3a7b-dee1-4542-b1a8-ea8f94b7c08a.jpg)
Скриншот как все должно быть:
![IMG_20220823_223238.jpg](https://user-images.githubusercontent.com/110027540/186226256-b81ab42a-6403-4c8f-90c6-cae30bc36730.jpg)

**Информация об устройстве:**
 - Устройство: Redmi S2
 - OS: Android 9 | MIUI 12.0.2.0
 - Коммит: 857b63a

**Comment by gdlbo** [comment]
Not a bug
