### ISSUE TITLE
Невозможно установить обновление

### ISSUE THREAD

**Issue by Freggly** [vtosters/lite#679]
**Опишите сам баг**
Невозможно установить обновление

**Опишите действия для воспроизведения ошибки**
1. Скачал обновление в виде apk
2. Открыл apk-файл

**Опишите ожидаемый результат**
VTLite обновится без удаления предыдущей версии с сохранением настроек

youtube.com/shorts/SWp-_IIRiOg?feature=share

**Информация об устройстве:**
 - Устройство: Poco X3 Pro
 - OS: Android 11 | MIUI Global 12.5.4
 - Коммит: 9b462b9

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

**Comment by Freggly** [comment]
Проблема решена: нужно открывать apk файл из приложения "проводник", а не из приложения "загрузки"

**Comment by danyyok** [comment]
@Freggly
