### ISSUE TITLE
Подтверждение сброса настроек

### ISSUE THREAD

**Issue by danyyok** [vtosters/lite#684]
**Опишите вашу идею максимально подробно и понятно**
Необходима функция подтверждения сброса функций в настройках.Иногда можно случайно нажать на нее и сбросить все настройки

**Опишите возможное решение/реализацию функции (если понимаете как это можно реализовать на Java/C++)**
Простой диалог с подтверждением

**Comment by aliveoutside** [comment]
сделано в e709f6ac68ac66732ee8b9ef373f0afe284b3d13
