### ISSUE TITLE
Ошибка при скачивании фотографий

### ISSUE THREAD

**Issue by YanaKole** [vtosters/lite#686]
Добрый день. 
Скачиваю фото. 
Оно скачивается. 
И не открывается. 

Хотелось бы чтобы фото открывались)) 
![Screenshot_20220826_120244_com vtosters lite](https://user-images.githubusercontent.com/112165175/186869814-9af9ff4a-6824-4856-837a-197a8348b738.jpg)
![Screenshot_20220826_120249_com google android apps docs editors docs](https://user-images.githubusercontent.com/112165175/186869827-9fe77348-d77f-4c7e-b73c-df718f9a87c2.jpg)

**Информация об устройстве:**
 - Устройство: honor 20
 - OS: Android 10
 - Коммит: e668cfb2a3

**Comment by k1zn** [comment]
вероятнее всего исправлено в 374b221f0dab411d986ae76a6ac691496a686afa
