### ISSUE TITLE
Ошибка обновлении ленты новостей

### ISSUE THREAD

**Issue by MRaist** [vtosters/lite#689]
Зависает при листании ленты

1. Зашел в приложение
2. Пролистал примерно 10 постов

Зависло и вылезает ошибка

![Screenshot_20220826-231653](https://user-images.githubusercontent.com/103269174/186984410-b3c46c95-d833-4926-a066-c7b152ad2b46.png)

 - Устройство: HTC Wildfire E lite
 - OS: Android 10 | HTC_WILDFIRE_E_LITE_RU_V005_20210316
 - Коммит: 8e12f50

**Comment by danyyok** [comment]
Логи?

**Comment by MRaist** [comment]
> 

Логов нет. Листаю ленту спокойно, потом зависает и ошибка типо приложение не отвечает. Кэш чистил

**Comment by k1zn** [comment]
@MRaist https://t.me/vtosters_faq/21

**Comment by MRaist** [comment]
> 

А как файл сюда скинуть?
