### ISSUE TITLE
Не отображаются некоторые посты в группах.

### ISSUE THREAD

**Issue by Young42** [vtosters/lite#690]
В группах видно не все посты.

1. Человек в личном сообщении или в беседе сделал репост из группы.
2. Попытался открыть пост, но приложение выдаёт сообщение "Запись не найдена".
3. Перешёл в группу и убедился, что пост там просто не отображается.
4. Зашёл в вк с браузера и нашёл нужный пост.

В группах должны отображаться все публикуемые записи.

**Скриншот ошибки**
![Screenshot_20220827-100417](https://user-images.githubusercontent.com/112239791/187019744-b327283d-c5de-4749-b6c1-fe999e980412.png)
![Screenshot_20220827-100424](https://user-images.githubusercontent.com/112239791/187019756-4c487827-d67d-4d03-9538-6535fff039c0.png)
![Screenshot_20220827-100724](https://user-images.githubusercontent.com/112239791/187019760-37f8b77a-c746-4dc7-87f4-b64cf99b89b2.png)
![Screenshot_20220827-100728](https://user-images.githubusercontent.com/112239791/187019768-0f93031e-73d2-44e2-a0fe-a18993128601.png)
![Screenshot_20220827-100853](https://user-images.githubusercontent.com/112239791/187019777-6a21d4b3-8abf-45b6-891f-7302d2bcf482.png)

 - Устройство: Realme C11
 - OS: Android 11 
 - Коммит: f887648

**Comment by k1zn** [comment]
вероятнее всего исправлено в 58905bbc593a988e955ffa2fcd8b1195987aa6df
если после выхода новой версии проблема останется, переоткрой
