### ISSUE TITLE
Долгий запуск приложения и замедленная работа приложения - отправка сообщений, загрузка контента

### ISSUE THREAD

**Issue by Aynu1** [vtosters/lite#691]
**Опишите сам баг**
Долгий запуск приложения и замедленная работа приложения - отправка сообщений, загрузка контента

**Опишите действия для воспроизведения ошибки**
1. Запустил приложение
2. Отправил сообщение

**Опишите ожидаемый результат**
Быстрый запуск приложения

**Скриншот ошибки**

**Информация об устройстве:**
 - Устройство: Google Pixel 3XL
 - OS: Android 12
 - Коммит: f887648 (В О Приложении написана версия коммита)

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**
![Screenshot_20220827-103453](https://user-images.githubusercontent.com/72130348/187020264-8f393471-0d43-456e-89d2-cb2f5eb26993.png)

**Comment by AyonovDenizs** [comment]
@Aynu1 Переустановка не помогла?

**Comment by aliveoutside** [comment]
Настройки тостера -> другое -> очистка кеша -> "очистить весь кеш"

**Comment by Aynu1** [comment]
Почистил все данные через настройки, теперь работает как обычно

**Comment by aliveoutside** [comment]
исправлено в v0.4.12
