### ISSUE TITLE
Не обновляется приложение и новости

### ISSUE THREAD

**Issue by Lorein1703** [vtosters/lite#692]
Уже сколько раз пытаюсь установить новые версии втлайта, что с сайта, что при обновлении внутри приложения когда открываешь обновщик - открывается само приложение и в результате ничего не обновляется, бомбит уже. Также новости - я уже устал читать 2 недели одни и те же же посты, лента ТУПО НЕ МЕНЯЕТСЯ никаким образом, уже аж плохо становится, когда видишь тот же самый пост в 10-й раз. (Очистка кэша ни одну из проблем не решает) 

1. Нажимаю обновить в приложении или скачиваю апк с сайта
2. Нажимаю на загруженный апк и вместо обновления открывается приложение

Я наконец-то смогу обновить приложение и не буду читать одни и теже же посты день за днём!!! 

Скриншот делать смысла не вижу, проблема и так понятна. 

 - Устройство: Xiaomi Redmi
 - OS: Android 10 | MiUi 12.5.1
 - Коммит: 9b462b9 

О происхождении этих багов мыслей нет.

**Comment by danyyok** [comment]
В настройках ленты есть порядок записей,включи "по времени публикации" 
А то что обновления не устанавливаются хз,ставь начисто

**Comment by Lorein1703** [comment]
Upd: note 7

**Comment by Lorein1703** [comment]
danyyok, за решение проблемы с новостями - благодарю, помогло. Про обновление приложения - подожду ответа разработчиков.
