### ISSUE TITLE
Антивирус снова ругается на бекдор в приложении 

### ISSUE THREAD

**Issue by AleXXXv1** [vtosters/lite#696]
Антивирус Сбера снова обнаружил бекдор в последних двух обновлениях и самом приложении.

**Comment by aliveoutside** [comment]
Я даже не знаю что тут можно сделать, со стороны касперского всё чисто https://opentip.kaspersky.com/2651B3A957D0566BEB08C59B84747DD19DE34894657D7176B444E94DD8668C7E/
А куда писать Сберу - непонятно

**Comment by AleXXXv1** [comment]
Либо в службу безопасности Сбера, либо разработчикам моб. приложения, возможно. Сам с таким не сталкивался :)
