### ISSUE TITLE
Автопереключение тёмной темы

### ISSUE THREAD

**Issue by QuestYouCraft** [vtosters/lite#697]
В классическом @vtosters и в оригинальном VK есть очень удобная функция под названием "Автоматическое включение тёмной темы в соответствии с настройками системы". Реализация этого описана тут: https://developer.android.com/develop/ui/views/theming/darktheme#support-dark-theme

**Comment by aliveoutside** [comment]
сделано в 0ed16b0836a6e87ed4f032347948f15a6e404bab
