### ISSUE TITLE
Баг с процентами и голосованиями

### ISSUE THREAD

**Issue by Alexrhrg** [vtosters/lite#698]
**Опишите сам баг**
При обновлении записи с голосованием проценты куда то уплывают

**Опишите действия для воспроизведения ошибки**
1. Проголосовал
2. Зашёл на страничку записи
3. Обновил
4. Проценты поплыли

**Опишите ожидаемый результат**
Интересная лента должна прогружать результаты

**Скриншот ошибки**

https://user-images.githubusercontent.com/112391788/187185535-157282ca-ce3b-4347-8533-0de30686451a.mp4

**Информация об устройстве:**
 - Устройство: Huawei honor 9x premium 
 - OS: Android 10 | EMUi 10.0.0
 - Коммит: e668cfb (В О Приложении написана версия коммита)

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

**Comment by k1zn** [comment]
дубликат #458
