### ISSUE TITLE
Лента новостей и записи сообществ 

### ISSUE THREAD

**Issue by Lorelein2017** [vtosters/lite#702]
После обновления столкнулась с такой проблемой: 
1. Не отображаются записи сообществ
2. Ничего нет в ленте новостей
![Screenshot_20220830-030849_VTLite](https://user-images.githubusercontent.com/110204480/187320242-61116c53-e0fa-4b30-9d94-b86d0ed5d9f1.jpg)
![Screenshot_20220830-030912_VTLite](https://user-images.githubusercontent.com/110204480/187320245-6c906364-0960-4e20-89ae-63477864470e.jpg)

**Comment by Lorelein2017** [comment]
*дополняют
Помог перезапуск приложения, но не факт, что и дальше такого не будет

**Comment by k1zn** [comment]
fixed in cf4855bdd10315e2ea76510498656611ddaaf990
