### ISSUE TITLE
Удаление папки для видео при смене аккаунта

### ISSUE THREAD

**Issue by HoV9ZoK** [vtosters/lite#705]
**Опишите сам баг**
При входе в приложение удаляется папка, которая указана как папка для видео.

**Опишите действия для воспроизведения ошибки**
1. Убедиться в наличии стандартной папки Movies.
2. Зайти в приложение.
3. Смените папку для видео на любую другую (Android, во смеху будет).
4. Снова зайти в приложение.

**Опишите ожидаемый результат**
До смены папки для скачивания видео:
Будет удалена стандартная папка Movies.
После смены папки:
Будет удаления новая папка.

**Информация об устройстве:**
 - Устройство: Redmi K20
 - OS: Android 11 | CrDroid 7.15
 - Коммит: 41ac03a

**Comment by ArgoniumCode** [comment]
Удаляется даже при входе в приложение, не обязательно смене аккаунта :/

**Comment by HoV9ZoK** [comment]
> Удаляется даже при входе в приложение, не обязательно смене аккаунта :/

У меня срабатывает только после остановки приложения/смены аккаунта.
Коммент исправил, спасибо.

**Comment by ArgoniumCode** [comment]
Исправлено в новейшей версии (?)
