### ISSUE TITLE
Ошибка при загрузке видео в истории

### ISSUE THREAD

**Issue by MrGreenier** [vtosters/lite#706]
При попытке выгрузить видео из галереи в сторис, приложение вылетает

Это фиксится полной очисткой кэша, история начинает грузиться, но так и не загружается, заканчивая ошибкой.

**Comment by danyyok** [comment]
Лог ошибки

Сторис не работает в втл,слишком версия старая

**Comment by k1zn** [comment]
@danyyok нет

только что загрузил историю из пикчи без проблем

**Comment by MrGreenier** [comment]
из пикчи работает. из видео - нет

**Comment by BopB3akoHe1** [comment]
Такая же проблема, зашёл посмотреть как исправить ошибку, но увы
