### ISSUE TITLE
При обновлении регистрации Firebase всё ещё не приходят уведомления

### ISSUE THREAD

**Issue by DrZomberg** [vtosters/lite#709]
Не поступают уведомления

Уведомления приходили только в течение часа месяц назад. 
Пробовал перезапускать приложение полностью после обновления регистрации, но это не помогает. MicroG установлен 

 - Устройство: HONOR 30S
 - OS: Android 10  EMUI 3.1.1
 - Коммит: 41ac03a

**Comment by gdlbo** [comment]
Надо зайти в аккаунт внутри MicroG, дать разрешение на прияниие уведомлений для VTLite и убрать все ограничения на работу в фоне для VTLite и MicroG

**Comment by DrZomberg** [comment]
![Screenshot_20220902_155831_com mgoogle android gms](https://user-images.githubusercontent.com/110172160/188151139-af3d9885-3a30-4faf-bc91-079214e3c3ce.jpg)

**Comment by gdlbo** [comment]
MicroG от Vanced не подойдёт для работы пушей
