### ISSUE TITLE
Шаги ВКонтакте

### ISSUE THREAD

**Issue by D3NKIZZZ** [vtosters/lite#715]
**Опишите сам баг**
При заходе в "Шаги ВКонтакте" бесконечная загрузка интерфейса приложения.

**Опишите действия для воспроизведения ошибки**
Попробовать зайти в приложение.

**Опишите ожидаемый результат**
Приложение должно загрузиться и функционировать, как в обычном VK.

**Скриншот ошибки**
(видео)

https://user-images.githubusercontent.com/112761896/188270571-e87699dd-405b-4461-867f-671936ffdd2f.mp4

**Информация об устройстве:**
 - Устройство: Infinix Hot 11S NFC
 - OS: Android 11 | XOS 7.6.0
 - Коммит: 41ac03a

**Comment by aliveoutside** [comment]
#602
