### ISSUE TITLE
Ошибка открытие заявок в друзья

### ISSUE THREAD

**Issue by kolya123kolya** [vtosters/lite#716]
**Опишите сам баг**
При открытие меню входяших заявок в друзья вызодит ошибка загруски

**Опишите действия для воспроизведения ошибки**
1. При открытие меню входяших заявок в друзья ошибка доступа
**Опишите ожидаемый результат**
Пожалуста пофиксите
![Screenshot_2022-09-03-16-03-54-201_com vtosters android](https://user-images.githubusercontent.com/70913062/188271695-f750a507-f59b-40ea-a01a-31f3a4dd2ffd.jpg)

**Скриншот ошибки**

**Информация об устройстве:**
 - Устройство: Poco F3
 - OS: Android 12 | miui 13
 - Коммит: 6138 (В О Приложении написана версия коммита)

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**
Добавить режим не видимки и закрепление чатов

**Comment by AyonovDenizs** [comment]
@kolya123kolya Че с комитом, брат?

**Comment by AyonovDenizs** [comment]
@kolya123kolya ВТОСТЕРС не поддерживается уже

**Comment by aliveoutside** [comment]
не относится к VTosters Lite
