### ISSUE TITLE
Удаление папки для скачивания 

### ISSUE THREAD

**Issue by Bodisimmo** [vtosters/lite#717]
**Опишите сам баг**
Блядский рот ваших прогеров, была полностью удалена папка Download со всеми данными (около 400 файлов) без способа восстановления 

**Опишите действия для воспроизведения ошибки**
1. Скачал вашу программу

**Опишите ожидаемый результат**
Оторвать руки кто писал код

**Скриншот ошибки**

**Информация об устройстве:**
 - Устройство: Huawei p30
 - OS: Android 11
 - Коммит: fa12e8f (В О Приложении написана версия коммита)

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

**Comment by k1zn** [comment]
3. пойти нахуй с таким отношением к кодерам

**Comment by Bodisimmo** [comment]
> 2. пойти нахуй с таким отношением к кодерам

Посмотрим, что ты бы сделал когда бы потерял свои личные данные из-за кривого кода

**Comment by aliveoutside** [comment]
должно быть исправлено в 4ce55a22f90808ba350645e1299611469e24fb56

у всех важных файлов должны быть бекапы, иначе они не важные
