### ISSUE TITLE
Репост

### ISSUE THREAD

**Issue by eaksen1109** [vtosters/lite#72]
Через некоторое время после листания ленты новостей, пропадает возможность кинуть репост друзьям

**Comment by gdlbo** [comment]
Что? Скриншоты пожалуйста

**Comment by eaksen1109** [comment]
Добрый день, как мог написал, появляется такая ситуация, висит бесконечно, после закрытия приложения, всё становится нормально, со временем появляется такая ситуация снова

Sent with a Spark
29 мар. 2022 г., 11:43 +0300, gdlbo ***@***.***>, написал (-а):

**Comment by uniqueUsernameIsNotAvailable** [comment]
Android 11, vtl 0.0.6
Не смог воспроизвести, отмотал двое суток, но смог делать репосты в обычном режиме
