### ISSUE TITLE
проблема с рекомендациями на старом дизайне

### ISSUE THREAD

**Issue by 667vwv** [vtosters/lite#721]
рекомендации не хотят обновляться.

[видео закинул на диск](https://disk.yandex.ru/i/6ZzDX2zjW9_kuQ)  
0.4.13 / 63f4ed3
redmi 9 / android 11

**Comment by k1zn** [comment]
@667vwv  запиши логи через дебаг меню

(настройки -> о приложении -> зажать текст сверху)
затем перезайти в настройки (прямо перезайти), сверху появится "дебаг меню", открой его, включи там "логирование api" и затем нажми "запись в файл"

после этих действий не перезапуская приложение повтори этот баг, перезайди в приложение и лог сохранится по пути /VK/logs
скинь его сюда

**Comment by 667vwv** [comment]
что-то загрузилось, то и закину. теперь, вроде, работает, оставляет один пост, а другие долго грузит. грешу на инет.
![Screenshot_2022-09-06-18-54-17-853_com vtosters lite](https://user-images.githubusercontent.com/102009600/188653923-d2c60f1f-b09f-4371-9f6f-29b2dbd6875f.jpg)


[VK.logup.zip](https://github.com/vtosters/lite/files/9497571/VK.logup.zip)

**Comment by k1zn** [comment]
@667vwv  чет лог пустой, запиши еще раз (надеюсь логирование апи не забыл включить (не трогай уже если включил))

**Comment by k1zn** [comment]
@667vwv  не в распаковке дело, я говорю в логе нету запроса к рекомендациям вообще, только вкшные лонгполлы и прочий мусор

**Comment by 667vwv** [comment]
только их и отдаёт после перезапуска 
![Screenshot_2022-09-06-19-11-19-100_com estrongs android pop](https://user-images.githubusercontent.com/102009600/188657882-56c9883f-625e-4d1d-a4e2-0b9ebcd58cb2.jpg)
![Screenshot_2022-09-06-19-11-23-169_com estrongs android pop](https://user-images.githubusercontent.com/102009600/188657887-a8ad8b7e-ef65-4efb-a664-c27413a45549.jpg)
 
![Screenshot_2022-09-06-19-09-50-052_com vtosters lite](https://user-images.githubusercontent.com/102009600/188657869-aa5fa12f-5669-4f0a-9743-5db3b825b297.jpg)
![Screenshot_2022-09-06-19-09-53-280_com vtosters lite](https://user-images.githubusercontent.com/102009600/188657876-7af77ae2-2729-4256-aa85-017682fb72cb.jpg)
![Screenshot_2022-09-06-19-09-56-141_com vtosters lite](https://user-images.githubusercontent.com/102009600/188657881-6ec53061-219f-42c4-b214-e414a238655b.jpg)

**Comment by aliveoutside** [comment]
ещё актуально?
