### ISSUE TITLE
Ошибка изменения имени в диалогах 

### ISSUE THREAD

**Issue by Mammoth5335** [vtosters/lite#722]
**Опишите сам баг**
При долгом использовании приложения, изменённое в приложении имя пользователя меняется на имя, стоящее у меня в контактах телефона, хотя у приложения нет разрешения на доступ к контактам. 

**Опишите действия для воспроизведения ошибки**
1. Долго сижу в приложении
2. Имя меняется на имя контактов телефона 

**Опишите ожидаемый результат**
Имя пользователя не изменяется на имя в контактах телефона, когда к ним нет доступа

**Скриншот ошибки**

**Информация об устройстве:**
 - Устройство: Samsung Galaxy М31
 - OS: Android 12 | OneUi 4.1
 - Коммит: 63f4ed3 (В О Приложении написана версия коммита)

**Comment by gdlbo** [comment]
Отключи синхронизацию контактов
