### ISSUE TITLE
Вылет при открытии уведомления о новой записи

### ISSUE THREAD

**Issue by TheGreatLine** [vtosters/lite#724]
**Опишите сам баг**
Вылет при открытии уведомления о новой записи

**Опишите действия для воспроизведения ошибки**
1. Нажал на уведомление о новой записи в сообществе
2. Вылет со всплывающим окошком "Ошибка"

**Опишите ожидаемый результат**
Исправление вылета.

**Скриншот ошибки**

**Информация об устройстве:**
 - Устройство: Samsung Galaxy S21 Ultra
 - OS: Android 12 | OneUi 4.1
 - 63f4ed3

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

**Comment by psamur** [comment]
@TheGreatLine Можно ссылку на пост, который не открывался?

**Comment by TheGreatLine** [comment]
Абсолютно ЛЮБОЙ пост.
Речь идёт об уведомлениях о новых записях из сообщества (что включаются по
колокольчику)

ср, 7 сент. 2022 г., 14:34 Pavel ***@***.***>:
