### ISSUE TITLE
Ошибка обновлении ленты новостей

### ISSUE THREAD

**Issue by Zhemkovch** [vtosters/lite#725]
****в сообщениях не работает поиск(в самом диалоге) 
**Так же не работает кнопка "показать вложения" в диалогах
В принципе все кнопки в открытом диалоге не работают.

![Screenshot_2022-09-06-23-24-15-780_com.vtosters.lite.jpg](https://user-images.githubusercontent.com/95728150/188731190-e37d575c-0e58-4484-b2e8-d2ebd9fe5ef4.jpg)

**Информация об устройстве:**
 - Устройство: Redmi Note 10S
 - OS: Android 13 | miui 13.0.3
 - Коммит: d68fb09

**Comment by k1zn** [comment]
обновись

**Comment by danyyok** [comment]
Срань господня
