### ISSUE TITLE
Не работает функция отключения автоматического обновления новостей

### ISSUE THREAD

**Issue by Sad-Man-357** [vtosters/lite#726]
**Опишите сам баг**
Лента новостей обновляется при входе в приложение

**Опишите действия для воспроизведения ошибки**
1. В настройках ленты новостей в пункте "Автоматическое обновление новостей" выставил "Не обновлять"
2. При открытии приложения лента всё равно обновляется автоматически

**Опишите ожидаемый результат**
Лента новостей не обновляется автоматически при входе в приложение (необходимо обновлять  вручную)

**Скриншот ошибки**
![b7fe4f83-2122-422c-9385-0758c5e1d260](https://user-images.githubusercontent.com/112997265/188784350-7c01ffba-340b-470a-a696-075d594ef0ae.jpg)

**Информация об устройстве:**
 - Устройство: Redmi Note 11 Pro
 - OS: Android 12 | Miui 13.0.3.0

**Comment by gdlbo** [comment]
У тебя на скриншоте даже видно что отключено сохранение (кеширование) постов в ленте

**Comment by Sad-Man-357** [comment]
Не думал, что эти 2 пункта связаны. Проверил сейчас со включенным (кешированием), в принципе новости не обновляются, но лента загружается с самого начала. А возможности продолжить с того поста, где закрыл приложение тут нет?
