### ISSUE TITLE
727

### ISSUE THREAD

**Issue by k1zn** [vtosters/lite#727]
создаю 727 issue чтобы его удалить

**Comment by gdlbo** [comment]
727 must die

**Comment by kr3st1k** [comment]
![20220907_090020.jpg](https://user-images.githubusercontent.com/20841380/188816906-59731bcb-6c0e-406f-b08b-fe3e211cec6c.jpg)

**Comment by DHCPCD9** [comment]
when you see it.

**Comment by oplexz** [comment]
@DHCPCD9 wysi
