### ISSUE TITLE
При заходе в музыку пишет ошибка и есть кнопка повторить которая ни на что не влияет

### ISSUE THREAD

**Issue by Qeertyover** [vtosters/lite#729]
**Опишите сам баг**
При заходе в музыку появляется ошибка

**Опишите действия для воспроизведения ошибки**
1. Этот баг происходит случайно

**Опишите ожидаемый результат**
Жду фикса бага/ошибки

**Скриншот ошибки**
![Screenshot_20220908_160231_com vtosters android](https://user-images.githubusercontent.com/113114679/189131229-ee3efc49-8bf6-4a94-96e5-7757bf2944dc.jpg)

**Информация об устройстве:**
 - Устройство: Honor 9X STK-LX1
 - OS: Android 10 | EMUI 10.0.0

**Дополнительная информация о баге или мыслях
Уже лично у меня была такая ошибка, но прошла и сейчас снова появилась и мне бы хотелось чтобы такого больше не было

**Comment by danyyok** [comment]
Гений оставляет иссуе по ВТЛ используя обычный тостер
ВТОСТЕРС не поддерживается, качай втлайт vtosters.app

**Comment by Qeertyover** [comment]
Пасиб, не шарю просто

**Comment by AyonovDenizs** [comment]
Юзеры ВТостерса (non lite) идут домой. Качай VTLite.
https://github.com/VTosters/lite/release/latest
