### ISSUE TITLE
Некорректное отображение темной темы приложения 

### ISSUE THREAD

**Issue by Staryi2000** [vtosters/lite#731]
**Опишите сам баг**
При включении темной темы телефона, темная тема приложения отображается некорректно, требуется включать ее в ручную 

**Опишите действия для воспроизведения ошибки**
1. Переключение темной темы телефона 
2. Открытие приложении Vtosters lite

**Опишите ожидаемый результат**
Корректное отображение темной темы в автоматическом режиме 

**Скриншот ошибки**

**Информация об устройстве:**
 - Устройство: Xiaomi mi mix 2s
 - OS: Android 10 MIUI 12.0.3
 - Коммит: 63f4ed3

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

**Comment by danyyok** [comment]
А где ты в втл нашел автоматическую смену темы?🤓

**Comment by Staryi2000** [comment]
> 

Ее там нет
Но раз приложение красится автоматом под тему системы телефона, то почему не сделать это корректно, либо выпилить это вовсе

**Comment by danyyok** [comment]
> > 
> 
> Ее там нет
> Но раз приложение красится автоматом под тему системы телефона, то почему не сделать это корректно, либо выпилить это вовсе

База вк старая,это вроде делается а вроде не делается

**Comment by inotflying** [comment]
Причём здесь оболочка, если VTL не умеет в автоматическую смену темы?

**Comment by aliveoutside** [comment]
> Причём здесь оболочка, если VTL не умеет в автоматическую смену темы?

проблема изначально в другом
