### ISSUE TITLE
Перезагрузка приложения после вкл/выкл "Подписи в настройках"

### ISSUE THREAD

**Issue by danyyok** [vtosters/lite#732]
**Опишите вашу идею максимально подробно и понятно**
После того,как пользоваться отключил или включил функцию "Показать подписи в настройках" приложение ничего не делает,пользователь сам должен перезагрузить приложение что бы настройки встали

**Опишите возможное решение/реализацию функции (если понимаете как это можно реализовать на Java/C++)**
Пезеагрузка приложения после включения/выключения😱

**Остальные мысли о предложенной функции**
#701

**Comment by aliveoutside** [comment]
dc4743f2a3949ac3edb1aa264a9e5db614dd951b
