### ISSUE TITLE
Ошибка звонков

### ISSUE THREAD

**Issue by stolyarvan** [vtosters/lite#733]
При попытке позвонить мне кому-то или наоборот - не удаётся вызов и пишет ошибка

1. Нажатие кнопки звонка
2. Неудача
p.s. в обратном направлении так-же

Ожидаем фикса ошибки, чтобы звонки в ВТЛайт были осуществимы.

![Screenshot_20220909_222525](https://user-images.githubusercontent.com/111465226/189431000-1e90a6ef-b6f4-4544-ba72-a911aad57262.jpg)
![Screenshot_20220909_222243_com huawei himovie overseas](https://user-images.githubusercontent.com/111465226/189431007-c4d3a618-a145-4f4e-88c7-fb7057d99c6c.jpg)
![Screenshot_20220909_222251_com huawei himovie overseas](https://user-images.githubusercontent.com/111465226/189431011-5ea28f50-2932-444a-8469-f376c2d0d0ed.jpg)
![Screenshot_20220909_222306_com huawei himovie overseas](https://user-images.githubusercontent.com/111465226/189431013-a63e5ee3-a673-4c45-8202-2720892a355f.jpg)
![Screenshot_20220909_222627](https://user-images.githubusercontent.com/111465226/189431016-1a60256f-9463-4fdc-9677-9cc9a0ecdb0f.jpg)

**Информация об устройстве:**
 - Устройство:  Honor 9X
 - OS: Android 10 | EMUI 10.0.0
 - Коммит: 63f4ed3

**Comment by k1zn** [comment]
ВКонтакте убили звонки на старых версиях
