### ISSUE TITLE
Ошибка отображения публикаций в группе

### ISSUE THREAD

**Issue by artemisbullshit** [vtosters/lite#736]
**Опишите сам баг**
После публикации записей в группе, некоторые из них исчезают и не отображаются, при переходе на них по ссылке пишется "Запись не найдена". При этом, остальным пользователям она видна. 

**Опишите действия для воспроизведения ошибки**
Опубликовал пост в личной закрытой группе с подписчиками. 

**Опишите ожидаемый результат**
Посты должны отображаться не только в официальном приложении. 

**Скриншот ошибки**
-

**Информация об устройстве:**
 - Устройство: Huawei y6
 - OS:? 
 - Коммит: 63f4ed3 

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

**Comment by gdlbo** [comment]
Добавь группу в исключения для блокировки рекламы/фильтров

**Comment by k1zn** [comment]
@artemisbullshit вероятнее всего у тебя включены фильтры, которые удаляют посты. Добавь группу в вайтлист фильтров (три точки внутри группы), либо отключи фильтры.
