### ISSUE TITLE
Сообщения пропускаются после захода в чат с уведомления

### ISSUE THREAD

**Issue by danyyok** [vtosters/lite#737]
**Опишите сам баг**
Если в беседе будет много сообщений (50+) соответственно появится и уведомление,и если нажать на уведомление пользователя перекинет в беседу,но не с начала переписки а в конец,хотя такого не должно быть

**Опишите действия для воспроизведения ошибки**
1. Нажал на уведомление с 50+ сообщениями (обязательно 40/50+)
2. Втлайт автоматически пролистал вниз беседы,не с начала переписки 

**Опишите ожидаемый результат**
При нажатии на уведомление все должно открытся с начала переписки

**Информация об устройстве:**
 - Устройство: Redmi S2
 - OS: Android 9 | MIUI 12.0.2.0
 - Коммит: e052552

**Дополнительная информация о баге или мыслях почему оно может происходить **
Если перейти в беседу со списка чатов беседа откроется с начала переписки (с хуйни "Не прочитанные сообщения" или д.р)

**Comment by Computershik73** [comment]
@danyyok у меня был редми s2
