### ISSUE TITLE
В Лайт версии не открывается поисковик музыки и рекомендации 

### ISSUE THREAD

**Issue by Yaaysjf** [vtosters/lite#740]
При входе в раздел "аудиозаписи" все отображается корректно, но стоит зайти в поисковик и вбить буквально любое название — выдаёт ошибку. При нажатии кнопки "повторить" ничего не происходит. С рекомендациями такая же история. 
Установлена новая лайт версия. 
 - Устройство: Honor 30i
 - OS: Android 9 | Magic UI 3.1. 0
 - Коммит: v0.4.13-beta 
![Uploading Screenshot_20220914_003536_com.vtosters.lite.jpg…]()
![Screenshot_20220914_003541_com vtosters lite](https://user-images.githubusercontent.com/113477379/190014206-ded13184-8e09-4d7f-923d-10148206363f.jpg)
![Uploading Screenshot_20220914_003544_com.vtosters.lite.jpg…]()

**Comment by GooDoG337** [comment]
Новый дизайн музыки включал?

**Comment by Yaaysjf** [comment]
> Новый дизайн музыки включал?

Нет, сейчас попробую

**Comment by Yaaysjf** [comment]
Все заработало, спасибо

**Comment by aliveoutside** [comment]
старый каталог музыки был убит со стороны вк, надо включать новый

вырезано в #739
