### ISSUE TITLE
Ошибка обновлении ленты новостей

### ISSUE THREAD

**Issue by DeLi0v** [vtosters/lite#741]
**Опишите сам баг**
При включении темной темы на устройстве, в приложении светлая тема не переключается на темную (и наоборот)

**Опишите ожидаемый результат**
Чтобы при переключении темы на устройстве она менялась и в приложении (в VTosters она работает)

**Информация об устройстве:**
 - Устройство: Xiaomi Redmi Note 9 Pro
 - OS: Android 11
 - Коммит: 63f4ed3

**Comment by GooDoG337** [comment]
В следующем обновлении планируется, как помню, а про ленту новостей поподробнее хочется узнать

**Comment by Computershik73** [comment]
@DeLi0v

**Comment by aliveoutside** [comment]
Как связаны заголовок и проблема?

0ed16b0836a6e87ed4f032347948f15a6e404bab

**Comment by DeLi0v** [comment]
> Как связаны заголовок и проблема?
> 
> 0ed16b0836a6e87ed4f032347948f15a6e404bab

Забыл изменить заголовок из шаблона
