### ISSUE TITLE
Ошибка синхронизации изменения темной темы на устройстве и в приложении 

### ISSUE THREAD

**Issue by DeLi0v** [vtosters/lite#742]
**Опишите сам баг**
При включении темной темы на устройстве, в приложении светлая тема не переключается на темную (и наоборот)

**Опишите ожидаемый результат**
Чтобы при переключении темы на устройстве она менялась и в приложении (в VTosters она работает)

**Информация об устройстве:**
Устройство: Xiaomi Redmi Note 9 Pro
OS: Android 11
Коммит: 63f4ed3

**Comment by GooDoG337** [comment]
Скорее всего добавят в следующем обновлении

**Comment by aliveoutside** [comment]
дубликат #741

сделано в 0ed16b0836a6e87ed4f032347948f15a6e404bab
