### ISSUE TITLE
Не работает поиск музыки

### ISSUE THREAD

**Issue by Ya1iX** [vtosters/lite#743]
Сам раздел музыки работает, я могу ее слушать, сохранять и т.п. Но при попытке воспользоваться поиском выдает ошибку.

1. Зайти в раздел музыки 
2. Нажать на строку поиска
3. Ввести запрос и отправить его

Должен выводиться список аудиозаписей, подходящих под запрос поиска.

![Screenshot_2022-09-14-16-20-24-772_com.vtosters.lite.jpg](https://user-images.githubusercontent.com/62989500/190166400-15b35ff2-9e4e-42a2-9745-af0250c1a179.jpg)

 - Устройство: Xiaomi Redmi Note 8 Pro
 - OS: Android 11 | MIUI 12.5.1 Stable
 - Коммит: 63f4ed3

Предполагаю, что ВК опять что-то поменяли в разделе музыки, либо неисправность в моем телефоне. Буквально на днях я установил антивирус Dr.Web Lite, не уверен что это взаимосвязано, но возможно это как-то влияет, хотелось получить точный ответ. Антивирус не ругался на приложение.

**Comment by person1030** [comment]
@Ya1iX Новый раздел музыки в настройки → медиа контент включи.

**Comment by Ya1iX** [comment]
> @Ya1iX Новый раздел музыки в настройки → медиа контент включи.

Благодарю, сработало

**Comment by aliveoutside** [comment]
дубликат #740

**Comment by Rusikfff** [comment]
> @Ya1iXНовый раздел музыки в настройках → медиаконтент включи.

А где найти это раздел? Можно по фоткам а то сколько искал не могу найти

**Comment by danyyok** [comment]
@Rusikfff Ебать даун

**Comment by EliteMrMikePro** [comment]
![cbeNnNFd1IgkPSdwYCynmiUvs9lST1hueGVZngvDWQ4dTMiy1cndZNzsIPPGnQtlJ1BEc8T-AfkliGIJINVrDBrJ](https://user-images.githubusercontent.com/113859734/190926934-6c019684-5030-4d38-9502-d61e2046c66b.jpg)



> @Ya1iX Новый раздел музыки в настройки → медиа контент включи.
Я вкл. но музыку не ищет возможно не то, если есть скрин  или более подробно пожалуйста.

**Comment by Rusikfff** [comment]
Где найти этот плеер??
![Uploading IMG_20220919_082734.jpg…]()

**Comment by Rusikfff** [comment]
![IMG_20220919_082734](https://user-images.githubusercontent.com/113856623/190954688-57ec1de7-2a63-4dc1-af5c-63cd6910044a.jpg)
Где найти? Не могу найти срочно надо

**Comment by EliteMrMikePro** [comment]
> ![IMG_20220919_082734](https://user-images.githubusercontent.com/113856623/190954688-57ec1de7-2a63-4dc1-af5c-63cd6910044a.jpg) Где найти? Не могу найти срочно надо

Установить vtoster lite там все ок
