### ISSUE TITLE
Ошибка при попытке найти исполнителя через плеер 

### ISSUE THREAD

**Issue by icoperot** [vtosters/lite#745]
"Ошибка" при попытке "тыкнуть" на исполнителя песни в плеере или специальном меню. 
Пробовал все возможные vpn (как те, что доступны в самом приложении, так и сторонние), эффекта ноль.
В старой версии приложения  VTosters (поддержка которого прекращена) поиск работает исправно. 

![Скрин1](https://user-images.githubusercontent.com/113563065/190283042-1f613318-cc1c-455e-a3ff-56f3c1472c28.jpg)
![Скрин 2](https://user-images.githubusercontent.com/113563065/190283050-03cf42f3-d198-4443-84b5-582da2c066a5.jpg)

Версия приложения: 0.4.13
Устройство: Galaxy s8, Android 9

**Comment by aliveoutside** [comment]
исправлено в 0.4.14

**Comment by icoperot** [comment]
> В старой версии приложения VTosters (поддержка которого прекращена) поиск работает исправно.

К сожалению всё так же ошибка

**Comment by icoperot** [comment]
> > В старой версии приложения VTosters (поддержка которого прекращена) поиск работает исправно.
> 
> К сожалению всё так же ошибка

В версии 0.4.15 ошибка сохраняется

**Comment by icoperot** [comment]
Пофиксили! Спасибо.
