### ISSUE TITLE
Возможность выбора очередности вкладок в "Музыке"

### ISSUE THREAD

**Issue by KaworuNoriaki** [vtosters/lite#748]
**  Идея заключается в том, чтобы можно было сразу переходить в свою музыку, а не в раздел "Главное" [который наху. никому не всрался (имхо)]

** Кажется видел уже что-то похожее в других клиентах так что очень надеюсь что это не сложно сделать

** Считаю это очень неудобным и некрасивым, каждый раз делать этот поганый свайп, я не знаю ни одного человека который в большинстве случаев заходил бы в музыку для поиска музыки (уж тем более через сам поиск, а не группы) а не для прослушивания своей (ктобымогподумать) музыки.

**Comment by inotflying** [comment]
В настройки так трудно зайти?

**Comment by aliveoutside** [comment]
> Идея заключается в том, чтобы можно было сразу переходить в свою музыку, а не в раздел "Главное" [который наху. никому не всрался (имхо)]

**настройки -> медиа -> музыка**
разве не оно?

**Comment by KaworuNoriaki** [comment]
Я идиот господа, прошу прощения
