### ISSUE TITLE
Ошибка темной темы после перезахода

### ISSUE THREAD

**Issue by Kymek** [vtosters/lite#751]
При перезаходе в VTLite слетает темная тема, на светлую

 - Устройство: Samsung Galaxy A52
 - OS: Android 12 | OneUi 4.1
 - Коммит: 1e0e432

**Comment by GooDoG337** [comment]
@Kymek "Использовать системную тему" отключено?

**Comment by Kymek** [comment]
@GooDoG337 Не заметил эту функцию, спасибо.
