### ISSUE TITLE
.

### ISSUE THREAD

**Issue by themrfire** [vtosters/lite#753]

**Comment by danyyok** [comment]
Научись уже блять делать нормальные иссуес,пожалуйста
Для тебя уже все было готово а ты блять все стираешь и в заголовке пишешь коммит
И не надо нахуй кидать видео разрабам,у них нет времени на тавое видео,в гитхабе есть поддержка фоток/видео
И кинь лог еще,почему у тебя на рабочий стол кидает
Возможно у тебя включена интеграция с вкх,а вкха нет

**Comment by themrfire** [comment]
> Научись уже блять делать нормальные иссуес,пожалуйста Для тебя уже все было готово а ты блять все стираешь и в заголовке пишешь коммит И не надо нахуй кидать видео разрабам,у них нет времени на тавое видео,в гитхабе есть поддержка фоток/видео И кинь лог еще,почему у тебя на рабочий стол кидает Возможно у тебя включена интеграция с вкх,а вкха нет

1. Я как хочу, так и описываю свою проблему. 🥱
2. ↑
3. В мобильной веб версии можно только кидать картинки. 🥱
4. Я скинул лог разработчику, вдруг ты мои данные там обнаружишь. 🥱
5. Я такой настройки не нашёл. 🥱

**Comment by danyyok** [comment]
> > Научись уже блять делать нормальные иссуес,пожалуйста Для тебя уже все было готово а ты блять все стираешь и в заголовке пишешь коммит И не надо нахуй кидать видео разрабам,у них нет времени на тавое видео,в гитхабе есть поддержка фоток/видео И кинь лог еще,почему у тебя на рабочий стол кидает Возможно у тебя включена интеграция с вкх,а вкха нет
> 
> 1. Я как хочу, так и описываю свою проблему. 🥱
> 2. ↑
> 3. В мобильной веб версии можно только кидать картинки. 🥱
> 4. Я скинул лог разработчику, вдруг ты мои данные там обнаружишь. 🥱
> 5. Я такой настройки не нашёл. 🥱

Всем похуй на то как ты хочешь,иссуе есть иссуе
С таким кривым и стертым иссуе тебе никто не ответит
Скачай гитхаб в плей маркете
Там нет никаких данных,в логе что блять пишет твое местоположение?данные об устройстве важны,и больше там ничего нет,кроме ошибки.Как я сказал,нахуя ты засоряешь лс разработчику если в твоем логе нет нихуя такого
А ты попробуй еще раз поискать

**Comment by danyyok** [comment]
> > > Научись уже блять делать нормальные иссуес,пожалуйста Для тебя уже все было готово а ты блять все стираешь и в заголовке пишешь коммит И не надо нахуй кидать видео разрабам,у них нет времени на тавое видео,в гитхабе есть поддержка фоток/видео И кинь лог еще,почему у тебя на рабочий стол кидает Возможно у тебя включена интеграция с вкх,а вкха нет
> > 
> > 1. Я как хочу, так и описываю свою проблему. 🥱
> > 2. ↑
> > 3. В мобильной веб версии можно только кидать картинки. 🥱
> > 4. Я скинул лог разработчику, вдруг ты мои данные там обнаружишь. 🥱
> > 5. Я такой настройки не нашёл. 🥱
> 
> Всем похуй на то как ты хочешь,иссуе есть иссуе
> С таким кривым и стертым иссуе тебе никто не ответит
> Скачай гитхаб в плей маркете
> Там нет никаких данных,в логе что блять пишет твое местоположение?данные об устройстве важны,и больше там ничего нет,кроме ошибки.Как я сказал,нахуя ты засоряешь лс разработчику если в твоем логе нет нихуя такого
> А ты попробуй еще раз поискать

Или ты опять не хочешь "засорять" свой телефон?😂

**Comment by themrfire** [comment]
> > > > Научись уже блять делать нормальные иссуес,пожалуйста Для тебя уже все было готово а ты блять все стираешь и в заголовке пишешь коммит И не надо нахуй кидать видео разрабам,у них нет времени на тавое видео,в гитхабе есть поддержка фоток/видео И кинь лог еще,почему у тебя на рабочий стол кидает Возможно у тебя включена интеграция с вкх,а вкха нет
> > > 
> > > 
> > > 
> > > 1. Я как хочу, так и описываю свою проблему. 🥱
> > > 2. ↑
> > > 3. В мобильной веб версии можно только кидать картинки. 🥱
> > > 4. Я скинул лог разработчику, вдруг ты мои данные там обнаружишь. 🥱
> > > 5. Я такой настройки не нашёл. 🥱
> > 
> > 
> > Всем похуй на то как ты хочешь,иссуе есть иссуе
> > С таким кривым и стертым иссуе тебе никто не ответит
> > Скачай гитхаб в плей маркете
> > Там нет никаких данных,в логе что блять пишет твое местоположение?данные об устройстве важны,и больше там ничего нет,кроме ошибки.Как я сказал,нахуя ты засоряешь лс разработчику если в твоем логе нет нихуя такого
> > А ты попробуй еще раз поискать
> 
> Или ты опять не хочешь "засорять" свой телефон?😂

Чел ты кто вообще такой? 🥱 Чего ты на меня так атаку ведёшь? 🥱 Я всего лишь написал свой issue, а ты решил до меня докопаться. 😠

**Comment by person1030** [comment]
@themrfire Чел, в чём проблема нажать на иконку "изображение"  и скинуть видео сюда?

**Comment by themrfire** [comment]
> @themrfire Чел, в чём проблема нажать на иконку "изображение" и скинуть видео сюда?

Не скидывается, пытаюсь скинуть видео, а текст с загрузкой видео исчезает. ☹️

**Comment by yebangithub** [comment]
https://user-images.githubusercontent.com/54277054/190589927-7499bab7-2148-4b74-8200-46c97266cbe1.mp4

загрузка видео

**Comment by yebangithub** [comment]
> > @themrfire Чел, в чём проблема нажать на иконку "изображение" и скинуть видео сюда?
> 
> Не скидывается, пытаюсь скинуть видео, а текст с загрузкой видео исчезает. ☹️


https://user-images.githubusercontent.com/54277054/190590445-6ab67a4c-a899-46d0-9815-e8e937110ea3.mp4

ещё видео

**Comment by AyonovDenizs** [comment]
@themrfire Шаблоны придумали для того, чтобы игнорировать?
