### ISSUE TITLE
Постоянно выскакивает окошко о новой версии

### ISSUE THREAD

**Issue by Plaksa1991** [vtosters/lite#754]
При перезаходе постоянно выскакивает окно о новой верси, хотя она уже установлена.
При нажатии на кнопку обновить, устанавливается скаченное обновление и так по кругу
![Screenshot_2022-09-16-13-43-13-63_9e1a5d6211a0228d32d39446541891f1](https://user-images.githubusercontent.com/113686098/190621987-fa814475-d408-4e16-bd55-cbfda96aaa96.jpg)

 - Устройство: Realme GT Neo 2
 - OS: Android 12, Realme UI 3.0
 - Коммит: 63f4ed3

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

**Comment by aliveoutside** [comment]
обновись ещё раз, проблема была на нашей стороне и другими подтверждено что она исправлена
