### ISSUE TITLE
Нету кнопки аудио/видео звонка

### ISSUE THREAD

**Issue by MyauchkaDaDaYa** [vtosters/lite#755]
Пропала кнопка звонков, ее нет как в сообщениях, так и в настройках.

1Собеседник не может мне позвонить, у мен нет уведомления, пишет, что звонок пропущен
2 В попытках перезвонить используя сообщения о пропущено вызове появляется экран звонка, но тут же вылетает обратно в диалог.

Отключил звонки в старой версии, когда перешёл из Втостерса на VTlite.

 - Устройство: Xiaomi Redmi 9T
 - OS: Android 11 | MIUI 12.5.8 (+ предыдущие версии)
 - Коммит: 090с82d (+все версии примерно с 3.8 обновления)

Много раз переустанавливать приложение, примерно с версии 3.8. В настройках так и не появлялся пункт отключения звонков. В официальной версии ВК все работает, но ваше приложение намного удобнее. 
Разрешения для приложения соответствующие включены. Началось все с момента, когда перестала работать музыка во Втостерса и я ушёл на ВТ лайт, где узнал о новых правилах ВК айди

**Comment by GooDoG337** [comment]
Нет звонков

**Comment by danyyok** [comment]
> Пропала кнопка звонков, ее нет как в сообщениях, так и в настройках.
> 
> 1Собеседник не может мне позвонить, у мен нет уведомления, пишет, что звонок пропущен
> 2 В попытках перезвонить используя сообщения о пропущено вызове появляется экран звонка, но тут же вылетает обратно в диалог.
> 
> Отключил звонки в старой версии, когда перешёл из Втостерса на VTlite.
> 
>  - Устройство: Xiaomi Redmi 9T
>  - OS: Android 11 | MIUI 12.5.8 (+ предыдущие версии)
>  - Коммит: 090с82d (+все версии примерно с 3.8 обновления)
> 
> Много раз переустанавливать приложение, примерно с версии 3.8. В настройках так и не появлялся пункт отключения звонков. В официальной версии ВК все работает, но ваше приложение намного удобнее. 
> Разрешения для приложения соответствующие включены. Началось все с момента, когда перестала работать музыка во Втостерса и я ушёл на ВТ лайт, где узнал о новых правилах ВК айди
> 

ВКонтакте отключили звонки на старых версиях вк,звонить можно в приложении гугл плей- VK Звонки
