### ISSUE TITLE
Вылет

### ISSUE THREAD

**Issue by Ubica282** [vtosters/lite#758]
![Screenshot_2022-09-17-00-33-17-94_b783bf344239542886fee7b48fa4b892](https://user-images.githubusercontent.com/102459744/190795756-efaa03b8-4bbb-49f1-8c86-f3930142b028.jpg)

**Comment by danyyok** [comment]
Жди обновы,вроде исправлено

**Comment by efessor** [comment]
https://foxbin.f0x1d.com/24VlLb3HIk

**Comment by aliveoutside** [comment]
исправлено в 8b614f786d6606c91ff0e02be1cdec2fc2617437
