### ISSUE TITLE
Ошибка воспроизведения музыки

### ISSUE THREAD

**Issue by theclouferc** [vtosters/lite#759]
**Опишите сам баг**
При попытке включить любую музыку ничего не происходит. При выборе трека и нажатии кнопки "Слушать далее" крашит приложение.
С интеграцией VK X всё также.

**Опишите действия для воспроизведения ошибки**
1. Выбрать трек, нажать три точки
2. Нажать "Слушать далее"

**Опишите ожидаемый результат**
Треки должны воспроизводиться 

**Скриншот ошибки**
(При нажатии кнопки "Слушать далее"
[VTL_log_2022-09-17.04-37-51.txt](https://github.com/vtosters/lite/files/9590724/VTL_log_2022-09-17.04-37-51.txt)
При воспроизведении музыки всё просто, 0 реакции

**Информация об устройстве:**
 - Устройство: Honor 8S Prime
 - OS: Android 9 | Emui 9.1.0
 - Коммит: db51fb0 (В О Приложении написана версия коммита)

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

**Comment by iTaysonLab** [comment]
если включена интеграция, то кнопка "воспроизвести в вкх" в меню работает или тоже крашит?
