### ISSUE TITLE
Фичи с последних версий официального приложения

### ISSUE THREAD

**Issue by HjA1011** [vtosters/lite#765]
1. При заходе в меню группы нужна кнопка "похожие группы"
2. Кеш музыки 
3. Раздел новостей с тремя вкладками "новости", "для вас" и "актуальное"

**Comment by AyonovDenizs** [comment]
Для первого возможно, добавлено с этого комита [(ссылка на Github Action)](https://github.com/vtosters/lite/actions/runs/3074168377)

**Comment by gdlbo** [comment]
Нет
В процессе
Нет
