### ISSUE TITLE
Добавление людей в список вайтлиста фильтров

### ISSUE THREAD

**Issue by danyyok** [vtosters/lite#767]
**Опишите вашу идею максимально подробно и понятно**
Все фильтры затрагивают **людей**,но для них нет функции с вайтлистом,как это было сделано с **сообществами**.

**Дополнительные мысли**
Также можно просто сделать так,что-бы фильтры не затрагивали людей,не добавляя кнопки "Добавить в вайтлист фильтров".

**Comment by gdlbo** [comment]
Бессмысленная шняга

**Comment by danyyok** [comment]
Для решения можно просто ввести айди человека в бэкап
Все просто👍
