### ISSUE TITLE
антивирус

### ISSUE THREAD

**Issue by tiititi** [vtosters/lite#768]
вот такая штука значит
![IMG_20220919_071456.jpg](https://user-images.githubusercontent.com/75739675/190948962-798430bc-d6f6-4556-aa27-4eb4048ff55a.jpg)![Screenshot_2022-09-19-07-13-15-390_com.kms.free.png](https://user-images.githubusercontent.com/75739675/190948966-df1e645d-0757-47e8-8ca6-a70cf84db031.png)

**Comment by AyonovDenizs** [comment]
#696 читать
