### ISSUE TITLE
Неправильное поведение перетаскивания музыки в списке воспроизведения

### ISSUE THREAD

**Issue by abel1502** [vtosters/lite#769]
**Опишите сам баг**
При перетаскивании музыки в списке воспроизведения "далее", в прошлых версиях поведение соответствовало интуиции. Когдя я тянул трек с одного места на другое, он просто туда перемещался. Сейчас же, в последней версии, то же действие приводит к тому, что перетянутый трек меняется местами с тем, на чьё место он перетянут. Например, если треки чшли по порядку 1 2 3 4 5 6, и трек 2 перетянули на место между 5 и 6, то раньше это давало порядок 1 3 4 5 2 6, а теперь - 1 5 3 4 2 6. Отдельный эксперимент показал, что свежая оф. версия ведёт себя как старая версия втлайта. 

**Опишите действия для воспроизведения ошибки**
1. Открыть музыку
2. Раздел "Моя музыка"
3. Включить любой клип
4. Нажать на бар плеера внизу
5. Включить рандомный порядок воспроизведения (м/б необязательно)
6. Свайпнуть влево - должно открыться меню "Далее" со списком следующих песен на очереди
7. Выполнить действия из первой секции

**Опишите ожидаемый результат**
Поведение, соответствующее оф. клиенту и старым версия втлайта.

**Скриншот ошибки**

**Информация об устройстве:**
 - Устройство: Samsung Galaxy M31
 - OS: Android 10 | OneUi Core 2.5
 - Коммит: 8b614f7

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

**Comment by abel1502** [comment]
@gdlbo Можно хоть какой-то комментарий? Это уже можно отключить, а я просто не нашёл как? Или у вас на сборке этого коммита не получилось воспроизвести? Или это намеренная фича втостерса, которую хочется пропихивать явно, без возможности отключения? Пока непонятно, почему wontfix

**Comment by abel1502** [comment]
Если я правильно понял суть метки vk bug, то в оригинальном vk такого как раз не происходит

**Comment by aliveoutside** [comment]
под VK Bug подразумевается баг конкретно на этой версии офвк, а не последней из плей маркета

**Comment by abel1502** [comment]
А, то есть можно ожидать фикс в дальнейшем? Ок, понял, спасибо

**Comment by abel1502** [comment]
Если что, в коммите 3d4be41 проблема сохраняется

**Comment by abel1502** [comment]
И в ecce32b

**Comment by abel1502** [comment]
На андроиде 11 у друга в той же версии проблемы нет
