### ISSUE TITLE
Вылетает при загрузке сюжета

### ISSUE THREAD

**Issue by NikSavchenk0** [vtosters/lite#77]
https://user-images.githubusercontent.com/58150480/160817288-0081f0d2-62ca-4505-bd6a-1dcdc10f3db0.mp4

Логи: https://foxbin.f0x1d.com/vEeWF93Fvp

**Comment by gdlbo** [comment]
https://github.com/vtosters/lite/commit/afeafba67da4d674f53aee4d97aa24bf754b08e6 Добавил проверку на нулл ибо вк на скрытых сюжетах не отдает много информации, поэтому аппа падает
