### ISSUE TITLE
Не работает кнопка 'Прочитано' в уведомлении

### ISSUE THREAD

**Issue by EAlexashin** [vtosters/lite#775]
**Опишите сам баг**
При нажатии кнопки 'Прочитано' в уведомлении о новом сообщении оно исчезает, но сообщение остаётся непрочитанным (при включенной "нечиталке")

**Опишите ожидаемый результат**
Отмечать сообщение прочитанным через кнопку в уведомлении

**Скриншот ошибки**
![Screenshot_20220920-102043](https://user-images.githubusercontent.com/113752841/191194938-a90d33d8-7c12-4119-9b3c-7760f46d5d07.jpg)

**Информация об устройстве:**
 - Устройство: OnePlus 7 Pro
 - OS: Android 11 | Oxygen OS
 - Коммит: 8b614f7

**Comment by hhrhhr** [comment]
Как включить эти кнопки (ответить/прочитано) в текущей версии? Я вижу только нравится/закладки.
![photo_5429378505629623425_y](https://github.com/user-attachments/assets/ca30e8ed-2553-4b29-ba5e-545150aea11c)
