### ISSUE TITLE
Не работает кнопка «Сервисы»

### ISSUE THREAD

**Issue by onegogtwogog** [vtosters/lite#779]
Хочу послушать музыку без добавления иконки в докбар, но когда нажимаю на кнопку «сервисы» меня кидает на пустую страничку 

Действия для воспроизведения ошибки:
1. Нажать на кнопку «сервисы»

Ожидаемый результат:
Появление меню «сервисы»

![IMG_20220922_200034](https://user-images.githubusercontent.com/114177928/191808479-0068f7e4-b98d-4f90-b4f6-0914f675b9c4.jpg)

Информация об устройстве:
 - Устройство:  Xiaomi mi 9 lite
 - OS: Android 11 | MIUI 12.5.1

 - Коммит: 8b614f7

Дополнительная информация о баге: Возможно это как-то связано с настройками vtosters

**Comment by k1zn** [comment]
Ты из редактора супераппа удалил меню

**Comment by onegogtwogog** [comment]
проблема исправлена
