### ISSUE TITLE
Смылены все фото в приложении

### ISSUE THREAD

**Issue by onegogtwogog** [vtosters/lite#780]
Все фото, обложки альбомов в качестве 8 бит

Для того, чтобы это увидеть, достаточно посмотреть на любое фото.

Фото должны быть нормального качества

![Screenshot_2022-09-22-20-14-29-987_com vtosters lite](https://user-images.githubusercontent.com/114177928/191810745-278a3bec-42ba-4bbf-a4bf-36921653c444.jpg)
![Screenshot_2022-09-22-20-14-46-350_com vtosters lite](https://user-images.githubusercontent.com/114177928/191810765-12bcacaf-381b-4414-af21-585908d3cc21.jpg)

 - Устройство: Xiaomi mi 9 lite
 - OS: Android 11 | MIUI 12.5.1
 - Коммит: 8b614f7

Когда в ленте нажимаешь на фото, оно прогружается до нормального качества, выходишь из него и оно остается в нормальном качестве, а остальные фото нет. С обложками альбомов и групп это не работает..

**Comment by GooDoG337** [comment]
Включена экономия трафика

**Comment by onegogtwogog** [comment]
> 

как ее отключить

**Comment by onegogtwogog** [comment]
> Включена экономия трафика

как ее отключить

**Comment by GooDoG337** [comment]
В настройках -> основное -> экономия трафика
