### ISSUE TITLE
Проблема отображения светлой темы

### ISSUE THREAD

**Issue by Kelvedez** [vtosters/lite#782]
**Опишите сам баг**
При перезагрузке приложения багуются шрифты и блоки в светлой теме

**Опишите ожидаемый результат**
Черный шрифт во время использования светлой темы

**Скриншот ошибки**

**Информация об устройстве:**
 - Устройство: Mi9 T
 - OS: Android 10
 - Коммит: 3d4be41
![Screenshot_2022-09-23-13-36-59-491_com vtosters lite](https://user-images.githubusercontent.com/114221098/191922547-d4f39fab-bd03-4b40-bd9b-d825e171a64a.jpg)
![Screenshot_2022-09-23-13-36-49-246_com vtosters lite](https://user-images.githubusercontent.com/114221098/191922558-916b5d92-6748-4ab5-a7a2-2b9d4c50d515.jpg)
![Screenshot_2022-09-23-13-36-43-502_com vtosters lite](https://user-images.githubusercontent.com/114221098/191922563-50d103ec-d75c-4cef-8902-f83f3cb3dfe2.jpg)

**Comment by gdlbo** [comment]
Я бы запретил miui и не тёмную тему

**Comment by Kelvedez** [comment]
> Я бы запретил miui и её тёмную тему

Я бы конечно починил порт зарядки и перепрошился, а так на светлой теме читать глаза не болят. Рябь же когда читаешь белым по черному

**Comment by gdlbo** [comment]
> > Я бы запретил miui и её тёмную тему
> 
> 
> 
> Я бы конечно починил порт зарядки и перепрошился, а так на светлой теме читать глаза не болят. Рябь же когда читаешь белым по черному

Отключи покраску втла в тёмную тему в настройках миуи и всё должно пофикситься

**Comment by inotflying** [comment]
Не зря Xiaomi выпилили принудительную покраску приложений

**Comment by person1030** [comment]
@inotflying Они убрали?

**Comment by inotflying** [comment]
> @inotflying Они убрали?

Да, но вроде они начали возвращать

**Comment by Kelvedez** [comment]
> > > Я бы запретил miui и её тёмную тему
> > 
> > 
> > Я бы конечно починил порт зарядки и перепрошился, а так на светлой теме читать глаза не болят. Рябь же когда читаешь белым по черному
> 
> Отключи покраску втла в тёмную тему в настройках миуи и всё должно пофикситься

А как конкретно это сделать?
