### ISSUE TITLE
Ошибка при открытии статей для донов

### ISSUE THREAD

**Issue by TotalRetard** [vtosters/lite#784]
При открытии статьи доступной только для донов предлагает подписаться на автора, хотя я и так подписан.

Стать доном сообщества, найти статью только для донов, открыть статью.

Хочется чтобы можно было читать статьи за которые платишь без проблем.

![Screenshot_2022-09-23-21-30-29-006_com vtosters lite](https://user-images.githubusercontent.com/114258935/192044462-42f733bb-b3d4-48c5-b1d1-9d9d00bb1660.jpg)

 - Устройство: Xiaomi mi 9t
 - OS: Android 10 | MIUI 12
 - Коммит: 3d4be41

Идей почему так - нет.

**Comment by gdlbo** [comment]
ошибка ещё актуальна?
