### ISSUE TITLE
Добавьте пожалуйста удаление диалога и чата в целом 

### ISSUE THREAD

**Issue by xxxxxxiiii** [vtosters/lite#785]
Эта функция очень удобна,я предлагаю идею создать еë.Так же как и в телеграмме.
В остальном всё хорошо,приложение нравится.

**Comment by person1030** [comment]
@xxxxxxiiii Типо удалить и для собеседника?

**Comment by psamur** [comment]
@xxxxxxiiii Удалить диалог локально (у себя) можно. Удалить диалог у обоих участников - нет. 

Такой фичи нет у ВКонтакте и разработчики ВТЛайта тут бессильны.

**Comment by aliveoutside** [comment]
диалог удалить можно удержанием по нему -> "Очистить историю"
удалить диалог у собеседника технически невозможно
