### ISSUE TITLE
Ошибка обновлении ленты новостей

### ISSUE THREAD

**Issue by b7bun** [vtosters/lite#786]
Новости не обновляются вообще

1. Обновил ленту интересных новостей
2. остается все так же

Интересная лента должна прогружать новые интересные результаты

 - Устройство: Realme 6 pro, а так же Samsung galaxy a51 (проверял на обоих телефонах)
 - OS: Android 10 
 - Коммит: 3d4be41
![Screenshot_2022-09-24-11-08-28-51_9e1a5d6211a0228d32d39446541891f1](https://user-images.githubusercontent.com/114273032/192077515-446dd28a-b312-4821-84a6-3875d222ef7b.jpg)

**Comment by gdlbo** [comment]
Включена интересная лента

**Comment by icynstant** [comment]
Откройте пожалуйста ошибку, проблема не исправлена, у меня включена интересная лента.
Скорее всего тут дело не в том что не появляются новые посты, а в том, что не удаляются старые. Та же проблема, прошу исправления.

**Comment by icynstant** [comment]
Подробнее расписал ошибку в #1510

**Comment by ayonovdenizs** [comment]
@icynstant https://github.com/vtosters/lite/issues/1510#issuecomment-1831906593

**Comment by ayonovdenizs** [comment]
@icynstant https://github.com/vtosters/lite/issues/1510#issuecomment-1831906593
