### ISSUE TITLE
Вылет приложения при включенном iOS стиле

### ISSUE THREAD

**Issue by RobertZhd** [vtosters/lite#787]
**Опишите сам баг**
При включенном iOS стиле в сообщениях, приложение вылетает, при попытке зайти в диалог

**Опишите действия для воспроизведения ошибки**
1. Включил iOS стиль в сообщениях
2. Зашёл в диалог

**Опишите ожидаемый результат**
Должен был быть стиль iOS в диалоге

**Скриншот ошибки**
![Screenshot_2022-09-24-10-32-14-602_com miui home](https://user-images.githubusercontent.com/103843517/192086093-2e16f080-5d55-425c-8016-b82e29d02eff.png)

**Информация об устройстве:**
 - Устройство: Xiaomi Redmi Note 5(pro)
 - OS: Android 8 | Miui 9.6
 - Коммит: 3d4be41

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

**Comment by gdlbo** [comment]
https://github.com/vtosters/lite/commit/70d597f6e81cebe0bf9281060794ce7edeec0d2c
