### ISSUE TITLE
Нет кешированной музыки

### ISSUE THREAD

**Issue by hxllbxy** [vtosters/lite#788]
Нет кешированной музыки
Нажал на кнопку скачивания трека, зашел в раздел музыки, проверил плейлисты и альбомы, ничего нет. Пробовал и обновлять.
![IMG_20220924_141214](https://user-images.githubusercontent.com/114290232/192094738-fb78e54b-3207-4a9b-9b01-ad86d6449838.jpg)
![Screenshot_2022-09-24-14-13-09-398_com vtosters lite](https://user-images.githubusercontent.com/114290232/192094781-82b845cc-df79-4e30-a0fb-2a87b358257b.jpg)
![Screenshot_2022-09-24-14-13-12-093_com vtosters lite](https://user-images.githubusercontent.com/114290232/192094783-e8015ad7-911f-4c3b-b683-716c8e0e90b3.jpg)

Думаю должен быть плейлист с кешированной музыкой как в ВТостерс

 - Устройство: Redmi Note 10 Pro
 - OS:  Android 12 SKQ1.210908.001 | MIUI 13.0.3
 - Коммит: 3d4be41

**Comment by person1030** [comment]
@hxllbxy Выключи интернет, и зайди в раздел музыки
