### ISSUE TITLE
Ошибка обновлении ленты новостей

### ISSUE THREAD

**Issue by valenskav** [vtosters/lite#792]
**Опишите сам баг**
При обновлении новостей, новости и интересное не обновляются, одни и те же новости висят на протяжении недели,если не больше. 

**Опишите действия для воспроизведения ошибки**
1. Обновил ленту, появились новости
2. При обновлении либо ничего не происходит, либо показывает то что было до

**Опишите ожидаемый результат**
Хочется как в vtosters, чтобы новости нормально обновлялись, и не было повторяющихся новостей

**Скриншот ошибки**

**Информация об устройстве:**
 - Устройство: Huawei nova 5t
 - OS: Android 9 | EMUI 12.0.0
 - Коммит: 3d4be41 (В О Приложении написана версия коммита)

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**
#

https://user-images.githubusercontent.com/114351337/192152857-18004f84-aa97-4d94-bcd4-9920474a7631.mp4

**Comment by gdlbo** [comment]
Включена интересная лента

**Comment by icynstant** [comment]
Откройте пожалуйста ошибку, проблема не исправлена, у меня включена интересная лента.
Скорее всего тут дело не в том что не появляются новые посты, а в том, что не удаляются старые. Та же проблема, прошу исправления.

**Comment by icynstant** [comment]
Подробнее расписал ошибку в #1510

**Comment by ayonovdenizs** [comment]
@icynstant https://github.com/vtosters/lite/issues/1510#issuecomment-1831906593

**Comment by ayonovdenizs** [comment]
@icynstant https://github.com/vtosters/lite/issues/1510#issuecomment-1831906593
