### ISSUE TITLE
Добавление возможности отключить проверку обновлений

### ISSUE THREAD

**Issue by AVAtarMod** [vtosters/lite#796]
**Опишите вашу идею максимально подробно и понятно**
Представляю это себе так: в настройках -> обновления добавить checkbox "Отключить проверку обновлений". По умолчанию неактивен. При включении показывать диалог подтверждения с следующим текстом:
"Отключение проверки обновлений приведет к тому, что вы перестанете получать уведомления о выходе новых версий в этом приложении.
Обратите внимание, функция "Сообщить о баге" будет отключена т.к поддержка старых версий по умолчанию не осуществляется. 
Информацию о выходе новых версий вы сможете получить здесь: https://t.me/vtosters
", а также отключается функция отчёта об ошибках (см. сообщение в кавычках выше).

**Опишите возможное решение/реализацию функции (если понимаете как это можно реализовать на Java/C++)**
Глянул код проекта по диагонали, не уловил точного места, где можно было бы вставить условное ветвление. По сути, нужен флаг и if, его использующий

**Comment by gdlbo** [comment]
Не поможет, к сожалению из-за большого количества умников пришлось убрать окончательно

**Comment by iTaysonLab** [comment]
@AVAtarMod смысла в этой фиче нет т.к опять начнут орать "ЫААА У МЕНЯ ПАСЛЕДНЯЯ ВЕРСИЯ!1!"

поэтому принудительные (и даже нет) обновления - это всегда мастхев

**Comment by GooDoG337** [comment]
В целом, понравилась идея отключать пункт "Сообщить о баге" в случае, если старая версия, но не думаю, что хотя бы 10% issues было сделано с помощью этой кнопки

**Comment by AVAtarMod** [comment]
@gdlbo, хорошо, если скомпилить самому, какие функции музыки и прочего сломаются? И как именно?

**Comment by ayonovdenizs** [comment]
@GooDoG337 Не хочешь вечное уведомление об обновлений? Прошу качать из Github Action

**Comment by ayonovdenizs** [comment]
@AVAtarMod Нет

**Comment by AVAtarMod** [comment]
@ayonovdenizs "А что, так можно было?"
А почему у вас из actions отключено уведомление?

**Comment by aliveoutside** [comment]
> "А что, так можно было?" А почему у вас из actions отключено уведомление?
https://github.com/vtosters/lite/blob/ecce32bfe75aa9606c98f0fd5c114b325e05461e/app/src/main/java/ru/vtosters/lite/ui/fragments/VTSettings.java#L453

подпись не наша, потому и отключается
