### ISSUE TITLE
После просмотра видео ничего не открывается . Везде чёрный экран. Помогает перезапуск приложения. На скриншотах: посмотрел видео и после нажал на комментарии .

### ISSUE THREAD

**Issue by Denchikoff** [vtosters/lite#804]
![Screenshot_20220929-123833_VTLite](https://user-images.githubusercontent.com/114657044/192997690-2857c12c-888a-4c9c-98af-e90370be3c1f.jpg)
![Screenshot_20220929-123826_VTLite](https://user-images.githubusercontent.com/114657044/192997697-6250d185-8836-4cd7-8dfb-78605be9fe49.jpg)
**Опишите сам баг**
При обновлении новостей вылезает ошибка

**Опишите действия для воспроизведения ошибки**
1. Обновил ленту интересных новостей
2. Пролистал до конца страницы

**Опишите ожидаемый результат**
Интересная лента должна прогружать результаты

**Скриншот ошибки**

**Информация об устройстве:**
 - Устройство: Samsung Galaxy J1 Mini
 - OS: Android 9 | OneUi 3.0
 - Коммит: fa12e8f (В О Приложении написана версия коммита)

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

**Comment by ayonovdenizs** [comment]
М-да

**Comment by gdlbo** [comment]
старая версия
