### ISSUE TITLE
Общие друзья 

### ISSUE THREAD

**Issue by mkalinych** [vtosters/lite#805]
Не отображается список общих друзей.
В самом профиле количество общих есть, а во вкладке общих 0.
![Screenshot_20220929-134138](https://user-images.githubusercontent.com/71986370/193011129-b4b9dace-7b5d-4cb5-b501-f6c2c5cb206d.png)
![Screenshot_20220929-134157](https://user-images.githubusercontent.com/71986370/193011139-8c77bf79-d081-4948-8cc9-4bfab8950d65.png)
 **Информация об устройстве:**
 - Устройство: Doogee S96PRO 
 - OS: Android 10 
 - Коммит: ecce32b
Кстати, ни на одном VTosters у меня они не отображаются. А на SOVA на всех есть. Вопрос - почему так?
Спасибо!

**Comment by tiititi** [comment]
ровно такая же фигня. уже писал о проблеме несколько месяцев назад. ждём-с багофикса

**Comment by k1zn** [comment]
@tiititi логи с апишкой вк нужны

**Comment by tiititi** [comment]
> @tiititi логи с апишкой вк нужны

так я уже кидал . ещё нужны?

**Comment by k1zn** [comment]
@tiititi давай

**Comment by tiititi** [comment]
![VK.logup.zip](https://github.com/vtosters/lite/files/9678566/VK.logup.zip)
вот. отпишись, все ли норм
