### ISSUE TITLE
Баг мини приложений 

### ISSUE THREAD

**Issue by Volt567** [vtosters/lite#807]
**Опишите сам баг**
Раздел мини приложений запускается поверх
Других 
**Опишите действия для воспроизведения ошибки**
1. Зайти в мини приложения отрыть любое приложение 
2. Перейти в любой раздел в догбаре  например  сообщения 

**Опишите ожидаемый результат**
Мини  приложения запустятся поверх 

**Скриншот ошибки**
![Screenshot_2022-09-30-11-47-22-748_com.vtosters.lite.jpg](https://user-images.githubusercontent.com/114720843/193198462-4bb66761-e386-4e37-b84a-69e7209f3575.jpg)
**Информация об устройстве:**
 - Устройство: Xiaomi Redmi Note 10 Pro

 - OS: Android 12 | miui 13.0.4
 - Коммит: ecce32b (В О Приложении написана версия коммита)

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

**Comment by ayonovdenizs** [comment]
@Volt567 Баг вк

**Comment by Volt567** [comment]
Понял спасибо
