### ISSUE TITLE
Вылеты 

### ISSUE THREAD

**Issue by Volt567** [vtosters/lite#812]
**Опишите сам баг**
Бывают вылеты при заходе в сообщения  и пишет что приложение не отвечает при попытке открыть диалоги 
**Опишите действия для воспроизведения ошибки**
1. Зайти в сообщения 
2.  Открыть любой диалог 

**Опишите ожидаемый результат**
Будет вылет 

**Скриншот ошибки**
[]()![IMG_20221003_091230.jpg](https://user-images.githubusercontent.com/114720843/193511511-37bdc7a0-0104-4b24-a7a7-2d0b8bd3cff4.jpg)
**Информация об устройстве:**
 - Устройство: Redmi Note 10 Pro
 - OS: Android 12| miui 13.0.4
 - Коммит: ecce32b (В О Приложении написана версия коммита)

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

**Comment by ayonovdenizs** [comment]
Логи?

**Comment by Volt567** [comment]
> **Опишите сам баг**
> Бывают вылеты и пишет что приложение не отвечает, если зайти в сообщение и открыть  диалог 
> **Опишите действия для воспроизведения ошибки**
> 1. Зайти в сообщения 
> 2. Открыть диалог 
> 
> **Опишите ожидаемый результат**
> Интересная лента должна прогружать результаты
> 
> **Скриншот ошибки**
> []()![IMG_20221003_091230.jpg](https://user-images.githubusercontent.com/114720843/193511511-37bdc7a0-0104-4b24-a7a7-2d0b8bd3cff4.jpg)
> **Информация об устройстве:**
>  - Устройство: Redmi Note 10 Pro
>  - OS: Android 12| miui 13.0.4
>  - Коммит: ecce32b (В О Приложении написана версия коммита)
> 
> **Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**
>

**Comment by Volt567** [comment]
> **Опишите сам баг**
> Бывают вылиты и пишет что приложение не отвечает 
> **Опишите действия для воспроизведения ошибки**
> 1. 
> 2. 
> 
> **Опишите ожидаемый результат**
> будет вылет 
> 
> **Скриншот ошибки**
> []()![IMG_20221003_091230.jpg](https://user-images.githubusercontent.com/114720843/193511511-37bdc7a0-0104-4b24-a7a7-2d0b8bd3cff4.jpg)
> **Информация об устройстве:**
>  - Устройство: Redmi Note 10 Pro
>  - OS: Android 12| miui 13.0.4
>  - Коммит: ecce32b (В О Приложении написана версия коммита)
> 
> **Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**
>
