### ISSUE TITLE
Ошибка обновлении ленты новостей

### ISSUE THREAD

**Issue by Saint-Mod19** [vtosters/lite#822]
**Опишите сам баг**
При переключении на "Интересное" страница не загружается, как будто без интернета

**Опишите действия для воспроизведения ошибки**
1. Отрыть вкладку новости
2. Переключить на страницу "Интересное"

**Опишите ожидаемый результат**
Интересная лента должна прогружать результаты

**Скриншот ошибки**
![Screenshot_2022-10-04-17-29-39-082_com vtosters lite](https://user-images.githubusercontent.com/93400000/193848265-15bc6c7b-edaa-4d4e-8bbc-045ea569b10d.jpg)

**Информация об устройстве:**
 - Устройство: Xiaomi Redmi Note 7
 - OS: Android 10 | MIUI 12.5.1
 - Коммит: 1a8da81

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

**Comment by k1zn** [comment]
нужны логи

**Comment by 33377730** [comment]
Советую стереть данные приложения и сделать заново вход в приложение
