### ISSUE TITLE
Не открываются статьи в группах 

### ISSUE THREAD

**Issue by Andrei25100** [vtosters/lite#825]
**Опишите сам баг**
Не открываются статьи в группах 

**Опишите действия для воспроизведения ошибки**
1. В группе нажимаю стати вижу их пытаюсь открыт но они не открываются а только крутится круг загрузки безконечно
2. В закладках сохраненные статьи из групп тоже не открывает а только безконечно загрузка крутится.

**Опишите ожидаемый результат**
Статьи должны открываться для их прочтения

**Скриншот ошибки**

**Информация об устройстве:**
 - Устройство: Xiaomi mi 11
 - OS: Android 12 | miui 13
 - Коммит: 1a8da81

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**
Все разрешения даны оптимизация батареи выкл, ставить пробовал Vtlite с ноля и всё равно не хочет открывать статьи

**Comment by Andrei25100** [comment]
![Screenshot_2022-10-06-01-11-31-982_com vtosters lite](https://user-images.githubusercontent.com/115118839/194174007-c09a99ae-a00a-419b-95ee-e40d9b743e2a.jpg)

**Comment by Andrei25100** [comment]
![Uploading Screenshot_2022-10-06-01-17-18-173_com.vtosters.lite.jpg…]()

**Comment by Andrei25100** [comment]
![Screenshot_2022-10-06-01-17-18-173_com vtosters lite](https://user-images.githubusercontent.com/115118839/194174242-c81d845a-700b-4953-98df-cc39819c5a0b.jpg)

**Comment by k1zn** [comment]
исправлено в следующей версии
