### ISSUE TITLE
В разделе музыка не отображаются мои добавоенные плейлисты

### ISSUE THREAD

**Issue by DavidUl040901** [vtosters/lite#827]
**Опишите сам баг**
При открытии докбара "музыка" не отображаются мои добавленные альбомы

**Опишите действия для воспроизведения ошибки**
1. Нажимаю на докбар "музыка"...

**Опишите ожидаемый результат**
В самом верху раздела "музыка" должны отображаться мои добавленные альбомы

**Скриншот  #ошибки**
[](url)

**Информация об устройстве:**
 - Устройство: Samsung Galaxy S9
 - OS: Android 9 | OneUi 3.0
 - Коммит: fa12e8f (В О Приложении написана версия коммита)

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

**Comment by GooDoG337** [comment]
@DavidUl040901 Попробуй перезайти в профиль

**Comment by DavidUl040901** [comment]
Перезашел. Все появилось
