### ISSUE TITLE
Отображение имён в беседе

### ISSUE THREAD

**Issue by DeLi0v** [vtosters/lite#829]
**Опишите сам баг**
В беседе не отображается имя человека, который отправил сообщение

**Опишите ожидаемый результат**
Имена пользователей должны показываться с сообщением от них, также как и аватарка

**Скриншот ошибки**
![IMG_20221007_153939.jpg](https://user-images.githubusercontent.com/109518046/194556527-5300e871-bf3d-4f9f-b13e-582144defa2d.jpg)

**Информация об устройстве:**
 - Устройство: Xiaomi Redmi Note 9 Pro
 - OS: Android 11 | MIUI Global 12.5.4
 - Коммит: 1a8da81

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

**Comment by danyyok** [comment]
@DeLi0v В работе
