### ISSUE TITLE
Стикеры дублируются во вкладке

### ISSUE THREAD

**Issue by Komanukechaann** [vtosters/lite#830]
Я ставлю свои основные паки во вконтакте, но их оказывается НАСТОЛЬКО много, что тяжело просто напросто искать подходящий. Ещё очень плохо и редко обновляется лента (хотя групп у меня в подписках очень даже достаточное количество, чтобы посты выходили каждые минут двадцать).

**Comment by ayonovdenizs** [comment]
@Komanukechaann Шаблон вышел из чата, вместе с титлом

**Comment by danyyok** [comment]
@Komanukechaann Со стикерами хз,а для нормальной ленты в настройках ленты(это уже ищи в настройках-настройки ленты) включи порядок записи на "новые"

**Comment by Timofei302** [comment]
![Screenshot_20221010-155207_VTLite.jpg](https://user-images.githubusercontent.com/59145732/194870780-8970c9bc-7e56-4d30-a9e0-818fdc0e70f8.jpg)
Такая ерунда так-же и в менеджере стикеров.

**Comment by aliveoutside** [comment]
Не могу воспроизвести проблему со стикерами

**Comment by Timofei302** [comment]
> Не могу воспроизвести проблему со стикерами

Она может буть не у всех. Плюс она может быть, а потом изчезнуть при следующем запуске. Короче спонтанно появляющийся баг, который ъуъ как бесит.

**Comment by Timofei302** [comment]
![Screenshot_20221010-161150_VTLite.jpg](https://user-images.githubusercontent.com/59145732/194874289-8a4f592d-35a3-44bf-8c44-c940d95ca5c7.jpg)
И вот что и требовалось доказать - баг изчез.

**Comment by Komanukechaann** [comment]
> @Komanukechaann Шаблон вышел из чата, вместе с титлом

Да и ладно, мне это не настоль сильно мешает, когда к словам существуют подсказки, поэтому я не действую радикально. Баг описала, кто-то с проблемой согласился, кто-то даже предложил решение. Если кому-то это будет столь сильно мешать, что он будет биться об стену от недовольства, то пускай пишет свой баг и оформляет его так подробно.

**Comment by Komanukechaann** [comment]
> ![Screenshot_20221010-161150_VTLite.jpg](https://user-images.githubusercontent.com/59145732/194874289-8a4f592d-35a3-44bf-8c44-c940d95ca5c7.jpg) И вот что и требовалось доказать - баг изчез.

Даже после этого моя проблема повторилась снова через..день кажется, буквально пару заходов в приложение и проблема показала себя.
