### ISSUE TITLE
Удаляются комментарии под постом

### ISSUE THREAD

**Issue by gr4n1t** [vtosters/lite#833]
**Опишите сам баг**
Пишу несколько слов под постом в комментариях, потом зависает все на 1-2сек и эти слова которые я написал удаляются. После этого приходится писать заново, но провисания больше нету.
Мелочь, но неприятно 

**Опишите действия для воспроизведения ошибки**
1. Заново зайти в приложение
2. Открыть комментарии под постом в ленте
3. Написать что-то
4. Некоторое время спустя происходит зависание

**Опишите ожидаемый результат**
Чтобы небыло этого зависания ¯\_(ツ)_/¯

**Информация об устройстве:**
 - Устройство: Samsung Galaxy J7 
 - OS: Android 8.1
 - Коммит: efe8a2c

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**
Даже необязательно что то писать под постом, достаточно открыть клавиатуру, немного подождать и произойдет зависание

**Comment by gdlbo** [comment]
Потому что в группе включены фильтры удаляющие твои комментарии

**Comment by gr4n1t** [comment]
Я только ввожу свой комментарий но не отправляю его. В этой строке для написания
Если нужно я заморочусь, скачаю приложение для записи экрана и засниму

**Comment by gdlbo** [comment]
Ну в любом случае даже если не отправил, то скорее всего это вкшный баг который не пофиксить
