### ISSUE TITLE
Не показывает добавленные плейлисты

### ISSUE THREAD

**Issue by Shamillh** [vtosters/lite#834]
**Опишите сам баг**
При открытии моей музыки можно увидеть только добавленные аудиозаписи 

**Опишите действия для воспроизведения ошибки**
1. Открыл музыку
2. Нажал " моя музыка "
3. Видны только добавленные аудио

**Опишите ожидаемый результат**
В моей музыке должны быть плейлисты
![Screenshot_2022-10-09-18-37-35-67_9e1a5d6211a0228d32d39446541891f1](https://user-images.githubusercontent.com/98417802/194765874-0a4a15c8-bbe5-41d3-bb3f-36ba3534345e.jpg)

**Информация об устройстве:**
 - Устройство: Realmi XT
 - OS: Android 11
 - Коммит: efe8a2c

**Comment by GooDoG337** [comment]
Перезайти в аккаунт

**Comment by gdlbo** [comment]
перезайди в аккаунт
