### ISSUE TITLE
Нету плеера в шторке уведомления

### ISSUE THREAD

**Issue by FunCakee** [vtosters/lite#835]
**Опишите сам баг**
Когда включаешь музыку, и выходишь из приложения ты не можешь переключить или выключить музыку в шторке уведомления, и постоянно приходится заходить в приложение

**Опишите ожидаемый результат**
Чтобы музыкальный плеер отображался в шторке уведомления и на экране блокировки

**Скриншот ошибки**
![Screenshot_20221010_032537](https://user-images.githubusercontent.com/98389344/194780152-9235674a-5ccb-4d55-8ac3-f5df9e66f6ab.jpg)
![Screenshot_20221010_032528](https://user-images.githubusercontent.com/98389344/194780156-60139665-0f6e-44d9-a062-f8c4f1978768.jpg)
![Screenshot_20221010_032524](https://user-images.githubusercontent.com/98389344/194780157-207e91d4-824f-4653-ae1e-aa61ced8bf5e.jpg)

**Информация об устройстве:**
 - Устройство: Vivo 1904
 - OS: Android 11

**Comment by gdlbo** [comment]
ты разрешил вк уведомления?

**Comment by FunCakee** [comment]
Да, все уведомления включены

**Comment by FunCakee** [comment]
> ты разрешил вк держать?

Да, все уведомления включенв

**Comment by ayonovdenizs** [comment]
> > ты разрешил вк держать?
> 
> Да, все уведомления включенв

Ты разрешил показывать категорию уведомлений плеера?

**Comment by FunCakee** [comment]
> > > ты разрешил вк держать?
> > 
> > 
> > Да, все уведомления включенв
> 
> Ты разрешил показывать категорию уведомлений плеера?

Да
![Screenshot_20221021_171350](https://user-images.githubusercontent.com/98389344/197183324-a4155cc5-766e-4db8-845d-674cf382127d.jpg)
