### ISSUE TITLE
Улучшение голосовых сообщений

### ISSUE THREAD

**Issue by Blank402** [vtosters/lite#838]
Приложение говно работает медлнее чем ВК тостер и платное Я школьник у меня нет денег а вы сука зделали его бесплатным по сути что за обычный ВК надо платить что за ваш Я лучше до последнего с ВК тостер останусь

**Comment by gdlbo** [comment]
@Blank402 а мы бедные студенты хотим кушать что-то получше роллтона, да и платных фич нетб

**Comment by abslike** [comment]
@Blank402 платных функций особо и нет, поэтому давай без бреда, пока тебе Issues не прикрыли на аккаунте

**Comment by ayonovdenizs** [comment]
@Blank402 Шиза?
