### ISSUE TITLE
Не скачиваются стикеры с телеграмма

### ISSUE THREAD

**Issue by krinof** [vtosters/lite#840]
не скачиваются стикеры с телеграмма

**Comment by ayonovdenizs** [comment]
Пофикшено с этого комита 
[Ссылка на GitHub Action](https://github.com/vtosters/lite/actions/runs/3214209594)

**Comment by gdlbo** [comment]
https://github.com/vtosters/lite/commit/9d2878b9dcdf6390327676079b0985e2aec4dccd
