### ISSUE TITLE
Не устанавливается на Google Pixel 7 Pro с Android 13

### ISSUE THREAD

**Issue by other909** [vtosters/lite#843]
При попытке установить с внутренней памяти последнюю версию выдает сообщение "App not installed as app isn't compatible with your phone".

![Screenshot_20221013-223649](https://user-images.githubusercontent.com/115772733/195771060-2f9ee484-6cd1-460d-8426-eb8ef202a773.png)

**Информация об устройстве:**
 - Устройство: Google Pixel 7 Pro
 - OS: Android 13

Возможно из-за разницы версий пакета или инструментария сборки и операционной системы Android 13, так как есть еще несколько приложений которые так же не устанавливаются, но на одно я нашел решение - TwitchMod, на 4pda есть собранная по новому версия и она установилась.

**Comment by gdlbo** [comment]
Очень странно. Имею сейчас на руках Pixel 6a и всё устаналивается без проблем 

Можешь попробовать через ADB установить?

![Screenshot_20221014-085610.png](https://user-images.githubusercontent.com/41114720/195772832-a6e74840-9d3a-4605-8f14-2e267b0e46c0.png)

**Comment by other909** [comment]
Выходит после ввода команды и где-то одной минуты ожидания выводится вот такая ошибка.

![Screenshot (3)](https://user-images.githubusercontent.com/115772733/195775902-ecc33219-2dde-40e4-8407-d63d1347c7a0.png)

**Comment by gdlbo** [comment]
Ультра странная шляпа

Это ошибка когда несовместимая архитектура используется

Ну у нас только armv7 который обратно совместимый с armv8, но у тебя почему-то андроид просто не хавает это и отказывается устанавливать

Может апдейты какие есть или бета ведра?

**Comment by other909** [comment]
Я только получил телефон, живу в США, сегодня день старта продаж. Пришел сразу с 13 Андроидом, прилетело какое-то обновление на 70 мб. уже после. Это не единственное приложение так, есть Qickpick галерея тоже не устанавливается, YMusic тоже.

**Comment by gdlbo** [comment]
Ну гугл опять сломали свои устройства на старте, поэтому ничего кроме ожидания бета апдейта (https://www.google.com/android/beta) который будет в следующем месяце для 7 пикселей не могу посоветовать

Скорее всего с бета апдейтом исправят проблему с совместимостью, иначе будут проблемы с софтом

**Comment by other909** [comment]
Понял. Просто интересно, я так же пользуюсь TwitchMod, если скачивать и вот все вплоть до 12 с такой же ошибкой выскакивало, но вот пересобранная 13 установилась.

![Screenshot_20221013-233547](https://user-images.githubusercontent.com/115772733/195778843-ddca1bf9-099b-4051-85a0-00f728d1ecfc.png)

**Comment by gdlbo** [comment]
Сейчас быстро посмотрел твичмод

Там в 13 версии используются библиотеки armv8, до этого было только armv7 и x86

Объясню проще на пальцах так сказать

Телефон отказывается работать с софтом который завязан на старой архитектуре и хавает только то что на новой, поэтому софт не устанавливается

Расчёт на то что на новой архитектуре есть обратная совместимость со старой, поэтому софт со старой архитектурой работает на новой без проблем, а гугл похоже забыли добавить в поддержку устанавливаемого софта старую архитектуру

**Comment by gdlbo** [comment]
Закрою issue тк проблема уже Google что дурачье сломало снова андроид на пикселях 👍

**Comment by aliveoutside** [comment]
судя по всему - гугл сделали так намеренно
https://twitter.com/MishaalRahman/status/1580692276908814336?cxt=HHwWgMDThYjQ3-8rAAAA

попробуем исправить, но не могу ничего обещать

**Comment by other909** [comment]
Интересно. Это получается все приложение старые теперь полетят. У меня просто много чего что я использовал не установилось. Ждать разработчиков. В любом случае, спасибо за ответы. Кстати я пробовал VKequals из их теоеги, последнюю версию, она тоже не установилась, только из маркета устанавливается.

**Comment by gdlbo** [comment]
@other909 Если у тебя есть возможность - присоединись в наш бета телеграм чат https://t.me/betavtchat

Будем на днях решать проблему совместимости на Pixel 7

**Comment by Computershik73** [comment]
Последняя бетка с 64 битными библиотеками встаёт? Думаю, должна. У меня на Android 13 встаёт. Правда, у меня PE.

**Comment by other909** [comment]
Уже разобрались в телеге, новые аппараты теперь поддерживают только 64битные приложения.

**Comment by k1zn** [comment]
cd0914041dcf027e88decc0fcf53a4090621712f
