### ISSUE TITLE
Лента обновляется автоматически

### ISSUE THREAD

**Issue by Buxloman** [vtosters/lite#844]
**Опишите сам баг**
Лента обновляется автоматически, хотя автоматическое обновление выключено

**Опишите действия для воспроизведения ошибки**
Лента обновляется автоматически

**Опишите ожидаемый результат**
Блокировка обновления ленты

**Скриншот ошибки**

**Информация об устройстве:**
Honor 30s.
Android10/magic 5.2.0

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**
Без понятия. Но на VToster, Блокировка работала отлично.

**Comment by gdlbo** [comment]
У тебя отключен кеш ленты?
