### ISSUE TITLE
не приходит смс с подтверждением вт-лайт

### ISSUE THREAD

**Issue by Srochno** [vtosters/lite#845]
Пытаюсь войти в вт-лайт. Отправляю смс с подтверждением...жду...жду..и так до бесконечности.

**Comment by gdlbo** [comment]
Нажми отправить ещё раз

**Comment by Srochno** [comment]
нажимал "отправить" 10 раз

**Comment by k1zn** [comment]
@Srochno а с офвк смс приходило в то время?

**Comment by Srochno** [comment]
@k1zn вообще никак не приходит, вк удалил
