### ISSUE TITLE
Не устанавливается обновление 0.4.22-beta

### ISSUE THREAD

**Issue by Fofan360** [vtosters/lite#849]
При попытки обновления приложения вылезает налпись "Не удалось обработать пакет"

1. Нажал кнопку "обновить" когда об этом сказало приложение
2. Дождался загрузки файла и при установке выдаёт "Не удалось обработать пакет"

Я считаю, что обновление всё-таки должно устанавливается

 - Устройство: Xiaomi Redmi Note 8 Pro
 - OS: Android 11 | MIUI 12.5.8
 - Коммит: d678ff5

Возможно данный баг возникает из-за добавления поддержки arm64-v8a
![Screenshot_2022-10-20-23-36-45-150_com google android packageinstaller](https://user-images.githubusercontent.com/116312796/197056015-09151e14-a082-4742-b827-0d9de8e57914.jpg)

**Comment by aliveoutside** [comment]
должно быть исправлено в fc44a9b263747943ca708aec9f053fd7bb22adce

**Comment by vnskoo** [comment]
у меня похожая ситуация. в моем случае я обновляю и вроде бы все обновилось, но когда захожу снова просят обновить, и так раз 5-6 уже. подскажите, что делать?

устройство: Honor 10i
Android 10 | EMUI 10.0.0
![Uploading Screenshot_20221021_161956_com.vtosters.lite.jpg…]()

**Comment by aliveoutside** [comment]
> у меня похожая ситуация. в моем случае я обновляю и вроде бы все обновилось, но когда захожу снова просят обновить, и так раз 5-6 уже. подскажите, что делать?
> 
> устройство: Honor 10i Android 10 | EMUI 10.0.0

установи .apk руками из папки "Загрузки" (Downloads)

**Comment by RmR-Rim** [comment]
> у меня похожая ситуация. в моем случае я обновляю и вроде бы все обновилось, но когда захожу снова просят обновить, и так раз 5-6 уже. подскажите, что делать?
> 
> устройство: Honor 10i Android 10 | EMUI 10.0.0

Аналогичная ситуация уже дня 3-4 после того, как обновился на новую версию. Захожу в приложении, появляется окно с обновлением. 

устройство: Xiaomi redmi note 9 pro | miui global 12.5.4
