### ISSUE TITLE
Улучшение голосовых сообщений

### ISSUE THREAD

**Issue by Mr-etc** [vtosters/lite#851]
Добавить кнопку отключения проверки обновлений. Было бы идеально!

**Comment by danyyok** [comment]
@Mr-etc Убрали для того что бы люди не делали баг-репорты со старых версий+обновления это всегда хорошо

**Comment by Mr-etc** [comment]
> @Mr-etc Убрали для того что бы люди не делали баг-репорты со старых версий+обновления это всегда хорошо

Нуу... можно сделать во время баг репорта проверку версии приложения и выдавать ошибку, мол обновитесь для начала. Простой api запрос на получение последней версии приложения)

**Comment by danyyok** [comment]
@Mr-etc Не знаю можно ли это реализовать на гитхабе

**Comment by Mr-etc** [comment]
> @Mr-etc Не знаю можно ли это реализовать на гитхабе
Ну ладно, не убирать, но сделать в виде бесшумного уведомления, чтоб не при каждом заходе в приложение вылетала эта модалка, а в целом все красивенько сделано)
P.s. Только вспомнил, ещё там что-то с уведомлениями, они не вылетают как всплывающие, а-ля во всех других мессенджерах 🤔

**Comment by danyyok** [comment]
@Mr-etc Да,было бы неплохо
Постоянно сижу на бета-бетах
