### ISSUE TITLE
Счётчик сообщений наезжает под другую кнопку 

### ISSUE THREAD

**Issue by lvlnko** [vtosters/lite#852]
**Опишите сам баг**
Счётчик новостей наезжает под другую кнопку 

**Опишите действия для воспроизведения ошибки**
1. Включил счётчик сообщений
2. Вставил 7 элементов в докбар

**Опишите ожидаемый результат**
Счётчик сообщений должен отображаться поверх

**Скриншот ошибки**
![Screenshot_2022-10-22-10-47-22-917_com vtosters lite](https://user-images.githubusercontent.com/115203001/197315874-8e698059-947b-4c0c-954b-fa6c012fa075.jpg)

**Информация об устройстве:**
 - Устройство: Xìaomi Redmi note 9 pro 
 - OS: Android 11 | MIUI 12.5.4
 - Коммит: 235b287

**Comment by gdlbo** [comment]
к сожалению это не исправить и единственным решением я вижу только уменьшение количества вкладок в докбаре

ну или отключить счетчики :)
