### ISSUE TITLE
Иногда пропадает галочка и файрочка 

### ISSUE THREAD

**Issue by Volt567** [vtosters/lite#857]
**Опишите сам баг**
Иногда пропадает галочка и файрочка, и функции 3а 99 руб перестают работать, приходиться перезапускать приложение, но при этом работают vt  функции 

**Скриншот ошибки**
![IMG_20221024_232747.jpg](https://user-images.githubusercontent.com/114720843/197581448-ce65aae3-2172-454e-abca-4790f4dd0390.jpg)

 **Скриншот ошибки 2**
 
 ![IMG_20221024_234643.jpg](https://user-images.githubusercontent.com/114720843/197581899-eccbe435-be2e-4c6d-a1fd-36e52925ce47.jpg)

**Информация об устройстве:**
 - Устройство: Xiaomi Redmi Note 10 Pro 
 - OS: Android 12 | Miui 13.0.4
 - Коммит: 235b287

**Comment by abslike** [comment]
@Volt567 бро тебе пора прошиваться

**Comment by Volt567** [comment]
А то есть проблема в miui?

**Comment by abslike** [comment]
@Volt567 забей, я думал бот не сможет ответить на твое сообщение и по рофлу написал это

**Comment by theFraGG** [comment]
У меня такой же бред, полностью файрочку пропала, а функции доступны
![Screenshot_20230307_144457_com vtosters lite](https://user-images.githubusercontent.com/127191392/223371025-63d2d38f-4693-4321-be04-1e9077bc3aa0.jpg)
![Screenshot_20230307_142107_com vtosters lite](https://user-images.githubusercontent.com/127191392/223371034-fe1f6ba9-3257-4c95-b88f-674c9f453afb.jpg)
