### ISSUE TITLE
Автоотключение подсказки стикеров 

### ISSUE THREAD

**Issue by elzabaka** [vtosters/lite#862]
**Опишите сам баг**
При включении подсказки стикеров, они не начинают работать, а просто отключаются. 

1.Открытие диалога. 
2. Открытие настроек стикеров через вкладку с эмодзи
3. Включение подсказок стикеров

**Опишите ожидаемый результат**
Работающие подсказки стикеров. 
**Скриншот ошибки**
![Screenshot_20221027_193711](https://user-images.githubusercontent.com/116831209/198348713-83360bc4-6927-4ea0-8b7e-30f69d56c13c.jpg)

**Информация об устройстве:**
 - Устройство: Honor X8
 - OS: Android 11
 - Коммит: 7dd30d5169

**Также не открывается магазин стикеров в диалоге**

**Comment by GooDoG337** [comment]
@elzabaka Обновись до последней версии
