### ISSUE TITLE
Ошибка "Allowing com.vtosters.lite fine..."

### ISSUE THREAD

**Issue by nullnesse** [vtosters/lite#863]
**Опишите сам баг**
Открываю приложение и по кд сообщение такое появляется. Очистка данных не помогла

**Скриншот ошибки**
![Screenshot_20221028-014241](https://user-images.githubusercontent.com/111252749/198412452-30c3d2d5-40e7-4036-97d3-419708a2961a.png)
И еще "...getCellLocation" иногда всплывает

**Информация об устройстве:**
- arm64-v8a архитектура если че
 - OS: Android 11 без гугл сервисов
 - Коммит: 235b287

**Comment by aliveoutside** [comment]
твой кастом зачем-то показывает варнинги которые должны быть только в логах
мы тут не поможем
