### ISSUE TITLE
Нельзя прослушать все чарты Вк

### ISSUE THREAD

**Issue by Swijet** [vtosters/lite#864]
Исчезла кнопка "показать всё" из чарта вк, больше 12 песен нельзя прослушать, на старых версиях ВТЛайт точно так же.

**Comment by abslike** [comment]
@Swijet не слушай чарты

**Comment by gdlbo** [comment]
Будет исправлено уже в следующем обновлении

**Comment by Swijet** [comment]
> @Swijetне слушай чарты

Не шути больше, тут о багах, а не про вкусы музыки.
