### ISSUE TITLE
Ошибка в элементарных вещах

### ISSUE THREAD

**Issue by Pavelpavel22** [vtosters/lite#865]
Задонатил на галочку, жду уже 4 дня, это вообще не нормальное явление!!! 
 ВОТ ВАМ И БАГ, С КОТОРЫМ ТОЛКОМ НЕ МОГУТ ИЛИ НЕ ХОТЯТ РАЗОБРАТЬСЯ.. 
 я понимаю что команда из двух человек, но и пользователей ВТостерср не 100 тысяч, по факту.

**Comment by k1zn** [comment]
когда ты покупал было написано, что время выдачи до 7 дней. жди

**Comment by Pavelpavel22** [comment]
Хорошо что 7 дней а не год

**Comment by Pavelpavel22** [comment]
У меня не титановое терпение...

**Comment by ayonovdenizs** [comment]
@Pavelpavel22 Про баги, возможно этот баг был пофикшен/фиксится. Тебе не могу сразу на блюдечке с голубой каемочкой.

**Comment by k1zn** [comment]
> У меня не титановое терпение...

это если что не покупка услуги, а добровольное пожертвование, за которое ты получишь галочку
будь добр подождать, ведь разработчик любит трогать траву, в отличии от других

**Comment by Pavelpavel22** [comment]
> @Pavelpavel22Про баги, возможно, этот баг был пофикшен/исправлен. Тебе не могу сразу на блюдечку с голубой каемочкой.

Ахахах, я ваще в шоке

**Comment by ayonovdenizs** [comment]
@Pavelpavel22 У разработчиков тоже не железные нервы

**Comment by aliveoutside** [comment]
> пользователей ВТостерср не 100 тысяч

ага, их больше
