### ISSUE TITLE
Ошибка показа времени песни в кешированной музыке

### ISSUE THREAD

**Issue by AlexShup** [vtosters/lite#868]
При прослушивании кешированной музыки в плеере показывает не 3 минуты песни,а например 1,5 минут

1. Включил кешированную песню 
2. Зашёл в плеер
3.Увидел что песня показывает что идёт она меньше,чем это должно быть

Кешированная музыка должна нормально отображать количество времени сколько она будет длиться,чтобы можно было пролистывать на интересный тебе момент

 - Устройство: Realme 8i 4/128
 - OS: Android 11| UI v2.0
 - Коммит: 235b287

**Дополнительная инфор
![Screenshot_2022-10-30-07-48-43-21_9e1a5d6211a0228d32d39446541891f1](https://user-images.githubusercontent.com/116985652/198858047-03c698ed-0abe-4893-a713-e32d90802a32.jpg)
![Screenshot_2022-10-30-07-48-01-09_9e1a5d6211a0228d32d39446541891f1](https://user-images.githubusercontent.com/116985652/198858048-c07f6e08-0f3b-4281-8daa-fcd685bd0119.jpg)
мация о баге или мыслях почему оно может происходить (если есть)**

**Comment by mexanoz** [comment]
Похожая беда при скачивании музыки в mp3. Редактор тегов показывает, что файл неполной длины, так же плеер в списке треков, хотя сам трек воспроизводится полностью.
Устройство: Redmi Note 8
ОС: Android 11, MIUI Global 12.5.2
Коммит: e47d6ac
Плеер: BlackPlayer 20.61
Редактор тегов: Kid3 3.9.2
![Screenshot_2022-11-04-05-24-23-137_com vtosters lite](https://user-images.githubusercontent.com/96656876/199981152-7783a0a0-1fc9-4f86-afd5-0c7cb0665b20.jpg)
![Screenshot_2022-11-04-05-24-47-913_com kodarkooperativet blackplayerex](https://user-images.githubusercontent.com/96656876/199981181-1b9f2385-9178-4ce1-ac13-57d2ed4ba653.jpg)
![Screenshot_2022-11-04-05-24-51-707_com kodarkooperativet blackplayerex](https://user-images.githubusercontent.com/96656876/199981348-2b4664f9-7e37-4f70-851a-53d4c26fc9e0.jpg)
![Screenshot_2022-11-04-05-26-29-377_net sourceforge kid3](https://user-images.githubusercontent.com/96656876/199981204-5c120fc9-980e-4937-8bd1-9a3ef2f0deb5.jpg)
