### ISSUE TITLE
Проблемы при обновлении v0.4.23-beta

### ISSUE THREAD

**Issue by sanchespace** [vtosters/lite#869]
При запуске приложения вылезает окно обновления до версии v0.4.23-beta.

![IMG_20221030_125116](https://user-images.githubusercontent.com/76971953/198872631-f5818fb8-2037-4fcc-a1ea-9e8b34db8b67.jpg)

Жму обновить - идет скачивание пакета. 

![IMG_20221030_125149](https://user-images.githubusercontent.com/76971953/198872656-67fc4936-e715-4b74-9404-f6f6320171b9.jpg)

После установки обновления, запускаю приложение. Снова вылезает то же самое окно с обновлением. И так по кругу.

![IMG_20221030_125247](https://user-images.githubusercontent.com/76971953/198872704-30f6a9b2-fbde-4400-a034-c5fc5297d263.jpg)
![Screenshot_2022-10-30-12-54-46-807_com vtosters lite](https://user-images.githubusercontent.com/76971953/198872757-c40b964b-c7a5-4972-8bee-fdd4f7be7c73.jpg)

Устройство: Xiaomi Redmi Note 8 pro
MIUI 12.5.5.0 стабильная (RGGRUXM)
Android 11

**Comment by ayonovdenizs** [comment]
Установи из проводника версию

вс, 30 окт. 2022 г., 15:55 sanchespace ***@***.***>:
