### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by eraserhome** [vtosters/lite#87]
![Screenshot_20220401-105325](https://user-images.githubusercontent.com/102503626/161223887-90ddbd0b-04d2-448b-aa88-3126b7cd36af.png)

**Comment by gdlbo** [comment]
нужны более подробные логи
загрузи файлом пожалуйста

**Comment by rustzz** [comment]
Краш при тексте "А мне" в диалогах
[VTL_log.txt](https://github.com/vtosters/lite/files/8403086/VTL_log.txt)
х

**Comment by rustzz** [comment]
Это другая ошибка. А здесь в стиках (лог выше)
