### ISSUE TITLE
Всплывающие окно

### ISSUE THREAD

**Issue by Shevel212** [vtosters/lite#874]
**Опишите сам баг**
Установил новую версию, а всплывающее окно до сих пор вылазиет

**Опишите действия для воспроизведения ошибки**
1. Захожу в Втостер Лайт
2. Обновляю, перезахожу

**Опишите ожидаемый результат**
Отсутствие всплывающего окна

**Скриншот ошибки**
Нет
**Информация об устройстве:**
 - Устройство: Realme 8
 - OS: Android 11| (не знаю)
 - Коммит: fa12e8f (В О Приложении написана версия коммита)

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

**Comment by psamur** [comment]
@Shevel212 Прочитай первый абзац в этом самом окне
