### ISSUE TITLE
Показывать общих друзей в профиле

### ISSUE THREAD

**Issue by asgorlov** [vtosters/lite#882]
Когда заходишь на профиль знакомого, то рядом с друзьями показываются иконки тех, кто в друзьях у человека(иконок отображается три, а во вкладке общих один)
![IMG_20221106_113648~2](https://user-images.githubusercontent.com/48188924/200156326-0492828a-5bb6-4d11-8297-55f8a8d7a095.jpg)
![IMG_20221106_113721](https://user-images.githubusercontent.com/48188924/200156357-4a74872e-caa1-4d9f-bd5d-0b538f74e3fb.jpg)

Удобней было бы, если сначала показывались иконки общих друзей. А если таковых нет, то либо ничего, либо иконки тех, кто уже есть в друзьях у профиля.

**Comment by gdlbo** [comment]
Когда вк не прогружает всех друзей, то тогда криво отображаются общие

Не пофиксить
