### ISSUE TITLE
Добавление акцентов и кастомизации 

### ISSUE THREAD

**Issue by DjackVorobeu** [vtosters/lite#884]
Здравствуйте
Ответьте пожалуйста, ведётся ли работа по добавлению акцентов и кастомизации приложения?
Да или нет, один ответ, третьего не дано
Я в основном только ради этой функции и устанавливал ваше приложение, и очень грустно что происходит вот такое :(

**Comment by inotflying** [comment]
Да

**Comment by abslike** [comment]
@DjackVorobeu ведётся

**Comment by DjackVorobeu** [comment]
> @DjackVorobeu ведётся

👍

**Comment by aliveoutside** [comment]
дубликат #240
