### ISSUE TITLE
Точное время в сообщениях

### ISSUE THREAD

**Issue by RIP57** [vtosters/lite#886]
Очень полезная (для меня уж точно) функция точного времени в сообщениях. Именно под каждым сообщением чтоб  было время с секундами

**Comment by ayonovdenizs** [comment]
@RIP57 А зачем точное время блять, ты чё следишь блять сколько человек пишет? Во дурной

**Comment by RIP57** [comment]
А че, проблема какая то сделать? Или навыков не хватает? 
![IMG_20221107_130437](https://user-images.githubusercontent.com/117624988/200282998-c8dd8e24-cc93-4e08-9c6e-ce24f72078e5.jpg)

**Comment by ayonovdenizs** [comment]
@RIP57 Цитирую: "идея для фичи хорошая, но не будет пользоваться большим спросом"

**Comment by ayonovdenizs** [comment]
@RIP57 Цитирую разработчика: "я пытался сделать секунды, но у меня вк стал вылетать с проблемой лэйаута"

**Comment by RIP57** [comment]
Тогда без вопросов
