### ISSUE TITLE
Не работает прослушивание голосового сообщения 

### ISSUE THREAD

**Issue by knestor999** [vtosters/lite#887]
**Сам баг**
При нажатии на кнопку воспроизведения голосового сообщения, ничего не происходит и затем появляется системное окно, в котором написано: "Не удалось воспроизвести голосовое сообщение. Проверьте соединение и повторите попытку 

**Действия для воспроизведения ошибки**
1. Открыть чью либо переписку
2. Нажать на кнопку воспроизведения голосового сообщения 

**Ожидаемый результат**
При нажатии, должно начаться воспроизведение голосового сообщения

**Скриншот ошибки**
![IMG_20221107_181406](https://user-images.githubusercontent.com/110788002/200297377-a7674f55-c0d6-4b81-85c8-028892090aec.jpg)

**Информация об устройстве:**
 - Устройство: Xiaomi Redmi Note 9 Pro
 - OS: Android 11 | MIUI 12.5.5
 - Коммит: e47d6ac

**Comment by aliveoutside** [comment]
скорее всего у тебя стоит 1,5х или 2х скорость воспроизведения

**Comment by knestor999** [comment]
> скорее всего у тебя стоит 1,5х или 2х скорость воспроизведения

и вправду. спасибо за помощь
