### ISSUE TITLE
Не работает отключение возможных друзей

### ISSUE THREAD

**Issue by Andrei25100** [vtosters/lite#889]
Включено отключение возможных друзей , но их всё ровно показывает.
![IMG_20221108_100141](https://user-images.githubusercontent.com/115118839/200497102-ab6212eb-33ff-46fb-b40c-0763d1bb8336.jpg)
![IMG_20221108_100208](https://user-images.githubusercontent.com/115118839/200497108-104515dc-b785-4b73-80b0-2e1379618717.jpg)

**Информация об устройстве:**
 - Устройство: Xiaomi mi 11
 - OS: Android 12 | MIUI 13
 - Коммит: e47d6ac

**Comment by gdlbo** [comment]
Интерфейс -> Другое -> Скрыть рекомендации друзей

**Comment by Andrei25100** [comment]
Спасибо

вт, 8 нояб. 2022 г., 10:11 gdlbo ***@***.***>:
