### ISSUE TITLE
Белый экран

### ISSUE THREAD

**Issue by mauzer48** [vtosters/lite#893]
**Опишите сам баг**

Периодически через какое то время вылезает белый экран в втлайт, помогает только перезагрузка приложения, как исправить?

**Информация об устройстве:**
 - Устройство: Samsung Galaxy J1 Mini
 - OS: Android 9 | OneUi 3.0
 - Коммит: fa12e8f (В О Приложении написана версия коммита

**Comment by gdlbo** [comment]
logs?
