### ISSUE TITLE
Очень плохо работает по wifi

### ISSUE THREAD

**Issue by SonnDrake** [vtosters/lite#894]
**Опишите сам баг**
Открытие сообщений или уведомлений при подключении по wifi происходит неимоверно долго. Стоит переключиться на мобильный интернет все происходит практически мгновенно

**Опишите действия для воспроизведения ошибки**

Открыл приложение, тапнул на сообщения

**Опишите ожидаемый результат**

То, что сообщения или уведомления откроются достаточно быстро

**Информация об устройстве:**
 - Устройство: One plus
 - OS: android 11 Oxygen OS 11.0.9.1.GM21AA
 - Коммит: e47d6ac

Проблема замечена после ряда обновлений подряд и двух недель на мобильном интернете.

Две недели назад было ок

**Comment by aliveoutside** [comment]
ничего касаемо интернета мы не трогали
кроме тебя никто из юзеров не жаловался, увы
воспроизвести проблему мы не можем
