### ISSUE TITLE
Не появляются нормально уведомления 

### ISSUE THREAD

**Issue by KoolDENDY** [vtosters/lite#896]
**Опишите сам баг**
Уведомления приходят, но без значка и не выходят на экран, приходится опускать шторку

**Опишите действия для воспроизведения ошибки**
1. Получение уведомления 

**Опишите ожидаемый результат**
Чтобы был значок приложения и выводили уведомления

**Информация об устройстве:**
 - Устройство: Samsung Galaxy A73 5G
 - OS: Android 12 | OneUi 4.1
 -коммит: e47d6ac

**Comment by gdlbo** [comment]
Настрой уведомления клиенту на своей мобиле
