### ISSUE TITLE
Тематический значок

### ISSUE THREAD

**Issue by KiraLinux** [vtosters/lite#898]
Добавьте соответствующий значок под общий новый стиль андроид 

![Screenshot_20221112-201343_crDroid Home](https://user-images.githubusercontent.com/20641834/201486427-5997c7a8-230a-4974-a874-c235566845a4.png)

**Comment by GooDoG337** [comment]
В Андроид13 тематический знак есть

**Comment by gdlbo** [comment]
Monet иконка уже есть с официальным api на android 13

**Comment by KiraLinux** [comment]
А почему не работает тогда?

**Comment by KiraLinux** [comment]
А как же андроид 12?

**Comment by gdlbo** [comment]
> А как же андроид 12?

Android 12 официально не поддерживает новые иконки и там всё сделано страшно, поэтому мы используем только официальные апи для этого
