### ISSUE TITLE
Очень долгая загрузка фото/видео при вложении в диалоге

### ISSUE THREAD

**Issue by a1elen** [vtosters/lite#900]
При открытии меню вложений к сообщению фото/видео очень долго загружаются фотографии (примерно 13 секунд)
Возможно связано с большим количеством фотографий на телефоне, но на официальном клиенте такого нет
Актуальная версия vtlite
![20221115_010031](https://user-images.githubusercontent.com/112384717/201720824-699535ab-23fb-499b-9be5-b3f2e1736b13.jpg)

**Comment by danyyok** [comment]
@a1elen Актуальная версия это какая
