### ISSUE TITLE
Изменение прикреплённого сообщения в редактировании ответа 

### ISSUE THREAD

**Issue by nyafti** [vtosters/lite#901]
Оно не работает. Если меняешь прикреп, редактируя и отправляя сообщение, прикреп не меняется. Проблема распространяется на все прикрепы: репосты записей со стены, сообщения собеседника, собственные сообщения.

**Comment by Wperdex** [comment]
@nyafti не понял о чём речь, прикрепите скрины проблемы, если она ещё актуальна.
