### ISSUE TITLE
Скачивается не весь диалог

### ISSUE THREAD

**Issue by Foxcub1030** [vtosters/lite#902]
**Опишите сам баг**
При скачивании диалога, скачивается не весь диалог, а только за последнее время

**Опишите действия для воспроизведения ошибки**
1. Нажал кнопку "скачать диалог"
2. Открыл файл через проводник

**Опишите ожидаемый результат**
Диалог должен быть скачан полностью

**Информация об устройстве:**
 - Устройство: Realme 9 prp
 - OS: Android 12 | RealmeUI 3.0
 - Коммит: 501e394

**Comment by k1zn** [comment]
известно
