### ISSUE TITLE
Вылетает из диалога при отправке телеграмм стикеров 

### ISSUE THREAD

**Issue by MucTuK8** [vtosters/lite#904]
Вылетает из диалога при отправке телеграмм стикеров

1. Зашел в диалог с другом 
2. Он скинул тг стикер
3. Диалог закрывается 
4. Захожу в диалог 
5. Стикер прогружается, но часть сообщений исчезает

**Информация об устройстве:**
 - Устройство: Realme C3
 - OS: Android 10
 - Коммит: 501e394

У друга анологичный баг. Версии клиента одинаковые.
Его устройство:
-Устройство: Xiomi mi6
-OS: Android 9
-Коммит: 501e394

**Comment by abslike** [comment]
@MucTuK8 логи

**Comment by aliveoutside** [comment]
> @MucTuK8 логи

пока нечего тут логировать, посмотрю позже
