### ISSUE TITLE
Прошу добавить функцию изменения имени собеседников, чтобы можно были менять с имени которое в контаках на имя, которое установлено в ВК (данная настройка есть в официальном приложении ВК: Аккаунт - Именя собеседников)

### ISSUE THREAD

**Issue by SolovyanovDV** [vtosters/lite#905]
.

**Comment by danyyok** [comment]
@SolovyanovDV Настройки-другое
Такая функция есть,научись писать и писать issue нормально

**Comment by SolovyanovDV** [comment]
И где она находится? В Настройках -Другое у меня нет такого

**Comment by abslike** [comment]
![Screenshot_20221117-133932_VTLite](https://user-images.githubusercontent.com/78505436/202397967-4469e0ba-44ff-4e79-a1eb-617af93ce880.png)
вот держи

**Comment by danyyok** [comment]
@abslike И это ты так в настройки зашёл?

**Comment by danyyok** [comment]
@SolovyanovDV Скинь скриншот настроек

**Comment by SolovyanovDV** [comment]
![Screenshot_20221117-124457_VTLite.jpg](https://user-images.githubusercontent.com/62283889/202398856-73d2b1dc-47cf-4bad-8bf1-8856fd1ca14c.jpg)

**Comment by abslike** [comment]
@danyyok извиняюсь, попутал

**Comment by danyyok** [comment]
> ![Screenshot_20221117-124457_VTLite.jpg](https://user-images.githubusercontent.com/62283889/202398856-73d2b1dc-47cf-4bad-8bf1-8856fd1ca14c.jpg)

Синхронизация контактов,первый пункт

**Comment by SolovyanovDV** [comment]
Лол, я не про синхронизацию писал. Прочитай внимательнее, о чем было написано

**Comment by SolovyanovDV** [comment]
![Screenshot_20221117-122939_VK.jpg](https://user-images.githubusercontent.com/62283889/202399627-eac8569e-7b9f-4400-b882-5c4b4845eb5e.jpg)

**Comment by danyyok** [comment]
> ![Screenshot_20221117-122939_VK.jpg](https://user-images.githubusercontent.com/62283889/202399627-eac8569e-7b9f-4400-b882-5c4b4845eb5e.jpg)
> Я про эту функцию

ЭТО ТОЖЕ САМОЕ БЛЯТЬ

**Comment by SolovyanovDV** [comment]
![Screenshot_20221117-122939_VK.jpg](https://user-images.githubusercontent.com/62283889/202399627-eac8569e-7b9f-4400-b882-5c4b4845eb5e.jpg) нет. в официальном приложении это разные вещи, есть синхронизация, но имя можно оставить, как в ВК

**Comment by SolovyanovDV** [comment]
Имена собеседников относится к настройкам Аккаунта. А синхронизация контанков из телефона это уже функция в приложении

**Comment by danyyok** [comment]
> ![Screenshot_20221117-122939_VK.jpg](https://user-images.githubusercontent.com/62283889/202399627-eac8569e-7b9f-4400-b882-5c4b4845eb5e.jpg) нет. в официальном приложении это разные вещи, есть синхронизация, но имя можно оставить, как в ВК

Отклю синхронизацию контактов в лайте и обнови список чатов

**Comment by danyyok** [comment]
> > ![Screenshot_20221117-122939_VK.jpg](https://user-images.githubusercontent.com/62283889/202399627-eac8569e-7b9f-4400-b882-5c4b4845eb5e.jpg) нет. в официальном приложении это разные вещи, есть синхронизация, но имя можно оставить, как в ВК
> 
> Отключи синхронизацию контактов в лайте и обнови список чатов

Имена собеседников изменятся из ВК

**Comment by SolovyanovDV** [comment]
Блин, зачем так сделано) Интуитивно не удобно
