### ISSUE TITLE
Не скачивается музыка

### ISSUE THREAD

**Issue by lEbOv** [vtosters/lite#908]
И нигде не отображается:(

**Comment by danyyok** [comment]
@lEbOv Самый подробный и сильный issue

**Comment by lEbOv** [comment]
> @lEbOvСамый подробный и сильный выпуск

Ну а что ещё? Все кратко и по фактам

**Comment by danyyok** [comment]
@lEbOv Напиши подробнее свой краткий issue и что нибудь сделаем

**Comment by aliveoutside** [comment]
не по форме, пересоздай issue с заготовкой для репорта багов
