### ISSUE TITLE
Не отправляется сообщение 

### ISSUE THREAD

**Issue by Maxon1218** [vtosters/lite#911]
**Опишите сам баг**
Не могу отправлять сообщения 

**Опишите действия для воспроизведения ошибки**
Я просто пишу кому либо сообщение, и появляется знак с часами, так называемый "режим ожидания" 

**Опишите ожидаемый результат**
Сообщение должно отправиться 

**Скриншот ошибки**
![Screenshot_20221119_150756_com vtosters lite](https://user-images.githubusercontent.com/118609517/202850076-fcf9a172-c138-4931-b034-42a2886085c6.jpg)

**Информация об устройстве:**
 - Устройство: Honor 9a Moa-lx9n
 - OS: Android 
 - Коммит: 501e394 (В О Приложении написана версия коммита)

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**
Не знаю, резко произошло

**Comment by danyyok** [comment]
> **Опишите сам баг**
> Не могу отправлять сообщения 
> 
> **Опишите действия для воспроизведения ошибки**
> Я просто пишу кому либо сообщение, и появляется знак с часами, так называемый "режим ожидания" 
> 
> **Опишите ожидаемый результат**
> Сообщение должно отправиться 
> 
> **Скриншот ошибки**
> ![Screenshot_20221119_150756_com vtosters lite](https://user-images.githubusercontent.com/118609517/202850076-fcf9a172-c138-4931-b034-42a2886085c6.jpg)
> 
> **Информация об устройстве:**
>  - Устройство: Honor 9a Moa-lx9n
>  - OS: Android 
>  - Коммит: 501e394 (В О Приложении написана версия коммита)
> 
> **Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**
> Не знаю, резко произошло
> 

Прокси включено? (Настройки-Прокси)
