### ISSUE TITLE
Не могу выйти из режима офлайн

### ISSUE THREAD

**Issue by Dzzzhon** [vtosters/lite#913]
**Опишите сам баг**
Сатаря версия втостера не выключает режим офлайн

**Опишите действия для воспроизведения ошибки**
1. зашел в настройки офлайна
2. не меняется режим

**Опишите ожидаемый результат**
должен показываться  онлайн

**Скриншот ошибки**

**Информация об устройстве:**
 - Устройство: xiaomi pad 5
  - OS: Android 11 rkq1.200826.002
 - Коммит: приложение уже удалил

приложение старой версии поддержку которого вы закрыли после чего перестала работать эта функция и я удалил его

**Comment by abslike** [comment]
@Dzzzhon скачай vk messenger и там выключи оффлайн

**Comment by aliveoutside** [comment]
не относится к втлайту
