### ISSUE TITLE
Ошибка загрузки телеграмм стикеров 

### ISSUE THREAD

**Issue by Gidgirvjeivdubf** [vtosters/lite#917]
**Опишите сам баг**
При попытке загрузить стикер с наименованием "lennysticker" загружается "lelennysticker", т.е. другой набор.

**Опишите действия для воспроизведения ошибки**
1. Зайди в добавление стикеров
2. Подтвердить бота
3. Вставить ссылку https://t.me/addstickers/lennysticker
4. Добавится другой набор 

**Опишите ожидаемый результат**
Исправить ошибку.

**Скриншот ошибки**
![dmricLtH3N3xEF-0CbsIyI44a8uEFihPUyk_PNkF88YSXt70tEc1WDg1B2QhKI93pexg2IX1WQhuYI3-uu5T61DK](https://user-images.githubusercontent.com/118828534/203339763-eb225565-69d5-41be-b3ce-87dddc981230.jpg)
![IR5w4Eg3tVofwIS3PX55h_pM_IWyI93uDBUunJTq4nmF7cZDWWTBxDeH77Lxuw77aH9s-V_WxlLKqyE6kUscKJa6](https://user-images.githubusercontent.com/118828534/203339774-ff45e0fa-3f87-4a61-a6d2-99fe3d61d306.jpg)
![xjapfNQeyIb04gFrGOF6D0cQYjY38x0VsH1x7X_0A2wVVpWuzzbx9zopFAsgFRRBtjy4LMitP4rFQmEiFd-onB-J](https://user-images.githubusercontent.com/118828534/203339781-1d5ca54a-3fed-4012-859a-19031203f54a.jpg)

**Информация об устройстве:**
 - Устройство: poco x3 pro 
 - OS: Android 12 SKQ1.211006.001
 - Коммит: 501e394
(В О Приложении написана версия коммита)

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

**Comment by k1zn** [comment]
не могу повторить - добавляется тот набор, который я и вставил
