### ISSUE TITLE
Ошибка в групповом чате

### ISSUE THREAD

**Issue by alexp7770** [vtosters/lite#919]
Добрый день! В беседе не видно имени людей которые пишут сообщения, видно только когда их от кого то переслали. В оф приложении ВК это есть (и это очень удобно). 
Действие: 
Просто откройте любой групповой чат и увидите сами, данная проблема наблюдается как минимум у двух пользователей. 

**Опишите ожидаемый результат**
Хочется видеть имена тех кто пишет в беседе, по тому, что по аватаркам всех не знаешь, а каждый раз заходить на страницу, что-бы увидеть имя не удобно. 

**Скриншот ошибки**
![Screenshot_2022-11-23-19-25-01-64_9e1a5d6211a0228d32d39446541891f1](https://user-images.githubusercontent.com/118926945/203616501-996900a3-6408-464a-8e25-96578b6abebc.jpg)

**Информация об устройстве:**
 - Устройство: really 8 pro
 - OS: Android 12 | RealmiUi 3.0
 - Коммит: 501e394

**Comment by gdlbo** [comment]
Это не баг
