### ISSUE TITLE
Ошибка обновлении ленты новостей

### ISSUE THREAD

**Issue by Swijet** [vtosters/lite#923]
При обновлении новостей вылезает ошибка

В новостях при свайпе вправо во вкладке "интересное" вылезает ошибка загрузки 

![Screenshot_2022-11-26-20-01-54-147_com vtosters lite](https://user-images.githubusercontent.com/116867952/204095462-d2095aa7-e1b4-4990-a99b-471c229c5e12.jpg)

**Comment by ayonovdenizs** [comment]
@Swijet Коммит? Версия?

**Comment by Swijet** [comment]
Самая последняя версия

**Comment by ayonovdenizs** [comment]
@Swijet "Последней" не существует. Только номер

**Comment by Swijet** [comment]
v0.4.24-beta

**Comment by k1zn** [comment]
@Swijet предоставь логи
как записать логи - смотри github.com/vtosters/lite
