### ISSUE TITLE
Подтверждение удаления трека из кеша

### ISSUE THREAD

**Issue by danyyok** [vtosters/lite#924]
**Опишите вашу идею максимально подробно и понятно**
Необходима функция подтверждения удаления трека из кеша,простое нажатие на кнопку мусорки (которая в 3-х точках) сразу же удаляет трек из кеша без подтверждения этого

**Опишите возможное решение/реализацию функции (если понимаете как это можно реализовать на Java/C++)**

**Остальные мысли о предложенной функции**
Подтверждение есть,если удалять трек из **библиотеки**

**Comment by aliveoutside** [comment]
не необходима, иконка прямо даёт понять что она делает
