### ISSUE TITLE
Не работают звонки

### ISSUE THREAD

**Issue by dsys1100** [vtosters/lite#934]
**Опишите сам баг**
При попытке позвонить человеку приложение вылетает, также при входящем звонке экрана вызова нет, после приходит сообщение о пропущенном звонке

**Опишите действия для воспроизведения ошибки**
1. Зашёл к человеку на страницу
2. Нажал Позвонить, Аудиозвонок (при Видеозвонке тоже самое)

**Опишите ожидаемый результат**
Звонок должен был начаться

**Информация об устройстве:**
 - Устройство: Samsung Galaxy S10e
 - OS: Android 12 | OneUi 4.1 (сток)
 - Коммит: 501e394

**Лог** 
[Текст на пастебине](https://pastebin.com/jCXbyS6H) 

**Видео**
[Видео на гугл диске](https://drive.google.com/file/d/1-8ubnH-Yr7hPAKPGqSxlUFw-m5jKJe3I/view?usp=drivesdk)

**Comment by ayonovdenizs** [comment]
@dsys1100 Звонки убиты вк для старых версий

**Comment by aliveoutside** [comment]
![image](https://user-images.githubusercontent.com/53598473/205434391-3377e1f9-dccf-40f4-ab9e-da7a49bbdb82.png)
#14
