### ISSUE TITLE
Ошибка обновления сообщений

### ISSUE THREAD

**Issue by 1Qulan1** [vtosters/lite#937]
**Опишите сам баг**
Не обновляются сообщения

**Опишите действия для воспроизведения ошибки**
1. Нажал на кнопку обновления сообщения

**Опишите ожидаемый результат**
Сообщения должны обновиться

**Скриншот ошибки**
![Screenshot_20221204-191738](https://user-images.githubusercontent.com/119804815/205502469-78850448-658c-41ed-bb55-d99170f9f589.jpg)

**Информация об устройстве:**
 - Устройство: Huawei y7 2019
 - OS: Android 8 EMUI 8.2
 - Коммит: 501e394

**Comment by aliveoutside** [comment]
https://downdetector.br-analytics.ru/vkontakte

У вк снова проблемы
