### ISSUE TITLE
Ошибка оффлайн режима

### ISSUE THREAD

**Issue by deatherz192** [vtosters/lite#941]
В оффлайн режиме иногда закидывает в онлайн на мгновенье

Заметил, что это иногда происходит просто при переходе во вкладку сообщений. Также при переходе туда все непрочитаные сообщения в один момент появляются в шторке, и я оказываюсь онлайн

Скрин настроек прикрепил 

 - Устройство: Poco X3 Pro
 - OS: Android 12 | MiUi 13.0.2
 - Коммит: 501e394

![IMG_20221207_160712](https://user-images.githubusercontent.com/106407810/206163468-dddbd4fa-56b8-449b-b764-1ad66e916cb5.jpg)

**Comment by k1zn** [comment]
@deatherz192 так и должно быть, когда ты отправляешь запросы вк выставляет тебе онлайн

**Comment by deatherz192** [comment]
> @deatherz192 когда ты жмешь на вкладку, ты делаешь запрос на получение новых сообщений

Понял, спс
