### ISSUE TITLE
Не отображаются оболожки артистов в музыке

### ISSUE THREAD

**Issue by Patl1k** [vtosters/lite#942]
**Опишите сам баг**
Не видно нормально обложку треков, тоесть они размываются в большие квадратики, а хочется посмотреть на нормальную обложку

**Опишите действия для воспроизведения ошибки**
1. Зашёл в раздел музыки
2. Открыл желаемый трек

**Опишите ожидаемый результат**
Видеть нормальные, чëткие, в нормальном качестве ,(родные) , без размытия обложки

**Скриншот ошибки**

**Информация об устройстве:**
 - Устройство: Xiaomi mi 10T
 - Android 12 SQ1. 211006.001

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

**Comment by danyyok** [comment]
Версия,скриншот?

**Comment by gdlbo** [comment]
Сделайте репорт во всем необходимым пунктам для отправки информации о баге
