### ISSUE TITLE
Показывается другое видео в историях.

### ISSUE THREAD

**Issue by Sheidheda666** [vtosters/lite#947]
**Опишите сам баг**
Когда выкладываю в историю больше одного видео, непонятно откуда показывается одно и то же видео, совершенно мне неизвестное.

**Опишите действия для воспроизведения ошибки**
1. Нажать на создание истории.
2. Загрузить видео из галереи.
3. Дождаться, пока видео загрузится.
4. После загрузки зайти в свою историю.

**Опишите ожидаемый результат**
Иметь возможность видеть в истории именно те видео, которые я выкладываю.

**Скриншот ошибки**
![Screenshot_2022-12-11-20-36-23-78_9e1a5d6211a0228d32d39446541891f1](https://user-images.githubusercontent.com/120330975/206920832-4e5582e9-74a2-4fb2-a78d-a583b23d10a5.jpg)

**Информация об устройстве:**
 - Устройство: Realme 9 Pro 5G
 - OS: Android 13 | realme UI 3.0
 - Коммит: 501e394 (В О Приложении написана версия коммита)

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

**Comment by Sonatos** [comment]
Та же ошибка.
При просмотре историй с несколькими видео-фрагментами, показывается только самый первый:
-Если самостоятельно пролистнуть с первого фрагмента дальше;
-Если ролик проиграется и автоматически перейдёт на некст фрагменту.

Перезагрузка, переустановка, лазание в настройках не помогли. Версия самая свежая на 13.12.22

**Comment by sistokol** [comment]
Тоже самое происходит уже больше месяца. Устройство poco f3

**Comment by gdlbo** [comment]
исправлено
