### ISSUE TITLE
Ошибка в сообщениях

### ISSUE THREAD

**Issue by Lambada253** [vtosters/lite#949]
В чате в самом низу не пропадает надпись *"имя пользователя" сделал скриншот* Эта надпись только в одном сообщении весит уже около месяца. Не исчезает даже при вкл/выкл детекта скриншотов

**Информация об устройстве:**
 - Устройство: Honor 50
 - OS: Android 12 | Magic UI 6.0.0
 - Коммит: 501e394
![Screenshot_20221215_031456_edit_359757190682553](https://user-images.githubusercontent.com/120610651/207744339-0a1610ba-b80a-4519-adf6-80e7192f8374.jpg)
![Screenshot_20221215_031448](https://user-images.githubusercontent.com/120610651/207744360-53c50bef-53fa-40c3-9cf4-1b5b0d220fc7.jpg)

**Comment by gdlbo** [comment]
Это нормально, оно и не должно исчезать

Отключение детекта позволяет не отправлять этот статус вк

**Comment by Lambada253** [comment]
Решил проблему неделю назад. Обновил сообщения
