### ISSUE TITLE
Не отображаются некоторые посты в группах

### ISSUE THREAD

**Issue by MillenniuM-91** [vtosters/lite#950]
**Опишите сам баг**
Не отображаются некоторые посты в группах, а если открыть по ссылке пишет "запись удалена"

**Скриншот ошибки**
Пример поста: vk.com/wall-20017667_15676
![IMG_20221215_155254](https://user-images.githubusercontent.com/102908880/207864327-1635c5e3-e88c-4bc4-be50-2e22364115b8.jpg)

**Информация об устройстве:**
 - Устройство: Xiaomi mi mix 2s
 - OS: Android 10 | MIUI 12.0.5
 - Коммит: 501e394

**Дополнительная информация о баге или мыслях почему оно может происходить (если есть)**

**Comment by TheMorzh** [comment]
Настройки - Лента - Однотипные новости выключи и всё будет нормально

**Comment by MillenniuM-91** [comment]
> Настройки - Лента - Однотипные новости выключи и всё будет нормально
Благодарю, помогло, все равно баг получается)

**Comment by gdlbo** [comment]
Не баг, было выше описано что так работает блокировка рекламы и как-то красиво выводить сообщение что пост удален невозможно
