### ISSUE TITLE
Ошибка со статьями группы

### ISSUE THREAD

**Issue by Xazmadan** [vtosters/lite#953]
**Опишите сам баг**
при просмотре статей в закрытых сообществах пишет, что статья доступна только для участников сообщества, хотя я состою в нем

**Опишите действия для воспроизведения ошибки**
1. Нажал на статью в закрытом паблике

**Опишите ожидаемый результат**
Статья должна отображаться

**Скриншот ошибки**

![1671308040262.jpg](https://user-images.githubusercontent.com/69046303/208264501-ebffb872-f3f4-495a-b369-d5e2298a7e95.jpg)

**Информация об устройстве:**
 - Устройство: Redmi 9
 - OS: Android 10 QP1A. 190711.020
 - Коммит: 501e394 (В О Приложении написана версия коммита)

**Comment by gdlbo** [comment]
Должно быть исправлено в v0.5
