### ISSUE TITLE
Ошибка со статьями для донов

### ISSUE THREAD

**Issue by ssnowier** [vtosters/lite#955]
При входе в статью для донов в своей же группе, появляется уведомление о донате в группу

1. Захожу в группу
2. Захожу в закрепление со статьями
3. Нажимаю на статью для донов
4. Появляется уведомление о донате в группу

Должна отображаться статья для донов в своей же группе

![Screenshot_20221218-152909_VTLite](https://user-images.githubusercontent.com/120932422/208298441-105fb7f4-bda0-4233-b7c8-2d944cd77ebd.png)

 - Устройство: Samsung Galaxy S10
 - OS: Android 11 | OneUi 3.1
 - Коммит: 501e394

**Comment by gdlbo** [comment]
Проблема должна быть решена в v0.5
