### ISSUE TITLE
Не оффлайн, а в сети.

### ISSUE THREAD

**Issue by Klycs** [vtosters/lite#957]
Включил функцию быть в оффлайне.
Захожу через приложение (втостер)захожу в профиль проверить когда был в сети могу быть и когда то был(час назад и т.д.) в сети, а могу быть "только что". Как починить? Чтоб я был всегда в оффлайне, а то бесит уже,
Надеюсь поймёте меня)

**Comment by aliveoutside** [comment]
не относится к vtosters lite

**Comment by aliveoutside** [comment]
> а могу быть "только что"
разные действия типа отправки сообщений и обновления ленты вызывают это, об этом написано под ползунком в настройках
