### ISSUE TITLE
Вечная обработка видео

### ISSUE THREAD

**Issue by Ubica282** [vtosters/lite#96]

**Comment by MillenniuM-91** [comment]
Ни одно видео загруженное в вк не отрывается. "Всплывает сообщение: это видео все еще обрабатывается. Пожалуйста повторите попытку позже.", хотя с других клиентов все прекрасно работает

**Comment by yakakshawerma** [comment]
> Большая часть видео, загруженного на сервисы вк, из диалогов не отрывается. "Всплывает сообщение: это видео все еще обрабатывается. Пожалуйста повторите попытку позже.", хотя с других клиентов все прекрасно работает. Причем спонтанным образом. От одного человека может открываться, следующее уже нет. Может дело в кодеках iphone

Такая же проблема

**Comment by MillenniuM-91** [comment]
Как вариант добавить возможность воспроизведения видео во внешнем плеере. Не нашел такую функцию в настройках

**Comment by MillenniuM-91** [comment]
> > Как вариант добавить возможность воспроизведения видео во внешнем плеере. Не нашел такую функцию в настройках
> 
> Такая функция уже существует Настройки -> Интерфейс -> Использовать внешний видеоплеер

хм, действительно есть, только результат тот же,  не работает) Выдает то же всплывающее окно
