### ISSUE TITLE
Не работают функции VT

### ISSUE THREAD

**Issue by pasha-zzz** [vtosters/lite#964]
При нажатии на VT фукции грит, что эта версия больше не поддерживается.
Но стоит и так 0.4.24 и новее нет.

**Comment by danyyok** [comment]
@pasha-zzz Скриншот?

**Comment by pasha-zzz** [comment]
![image](https://user-images.githubusercontent.com/8224786/209457737-0f07b9c5-6f67-48cc-bb78-af9eba50281c.png)

**Comment by danyyok** [comment]
@pasha-zzz Коммит приложения?

**Comment by pasha-zzz** [comment]
501e394

**Comment by aliveoutside** [comment]
наверное, только переустановка поможет

**Comment by pasha-zzz** [comment]
> наверное, только переустановка поможет

Поверх переустанавливал. Надо сначала снести?

**Comment by kussaqqqehateyou** [comment]
@pasha-zzz да, удаление полностью. потом установка по новой

**Comment by pasha-zzz** [comment]
Хватило полной очистки данных приложения. Спасибо.
