### ISSUE TITLE
Ошибка скрытия онлайна

### ISSUE THREAD

**Issue by MrA628** [vtosters/lite#965]
VkLite перестал поддерживать функцию офлайна

Заметил давно, но удостовериться смог только сейчас, что при включении/выключении пункта "скрыть онлайн" ничего не меняется

Ожидал такой же качественно работы функции, что и на стареньком VkTosters

1 скрин - включены все галочки во вкладке "онлайн"
2 скрин - выключены все галочки во вкладке "онлайн"
![Screenshot_2022-12-26-00-22-49-352_com vtosters lite](https://user-images.githubusercontent.com/121405574/209482264-dcf8a849-7f58-43fa-8d6f-d00485acda68.jpg)

![Screenshot_2022-12-26-00-23-06-778_com vtosters lite](https://user-images.githubusercontent.com/121405574/209482277-f8b72105-4013-4d27-a6e2-ce3ee84d1023.jpg)

От устройства не зависит

Могу предложить, что баг связан с изменением политики самого Vk

**Comment by ayonovdenizs** [comment]
Читать настройки не учили?

**Comment by MrA628** [comment]
Нет, не учили
А если и учили, то я тупой
Помогите пожалуйста

**Comment by ayonovdenizs** [comment]
![Screenshot_20221226-100100](https://user-images.githubusercontent.com/77270222/209498225-504494d1-968c-4977-a219-339e8fe22605.png)

**Comment by MrA628** [comment]
Включены все пункты, но ничего не меняется

**Comment by MrA628** [comment]
![Screenshot_2022-12-26-07-14-09-438_com vtosters lite](https://user-images.githubusercontent.com/121405574/209499055-0f62c3d2-ac3e-4e95-910a-a7698cd19a2e.jpg)
Включено все как на картинке, но нет надписи "был в сети недавно"

**Comment by kussaqqqehateyou** [comment]
@MrA628 "был(а) в сети недавно" делается через вк мессенджер. пункт оффлайна работает по другому.

**Comment by MrA628** [comment]
О, вот то что мне нужно было, спасибо
И на последок уточню
Скачать VkMessenger можно с вашего сайта, который для ПК, зайти под своим аккаунтом и все будет хорошо?

**Comment by kussaqqqehateyou** [comment]
@MrA628 вк мессенджер скачивается в GPlay или AppStore

**Comment by MrA628** [comment]
О, т.е. не обязательно скачивать версию для ПК? Отлично!
Спасибо, можно закрывать тему
