### ISSUE TITLE
Цвет акцента в 0.5

### ISSUE THREAD

**Issue by newspeednova** [vtosters/lite#969]
В 0.5 версии зачем то сменили цвет акцента в старом дизайне с классического тёмно синего на голубой. На белом фоне голубые буквы, это боль для глаз! А настраивать, как в милкшейке акцент нельзя. Верните пожалуйста классику. Зачем вообще было это изменять?

**Comment by aliveoutside** [comment]
> это боль для глаз

можно конкретный пример, где это нечитаемо? в основных разделах, диалогах и т.д. всё нормально читается

> А настраивать, как в милкшейке акцент нельзя

временно так, он отключен из-за проблем с покрасками

> Зачем вообще было это изменять

не хочу углубляться в тех. подробности, но это из-за самой системы покраски, назло кому-то мы бы не стали что-то изменять

**Comment by newspeednova** [comment]
Оно читаемо. Не в том дело. Возможно у меня имеются проблемы с глазами. На не контрастных и довольно светлых буквах взгляд плохо фокусирется. А ведь в большинстве, это именно заголовки. А во вкладке с уведомлениями, вообще боль. Там почти весь текст голубого цвета. Все сливается и приходится глаза напрягать.
Скрины еще випервый раз хотел отправить, но они не отражают того, как оно в живую воспринимается.
Да причем тут назло.:) Понятно, что не для этого. У меня в принципе два варианта было. Проблема, связанная с новыми настройками цветов или просто вы посчитали, что так красивее. В новых версиях ВК уже давно похожеие цвета. Надеялся конечно на первое. Был бы шанс, что это временно.
Спасибо за ответ! Надеюсь все же вернете, как было.

**Comment by newspeednova** [comment]
Просто хотелось, что бы старый дизайн, все же оставался старым дизайном.

**Comment by newspeednova** [comment]
Раньше цвет был приблизительно #4c75a3, а не #71aaeb. :(
