### ISSUE TITLE
Краш при открытии вкладки "Фото"

### ISSUE THREAD

**Issue by morrrtis** [vtosters/lite#972]
Приложение крашится при попытке открыть раздел "Фото" в докбаре

1. Вынести раздел "Фотографии" на докбар.
2. Нажать на этот раздел

![Screenshot_2022-12-27-02-36-59-68_9e1a5d6211a0228d32d39446541891f1.jpg](https://user-images.githubusercontent.com/114264659/209588535-7c4cb0ca-b1e8-4899-bb9c-255ad406944a.jpg)

Информация об устройстве:
 - Устройство: OnePlus 7 Pro
 - OS: Android 12 | OxygenOS 12
 - Коммит: 52f69c7

**Comment by gdlbo** [comment]
Спасибо за репорт

https://foxbin.f0x1d.com/6j6l3C8rsm лог ошибки


Будем разбираться!

**Comment by Vologhat** [comment]
@gdlbo @gdlbo ты фрагмент нахуй сломал
