### ISSUE TITLE
Ошибка авторизации

### ISSUE THREAD

**Issue by Neovolter** [vtosters/lite#973]
При авторизации вылезает ошибка "во время загрузки данных произошла ошибка , проверьте интернет подключение"

Предисловия
1. Инет подключен
2. Апп открыт в незалогиненном состоянии

Шаги
1. Нажать log in
3. Ввести валидные креденциалы
4. Нажать log in

ОР
Успешная авторизация в аккаунт

**Информация об устройстве:**
 - Устройство: Lenovo tab 4 10 plus TB-X704L
 - OS: Android 10 Lineage os 17.1 
 - OS build number: lineage_TBX704-userdebug 10 QQ3A.200805.001 eng.joerg.20221011.105628 test-keys
 -  версия эппа 0.5 commit 80b8399cb891887bf15d83d1d7497ca93f1cd868

**Comment by k1zn** [comment]
[api.vk.com](https://api.vk.com) грузит? должен выдавать "403"

**Comment by Neovolter** [comment]
> [api.vk.com](https://api.vk.com) грузит? должен выдавать "403"

403 в браузере
