### ISSUE TITLE
Мне приходит уведомление о входе из других городов , чем это обосновано

### ISSUE THREAD

**Issue by Geroinashego** [vtosters/lite#983]
Зашел на аккаунт и приходят оповещения о входе на мой аккаунт из других городов 
![Screenshot_20221228-005454](https://user-images.githubusercontent.com/121522621/209727076-dd43a9c1-5e71-4cd3-87e7-2c97c8e4d3d3.png)
![Screenshot_20221228-005427](https://user-images.githubusercontent.com/121522621/209727089-843f69db-d609-46a5-8165-672b29edef84.png)

**Comment by psamur** [comment]
@Geroinashego Заверши все сеансы в настройках VK ID, смени пароль и установи 2ФА. 

У ВТЛайта открытый исходный код и ноль побуждений заниматься подобным. Скорее всего, свой пароль ты посеял на какой-нибудь фишинг рулетке стикеров или раздаче пяти миллиардов долларов от Путина по новой госпрограмме.

**Comment by aliveoutside** [comment]
мы тут ни причём

**Comment by Geroinashego** [comment]
Проблема в том что пароль мой нигде не сверкал , а уведомления приходят когда я вхожу с вк тостер .
