### ISSUE TITLE
Ошибка при воспроизведении голосовых сообщений на скорости х1.5 и х2

### ISSUE THREAD

**Issue by sanvlkv** [vtosters/lite#989]
При воспроизведении голосовых сообщений на скорости 2х и 1.5х возникает ошибка, воспроизведения не происходит.

**Опишите действия для воспроизведения ошибки**
1. Открыл личные сообщения
2. Нажал на воспроизведение голосового сообщения
3. Установил в верхнем правом углу скорость воспроизведения

**Опишите ожидаемый результат**
Скорость голосового сообщения должна возрасти
**Скриншот ошибки**

**Информация об устройстве:**
 - Устройство: Google Pixel 5 - OS: Android 13 
 - Коммит: 8eb7251
![Screenshot_20221229-101542](https://user-images.githubusercontent.com/121596517/209906662-dead9699-225a-4dfe-866a-520270477a7f.png)

**Comment by gdlbo** [comment]
Древний вк баг который не фиксили с релиза ускорения голосовых сообщений и только относительно недавно исправили в вк
